### ISSUE TITLE
Prisma issue with Javascript number

### ISSUE THREAD

**Issue by deski-app** [prisma/studio#1006]
1. Prisma version (`prisma -v` or `npx prisma -v`):
**8.3.1**

2. Logs from Developer Tools Console or Command line, if any:
```
-
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
yes

5. Prisma schema (if relevant):
```
time            Int @db.BigInt
```

A Javascript number is 64-bit and should be mapped to Postgres BigInt type to avoid overflow. 
- If I use a regular `Int` for storing a numerical timestamp with milliseconds I get an overflow. 
- If I use @BigInt as Postgres data type a Javascript BigInt is returned. It is unnecessary, and ads a lot of complexity.

My attempt to force the desired behaviour failed as well: 
`time            Int @db.BigInt`
And Prisma has no support for custom deserialisers.

**Comment by petradonka** [comment]
This looks like a Prisma Client issue (https://github.com/prisma/prisma). There are already a few `BigInt` related issues there, it'd be best to check if your issue differs from the ones already open in that repo.

I'm closing this issue, as you might find an already existing one in `prisma/prisma` that addresses your issue.
