### ISSUE TITLE
Tabs should have minimal width

### ISSUE THREAD

**Issue by schickling** [prisma/studio#101]
Also: Design is slightly off.

Actual:

![image](https://user-images.githubusercontent.com/1567498/64677772-8ab82a00-d478-11e9-8caf-dd008621739a.png)

Expected:

![image](https://user-images.githubusercontent.com/1567498/64677794-94da2880-d478-11e9-9f24-3163ac7f69f6.png)

**Comment by madebysid** [comment]
Ah, right now, this is done so tabs have a max and a min width, and depending on the number of tabs, it changes so all of them can fit. Can change!

**Comment by madebysid** [comment]
Should be fixed with alpha.176
