### ISSUE TITLE
Error on clean start-up

### ISSUE THREAD

**Issue by damdafayton** [prisma/studio#1014]
### Bug description

![prisma](https://user-images.githubusercontent.com/83017311/187313350-1ec441cc-8727-4572-936d-b0e12531ca38.png)

### Prisma information

prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0

### Environment & setup

- OS: Windows 10
- Browser: Chrome
- Database: MongoDB

**Comment by petradonka** [comment]
Hey @damdafayton, could you add a few more details about how to reproduce the issue and how regularly it happens? There should also be more logs under the "Show details" section of the modal you shared, could you share those as well? Thanks!

**Comment by damdafayton** [comment]
Hi @petradonka,
"Show details" is empty thats why I didnt share it. I am not sure how to reproduce it. I have deleted everything and re-installed and still it doesnt work. Maybe there are logs somewhere?

**Comment by petradonka** [comment]
Have you tried clearing out your IndexedDB (https://github.com/prisma/studio/issues/895#issuecomment-1083051249)? Does the issue happen in other browsers too? Did anything change recently on your side, do you know when Studio last worked in this project?

**Comment by damdafayton** [comment]
@petradonka Thanks. Clearing IndexedDB solved the problem.
