### ISSUE TITLE
Cell editing design is off

### ISSUE THREAD

**Issue by schickling** [prisma/studio#102]
https://www.loom.com/share/3d22f4faa1364e76a6475a0324ebad91

**Comment by madebysid** [comment]
If you meant the irregular alignment, that is fixed with alpha.176.

**Comment by schickling** [comment]
What I'm referring to is that the text which should be edited shouldn't "change" or "jump around". See this screenshot:

![image](https://user-images.githubusercontent.com/1567498/64715442-c2e35b00-d4c0-11e9-8576-6beb5046bf7d.png)

**Comment by madebysid** [comment]
Fixed with alpha.194
