### ISSUE TITLE
Unable to init PersistenceStore undefined

### ISSUE THREAD

**Issue by magazinecrm** [prisma/studio#1023]
### Bug description

I am getting the following error
udio is up on http://localhost:5555

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
Could you share a bit more info about your environment? What browser are you using? Which Prisma version are you on?

Are you consistently running into this issue? Have you tried [clearing your IndexedDB](https://github.com/prisma/studio/issues/895#issuecomment-1083051249)?
