### ISSUE TITLE
404 Errors Within Kubernetes Pod

### ISSUE THREAD

**Issue by SkelatorIndy** [prisma/studio#1025]
<h1>Problem</h1>

I've set up a Kubernetes environment that runs an express API with Prisma. I've also set up an ingress service that directs traffic either to the API itself, or to Prisma studio for easy access in a browser outside of the Kubernetes pods. When I run the API directly in the command line, I'm able to access Prisma studio perfectly fine, however when it's run through the Kubernetes cluster, I am able to access the endpoint and the page title shows I am accessing Prisma studio, but I get a bunch of 404 errors regarding databrowser.js, vendor.js, index.js, and index.css. I can't seem to find anything that should be causing this so I'm not sure what the issue is, since when looking within the Docker container that runs the service, everything seems to have been installed perfectly fine.
If any more information is needed just lmk. Thanks!

![image](https://user-images.githubusercontent.com/13159212/192071748-627f30fd-0dd0-42e6-b1dc-8f27310af069.png)

<h2>Prisma Information</h2>

prism: 4.3.1
@prisma/client: 4.3.1
Current platform: linux-musl
Query Engine (Node-API): libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-linux-musl.so.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0

**Comment by janpio** [comment]
"auth" is the URL that serves your local Studio instance?

**Comment by SkelatorIndy** [comment]
Yeah, the URL going through the ingress is "/db/auth". The ingress service has a rewrite rule that redirects back to "/" since the actual url of "/db/auth" would not be recognized if it was rerouted to the actual pod.

**Comment by jasonkuhrt** [comment]
Heya, few questions:

- How is the docker image for the studio built? Or is it just using the app image with a different entrypoint?
- How is k8s (short for kubernetes) ingress setup?
- Before debugging in the larger k8s context it probably should be confirmed if the setup works with just docker, e.g. run a container locally and send traffic, does it work?

**Comment by SkelatorIndy** [comment]
**UPDATE**

I've found that Studio works IF I have the path as just `/` instead of `/db/auth`. It seems that the files that are giving the 404 error are accessible through `testing.dev` but not `testing.dev/db/auth` because, according to the headers for the file fetching, it's trying to access the files at `testing.dev/db/assets/index.js`, for example, instead of `testing.dev/assets/index.js`. 
It's fairly obvious why it won't work now, but I'm still unsure of how to solve this kind of issue, save for just setting the route to `/`, which really is not an option anyway. Hopefully this helps.

**Comment by janpio** [comment]
Does it work if you set the route to `/db/auth/`? It might just be the missing trailing slash which makes it try to load them one level up by default?

**Comment by SkelatorIndy** [comment]
Unfortunately that doesn't work. I thought that could be the case since it was removing one level, so I had set it to `/db/auth/test` and tried with that but it still didn't work.

**Comment by jasonkuhrt** [comment]
> it's trying to access the files at testing.dev/db/assets/index.js, for example, instead of testing.dev/assets/index.js.

This resource fetch comes from Prisma studio when launched from the prisma CLI, correct?

Are there no aspects of request (like user-agent header) that you can use to route a request to `/` to a specific k8s service? I don't recall k8s ingress being powerful enough to do this, but maybe its gotten more powerful and/or maybe you could put up a reverse proxy to do it at that level (not sure if putting up a reverse proxy is easy for you, or if its anyways easy to do in the context of k8s).

Thinking: Could you have a pod with three containers within, one for the reverse proxy to intelligently split traffic, one for your app, and one for studio?

Probably a simpler way to achieve a final solution but just kicking the tires a bit here.

**Comment by SkelatorIndy** [comment]
It seems the resource fetch is called when trying to load up Studio in the browser, on the fly, not on boot from the CLI. As for redirecting, I do have a rule in the ingress rules I posted above (`nginx.ingress.kubernetes.io/rewrite-target: /`) which is rewriting the target in the specific k8s pod to `/` instead of `/db/auth` since it doesn't seem I can change the endpoint for Prisma Studio and without it you would get a 404 error since Studio runs on the top level. 
I can mess around with the 3 container method and see if anything works though, so thanks for that suggestion. Hopefully if that works I'll be able to work backwards and make it a bit cleaner and more efficient.

**Comment by janpio** [comment]
Does it work with your original config `/db/auth` and then you request `/db/auth/assets/index.js` in a browser window?
