### ISSUE TITLE
I can't open Prisma studio when I used npx prisma studio

### ISSUE THREAD

**Issue by parametprame** [prisma/studio#1027]
### Bug description

<img width="573" alt="image" src="https://user-images.githubusercontent.com/43013637/192828021-88d6d6fe-07d7-4569-89c3-bf3f98249b32.png">

### How to reproduce

I used npx prisma prisma studio

### Expected behavior

Can open prisma studio on browser

### Prisma information

> risma                  : 4.3.1
@prisma/client          : 4.4.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0

### Environment & setup

- OS: Mac OS
- Browser:  Chrome
- Database: PostgreSQL

### Prisma logs

`Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at xt.serialize (http://localhost:5555/assets/index.js:1:49974)
    at xt.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at xt.update (http://localhost:5555/assets/index.js:1:49831)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at xt.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:83936
    at Array.forEach (<anonymous>)`

**Comment by hitfm00** [comment]
I have the same

**Comment by petradonka** [comment]
It looks like you're running into an existing issue we're aware of. Could you give [this workaround ](https://github.com/prisma/studio/issues/895#issuecomment-1083051249)(https://github.com/prisma/studio/issues/895#issuecomment-1083051249) a shot and see if it works for you?
