### ISSUE TITLE
Prisma Studio is not working

### ISSUE THREAD

**Issue by DeqodeSourabh** [prisma/studio#1028]
### Bug description

A non-recoverable error has occurred and Studio has to be restarted. Please consider reporting this error to us by opening an issue on GitHub and attaching the error details. If this persists, please clear out your IndexedDB and try again.

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
Hello - If you're still running into issues, please provide a few more details by filling in this issue with information such as the version you're using and relevant logs.Thanks!
