### ISSUE TITLE
How to navigate to related records?

### ISSUE THREAD

**Issue by schickling** [prisma/studio#103]
How do I navigate to the related `author` and/or `comments` here? 

![image](https://user-images.githubusercontent.com/1567498/64677993-f13d4800-d478-11e9-8e06-0df114f9c049.png)

**Comment by idan** [comment]
Requires further discussion around what a good UX is here
* Tree view is better at showing relations
* Table view can open new tabs pre-filtered?
* Needs design

**Comment by madebysid** [comment]
Here's a rough idea:

<img width="1778" alt="Screenshot 2020-01-13 at 15 05 51" src="https://user-images.githubusercontent.com/7689783/72345216-6f358800-36d3-11ea-8522-6ab203f6b51b.png">

We open relations as a separate pane. This works like the sidepanel we killed, but with the same table UI that we show everywhere else

**Comment by madebysid** [comment]
I've made it so Cmd+clicking on a relation cell opens that model in a new tab. Ideally though, this is the behaviour I'd like to have: https://github.com/prisma/studio/issues/474 (up for debate)
The new issue aligns with the fact that we plan to temporarily remove `Saved Tabs` till we have a better solution
