### ISSUE TITLE
I am getting non-recoverable error has occurred and studio has to be restarted

### ISSUE THREAD

**Issue by adityagupta-u1** [prisma/studio#1036]
### Bug description

![Screenshot (76)](https://user-images.githubusercontent.com/87804608/195171513-fd7a9e7d-4d5d-497a-833f-93c3fa20f718.png)

### Prisma information

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  // NOTE: When using postgresql, mysql or sqlserver, uncomment the @db.text annotations in model Account below
  // Further reading: 
  // https://next-auth.js.org/adapters/prisma#create-the-prisma-schema
  // https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string
  url      = env("DATABASE_URL")
}

model Example {
  id String @id @default(cuid())
}

// Necessary for Next auth
model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?
  user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  password      String?   @db.Text
  post          Post[]
  likes         Like[]
}

model Like {
  id        String   @id @default(uuid())
  user      User     @relation(fields: [userEmail], references: [email])
  userEmail String   
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  post      Post? @relation(fields: [postId], references: [id])
  postId    String? @unique
}

model Post {
  id        String   @unique @default(uuid())
  title     String
  body      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  user      User    @relation(fields: [userEmail], references: [email])
  userEmail String
  Like      Like[] 
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
Could you share any logs that are under "Show details"? Are you able to consistently reproduce the issue?
