### ISSUE TITLE
Fatal Error Issue

### ISSUE THREAD

**Issue by viandesmetropolitain** [prisma/studio#1043]
### Bug description

When i change a product code to another one that exist, the system shows a fata error

### Expected behavior

it should normally just change the data on the dataset and on what would appear to the users

### Environment & setup

- Link to Data Browser instance: 
- OS: 
- Browser: 
- Database: 

### Screenshot of page where the problem happened (if applicable)

![image](https://user-images.githubusercontent.com/115946223/196612464-ff24e72c-630d-4419-b440-ef6bc34d8103.png)

**Comment by petradonka** [comment]
Could you share the information under the "Show details" toggle section? That would help us figure out what's happening.

**Comment by viandesmetropolitain** [comment]
![WhatsApp Image 2022-10-22 at 1 17 25 AM (1)](https://user-images.githubusercontent.com/115946223/197321995-e76671ce-16ae-4edf-adb0-ac4c15e4c27f.jpeg)
![WhatsApp Image 2022-10-22 at 1 17 25 AM](https://user-images.githubusercontent.com/115946223/197321996-cf1d2f65-6ece-47b7-bcb7-2cb154ee7bc6.jpeg)

**Comment by petradonka** [comment]
Thanks for the extra info! Could you also share your schema file with us? That'll help us better nail down where this error could be coming from.
