### ISSUE TITLE
HTTP error 500

### ISSUE THREAD

**Issue by draew6** [prisma/studio#1046]
### Bug description

Fatal Error - Error in HTTP Request (Status: 500)

### How to reproduce

Error in HTTP Request (Status: 500)
When I or other user open project on any device. Its like that for a week minimum. I akready tried to remove DB from Dev Tools Application

### Prisma information

No changes in schema

### Environment & setup

- OS: Windows, ChromeOS, Android
- Browser: Chrome
- Database: Postgres

**Comment by petradonka** [comment]
Are you using Studio or the PDP Data Browser? Which Prisma version are you using locally?
