### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by edfragoso** [prisma/studio#1056]
### Bug description

Error starting Prisma Client: {
  "message": "\nYou don't have any \u001b[1mmodels\u001b[22m defined in your \u001b[1mschema.prisma\u001b[22m, so nothing will be generated.\nYou can define a model like this:\n\n\u001b[1m\u001b[36mmodel User\u001b[39m \u001b[38;2;107;139;140m{\u001b[39m\u001b[22m\n\u001b[1m  id\u001b[38;2;127;155;175m    Int\u001b[39m     \u001b[36m@id @default(autoincrement())\u001b[39m\u001b[22m\n\u001b[1m  email\u001b[38;2;127;155;175m String\u001b[39m  \u001b[36m@unique\u001b[39m\u001b[22m\n\u001b[1m  name\u001b[38;2;127;155;175m  String\u001b[39m?\u001b[22m\n\u001b[1m\u001b[38;2;107;139;140m}\u001b[39m\u001b[22m\n\nMore information in our documentation:\n\u001b[4mhttps://pris.ly/d/prisma-schema\u001b[24m\n",
  "stack": "\nYou don't have any \u001b[1mmodels\u001b[22m defined in your \u001b[1mschema.prisma\u001b[22m, so nothing will be generated.\nYou can define a model like this:\n\n\u001b[1m\u001b[36mmodel User\u001b[39m \u001b[38;2;107;139;140m{\u001b[39m\u001b[22m\n\u001b[1m  id\u001b[38;2;127;155;175m    Int\u001b[39m     \u001b[36m@id @default(autoincrement())\u001b[39m\u001b[22m\n\u001b[1m  email\u001b[38;2;127;155;175m String\u001b[39m  \u001b[36m@unique\u001b[39m\u001b[22m\n\u001b[1m  name\u001b[38;2;127;155;175m  String\u001b[39m?\u001b[22m\n\u001b[1m\u001b[38;2;107;139;140m}\u001b[39m\u001b[22m\n\nMore information in our documentation:\n\u001b[4mhttps://pris.ly/d/prisma-schema\u001b[24m\n"
}
Error: Error starting Prisma Client: {
  "message": "\nYou don't have any \u001b[1mmodels\u001b[22m defined in your \u001b[1mschema.prisma\u001b[22m, so nothing will be generated.\nYou can define a model like this:\n\n\u001b[1m\u001b[36mmodel User\u001b[39m \u001b[38;2;107;139;140m{\u001b[39m\u001b[22m\n\u001b[1m  id\u001b[38;2;127;155;175m    Int\u001b[39m     \u001b[36m@id @default(autoincrement())\u001b[39m\u001b[22m\n\u001b[1m  email\u001b[38;2;127;155;175m String\u001b[39m  \u001b[36m@unique\u001b[39m\u001b[22m\n\u001b[1m  name\u001b[38;2;127;155;175m  String\u001b[39m?\u001b[22m\n\u001b[1m\u001b[38;2;107;139;140m}\u001b[39m\u001b[22m\n\nMore information in our documentation:\n\u001b[4mhttps://pris.ly/d/prisma-schema\u001b[24m\n",
  "stack": "\nYou don't have any \u001b[1mmodels\u001b[22m defined in your \u001b[1mschema.prisma\u001b[22m, so nothing will be generated.\nYou can define a model like this:\n\n\u001b[1m\u001b[36mmodel User\u001b[39m \u001b[38;2;107;139;140m{\u001b[39m\u001b[22m\n\u001b[1m  id\u001b[38;2;127;155;175m    Int\u001b[39m     \u001b[36m@id @default(autoincrement())\u001b[39m\u001b[22m\n\u001b[1m  email\u001b[38;2;127;155;175m String\u001b[39m  \u001b[36m@unique\u001b[39m\u001b[22m\n\u001b[1m  name\u001b[38;2;127;155;175m  String\u001b[39m?\u001b[22m\n\u001b[1m\u001b[38;2;107;139;140m}\u001b[39m\u001b[22m\n\nMore information in our documentation:\n\u001b[4mhttps://pris.ly/d/prisma-schema\u001b[24m\n"
}
    at qs.init (http://localhost:5555/assets/index.js:1:82942)

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
Hey @edfragoso: as the error suggests, you need some models to be defined in your schema. Do you have any defined? Could you share your schema file?

**Comment by edfragoso** [comment]
Hello, thanks for your attention.
I'm learning, I solved the problem, don't ask me how!

**Comment by petradonka** [comment]
If you're just starting out with Prisma, I suppose you must've added models to your schema. Either way, glad to hear the problem is solved! 👌
