### ISSUE TITLE
Option --browser none is ignored

### ISSUE THREAD

**Issue by yanickrochon** [prisma/studio#1060]
### Bug description

My `package.json` looks like this:

```js
{
   "scripts": {
      "dev": "pnpm with-env prisma studio --port 5556 --browser none",
   }
}
```

But doing `pnpm dev`, the new browser window is _always_ open with Prisma Studio. This is especially annoying when restarting the app, as the browser tab needs to be closed, losing the focus to the editor in the process.

### How to reproduce

Use `pnpm` to start prisma studio.

### Expected behavior

If I set `---browser none`, no browser should be open.

### Prisma information

This is using `"@prisma/client": "^4.6.1"`

### Environment & setup

- OS: Linux (Debian)
- Browser: Brave (Chrome)
- Database: SQLite

### Prisma logs

```
app:dev: > @vit3x/db@0.1.0 dev /home/yanick/dev/node/vit3x/packages/db
app:dev: > pnpm with-env prisma studio --port 5556 --browser none
app:dev:
app:dev: > @vit3x/db@0.1.0 with-env /home/yanick/dev/node/vit3x/packages/db
app:dev: > dotenv -e ../../.env "prisma" "studio" "--port" "5556" "--browser" "none"
app:dev:
app:dev: Prisma schema loaded from prisma/schema.prisma
app:dev: Prisma Studio is up on http://localhost:5555
```
(Browser window opens at this point.)

**Comment by yanickrochon** [comment]
For what's worth, I see [this line](https://github.com/prisma/prisma/blob/8e90f8a1ca12f9b596f92bae811d9d92266aab7a/packages/cli/src/Studio.ts#L112)

```ts
    if (!browser || browser.toLowerCase() !== 'none') {
```

but even omitting the `--browser` option opens the browser.

**Comment by janpio** [comment]
Does it work when you run it without `with-env` but `prisma studio` directly?
I do not know `pnpm with-env`, but when using `dotenv-cli` manually you have to double `--` parameters for the original command. In your case that could mean `pnpm with-env prisma studio -- --port 5556 --browser none` for example. Otherwise `dotenv` gets the parameters `--port` and `--browser`.

**Comment by yanickrochon** [comment]
Ah! the `--` did the trick! Thanks!
