### ISSUE TITLE
bug this google chrome for codespace this github

### ISSUE THREAD

**Issue by Mateusnasciment** [prisma/studio#1064]
### Bug description

A non-recoverable error has occurred. Reload Studio to continue.
            Consider reporting this error to us by opening an issue on GitHub
            and attaching the error details.

### Environment & setup

- Link to Data Browser instance: 
- OS: 
- Browser: 
- Database: 

### Prisma logs

-

**Comment by Mateusnasciment** [comment]
s

**Comment by petradonka** [comment]
Hello - If you're still running into issues, please provide a few more details by filling in this issue with information such as the version you're using, relevant logs, error details, and what you're seeing happening. That'll help us figure out what's going wrong. Thank you!
