### ISSUE TITLE
Unable to process `count` query undefined

### ISSUE THREAD

**Issue by sir-guevara** [prisma/studio#1067]
### Bug description

A non-recoverable error has occurred. Reload Studio to continue. Consider reporting this error to us by opening an issue on GitHub and attaching the error details.
Unable to process `count` query
undefined

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
It looks like this is a duplicate of https://github.com/prisma/studio/issues/890, so closing this issue.
