### ISSUE TITLE
Fatal Error in prisma studio

### ISSUE THREAD

**Issue by matthieubouchard** [prisma/studio#1074]
1. Prisma version (`prisma -v` or `npx prisma -v`):
prisma: 3.15.2
@prisma/client: 3.15.2
Studio: 0.462.0

2. Logs from Developer Tools Console or Command line, if any:
```
The operation failed for reasons unrelated to the database itself and not covered by any other error code.
```
<img width="455" alt="Screen Shot 2023-01-05 at 5 35 08 AM" src="https://user-images.githubusercontent.com/10106752/210760084-28ca1954-3d3a-4ba7-a974-cc1705c707c8.png">

4. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
yes, seems related to studio
5. Prisma schema (if relevant):
```

```

I'm reporting because the feecback from studio suggested to. I see there is major update to 4.8.0 so I will try that when I have some time. I cleared out the indexedDB and still have the issue

**Comment by petradonka** [comment]
Thanks for sharing some details. Looks like you're on a pretty old version of Prisma, would upgrading be an option for you, and checking if you are still running into issues on the latest version?
