### ISSUE TITLE
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again. 

### ISSUE THREAD

**Issue by biancadcastro** [prisma/studio#1079]
### Bug description

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment]
Hey @biancadcastro - is this an issue specifically with Studio? Could you share a bit more information about the steps that are leading you to this error and what you'd expect to happen? Thank you.

**Comment by biancadcastro** [comment]
> Hey @biancadcastro - is this an issue specifically with Studio? Could you share a bit more information about the steps that are leading you to this error and what you'd expect to happen? Thank you.

it doesn't work too

**Comment by petradonka** [comment]
Could you share some more info about the steps that are leading you to this error? Does Prisma Client otherwise work, is the issue specific to Studio?
