### ISSUE TITLE
Browser based keyboard shortcuts

### ISSUE THREAD

**Issue by schickling** [prisma/studio#108]
There are currently a few keyboard shortcuts (e.g. `CMD + R`) that override browser specific shortcuts. We should discuss how we intend the behavior to be when using Studio in the browser as opposed to as a standalone desktop app. This is especially important as it seems like the browser version of Studio is the more common form of usage.

This is related to this spec: https://github.com/prisma/specs/tree/master/studio

**Comment by matthewmueller** [comment]
Are there any keyboard shortcuts that override browser behavior @madebysid? I've tested `cmd + r` & `cmd + 1`. 

In general, I don't think we should override _any_ browser shortcuts, but we should be able to alter shortcuts depending on context (e.g. electron).

**Comment by madebysid** [comment]
@matthewmueller I've currently disabled / remapped all shortcuts that I know conflict with native browser shortcuts.

About platform specific shortcuts: I'd like to have that as well. That isn't possible right now, but shortcuts were built keeping it in mind, so it will be once we decide to spend time on it.

**Comment by matthewmueller** [comment]
Perfection
