### ISSUE TITLE
Prisma studio start Error

### ISSUE THREAD

**Issue by hikaru-jinno** [prisma/studio#1083]
### Bug description

Error starting Prisma Client: {
  "code": "ENOENT",
  "message": "ENOENT: no such file or directory, copyfile '/Users/jinnohikaru/.cache/prisma/master/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/darwin-arm64/libquery-engine' -> '/usr/local/lib/node_modules/prisma/engines/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/libquery_engine-darwin-arm64.dylib.node'",
  "stack": "ENOENT: no such file or directory, copyfile '/Users/jinnohikaru/.cache/prisma/master/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/darwin-arm64/libquery-engine' -> '/usr/local/lib/node_modules/prisma/engines/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/libquery_engine-darwin-arm64.dylib.node'"
}
Error: Error starting Prisma Client: {
  "code": "ENOENT",
  "message": "ENOENT: no such file or directory, copyfile '/Users/jinnohikaru/.cache/prisma/master/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/darwin-arm64/libquery-engine' -> '/usr/local/lib/node_modules/prisma/engines/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/libquery_engine-darwin-arm64.dylib.node'",
  "stack": "ENOENT: no such file or directory, copyfile '/Users/jinnohikaru/.cache/prisma/master/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/darwin-arm64/libquery-engine' -> '/usr/local/lib/node_modules/prisma/engines/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/libquery_engine-darwin-arm64.dylib.node'"
}
    at qs.init (http://localhost:5555/assets/index.js:1:82961)

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by janpio** [comment]
Seems like a temporary problem. Open a new issue please if this is reproducible.
