### ISSUE TITLE
studio dont display data with id   String @id @default(uuid())

### ISSUE THREAD

**Issue by Thomasbzc** [prisma/studio#1118]
### Bug description

studio dont display data with id   String @id @default(uuid())

### How to reproduce

First of all you need to create an entity with  String @id @default(uuid())

### Prisma information

  id   String @id @default(uuid())
  name String
  description String
  url String
  datePublished DateTime

### Environment & setup

- OS: 
- Browser: 
- Database: 
any

**Comment by janpio** [comment]
What does it display instead?
