### ISSUE TITLE
Rethink design for (to-many) relations in table

### ISSUE THREAD

**Issue by schickling** [prisma/studio#112]
![image](https://user-images.githubusercontent.com/1567498/64687959-bc86bc00-d48b-11e9-9777-82f2dd380df6.png)

**Comment by idan** [comment]
@schickling @kuldar this screenshot doesn't capture the terribleness of the problem, can you shed a little more light on what makes this a bad UI?

**Comment by madebysid** [comment]
With the relation accordion as well as the `Open in New Tab` button, this shouldn't be as big of a problem anymore, so closing! Please do reopen if you feel otherwise!
