### ISSUE TITLE
`Error: spawn xdg-open ENOENT` on `prisma studio`

### ISSUE THREAD

**Issue by janpio** [prisma/studio#1128]
Some users are reporting that they get `Error: spawn xdg-open ENOENT` when running `prisma studio` (see parts of https://github.com/prisma/prisma/issues/19010).

A workaround is to tell Studio not to open a browser window:
```
  Start Studio without opening in a browser
    prisma studio --browser none
    BROWSER=none prisma studio
```

Background: Prisma Studio uses the npm package `open` to open a browser window with Studio when you run the command by default (https://github.com/prisma/prisma/blob/c7e97a5c39584aa24f2b15a5c4d4d6ecbab90a95/packages/cli/src/Studio.ts#L114-L117). It could be that a recent update in some operating system might have removed the default tool that is used for that.

What docker image or operating system are you getting this error?

**Comment by soulchild** [comment]
Seeing this with a `node-18:slim` Docker base image which (at the time of writing) is based on `Debian GNU/Linux 12 (bookworm)`.

**Comment by janpio** [comment]
Can you please try both the `node:18-bullseye-slim` and `18-bookworm-slim` Docker images to potentially pinpoint that the upgrade of `node:18-slim` from Bullseye to Bookworm might be the cause of this?

**Comment by janpio** [comment]
Another user @erlangparasu: https://github.com/prisma/prisma/issues/19010#issuecomment-1593866533

> Got `Error: spawn xdg-open ENOENT` too
> 
> ```
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.6 LTS
> Release:        20.04
> Codename:       focal
> ```
> 

_Originally posted by @erlangparasu in https://github.com/prisma/prisma/issues/19010#issuecomment-1593866533_

**Comment by janpio** [comment]
And another one @nikkhn:

> Can confirm im seeing the same issue with prisma version 4.15 when starting prisma studio

_Originally posted by @nikkhn in https://github.com/prisma/prisma/issues/19010#issuecomment-1593081646_
            
No OS information unfortunately.

**Comment by nikkhn** [comment]
@janpio I just downgraded versions and double checked, and it does not open Prisma Studio in the browser, just tells me that it is up on localhost.

**Comment by aqrln** [comment]
We identified the problem and have a solution in https://github.com/prisma/prisma/pull/19812.

**Comment by afturner** [comment]
And as a temporary fix, you can pass `--browser none` to `prisma studio` to prevent studio from trying to open the browser automatically.
