### ISSUE TITLE
Allow for column resizing

### ISSUE THREAD

**Issue by schickling** [prisma/studio#113]
![image](https://user-images.githubusercontent.com/1567498/64688566-ea203500-d48c-11e9-8151-1c346ee0278e.png)

Open Questions:

- [ ] How/where to store resizing
- [ ] What should happen if the underlying schema changes?
- [ ] Should this state be shareable across teams? (Idea: This could be handled via Prisma Cloud)

**Comment by idan** [comment]
This would be an obvious improvement, but if it's not great at Beta we will not die of shame. Marking post-beta for now.

**Comment by madebysid** [comment]
New table handles this now.
