### ISSUE TITLE
Prisma studio is loading data from cache after changes on database

### ISSUE THREAD

**Issue by jordisantamaria** [prisma/studio#1148]
### Bug description

I did **npx prisma migrate reset** to recreate a database with different tables and data, and prisma studio shows me the data I had before.

I tried to also clear browing data to remove cache but it didn't work.

### How to reproduce

1. Change database tables
2. Run **npx prisma migrate reset**
3. Run **npx prisma studio** and check data

### Expected behavior

Prisma studio showing new data

### Prisma information

```
Environment variables loaded from .env
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
```

### Environment & setup

- OS: Linux mint
- Browser: Chrome
- Database: SQLite

**Comment by janpio** [comment]
Prisma Studio doesn't really have a cache that would be able to contain all previous data. Are you sure `migrate reset` actually did remove the data? Can you confirm via an external tool? And are you sure Studio is using the same database?

**Comment by jordisantamaria** [comment]
Yes, I checked it with sqlite3.

Prisma studio:
![image](https://github.com/prisma/studio/assets/6263700/20eff31a-ce8e-454c-84ff-a748eedaffc4)

Sqlite3 (hiding some select * fields)
![image](https://github.com/prisma/studio/assets/6263700/19bb06a7-ebbe-45ca-a6b2-9bb14eaefcd1)

**Comment by janpio** [comment]
Prisma using even different colums than you get via `sqlite` indicates that Prisma Studio is running with a Prisma schema that defines these columns (e.g. `username`).

Are you sure everything is using the same database and Prisma schema (for `migrate reset` for example)?
Did you actually generate a migration for the current state of your Prisma Schema file?

**Comment by jordisantamaria** [comment]
I tried to run prisma studio like this `npx prisma studio --schema=./prisma/schema.prisma` and now it works fine.

**Comment by jordisantamaria** [comment]
Btw to test it, I created a project from this template repository https://github.com/epicweb-dev/epic-stack

**Comment by janpio** [comment]
Thanks for the update, that fits my expectations.
