### ISSUE TITLE
Equidistant column space distribution for databrowser columns

### ISSUE THREAD

**Issue by schickling** [prisma/studio#115]
I'm not a huge fan of the equidistant column space distribution for databrowser columns. I'd like to discuss whether we should just revert back to using the default column size outlined in #114 and accept potential unused whitespace to the right.

![image](https://user-images.githubusercontent.com/1567498/64688828-7599c600-d48d-11e9-94a0-bd044ff0f5f8.png)

**Comment by idan** [comment]
Closing in favor of #114
