### ISSUE TITLE
A persistent non-recoverable error has occurred.

### ISSUE THREAD

**Issue by ayfan1** [prisma/studio#1155]
### Bug description

Error starting Prisma Client: {
  "code": "EPERM",
  "message": "EPERM: operation not permitted, utime '/Users/frontend/.cache/prisma/master/2804dc98259d2ea960602aca6b8e7fdc03c1758f/darwin-arm64/libquery-engine'",
  "stack": "EPERM: operation not permitted, utime '/Users/frontend/.cache/prisma/master/2804dc98259d2ea960602aca6b8e7fdc03c1758f/darwin-arm64/libquery-engine'"
}
Error: Error starting Prisma Client: {
  "code": "EPERM",
  "message": "EPERM: operation not permitted, utime '/Users/frontend/.cache/prisma/master/2804dc98259d2ea960602aca6b8e7fdc03c1758f/darwin-arm64/libquery-engine'",
  "stack": "EPERM: operation not permitted, utime '/Users/frontend/.cache/prisma/master/2804dc98259d2ea960602aca6b8e7fdc03c1758f/darwin-arm64/libquery-engine'"
}
    at qs.init (http://localhost:5555/assets/index.js:1:82961)

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by janpio** [comment]
Seems like something blocked access to some file. Can you reproduce this?
