### ISSUE TITLE
Implement pagination for nested records in the Tree view

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#116]
Currently, if you expand a record with a 100K relations, they'll all just show up. Instead, show only the first 10, and load more using a `Load More` button (NOT infinite scroll). This will prevent a sudden performance degradation as soon as you open a record.

Also leads to situations like these:
![image](https://user-images.githubusercontent.com/7689783/64686823-9cee9400-d489-11e9-89f1-fcf5b9db48ec.png)

**Comment by idan** [comment]
I'm tempted to label this a bug as it can lead to users' browsers melting down.

**Comment by madebysid** [comment]
Moving out of beta for now, showing array slices should work for the time being.
