### ISSUE TITLE
Error Prims Studio

### ISSUE THREAD

**Issue by aymanechaaba1** [prisma/studio#1167]
### Bug description

Error starting Prisma Client: {
  "code": "EPERM",
  "message": "EPERM: operation not permitted, utime '/Users/aymane/.cache/prisma/master/61e140623197a131c2a6189271ffee05a7aa9a59/darwin-arm64/libquery-engine'",
  "stack": "EPERM: operation not permitted, utime '/Users/aymane/.cache/prisma/master/61e140623197a131c2a6189271ffee05a7aa9a59/darwin-arm64/libquery-engine'"
}

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by janpio** [comment]
Not enough information.

How can we reproduce this?
