### ISSUE TITLE
Same tabs get restored multiple times

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#117]
Sometimes, the same tabs get restored multiple times, not sure how it happens, or when.

![image (1)](https://user-images.githubusercontent.com/7689783/64692853-52274900-d496-11e9-8231-77db69f7554c.png)

**Comment by madebysid** [comment]
Shouldn't happen anymore. @schickling Please reopen if you see it again!

**Comment by madebysid** [comment]
Reopening because I saw it again

**Comment by idan** [comment]
Marked candidate for discussion during upcoming sync

**Comment by madebysid** [comment]
FINALLY happened to my machine as well. Steps to reproduce:

1. `prisma2 dev`
2. Stop `prisma2 dev` and start it up again.

When Studio tries to reconnect its WS connection (and succeeds), the same tab is restored again (since the app is bootstrapped again).

**Comment by idan** [comment]
🎉 Unmarked candidate as this is now a confirmed bug.

@madebysid please update with effort low/high as appropriate once you have a sense for how difficult this will be.  🙏

**Comment by madebysid** [comment]
This should be fixed now. Haven't seen it in a while, and there is now a test for this as well.
