### ISSUE TITLE
Databrowser: Adjust visual state when record is selected

### ISSUE THREAD

**Issue by schickling** [prisma/studio#118]
Instead of this:

![image](https://user-images.githubusercontent.com/1567498/64715652-2cfc0000-d4c1-11e9-8a4c-8f164b529368.png)

Should be:

![image](https://user-images.githubusercontent.com/1567498/64715669-3a18ef00-d4c1-11e9-8f1c-58b020b84dd4.png)

**Comment by madebysid** [comment]
Fixed with alpha.194
