### ISSUE TITLE
Use prisma-client-js's aggregations 

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#119]
Currently, `count` is not implemented in photon, but when it does, use that for the following cases:

1. When fetching the total number of records in a model's script
2. When fetching the count of related records in the table view

**Comment by idan** [comment]
Is this implemented in photon yet? @timsuchanek

**Comment by timsuchanek** [comment]
Yes, Photon exposes this! It's available on `photon.users.count()`

**Comment by madebysid** [comment]
We no longer show the total number of records in the sidebar anymore, so 1. is irrelevant now.

For 2., there isn't a way to count the number of relations via photon yet, so this issue unfortunately is still going to have to remain open.

**Comment by madebysid** [comment]
For the first point in the original post, created: https://github.com/prisma/studio/issues/214. This is possible and will be implemented using the current `.count()` query.

However, there are a couple of other things that are missing, documenting them here to be treated as requirements, so-to-speak.

1. It needs to be able to account for `after` & `skip` parameters, since these two params will directly affect the total number of records that are fetched. Studio allows you to manually specify these values for saved / detached queries in the databrowser. Since `.count()` does not take any parameters yet, the count on the databrowser might be wrong if the user changes them. Accounting for `skip` is simple enough by subtraction, but `after` might not always be possible.

2. For accomplishing the second point in the original post, there's no way to count the number of relations yet. The idea was to use these count to populate the relation counts in the results table rather than `include` the full relation as a field to be returned (as it is done right now).

Not sure what the priorities for these are.

Also created https://github.com/prisma/photonjs/issues/252 for this.

@idan @schickling This might affect the milestone on here.
