### ISSUE TITLE
Field selection: Add field type

### ISSUE THREAD

**Issue by schickling** [prisma/studio#120]
![image](https://user-images.githubusercontent.com/1567498/64783130-46f01e00-d567-11e9-9e33-aadf04c43e6b.png)

```
id ID
email String
name String?
...
```

**Comment by madebysid** [comment]
@schickling Next alpha release will have this.

This is how it looks:
<img width="295" alt="Screenshot 2020-03-27 at 16 18 06" src="https://user-images.githubusercontent.com/7689783/77771550-1d9c6880-7047-11ea-8833-72e26ca8ee86.png">

Also experimented with left alignment, but it looked funky:
<img width="302" alt="Screenshot 2020-03-27 at 16 17 38" src="https://user-images.githubusercontent.com/7689783/77771592-2a20c100-7047-11ea-8e10-7acf63e2278e.png">

Sticking with right-align for now!
