### ISSUE TITLE
Loading Priama

### ISSUE THREAD

**Issue by NuriBydel** [prisma/studio#1205]
### Bug description

A persistent non-recoverable error has occurred. Force reload to clear temporary data and reopen Studio. Consider reporting this error to us by opening an issue on GitHub and attaching the error details.
![Screen Shot 2024-01-24 at 7 04 57 am](https://github.com/prisma/studio/assets/112521603/aa43fbe4-88a9-45c3-bc0f-e1865433fa8e)

### Expected behavior

A persistent non-recoverable error has occurred. Force reload to clear temporary data and reopen Studio. Consider reporting this error to us by opening an issue on GitHub and attaching the error details.

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by janpio** [comment]
Not enough information, please share what is behind "Show details" next time. Thank you.
