### ISSUE TITLE
`.env.local` should take precedence over `.env`

### ISSUE THREAD

**Issue by pedrominicz** [prisma/studio#1212]
### Bug description

I have placeholder database credentials in `.env` while the real credentials are in `.env.local`. It is natural to do this in a Next.js project because I don't want to commit the credentials. However, when I run `npx prisma studio` Prisma tries to use the placeholder credentials.

### How to reproduce

In any Next.js project using Prisma:
1. Create a `.env` file with invalid placeholder database credentials
2. Create a `.env.local` file with the real credentials
3. Run `npm run dev`
4. Run `npx prisma studio`

The Next.js app will run without issues but Prisma Studio will not work.

### Expected behavior

Prisma Studio should give preference to `.env.local`.

### Prisma information

```
Environment variables loaded from .env
prisma                  : 5.10.1
@prisma/client          : 5.10.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v21.6.1
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.498.0
```

### Environment & setup

- OS: Archlinux
- Browser: Chromium
- Database: MongoDB

**Comment by janpio** [comment]
Prisma only supports `.env`. To use other files to load values into your environment variables, you can just use https://www.npmjs.com/package/dotenv-cli.
