### ISSUE TITLE
Static Hosting by Server?

### ISSUE THREAD

**Issue by keinsell** [prisma/studio#1217]
It's possible to static host prisma studio by server?

**Comment by janpio** [comment]
Here is an example: https://www.flightcontrol.dev/docs/reference/examples/prisma-studio

**Comment by keinsell** [comment]
@janpio Sorry but this do not solve thing I had on mind, solution you have presented is reverse proxy to `prisma studio` command I really want to avoid such because from my perspective it requires another container - I was thinking about "embdeeding" prisma studio into my current Golang server and serving it as static assets - is that possible?

**Comment by janpio** [comment]
No. Prisma Studio is run as a Node Express server, started via Prisma CLI.
