### ISSUE TITLE
Request for Statis IP for Data Platform

### ISSUE THREAD

**Issue by hckhanh** [prisma/studio#1224]
### Bug description

Can you enable Static ip in my data platform account: https://console.prisma.io/cltjxmm2800y9yc0vd388kzkf/overview

### Environment & setup

- Link to Data Browser instance: 
- OS: 
- Browser: 
- Database:

**Comment by nurul3101** [comment]
Hello @hckhanh 👋 

We are working on adding support for Static IPs and are planning to ship it very soon.

I'll inform you as soon as they are available for you to try out.

**Comment by nurul3101** [comment]
Hey folks 👋 

I'm following up as you have previously expressed interest in having Static IP support within Prisma Accelerate. We are excited to share that Static IP is now available with Prisma Accelerate!
 
You can enable Static IP for your Prisma Accelerate projects allowing for more secure connections to your databases by utilizing predictable IPs.
 
To enable Static IP for your Prisma Accelerate projects, a subscription to one of our paid plans is required. With your subscription active, enabling Static IP is effortless through the [Prisma Console](https://console.prisma.io/). It can be enabled for both new and existing projects directly within the Console. For more information on enabling Static IP, including step-by-step instructions, please visit our [blog post](https://www.prisma.io/blog/accelerate-static-ip-support) and the [documentation](https://www.prisma.io/docs/accelerate/).
