### ISSUE TITLE
PRISMA ERROR

### ISSUE THREAD

**Issue by kennykay20** [prisma/studio#1230]
### Bug description

I am having an error message to open prisma studio --- Error starting Prisma Client: {   "code": "EPERM",   "message": "EPERM: operation not permitted, utime 

### Prisma information

prisma : 5.12.1

### Environment & setup

OS: Mac OS
Browser: Chrome
Database: SQLite

**Comment by janpio** [comment]
Something blocked file access for Studio.

**Comment by kennykay20** [comment]
Hi, please can you share more light on this?

**Comment by janpio** [comment]
Not really. Something on your computer prevented the process to run `utime` on the file that is missing from the error your pasted here (it usually comes right after what you included). Can you share the full error message you are getting? When exactly are you getting it?
