### ISSUE TITLE
Inline cell editing: How to set a value to null?

### ISSUE THREAD

**Issue by schickling** [prisma/studio#124]
Additional question: Should this be doable using only the keyboard as well?

**Comment by johannesschobel** [comment]
`PgAdmin` (web interface for PostgreSQL) has a `Null?` checkbox when entering values to a respective cell.

Checking this field removes the current value and sets it to `null` ( as you may guess ;) )

**Comment by madebysid** [comment]
@schickling Here's a first prototype for this: https://87-prisma-studio.now.sh/preview?project=capabilities

In here, I render an extra `X` button on the currently active cell. Clicking on this button the first time will "clear" the value. This means the value will be set to `""` if the field is a String, `0` if the field is a Number etc. Clicking it again will set the value to `null`. This isn't out on alpha or anything yet, let me know how this feels, and we can take it from there.

**Comment by matthewmueller** [comment]
Sweet, I'm glad we have a way to do this now :-) 

I have a different interaction I'd like use to consider. Deleting with backspace defaults to the "lowest valid result". Here's what I mean:

Given a `Type`, when a cell is active and I press backspace, I get the following result:

|Type|Result|
|:-:|:-:|
|String|empty string|
|String?|null|
|Int|0|
|Int?|null|
|Float|0.0|
|Float?|null|
|DateTime|0001-01-01 00:00:00 +0000 UTC <sup>[1]</sup>| 
|DateTime?|null|
|Json|"null"|
|Json?|null|

<sup>[1]</sup> Or something like this. This is what Go does for empty times, but maybe it's dependent on the DB)

**Comment by madebysid** [comment]
@johannesschobel @schickling @matthewmueller This is now possible on alpha.

There isn't a button to do this (I don't think this is a common enough use case), but if you press `Delete` or `Backspace` on a cell, it will set that cell's value to its lowest valid state. The table above by @matthewmueller above is exactly how it behaves.
