### ISSUE TITLE
Design a state for viewing and editing list of scalars/enums in a table

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#125]

**Comment by idan** [comment]
Necessary for supporting PG lists and JSONB, I assume

**Comment by madebysid** [comment]
alpha.279 has UI to edit string, int, float and enum lists inline. It is similar to what we had in the details sidebar before it was removed.

@idan Could you check it out and see how it feels? Should we close this issue or do we keep it open for a better design?

**Comment by matthewmueller** [comment]
<img width="402" alt="Screenshot 2020-03-02 at 11 23 03" src="https://user-images.githubusercontent.com/170299/75667671-5891c300-5c78-11ea-8e44-c376b2613adf.png">

This is good enough for now.

**Comment by madebysid** [comment]
Closing, since @eemmiillyy implemented a better scalar list editing flow
