### ISSUE TITLE
Every time I open Prisma Studio it crashes

### ISSUE THREAD

**Issue by swxtz** [prisma/studio#1256]
### Bug description

Every time I open Prisma Studio it says that it was unable to communicate with the Prisma client, requiring me to reset the browser cache using shift + F5

### How to reproduce

1. Run the database.
2. Run <bun | pnpx | npx> prism migrate dev, to update the database.
3. Run <bun | pnpx | npx> Prisma Studio to open Prisma Studio
4. the bug appears

### Prisma information

prisma                  : 5.15.1
@prisma/client          : 5.15.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 5675a3182f972f1a8f31d16eee6abf4fd54910e3 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 5675a3182f972f1a8f31d16eee6abf4fd54910e3 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.15.1-1.5675a3182f972f1a8f31d16eee6abf4fd54910e3
Default Engines Hash    : 5675a3182f972f1a8f31d16eee6abf4fd54910e3
Studio                  : 0.501.0

### Environment & setup

- OS: Arch linux
- Browser: Brave
- Database: PostgresSQL
- Javascript Runtime: Bun 1.1.15

**Comment by dani-mp** [comment]
Hey, @swxtz, did you find a workaround in these two weeks? I'm also experiencing the same problem.

**Comment by dani-mp** [comment]
I realized my error was happening because a different process took port 5555. You can try with `npx prisma studio --port 5556` and see if that fixes it. It works for me now.

**Comment by janpio** [comment]
What error exactly are you getting @swxtz? Please post the full error message or a screenshot what you are experiencing. Thanks.

**Comment by swxtz** [comment]
I updated the lib and the error never occurred again so I won't be able to post a screenshot with the error
