### ISSUE TITLE
Prisma not working 

### ISSUE THREAD

**Issue by zaraduruji** [prisma/studio#1259]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by janpio** [comment]
What exactly is not working? You did not leave any information unfortunately about what error you are getting.
