### ISSUE TITLE
Have a (hidden?) configuration panel for experimental settings

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#126]
Potential list of configurations:
- Exposed theme variables 
- Table/content font size

**Comment by idan** [comment]
@kuldar @madebysid Would this have a meaningful impact on our development velocity?

**Comment by madebysid** [comment]
I think this would help Kukdar immensely, but needs a little bit of work on my end

**Comment by idan** [comment]
@madebysid effort low vs high?

**Comment by madebysid** [comment]
Relatively low effort I’d say
