### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by schickling** [prisma/studio#127]

**Comment by madebysid** [comment]
This exists now

**Comment by ali-master** [comment]
Hi @madebysid 

How can I contribute to the Prisma Studio?

**Comment by madebysid** [comment]
Hey @ali-master! Studio is unfortunately not open source, so there are currently no external contributors. 
I really appreciate the sentiment though, and if you want to contribute, there are other projects on the Prisma org that would love your support too!
