### ISSUE TITLE
Rethink "New tab flow"

### ISSUE THREAD

**Issue by schickling** [prisma/studio#129]
![image](https://user-images.githubusercontent.com/1567498/64790090-ce448e00-d575-11e9-91c8-22a77bc6b929.png)
![Image 3](https://user-images.githubusercontent.com/1567498/64790110-d997b980-d575-11e9-8a28-6f8781b6534b.jpeg)

**Comment by idan** [comment]
@schickling @kuldar What was the goal here? What will this improve/accomplish?

**Comment by idan** [comment]
Seems like a duplicate of #53?

**Comment by madebysid** [comment]
@hrescak has simplified this now, so there is only way to navigate. Closing!
