### ISSUE TITLE
Add spinner when complex tree field is loading

### ISSUE THREAD

**Issue by schickling** [prisma/studio#130]
![image](https://user-images.githubusercontent.com/1567498/64793372-3d70b100-d57b-11e9-9ddc-ecc6741fc703.png)

Also remove the loading indicator behind the field

**Comment by madebysid** [comment]
@schickling Is this issue the same as this loader we made a while ago?

<img width="424" alt="Screenshot 2019-10-22 at 12 10 48" src="https://user-images.githubusercontent.com/7689783/67276463-028c6200-f4c5-11e9-92f9-570d6b1aee47.png">

**Comment by schickling** [comment]
No the idea was to turn the "►" button (on the left side of a field) into a spinner while the data is still loading, so the user can't yet expand.
