### ISSUE TITLE
Prisma Studio standalone (mac) - Can't append "?sslmode=prefer" to Connection string

### ISSUE THREAD

**Issue by emolr** [prisma/studio#135]
I'm running a managed Postgres database on Heroku that requires `?sslmode=prefer` to connect. ( Found this tip somewhere by @schickling 👍).

But when trying to connect in Prisma studio, it serializes the `?` into `%3F` and therefore makes the connection impossible. 

I'm able to use studio via the `prisma2 dev` command and open `http://localhost:5555` in my browser.

**Comment by madebysid** [comment]
@emolr Ah, I was able to see this as well, I'll push out a fix soon and let you know!

**Comment by janpio** [comment]
Is this fixed @madebysid?

**Comment by madebysid** [comment]
Nope, I haven't looked at Electron issues for a while, since an official Electron app no longer exists (for the time being)
