### ISSUE TITLE
Error after connecting the database

### ISSUE THREAD

**Issue by vladimirvolek** [prisma/studio#136]
![image](https://user-images.githubusercontent.com/3112191/65193443-775e1d80-da7b-11e9-8ed7-4390d43d6b50.png)

**Comment by madebysid** [comment]
Hey @vladimirvolek, interesting that you're using the Electron version! Does this also happen when you open Studio when using `prisma dev`?

**Comment by madebysid** [comment]
Hey @vladimirvolek, please let me know if you're still seeing this on the latest `prisma2 dev` version, I'll reopen :)
