### ISSUE TITLE
[prisma2 sqlite] only create new user, then crash

### ISSUE THREAD

**Issue by gabrieltong** [prisma/studio#137]
<Anything that helps us reproduce the error goes here>

**Error dump**
Cannot read property 'model' of null

**Stacktrace**

    in C
    in div
    in C
    in Unknown
    in div
    in div
    in t
    in div
    in ks
    in div
    in Ra
    in div
    in fr
    in u
    in div
    in fr
    in div
    in C
    in div
    in div
    in div
    in div
    in C
    in div
    in Unknown
    in u

**Comment by madebysid** [comment]
Hey @gabrieltong, did you create the user from within Studio, or via a script?

**Comment by madebysid** [comment]
Hey @gabrieltong , please let me know if you're still seeing this with the latest preview (preview-13), and I'll reopen it!
