### ISSUE TITLE
Prisma Studio endpoint error" This site can’t be reached" 

### ISSUE THREAD

**Issue by ansarizafar** [prisma/studio#139]
I am using prisma2 preview 10 on Ubuntu 16.04 with Postgres here is my schema file
````
datasource db {
provider = "postgres"
url      = "postgresql://postgres:billgates3@localhost:5432/prisma"
}
generator js {
  provider = "photonjs"
}

model User {
  id        String   @default(uuid()) @id
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  }

enum Role {
  USER
  ADMIN
}
````

I am unable to access studio at  Studio endpoint: http://localhost:5555/ browser is showing "This site can’t be reached" message. No error is shown by prisma2 dev command
![image](https://user-images.githubusercontent.com/5788284/64471562-c0090300-d16c-11e9-8b10-f21cf4f50c38.png)

**Comment by idan** [comment]
Marked candidate for discussion at upcoming sync

**Comment by ansarizafar** [comment]
It's working on my machine now.
