### ISSUE TITLE
prisma studio failed to start

### ISSUE THREAD

**Issue by nicke** [prisma/studio#140]
When starting the newest prisma studio it shows only "Fallback Tab". In developer tools I see:

```
Studio version 0.94.0
studioBundle.js:94 Project load failed:  TypeError: Cannot read property 'hash' of null
    at ci.get hash (studioBundle.js:108)
    at ge (studioBundle.js:16)
    at e.computeValue (studioBundle.js:16)
    at e.trackAndCompute (studioBundle.js:16)
    at e.get (studioBundle.js:16)
    at e.read (studioBundle.js:16)
    at ci.get (studioBundle.js:16)
    at new ci (studioBundle.js:108)
    at hi.add (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at hi.i (studioBundle.js:16)
    at hi.getByScriptId (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at hi.i (studioBundle.js:16)
    at bi.switch (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at bi.i (studioBundle.js:16)
    at cn.init (studioBundle.js:108)

**Comment by madebysid** [comment]
Hey @nicke, At first glance it looks like Studio messed up during initial load (from IndexedDB)

Could you do me a favour and dump all IndexedDB data and put it in a gist somewhere?
```
(() => {
  const asyncForEach = (array, callback, done) => {
    const runAndWait = i => {
      if (i === array.length) done();
      return callback(array[i], () => runAndWait(i + 1));
    };
    return runAndWait(0);
  };

  const dump = {};
  const dbRequest = window.indexedDB.open("Prisma Studio");
  dbRequest.onsuccess = () => {
    const db = dbRequest.result;
    const stores = Array.from(db.objectStoreNames);

    const tx = db.transaction(stores);
    asyncForEach(
      stores,
      (store, next) => {
        const req = tx.objectStore(store).getAll();
        req.onsuccess = () => {
          dump[store] = req.result;
          next();
        };
      },
      () => {
        console.log(JSON.stringify(dump));
      }
    );
  };
})();
```

After this, if you clear IndexedDB, it should go back to normal. The IDB dump will probably help me figure out what broke. Thanks so much!

**Comment by nicke** [comment]
Hi @madebysid,

this is the result of the script 
{"actions":[],"enums":[],"fields":[],"models":[],"projects":[{"id":"ck0nnrjha0001xqjv226e9xse","activeTabId":"fallback-tab","tabOrder":[]},{"id":"ck0r2cjha0001n0ra647a1os6","activeTabId":"fallback-tab","tabOrder":[]}],"scripts":[],"sessions":[],"tabs":[]}

... and also this error:

VM111:20 Uncaught DOMException: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.
    at <anonymous>:20:24
    at runAndWait (<anonymous>:5:14)
    at <anonymous>:5:39
    at IDBRequest.req.onsuccess (<anonymous>:23:11)


After clear IndexedDB I get:

Studio version 0.92.0
studioBundle.js:94 ------Starting IndexedDB migration------
studioBundle.js:94 ---Running migration for v1---
studioBundle.js:94 Created projects table
studioBundle.js:94 Created openTabs table
studioBundle.js:94 Created sessions table
studioBundle.js:94 Created scripts table
studioBundle.js:94 ---Migrated to v1---
studioBundle.js:94 ---Running migration for v2---
studioBundle.js:94 Created models table
studioBundle.js:94 Created fields table
studioBundle.js:94 Created enums table
studioBundle.js:94 ---Migrated to v2---
studioBundle.js:94 ---Running migration for v3---
studioBundle.js:94 Found all sessions Array(0)
studioBundle.js:94 Found all scripts Array(0)
studioBundle.js:94 ---Migrated to v3---
studioBundle.js:94 ---Running migration for v4---
studioBundle.js:94 Created tabs table
studioBundle.js:94 Found all openTabs Array(0)
studioBundle.js:94 Deleted openTabs table
studioBundle.js:94 ---vMigrated to v4---
studioBundle.js:94 ---Running migration for v5---
studioBundle.js:94 Found all tabs Array(0)
studioBundle.js:94 Found all projects Array(0)
studioBundle.js:94 ---Migrated to v5---
studioBundle.js:94 ---Running migration for v6---
studioBundle.js:94 Added projectId to tabs table keyPath
studioBundle.js:94 Repopulating tabs with:  []
studioBundle.js:94 Added projectId to sessions table keyPath
studioBundle.js:94 Repopulating sessions with:  []
studioBundle.js:94 Added projectId to scripts table keyPath
studioBundle.js:94 Repopulating scripts with:  []
studioBundle.js:94 Added projectId to models table keyPath
studioBundle.js:94 Repopulating models with:  []
studioBundle.js:94 Added projectId to fields table keyPath
studioBundle.js:94 Repopulating fields with:  []
studioBundle.js:94 Added projectId to enums table keyPath
studioBundle.js:94 Repopulating enums with:  []
studioBundle.js:94 Created actions table
studioBundle.js:94 ---Migrated to v6---
studioBundle.js:94 ------IndexedDB migration complete------
studioBundle.js:94 Project load failed:  TypeError: Cannot read property 'hash' of null
    at gi.get hash (studioBundle.js:108)
    at ge (studioBundle.js:16)
    at e.computeValue (studioBundle.js:16)
    at e.trackAndCompute (studioBundle.js:16)
    at e.get (studioBundle.js:16)
    at e.read (studioBundle.js:16)
    at gi.get (studioBundle.js:16)
    at new gi (studioBundle.js:108)
    at vi.add (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at vi.i (studioBundle.js:16)
    at vi.getByScriptId (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at vi.i (studioBundle.js:16)
    at Si.switch (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at Si.i (studioBundle.js:16)
    at dn.init (studioBundle.js:108)

**Comment by madebysid** [comment]
That's super weird, looks like an empty DB, but it failed to start. I did push out one more release since this, so could you also maybe try the latest alpha? (npm i -g prisma2@alpha). If you still see it, would it be possible to upload your project to a repo so I can reproduce it? Thanks!

**Comment by nicke** [comment]
... it seems to be a problem using postgresql. MySQL is working using the same schema.

**Comment by madebysid** [comment]
Oh? Studio can't directly talk to your DB during `prisma2 dev`, so I think this might be something wrong on the CLI's end. Would it be possible to get the breaking schema? You could also create an issue on https://github.com/prisma/prisma2 if you can reliably reproduce the error, and someone should be able to take a look and figure out what's wrong!

**Comment by idan** [comment]
Marked candidate for discussion during upcoming sync
