### ISSUE TITLE
UI Regression: Improve design when `prisma dev` has stopped running

### ISSUE THREAD

**Issue by schickling** [prisma/studio#143]
![image](https://user-images.githubusercontent.com/1567498/65313099-1bd38300-db94-11e9-8bd9-dbc659b6c047.png)

Old design:

![image](https://user-images.githubusercontent.com/1567498/65313192-3f96c900-db94-11e9-8c4e-d29d23bfac5f.png)

**Comment by madebysid** [comment]
Assigning to myself, the thing is behind the tab bar. Fixed now.

**Comment by madebysid** [comment]
Fixed with alpha.194
