### ISSUE TITLE
Visualize whether field is nullable

### ISSUE THREAD

**Issue by schickling** [prisma/studio#144]
Problem: I'd like to see whether a field is nullable or not.

Screenshot (current version):
![image](https://user-images.githubusercontent.com/1567498/65336631-03c92700-dbc7-11e9-8796-f3ea5c7780a6.png)

Schema:
![image](https://user-images.githubusercontent.com/1567498/65336638-09267180-dbc7-11e9-8c95-6cafc7e4bc55.png)

This was visible in older design versions:

![image](https://user-images.githubusercontent.com/1567498/65336773-40951e00-dbc7-11e9-9345-4cf5a742cb1e.png)

**Comment by idan** [comment]
I'd like to think of this holistically together with #157 — whether the nullable is another icon or a tweak on the existing icons, alongside "readonly". Should feel like one system of iconography.

Out of curiosity:
* why did we abandon the older approach for icons?
* How do we handle custom field types, like dates?

**Comment by idan** [comment]
A quick experiment: 
![image](https://user-images.githubusercontent.com/22723/66155523-af657480-e5d4-11e9-9cc2-41b78e404773.png)

**Comment by schickling** [comment]
@idan note that my old screenshot was based on Prisma one which used GraphQL SDL to define your schema. Prisma 2 uses it's own Prisma Schema Language (PSL) with the following difference regarding nullability:

- GraphQL SDL: `optionalField: String` / `requiredField: String!`
- PSL: `optionalField: String?` / `requiredField: String`

**Comment by idan** [comment]
@schickling gotcha. Refreshed:

![image](https://user-images.githubusercontent.com/22723/66356883-908f1700-e921-11e9-87de-40bedb9de615.png)

**Comment by schickling** [comment]
@idan I think that'll do the trick for now. @kuldar what do you think?

**Comment by madebysid** [comment]
Will be available in alpha.267.
