### ISSUE TITLE
Sidebar improvements

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#147]
- [x] Add a bit stronger dropshadow to expanded sidebar
- [x] The cursor should be a `pointer` only when hovering over a link. Currently it stays `pointer` while hovering over any sidebar area.
- [ ] Decide if we need to keep the "expand sidebar" button at the bottom

![sidebar](https://user-images.githubusercontent.com/1710629/65489443-7712b780-deab-11e9-8d3b-cbbc82b931a5.gif)

**Comment by madebysid** [comment]
@kuldar 
> Decide if we need to keep the "expand sidebar" button at the bottom

This makes the sidebar sticky. The only other way to do that is by pressing Cmd+B. Are we thinking about getting rid of the stickyness altogether?

**Comment by madebysid** [comment]
Created https://github.com/prisma/studio/issues/152 for the Expand button discussion. The other two things on here should be out now on the latest alpha.
