### ISSUE TITLE
Databrowser table improvements

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#148]
- [x] When entering an edit mode on a boolean/enum cell, automatically make the current value be selected in dropdown and have the arrow keys affect the dropdown selection, not cell selection.
![enum-dropdown](https://user-images.githubusercontent.com/1710629/65490211-05d40400-dead-11e9-86d0-69e3535b3ffd.gif)

- [ ] When having a cell dropdown open, clicking on another cell should close the dropdown but also select the clicked cell
![dropdown-click](https://user-images.githubusercontent.com/1710629/65490346-46338200-dead-11e9-83c5-0621e5b15ba2.gif)

- [x] The selected row background and bottom/top borders should be full width even for just few column tables.
![Screenshot 2019-09-24 at 09 26 07](https://user-images.githubusercontent.com/1710629/65490461-7d099800-dead-11e9-98d8-d0bbdda9a0db.png)

- [x] When hovering a cell, the cursor should stay `default` and change to `text` only when editing a text cell
- [x] When cell is selected, `shift+enter` should expand selection to the whole row. (And maybe while whole row is selected, hitting `enter` would move selection to the first cell of the row?)
- [ ] This is low priority and I'm not sure how easy it is, but ideally we'd like to avoid having text being selected in cell, when a user double clicks on a cell to edit it. Note, that the text should still be selectable when click-dragging over it as usual. It's just the double click use-case when the flashing text selection seems weird.
![double-click](https://user-images.githubusercontent.com/1710629/65491102-b2fb4c00-deae-11e9-99a3-be3943c22973.gif)
- [x] While a cell is selected, hitting `tab` should move the selection to next cell and `shift+tab` to the previous cell. Ideally the selection movement would also wrap lines (moving right on a last column takes you to the first column of next record).
- [x] Hitting `esc` should deselect a cell/row

**Comment by madebysid** [comment]
@kuldar I've pushed out a version with fixes for the [x] items, please check it out and close this if it is all done!

A couple of notes on some items:
> When hovering a cell, the cursor should stay default and change to text only when editing a text cell
This was already happening, unless I misunderstood?

> This is low priority and I'm not sure how easy it is, but ideally we'd like to avoid having text being selected in cell, when a user double clicks on a cell to edit it. Note, that the text should still be selectable when click-dragging over it as usual. It's just the double click use-case when the flashing text selection seems weird.
Here's a discussion: https://github.com/prisma/studio/issues/153

> When having a cell dropdown open, clicking on another cell should close the dropdown but also select the clicked cell
This is not very simple to do the way I've implemented "click-outside"s. If this is something that you think is really worth it, I'll create a separate issue for it and tackle it in the next milestone!

**Comment by madebysid** [comment]
@kuldar I've pushed out a version (alpha.205) with fixes for the ticked items, please check it out and close this if it is all done!

A couple of notes on some items:

> When hovering a cell, the cursor should stay default and change to text only when editing a text cell

This was already happening, unless I misunderstood?

> This is low priority and I'm not sure how easy it is, but ideally we'd like to avoid having text being selected in cell, when a user double clicks on a cell to edit it. Note, that the text should still be selectable when click-dragging over it as usual. It's just the double click use-case when the flashing text selection seems weird.

Here's a discussion for this: #153

> When having a cell dropdown open, clicking on another cell should close the dropdown but also select the clicked cell

This is not very simple to do the way I've implemented "click-outside"s. If this is something that you think is really worth it, I'll create a separate issue for it and tackle it in the next milestone!

**Comment by kuldar** [comment]
>> When hovering a cell, the cursor should stay default and change to text only when editing a text cell

> This was already happening, unless I misunderstood?

I guess this will mostly be resolved by making cells non-selectable by default (#153), but currently the cursor changes to `text` mode every time you hover over a text, regardless if a cell is in edit mode.

![cursor](https://user-images.githubusercontent.com/1710629/65674557-1e7b2000-e04d-11e9-99f9-c6f8c429cd7b.gif)

**Comment by madebysid** [comment]
Agree, #153 will fix this.

> When having a cell dropdown open, clicking on another cell should close the dropdown but also select the clicked cell

Just to confirm, can I drop this one then?
