### ISSUE TITLE
Should text in the results table be selectable?

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#153]
I'm talking specifically about the ability to do this:

![Screenshot 2019-09-25 at 11 28 56](https://user-images.githubusercontent.com/7689783/65588430-cdedbf00-df87-11e9-9aa5-73f6c6212c6d.png)

This really is a very small detail, doesn't need a long discussion, but it is something that came to mind while building it.

Initially, I thought that selecting a cell's value without editing it might be a viable use-case, but I'm not so sure anymore.

Here are some factors I'm considering

Focusing on a couple of points by @kuldar on https://github.com/prisma/studio/issues/148:
> When hovering a cell, the cursor should stay default and change to text only when editing a text cell

and

> This is low priority and I'm not sure how easy it is, but ideally we'd like to avoid having text being selected in cell, when a user double clicks on a cell to edit it. Note, that the text should still be selectable when click-dragging over it as usual. It's just the double click use-case when the flashing text selection seems weird.

These two are contradictory, in a way. Default browser behaviour dictates that selectable text has that line-cursor icon. Default browser behaviour also dictates that double-clicking on some text selects the nearest word (which is what the second point is about)

While I can override both these behaviours, doing so wouldn't make it look like the text is selectable. Moreover, it is very common for text to be truncated by an ellipsis anyway. So now I'm thinking if selecting a cell's value without editing it really is a viable use-case in the first place.

For the Electron app's "native" feel, having selectable text is a no-no as well.

Since we are going for a spreadsheet-esque feel, I looked at Google Sheets/Airtable, who don't let you do this either. Not sure about Excel, but I doubt they do either.

Was wondering if @kuldar had any thoughts on this?

**Comment by kuldar** [comment]
I think it might be fine to disable the text selection, but then we should probably auto-select textfield's content when you're switching to "edit" mode. This way people can still double-click on a field and hit `cmd+c` to get the value.

**Comment by idan** [comment]
Another refinement: in view mode, have a "copy" button (clipboard icon) appear on hover. Having to do keyboard gymnastics to select an ellipsized cell is not a great experience.

**Comment by idan** [comment]
Done!
