### ISSUE TITLE
Non-editable UI for fields when connecting to a read-only database.

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#157]
Fields like the ID, createdAt, updatedAt are special fields that you cannot really change, but they hold values. @timsuchanek suggested we mark them as non-editable in the header somehow.

@kuldar Thoughts?

**Comment by schickling** [comment]
That's not necessarily true. You should for example be able to change the `id` value.

**Comment by idan** [comment]
Some drive-by suggestions:
* Readonly icon in editor
* Grey columns to indicate their disabled state
* Force these columns to be the leftmost ones if shown?

**Comment by matthewmueller** [comment]
Moving this to post-Beta. No columns should be read-only anymore, we're removing this assumption now that Prisma Client supports updating the `@id` column. 

In the future we'll support logging into read-only databases. For these cases, we'll want some sort of UI distinction (grayed out boxes or something)

**Comment by janpio** [comment]
> now that Prisma Client supports updating the `@id` column.

I think this is not true for auto incremented values.

**Comment by matthewmueller** [comment]
Looks possible!

```prisma
model b {
  id Int @id
}
```

![image](https://user-images.githubusercontent.com/170299/75793131-35960a80-5d6f-11ea-8846-ca18af03f12f.png)

**Comment by madebysid** [comment]
I think this issue is now irrelevant, given that all kinds of fields are now editable
