### ISSUE TITLE
Cannot read property 'model' of null

### ISSUE THREAD

**Issue by rpatelcode** [prisma/studio#158]
![image](https://user-images.githubusercontent.com/27360619/65651964-1b951680-dfde-11e9-92a2-1c8abe781b73.png)

**Error dump**
Cannot read property 'model' of null

**Stacktrace**

    in C
    in div
    in div
    in fr
    in div
    in t
    in C
    in C
    in div
    in div
    in div
    in div
    in C
    in div
    in Unknown
    in u

**Comment by rpatelcode** [comment]
![image](https://user-images.githubusercontent.com/27360619/65652165-de7d5400-dfde-11e9-99fb-7075cfe59da8.png)

**Comment by madebysid** [comment]
Hey @rpatelcode, I see you're on preview-12. Could you also try out the prisma2 alpha (you might want to clear your IndexedDB if you continue to see errors) using `npm i -g prisma2@alpha`? It includes some changes and fixes, and I just want to make sure this hasn't already been fixed. The alpha will land on the `preview` release today as well.

**Comment by rpatelcode** [comment]
Thank you so much @madebysid it has been started working now.
