### ISSUE TITLE
Render versions of dependencies in console.log

### ISSUE THREAD

**Issue by schickling** [prisma/studio#159]
![image](https://user-images.githubusercontent.com/1567498/65673685-8df01000-e04b-11e9-97c5-d6ba7d407280.png)

Related: 

- #180

**Comment by idan** [comment]
Is the goal here to `console.log` the studio version on boot?

**Comment by madebysid** [comment]
@idan The goal is to output versions of all prisma dependencies: photon, lift, and the CLI. Studio's version is already logged.

**Comment by idan** [comment]
Log as much info about the installed versions of CLI, photon, lift, etc
