### ISSUE TITLE
Studio doesn't show any data

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#163]
I'm trying to run this dataset using Prisma Studio: https://github.com/infoverload/datasets/tree/master/datasets/sqlite/climate

When running `prisma2 dev`, I successfully get an endpoint for Studio, but it doesn't show any data:

![image](https://user-images.githubusercontent.com/4058327/65754356-29978400-e111-11e9-893a-fa130a7eaa1e.png)

The SQLite browser proves that there is data in the DB file though:

![image](https://user-images.githubusercontent.com/4058327/65754401-47fd7f80-e111-11e9-97fc-f011afd20447.png)

- `City` has 105 records
- `MonthlyAvg` has 1260 records

**Comment by madebysid** [comment]
@nikolasburk Are you on preview-12 (Studio v0.92.0 in the DevTools console)? Could you also try this out with preview-13 which will be released today? There's a bunch of changes there, and I just want to make sure this still happens! If it does, could you also check to see if there are any errors in the Console / `prisma2 dev` CLI?

**Comment by nikolasburk** [comment]
Yes, currently on preview-12. I'll try with preview-13 once it's released 👍

**Comment by madebysid** [comment]
@nikolasburk Were you able to see this after preview 13 as well?

**Comment by nikolasburk** [comment]
Preview 13 seems to have fixed it, thanks! 🙏
