### ISSUE TITLE
Reload unintuitive

### ISSUE THREAD

**Issue by timsuchanek** [prisma/studio#164]
## Reload in Table Plus
![image](https://user-images.githubusercontent.com/1094804/65761905-16d87b80-e120-11e9-8bf8-2c9f663d4c70.png)

## Reload in Studio
![image](https://user-images.githubusercontent.com/1094804/65761940-28218800-e120-11e9-8365-11ae24967aba.png)

As a user, who just wants the data to reload, without knowing that Photon is used under the hood, I don't know, what `Run` means in this context. I just want the UI to reload.
I suggest either calling it `Reload` or replacing it with a reload icon.

**Comment by madebysid** [comment]
Just found this issue, this is done. Moreover, I've changed behaviour to say "Run" when you're in "Code" mode, and "Reload" otherwise (visual mode). I think the two different contexts warranted different actions.
