### ISSUE TITLE
Implement "install studio command into $PATH"

### ISSUE THREAD

**Issue by timsuchanek** [prisma/studio#166]
It's very cumbersome to need a `prisma studio` command running in the CLI all the time.

The same as Visual Studio Code allows you to just do `code .` in the terminal, I would like the same for studio: `studio .`, which opens the Electron App.

**Comment by divyenduz** [comment]
Internal note: dropping from this sprint because priority and spec (project based or db based or something else)

**Comment by idan** [comment]
[VS Code](https://code.visualstudio.com/docs/setup/mac) calls it "install 'code' command in PATH". We can call it the same thing.

Open questions:
* [ ] Where is this functionality exposed?
* [ ] What's the command itself? `studio`?
* [ ] What if `prisma dev` is not running? Stupid solution: "Please run the server with `prisma dev` first" error message

**Comment by idan** [comment]
Tempted to put this in post-beta but it's significant, let's discuss at sync

**Comment by idan** [comment]
Deprioritized because electron

**Comment by idan** [comment]
Given the future with `yarn add prisma`, this is kind of moot.
