### ISSUE TITLE
[Bug] Unable to commit changes.

### ISSUE THREAD

**Issue by KyleTryon** [prisma/studio#180]
My first time setting up Prisma2, I have created a custom schema.prisma to represent my data. I have received no errors when running `prisma2 dev` and there are no validation errors showing in VS code with the Prisma extension.

edit: can confirm it also happens on a standard template. Javascript > GraphQL + Auth with no changes made.

I am attempting to add a **user** via studio.

data model:
```
model User {
  id       String   @default(cuid()) @id
  username String
  joinDate DateTime @default(now())
  email    String   @unique
  password String
}
```

After clicking the commit button I receive this console log:
[prismastudioconsolelog.log](https://github.com/prisma/studio/files/3668209/prismastudioconsolelog.log)
Where it looks like perhaps the data was entered, but I do not see it.

And the "commit" button stays forever spinning.

![image](https://user-images.githubusercontent.com/33272306/65840547-81d4ae80-e2e8-11e9-9c03-8655b84a928a.png)

**Comment by madebysid** [comment]
Hey @KyleTryon, thanks for the detailed issue!
From the logs, I gather that you're on Studio version 0.92.0, which shipped with prisma2 preview-12. Could you also try this out on the latest preview (preview-13)? I just want to make sure this still occurs, since I was able to create a user with the standard template that you used on preview-13.

If it does, I can then start investigating!

**Comment by KyleTryon** [comment]
Steps to reproduce.

- run: `prisma2 init hello-world`
- select: `starter kit`
- select: `javascript`
- select: `GraphQL API (+ Auth)`
- select: `SQLite`

_side note: I generally work on windows via WSL but this install process dies. For these tests I am SSHd into a remote linux (ubuntu) box._

Once the setup is complete.

- run: `cd hello-world`
- run: `prisma2 dev`

I am given the IP  `Studio endpoint: http://localhost:5555/`

However, I am over my local network so I am accessing via `192.168.1.150:5555`

![image](https://user-images.githubusercontent.com/33272306/65972212-7f349f00-e437-11e9-8887-034ad0948c5b.png)

_side note: There was actually a warning at the bottom mentioned 5 unsaved changes that I pressed discard on. So the client I assume has some offline capabilities that saved that._

Filling in data:
![image](https://user-images.githubusercontent.com/33272306/65972310-a7240280-e437-11e9-9c75-66042d64dfeb.png)

Click commit

![image](https://user-images.githubusercontent.com/33272306/65972356-b6a34b80-e437-11e9-8eb5-e1de1df4d7c6.png)

Stuck.


I checked the npm package at this point and noticed that even in the new project preview 12 was used.

I removed that manually and ran `npm install --save prisma2`


Here is the current package.json

```
{
  "name": "graphql-auth",
  "version": "1.0.0",
  "dependencies": {
    "bcrypt": "3.0.6",
    "graphql-shield": "5.7.3",
    "graphql-yoga": "1.18.3",
    "jsonwebtoken": "8.5.1",
    "prisma2": "^2.0.0-preview-13.2"
  },
  "scripts": {
    "start": "node src/index.js",
    "seed": "node prisma/seed.js",
    "postinstall": "prisma2 generate"
  }
}
```

With prisma now updated I repeated the test and got the same results.

**Comment by KyleTryon** [comment]
I have reinstalled prisma2 on my Windows machine with WSL and as a sudo user the issue seems resolved. Interestingly prisma2 init still installed "2.0.0-preview-12" by default. 

Studio behaves differently now though but in either case it is working 👍
