### ISSUE TITLE
Float values are not shown

### ISSUE THREAD

**Issue by benjixx** [prisma/studio#181]
When a model has a field of type Float, its column in Prisma2 Studio does not show any values at all.
Fetching data via the generated Photon API seems to work fine though.

Update:
This is currently tested with Prisma2 version 2.0.0-preview-13.1, but I've seen this issue before.

**Comment by madebysid** [comment]
Hey @benjixx, I was able to see this as well, expect a fix soon! I'll let you know here when I push it out

**Comment by madebysid** [comment]
Hey @benjixx, could you try installing the latest alpha (`npm i -g prisma2@alpha`) and see if this is fixed? This will also land in the next preview release.

**Comment by benjixx** [comment]
@madebysid I just tested this with the latest `alpha` version. Working as expected now. Thanks for the quick fix.

**Comment by madebysid** [comment]
Awesome! Please reopen if you find any issues with it!
