### ISSUE TITLE
Pressing Tab while editing a cell should not focus the browser's address bar

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#185]
Instead, exit the edit mode and move to the next cell horizontally

**Comment by idan** [comment]
@schickling any reason this is a particular candidate compared to all the other UI bugs/tweaks?

**Comment by schickling** [comment]
@idan I'd like to prioritize a smooth "create new record" flow. This issue is a big friction point right now.

**Comment by schickling** [comment]
This still seems broken.

**Comment by schickling** [comment]
Or at least doesn't implement the intended behavior. When editing a cell and pressing tab, it should edit the next field instead of bluring the cell.

**Comment by madebysid** [comment]
So `Tab` and `Shift+Tab` move to the next/previous cell AND start to edit it? (Rather than pressing Right arrow, and then Enter)

**Comment by schickling** [comment]
Yes, exactly. Including selecting the cell content.

**Comment by madebysid** [comment]
Should work as intended now, although there are definitely some improvements to be made. Specifically with relations and how they work if you press Tab while editing a (string) cell and the next one is a relation.

It is a niche case and hard to explain over text, so let's talk in person.

Closing this since the original issue is solved. Please reopen if you still think this behaviour is off!
