### ISSUE TITLE
Non-shortcut way to delete a record

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#186]
There isn't a point and click way to delete a record right now, so if someone doesn't know (or use) shortcuts, deleting records looks unimplemeted.

**Comment by idan** [comment]
Can't CRUD without D, but then again we have been okay so far, can also get pushed to post-beta if we have more important things to do.

**Comment by ignatif** [comment]
@madebysid can you please tell what shortcut is?

**Comment by madebysid** [comment]
@ignatif You should be able to select a cell, then Cmd+Shift+Right Arrow to turn the selection into a row. Then delete records using the Delete button that shows up!

**Comment by seanemmer** [comment]
Are the shortcuts documented somewhere?

**Comment by madebysid** [comment]
@seanemmer Nope, but I will try and document them today, will let you know here!

**Comment by madebysid** [comment]
@seanemmer I've pushed out alpha.262 (`npm i -g prisma2@alpha`) with a shortcut cheatsheet that can be accessed using `Cmd+/`. We'll definitely improve this in the future, but it lists all shortcuts as of now, which should be helpful.
It'll also land in the next preview release.

**Comment by madebysid** [comment]
Latest alpha also now has checkboxes next to rows that should make it easier to select (and delete) them. Closing!
