### ISSUE TITLE
Implementation detail: Generate Photon when Studio Server is started, not when user opens Studio in the browser

### ISSUE THREAD

**Issue by schickling** [prisma/studio#188]
Related to #111

**Comment by idan** [comment]
Candidate because: needs milestone

**Comment by idan** [comment]
Also impact

**Comment by janpio** [comment]
(Renamed because `prisma2 dev` is not the relevant bit here, but the start of the Studio Server is.)

**Comment by madebysid** [comment]
Happens with alpha.234+
