### ISSUE TITLE
Cannot Delete Values

### ISSUE THREAD

**Issue by johannesschobel** [prisma/studio#189]
Dear Prisma Team,

i recently played around with `Studio` and i really like the idea of having an easy to use "database administration panel". Nice work on this application!

I recently stumbled upon the following issue.
Please consider the following model:
```
model Person {
  @@map("persons")
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  title      String?
  firstname  String?
  middlename String?
  lastname   String?

  birthdate DateTime?
  gender    Int?
}
```
and note that - especially the `middlename` is flagged as "optional" (nullable) parameter.

I now directly add a new row in `Studio` and enter respective values. However, if i want to remove a value (i.e., set it to the default `null` value), this is not possible, as it automatically "falls back" to the latest value.

In order to illustrate this issue, i have made a short screencast for you.
![bug_prismastudio_cannotdelete](https://user-images.githubusercontent.com/9431350/66024071-2cb8b880-e4f3-11e9-8698-214686404e58.gif)

Hope this helps!
All the best

**Comment by madebysid** [comment]
@johannesschobel Ah that's certainly a bug, I'll take a look at it and fix it soon! Will let you know here when I push it out!

**Comment by johannesschobel** [comment]
That is awesome.. Thanks for your support

**Comment by madebysid** [comment]
Hey @johannesschobel, I'm sorry I completely forgot to get back to you on this, this has been fixed for a while. Please reopen if you're still seeing this!

**Comment by johannesschobel** [comment]
Dear @madebysid , i think i already double-checked it some time ago :D Thanks for your help!
