### ISSUE TITLE
Error while scrolling and creating new record

### ISSUE THREAD

**Issue by schickling** [prisma/studio#196]
When having clicked „new record“ and then scroll to the bottom in this example: https://prisma-studio.now.sh/preview?dataset=climate

**Error dump**
undefined is not an object (evaluating 'a.toFixed')

**Stacktrace**

    in ta
    in div
    in Unknown
    in div
    in Unknown
    in Unknown
    in div
    in Es
    in div
    in t
    in div
    in ks
    in bu
    in div
    in mr
    in Hu
    in div
    in mr
    in div
    in Unknown
    in div
    in div
    in div
    in div
    in Unknown
    in div
    in u

**Comment by madebysid** [comment]
Do you happen to have a Float value in your schema? In either case, #200 NEEDS finishing so I can figure out what this really is.

**Comment by madebysid** [comment]
Should be fixed with alpha.231
