### ISSUE TITLE
Should created records go to the top of the results table?

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#199]
I mean records that are created, but not yet committed.

If there already are a bunch of records in the results table:

The created record goes at the very bottom of the results list, and the browser tries to focus the first cell, which means the results list scrolls to the bottom, which prompts a `Load More` query. I guess I could control this, but it'll be weird to do and will go against an interaction we've set up (scroll to the bottom to load more). This will load more records, and will, in turn lead to the limbo record being pushed further down. This will continue till you've loaded all records.

I suggest we have uncommitted records be on the top of the list. It is easier to handle in code, but will also serve as a way to separate limbo records from committed records.

**Comment by janpio** [comment]
Things we talked about here:
- Endless scrolling vs. paging?
- How do Git clients do it with add to stage vs. committed
- 2 views, one with new but uncommitted things (problem: 2 scroll areas)

**Comment by madebysid** [comment]
After a discussion with @idan, we decided to move all pending actions (unsaved changes) and have them as a sticky section (or a pinned section) on top of the databrowser. This would also include created records.

Addressing @janpio's points: 

1. This stays unaffected. We're keeping endless scrolling rather than a page based system
2. Git clients pin staged files to the top. My reference was Sublime Merge, but I'm fairly certain GitHub Desktop does the same.
3. There shouldn't be double scroll areas, since it is a pinned section. We did talk about the case when pinned actions completely cover the results in the databrowser, but decided that it is rare enough to ignore. If someone has a ton of changes like that, they'd most likely do it in a script, or "commit" changes in batches, which renders this state irrelevant.

Here's how it'll roughly look like: 
![Untitled 3](https://user-images.githubusercontent.com/7689783/67862859-297d1080-fb23-11e9-9707-d0127188743e.png)

**Comment by schickling** [comment]
Does @idan still need to provide a design proposal or is this already actionable @madebysid?

**Comment by madebysid** [comment]
This is now actionable by me.

**Comment by madebysid** [comment]
Will be out with alpha.279.
