### ISSUE TITLE
`studio` binary that can be run (with global install)

### ISSUE THREAD

**Issue by janpio** [prisma/studio#202]
If you install `prisma` globally, you could theoretically have a `studio` binary that you can call everywhere, also with similar parameters to `code .` and similar use cases.

**Comment by madebysid** [comment]
@janpio Would `prisma2 studio` do the same thing now?

**Comment by janpio** [comment]
Yes, that would probably be a shorthand thing. I am not sure if you can start a long running process via the npm binary (which would let you return back to the command line instead of having the process running).

**Comment by madebysid** [comment]
`prisma2 studio` could start the studio server in the background to achieve what you want. That would then return control back to the command line.

The server would then kill itself when all clients disconnect so it doesn't keep running forever
