### ISSUE TITLE
Improve landing page of https://prisma-studio.now.sh/

### ISSUE THREAD

**Issue by idan** [prisma/studio#204]
* [x] Add more datasets
* [ ] Slightly less minimalist design :)
* [ ] Link to other Prisma things!
* [x] A warning that the preview deployment is read-only

**Comment by madebysid** [comment]
Added Climate, Northwind and Chinook from https://github.com/prisma/prisma-datasets/tree/master/datasets/sqlite. Can add more if we come across others. I've made it so the process of doing so is now pretty trivial for me.
