### ISSUE TITLE
Photon queries seem to fail

### ISSUE THREAD

**Issue by schickling** [prisma/studio#216]
Example: https://github.com/prisma-labs/nexus-prisma/tree/master/examples/blog

![image](https://user-images.githubusercontent.com/1567498/66717860-f83fd900-eddd-11e9-8d30-0b7db5fcb37b.png)

**Comment by madebysid** [comment]
@schickling The prisma2 version on there was pretty old, there have been breaking changes to photon since then. I updated it to alpha.236 (latest as of now) and `prisma2 dev` on the directory seems to be working then.

Created PR: https://github.com/prisma-labs/nexus-prisma/pull/478

**Comment by madebysid** [comment]
On second thought, if you see this after multiple refreshes or something else other than `prisma2 dev`, please reopen and let me know!
