### ISSUE TITLE
Relation popup broken

### ISSUE THREAD

**Issue by schickling** [prisma/studio#218]
![image](https://user-images.githubusercontent.com/1567498/66744157-f88eb180-ee7b-11e9-9cb6-ae304d77a315.png)

Repro: https://prisma-studio.now.sh/preview?dataset=climate

**Comment by madebysid** [comment]
Weird, this seems to work for me for the same record you're looking at. Do you see any errors in the console, or any failed requests in the Network tab of DevTools?

**Comment by madebysid** [comment]
https://www.loom.com/share/d573ed1404694a4cab5595ad03a13c45

**Comment by madebysid** [comment]
@schickling After some digging around, I discovered that this was a race condition, but in the preview deployment app itself, not Studio, so wasn't happening on `prisma2 dev`. I've now fixed this on https://prisma-studio.now.sh. Let me know if you still manage to see it though.
