### ISSUE TITLE
Error screen: Show button to reset state

### ISSUE THREAD

**Issue by schickling** [prisma/studio#222]

**Comment by madebysid** [comment]
There is now a button to remove all data and reload for fatal errors starting alpha.254.

<img width="1089" alt="Screenshot 2019-10-17 at 18 40 01" src="https://user-images.githubusercontent.com/7689783/67029430-8df4a480-f10d-11e9-8cd0-3533bd6cedad.png">

I guess https://github.com/prisma/studio/issues/237 would bring more such buttons?
