### ISSUE TITLE
Introduce loading state of schema changes

### ISSUE THREAD

**Issue by schickling** [prisma/studio#225]
Similar to the "dev server unreachable" state but less "error"-like / more friendly.

![image](https://user-images.githubusercontent.com/1567498/66749527-617d2600-ee8a-11e9-83fa-5ea48c8859d4.png)

> Note: Superseds #188

**Comment by madebysid** [comment]
@schickling I've introduced a "banner" for this in alpha.242, we can possibly tweak this as we go.

<img width="2032" alt="Screenshot 2019-10-14 at 18 50 01" src="https://user-images.githubusercontent.com/7689783/66768678-74f0b700-eeb3-11e9-8f20-4ba06c8f1df9.png">
