### ISSUE TITLE
Can't hit enter for @id fields

### ISSUE THREAD

**Issue by schickling** [prisma/studio#235]
https://www.loom.com/share/fce2dc3b3e0c46d2bce9ffb78a04828d

**Comment by madebysid** [comment]
Wait, you shouldn't be able to edit ID fields at all. :P Not being able to hit Enter is then intended.

Editing ID fields has other consequences with respect to relations etc. that I'm not sure about (if the query engine handles it all, or if I'm supposed to handle it etc.). I'll take that up as a part of https://github.com/prisma/studio/issues/172

**Comment by madebysid** [comment]
Starting alpha.254, you won't be able to edit ID fields. You can still enter edit mode, but you won't be able to change it. I've made this design decision for now, documented it so we can discuss this next Tuesday!
