### ISSUE TITLE
First run on blank starter with MySQL - photon error

### ISSUE THREAD

**Issue by divyenduz** [prisma/studio#238]
To reproduce: 

1. Prisma init, blank project, MySQL
2. Run `prisma2 dev`

1. Prisma2 version (`prisma2 -v`):

```
divyendusingh [cli]$ prisma2 -v
prisma2@2.0.0-alpha.253, binary version: 332b3baf392a718cffaccff674ebea649d05fcbd
```

2. Logs from Developer Tools Console, if any:
![image](https://user-images.githubusercontent.com/746482/67073085-94733280-f186-11e9-9a5c-a662ce17a62d.png)

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
```groovy
datasource db {
  provider = "mysql"
  url      = "mysql://root:prisma@localhost:3306/p2-studio"
}

generator photon {
  provider = "photonjs"
}

model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

Observed error: 

![image](https://user-images.githubusercontent.com/746482/67073026-77d6fa80-f186-11e9-8ffc-380785b96533.png)

dev output shows that everything is up to date: 
![image](https://user-images.githubusercontent.com/746482/67073061-84f3e980-f186-11e9-8ebe-6bfbc67a4dd6.png)

Additional notes: 

- The database was created by the `prisma2 dev` command. 
- Clearing index DB fixed it though. Might be related to this https://github.com/prisma/studio/issues/234 as I had the same project path as an older project but new database (index DB from yesterday though)

**Comment by madebysid** [comment]
@divyenduz Yep this is most likely https://github.com/prisma/studio/issues/234, since the generated photon query was wrong.

As an FYI though, the photon.js status you see on `prisma2 dev` has nothing to do with Studio :P
Studio Server generates its own in-memory photon.

Closing this since it is a no-op, but we should discuss https://github.com/prisma/studio/issues/246 on Tuesday to get rid of problems like this.
