### ISSUE TITLE
Switching tab with keyboard shortcut (cmd + 1) closes an open tab

### ISSUE THREAD

**Issue by divyenduz** [prisma/studio#239]
This is only observed with `cmd + 1`, other shortcuts and using mouse to switch tabs works fine.

1. Prisma2 version (`prisma2 -v`):
divyendusingh [cli]$ prisma2 -v
prisma2@2.0.0-alpha.253, binary version: 332b3baf392a718cffaccff674ebea649d05fcbd

2. Logs from Developer Tools Console, if any:
NA

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
NA

GIF: 
![CleanShot 2019-10-18 at 09 12 57](https://user-images.githubusercontent.com/746482/67073690-ec5e6900-f187-11e9-9794-6c33d9ae39bf.gif)

**Comment by madebysid** [comment]
This should now be fixed with alpha.255!
