### ISSUE TITLE
Editing boolean observations

### ISSUE THREAD

**Issue by divyenduz** [prisma/studio#240]
Editing boolean observations:

1. Took a couple of clicks for the field to open the list (or maybe it is a double-click?)
2. While not selected, the cell shows `undefined` 

![CleanShot 2019-10-18 at 09 19 54](https://user-images.githubusercontent.com/746482/67074101-bbcaff00-f188-11e9-859f-54dddc6706dc.gif)

1. Prisma2 version (`prisma2 -v`):
divyendusingh [cli]$ prisma2 -v
prisma2@2.0.0-alpha.253, binary version: 332b3baf392a718cffaccff674ebea649d05fcbd

2. Logs from Developer Tools Console, if any:
NA

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
NA

**Comment by madebysid** [comment]
@divyenduz It is indeed a double click. In general, double-clicking in any cell takes you to an "edit" mode for the cell.

However, maybe we should make an exception for booleans/enums? Adding it as a candidate to discuss on Tuesday!

The `undefined` thing is a bug that I will look into right away!

**Comment by madebysid** [comment]
This should now be fixed with alpha.280
