### ISSUE TITLE
Partial "unconfirmed changes discard"

### ISSUE THREAD

**Issue by divyenduz** [prisma/studio#242]
In this image, I can discard all the uncommitted changes by clicking discard but how can I discard only one of these two lines? 🤔 

<img width="1631" alt="CleanShot 2019-10-18 at 09 28 05@2x" src="https://user-images.githubusercontent.com/746482/67074529-9ee2fb80-f189-11e9-9616-e418d7fec9d3.png">

Intuitively, I tired the following: 

1. Right click for a context menu for an option 
2. Trying to select the row and press delete

1. Prisma2 version (`prisma2 -v`):
divyendusingh [cli]$ prisma2 -v
prisma2@2.0.0-alpha.253, binary version: 332b3baf392a718cffaccff674ebea649d05fcbd

2. Logs from Developer Tools Console, if any:
NA

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
NA

**Comment by madebysid** [comment]
@divyenduz Ah discarding specific actions is unimplemented still. Adding this to be discussed on Tuesday!

**Comment by idan** [comment]
Commit or rollback is sufficient UI here. Closing/Wontfix.
