### ISSUE TITLE
Date fields - usability observations

### ISSUE THREAD

**Issue by divyenduz** [prisma/studio#243]
![image](https://user-images.githubusercontent.com/746482/67074810-23357e80-f18a-11e9-81bb-a603bac7fd03.png)

Observations: 

1. Selecting the field shows null, it should be blank
2. I don't know what date format to type 🙏. So. I wrote `2019-10-11` and trying to commit that lost all changes
![CleanShot 2019-10-18 at 09 33 36](https://user-images.githubusercontent.com/746482/67074948-7f000780-f18a-11e9-95ac-9a7fd55a16ec.gif)
3. It can show a nice placeholder like the ID field stating that "If the field is not provided, it will be auto generated" (a smaller version of this)

--- 

1. Prisma2 version (`prisma2 -v`):
divyendusingh [cli]$ prisma2 -v
prisma2@2.0.0-alpha.253, binary version: 332b3baf392a718cffaccff674ebea649d05fcbd

2. Logs from Developer Tools Console, if any:
NA

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
NA

**Comment by madebysid** [comment]
alpha.268 will have the following improvements that should help:

1. When you first edit the date AND it is empty, the value is automatically set to the current date. That should help people figure out what the format is.
2. The input's placeholder itself is now a (sample) ISO String, so even if you clear the input, that should be a helpful hint.

On top of all this, we have validation for actions now, so the field should turn red if you enter the wrong format.

This will also be helped in the near future when we have a proper date selector!

**Comment by madebysid** [comment]
Hey @RyanCwynar, I don't understand, are you looking for a date picker for editing? 
If so, then that's not planned right now, but we do realize that it is a good-to-have. Perhaps you could create a separate issue for its implementation?

If not, could you elaborate?

**Comment by RyanCwynar** [comment]
Ha. I think this was about being able to edit dates from the UI -- but not necessarily a datepicker. I think a simpler thing would just be to caste to ISO. So if I enter "2020-09-01" it can just assume zero values for all the time stuff. 

Not sure if this is something it already does? But I remember it.. not acting in an intuitive way. I sort of forgot the context, I was prototyping something with prisma a couple months ago and am about to again.. so I may return shortly with fresh context on the topic.

But if the first part makes sense and I'm not imagining things, I'll make another ticket.

**Comment by madebysid** [comment]
Ah yeah back then you had to enter a fully formed ISO string, but not anymore! You should be able to enter a partial date, and after you finish editing, your value will automatically be casted to an ISO string. So if you type in `2020-09-01` and press Enter, it'll get converted to `2020-09-01T00:00:00.000Z`.

I essentially use `new Date(<your-value>).toISOString()` internally, so its behaviour stand. Hopefully that's what you were looking for :)
