### ISSUE TITLE
Bug with adding records using the UI

### ISSUE THREAD

**Issue by tvvignesh** [prisma/studio#251]
Hi. I was trying to add records to a schema (which was related) like below. If you noticed, I had a schema for Phone, User and Email all of them with their own definitions and I was able to successfully commit using the UI to Phone and Email but when I try to reference those records in User schema I get the error in dev console like below and am not able to commit records.

![Screenshot from 2019-10-27 11-33-02](https://user-images.githubusercontent.com/1165845/67630490-93d94b00-f8ae-11e9-9553-089177969c06.png)

Schema below:
```
model Phone {
    id            String   @default(cuid()) @id
    alias         String
    contactNo     String
    contactType   String
    settingListID String[]
    tagListID     String[]
    createdDate   DateTime @default(now())
    updatedDate   DateTime @updatedAt
}

model Email {
    id            String   @default(cuid()) @id
    alias         String
    emailAddress  String
    emailType     String
    settingListID String[]
    tagListID     String[]
    createdDate   DateTime @default(now())
    updatedDate   DateTime @updatedAt
}

model User {
    id            String   @default(cuid()) @id
    firstName     String
    lastName      String
    displayName   String
    username      String
    dob           DateTime
    createdDate   DateTime @default(now())
    updatedDate   DateTime @updatedAt
    email         Email[]
    phone         Phone[]
    settingListID String[]
    tagListID     String[]
}
```

@madebysid  @pantharshit00

**Comment by madebysid** [comment]
@tvvignesh I think this is the same root issue as https://github.com/prisma/studio/issues/257, which is now fixed. Could you check to see if you're still seeing this in the latest alpha (alpha.389)
