### ISSUE TITLE
Improper count shown when selecting from a related schema

### ISSUE THREAD

**Issue by tvvignesh** [prisma/studio#252]
As you may see in the screenshot below, there is only one record added and selected but it shows 2 records selected as below.

Also, if you notice, it says: **Showing 1 of 0** while the total number of records available from the list you see is 1.

**Steps to reproduce:**

Double click to select the related schema, check the record. It shows 2 rows selected

![Screenshot from 2019-10-27 11-31-56](https://user-images.githubusercontent.com/1165845/67630547-68a32b80-f8af-11e9-8675-5cdbf4662f55.png)

Uncheck the one row and select it back again. It shows 1 row selected

![Screenshot from 2019-10-27 11-32-11](https://user-images.githubusercontent.com/1165845/67630546-68a32b80-f8af-11e9-939c-db7f83c16167.png)

**Comment by madebysid** [comment]
@tvvignesh I've made some changes to this dialog specifically and cannot seem to reproduce this anymore. Could you try out the latest alpha (alpha.276) and check if you still see this?

**Comment by madebysid** [comment]
@tvvignesh There was one issue here that wasn't fixed, but with the latest alpha (alpha.389), this should now work as expected. Please reopen otherwise!
