### ISSUE TITLE
Select All checkbox does not work in the UI when clicked

### ISSUE THREAD

**Issue by tvvignesh** [prisma/studio#253]
Hi. While I am able to select records individually using the checkbox, the event on select all button does not work. I don't find any error or logs in the console as well when clicked. I guess the event is not bound. Even tried refreshing the page and tried again.

![Screenshot from 2019-10-27 12-32-41](https://user-images.githubusercontent.com/1165845/67631011-79a36b00-f8b6-11e9-9f97-c37cd1994d4c.png)

@madebysid

**Comment by madebysid** [comment]
@tvvignesh Thanks for reporting! I just checked, and this is indeed unimplemeted, I'll have a fix out on alpha soon!

**Comment by madebysid** [comment]
@tvvignesh Hello! This is now (finally) fixed with the latest alpha (alpha.389 as of now), please give it another shot!
