### ISSUE TITLE
Minor UI issue: Optional / Question mark not shown for some fields

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#255]
1. Prisma2 version (`prisma2 -v`):

```
prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe
```

I have this model:

```prisma
model Item {
  id           String   @default(cuid()) @id
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  purchaseDate DateTime?
  name         String
  type         ItemType
  locatedIn    Room?
  invoice      Invoice?
  price        Float?
}
```

In the UI, Studio properly shows a question mark at the `locatedIn` and `invoice` fields but doesn't show it for `price` and `purchaseTime` even though that's also marked as optional on the model:

![image](https://user-images.githubusercontent.com/4058327/67670230-bd0fdf00-f973-11e9-80aa-7e6af08ab098.png)

**Comment by madebysid** [comment]
@nikolasburk I'm unable to reproduce this with the schema you've added. Are you still seeing this?

**Comment by nikolasburk** [comment]
Nope, seems to be fixed 👍
