### ISSUE TITLE
Can't add record that gets connected to another existing record upon creating

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#257]
I am trying to create a new `Item` record and connect it to an existing `ItemType` record based on these models:

```prisma
model Item {
  id           String   @default(cuid()) @id
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  purchaseDate DateTime?
  name         String
  type         ItemType
  locatedIn    Room?
  invoice      Invoice?
  price        Float?
}

model ItemType {
  id    String @default(cuid()) @id
  name  String @unique
  items Item[]
}
```

However, the `Item` record can't be created:

### Provide values for all fields

**Before commit**

![image](https://user-images.githubusercontent.com/4058327/67670353-019b7a80-f974-11e9-8df7-ec389617fa6a.png)

**After commit**

![image](https://user-images.githubusercontent.com/4058327/67670367-0bbd7900-f974-11e9-8c2d-e4f4f585400e.png)

### Provide values only for required fields: `name` and `type` 

**Before commit**

![image](https://user-images.githubusercontent.com/4058327/67670493-4fb07e00-f974-11e9-8509-20e098c8738e.png)

**After commit**

![image](https://user-images.githubusercontent.com/4058327/67670505-563ef580-f974-11e9-8f50-bfb609f4950c.png)

This is the warning message that was printed:

```
All actions were not processed. Pending actions:  {
  "Item": {
    "Item::2154fb85-6945-42dc-ad6a-a951267fe124": {
      "update": {
        "type": {
          "connect": "ItemType::ck23c7p44000014cbspsiwuuw"
        }
      }
    }
  }
}
```

```
Photon requests:  "photon.items.create(
{
  "data": {
    "name": "Some item"
  },
  "select": {
    "id": true,
    "name": true
  }
}
)"
```

1. Prisma2 version (`prisma2 -v`):

```
prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe
```

**Comment by madebysid** [comment]
@nikolasburk alpha.337 should have a fix for this, please give it a shot and let me know if you're still seeing this!

**Comment by madebysid** [comment]
Going to close this, I think this is fixed. Please reopen otherwise!

**Comment by bek-shoyatbek** [comment]
Did you find the solution , I'm facing the same problem
