### ISSUE TITLE
Updating code on hot reload in admin UI

### ISSUE THREAD

**Issue by tvvignesh** [prisma/studio#258]
Hi. This is a minor enhancement - You can take it very low on priority. When you run `prisma2 dev` everything is good and when I make modifications to my schema, it autoreloads without any issues. But, the code generated is not updated on hotreload.

Screenshot below - Notice that I modified the name userSchema to user which is updated in the Admin UI but the code still shows userSchema with error. You may want to update the references of the variable as well in the code as well on schema changes (something like what VSCode does when renaming imports).

![Screenshot from 2019-10-26 18-44-37](https://user-images.githubusercontent.com/1165845/67620114-ea984380-f820-11e9-81cf-5140eaf6ea40.png)

**Comment by madebysid** [comment]
@tvvignesh Is this the (auto-generated) script for one of the models? In that case, it should update and this is a bug.

If this is a script that you've written yourself, then Studio doesn't attempt to change it, since it'd require parsing JS. This can then be an improvement!

**Comment by tvvignesh** [comment]
@madebysid Thanks for the clarification. This was the autogenerated script. I just changed the schema file and studio got hot-reloaded and then saw this error. If it occurs again, I will confirm.
