### ISSUE TITLE
Adding Records with Required Fields has confusing UI

### ISSUE THREAD

**Issue by do4gr** [prisma/studio#260]
When adding a new record which has some of its fields required, the fields are pre-populated in the UI with default values. If not all of them are changed to user-entered values, the complete record is lost when hitting commit. There is no error message. 

Then all data needs to be entered again. Took me a bit to figure that out. Maybe required fields that would invalidate the commit should be colored?

**Comment by idan** [comment]
Discussed at review:
* Save button disabled until valid state is reached
* No placeholder values, they're a lie
* Red outline and icon for "invalid" state. Invalid because bad value, no value, etc. Yellow background for "new" fields.

**Comment by madebysid** [comment]
@do4gr This is now addressed with alpha.280
The placeholders shown are no longer lies. Moreover, the default value for fields when you create a new record now come from the Prisma Schema (if you have a `@default` attribute set). If not, then they fall back to sensible defaults. They're also no longer for show. They're real values that will be committed if you press save.

About the loss of data, that shouldn't happen anymore. You are now unable to commit if you have at least one invalid field value. If you click on the red pill that says `x Invalid changes`, it will take you to the first field with an invalid value. Rinse and repeat till you fix all problems, and then the `Save Changes` button will be enabled.

Let me know if you still face issues / have suggestions for improvement :D

**Comment by schickling** [comment]
@do4gr can you indeed confirm this issue addressed sufficiently for you?

**Comment by do4gr** [comment]
Sorry, somehow didn't catch the notification. 

The changes sound sensible to me. 

Just one question about the sensible default values: Are these valid when I press submit? My concern would be I add a big new row, and there are already values in required fields pre-populated by studio and now I am not sure whether I added the value or it is a default value that studio chose or it is a default value from the schema. And I could now just commit this without a warning right? 

I am not sure what behaviour I would want there, but maybe at least have these fields in a different color? If the user wanted the field required and did not specify a default value in the schema we should probably not make it too easy to have values in there.

**Comment by madebysid** [comment]
> Are these valid when I press submit?
Yep values generated by Studio (either by reading defaults from your schema or falling back to something are considered "valid"

> ... And I could now just commit this without a warning right?
Yes you can.

> If the user wanted the field required and did not specify a default value in the schema we should probably not make it too easy to have values in there.
I think that sounds sensible, not sure. Maybe we can discuss this next Tuesday? @schickling
