### ISSUE TITLE
Improve UX for keyboard-only "Add record" flow

### ISSUE THREAD

**Issue by schickling** [prisma/studio#261]
Currently it's not possible to add a record just using my keyboard but should be. Here is an example demonstrating what I'd like to see:

- Click "Add record"
- Studio automatically focusses first cell in edit mode
- User fills out value, presses tab, fills out next value, ...
- Presses CMD + Enter (?) to create the record

Note: It's fine for now to "ignore" relational fields for the scope of this issue.

**Comment by idan** [comment]
tl;dr CMD-enter shortcut to commit

**Comment by madebysid** [comment]
This is now possible on alpha.

After some discussion with @matthewmueller, we decided on the following behaviour:

Cmd+Enter will create a new record and focus you on the first field of that record. You can then change values if you just start typing, press Tab, and go on.

Once you're done, Cmd+S will "commit" your changes (save them to your DB)
