### ISSUE TITLE
Unify flows: Model selection / New tab

### ISSUE THREAD

**Issue by schickling** [prisma/studio#265]
There are currently a lot of different ways to roughly accomplish the same. We should think through whether we could/should unify these flows:

## 1. Via visual query builder

![image](https://user-images.githubusercontent.com/1567498/68030333-87436100-fcb9-11e9-9100-cbfa0e11c5df.png)

## 2. Via new tab popup

![image](https://user-images.githubusercontent.com/1567498/68030381-a510c600-fcb9-11e9-8602-cda42c6581a4.png)

## 3. Via sidebar

![image](https://user-images.githubusercontent.com/1567498/68030395-ae9a2e00-fcb9-11e9-9ffa-0e88181fcf9e.png)

## 4. Via code-based query builder

This flow could probably be ignored for the sake of this issue though.

![image](https://user-images.githubusercontent.com/1567498/68030431-beb20d80-fcb9-11e9-8b24-f23d9e43544a.png)

**Comment by madebysid** [comment]
@hrescak did this a while ago, and now we have a `New Tab` page. Closing!
