### ISSUE TITLE
Invalid field when opening

### ISSUE THREAD

**Issue by schickling** [prisma/studio#268]
https://prisma-studio.now.sh/preview?project=capabilities

![image](https://user-images.githubusercontent.com/1567498/68136734-0c32b280-ff26-11e9-8e96-1495075795e2.png)

**Comment by madebysid** [comment]
@schickling That's a photon issue I think. Reported it here: https://github.com/prisma/prisma2/issues/881

**Comment by matthewmueller** [comment]
The DateList has been removed from Capabilities. Is this still a problem @madebysid ?
