### ISSUE TITLE
Design ideas: Better data tables

### ISSUE THREAD

**Issue by schickling** [prisma/studio#272]
I recently came across this [**fantastic blog post**](https://uxdesign.cc/design-better-data-tables-4ecc99d23356) about designing better data tables. This describes a lot of great patterns that we had on our roadmap anyway.

**Comment by madebysid** [comment]
Things that are pretty low effort and can be tackled right after today's release:

- [ ] Sticky ID field (this would also mean the ID field is always the first column)
- [ ] Zebra stripes on rows
- [ ] Display density
- [ ] Expandable rows (The tree view might be better for viewing large amounts of data though)
- [ ] Sortable columns

RELATIVELY higher effort
- [ ] Searchable columns
- [ ] 

Let me know which ones you think are worth doing
cc @idan
