### ISSUE TITLE
Error: undefined target="exit"

### ISSUE THREAD

**Issue by schickling** [prisma/studio#273]
![image](https://user-images.githubusercontent.com/1567498/68426462-7e1a2e80-01a8-11ea-9283-6f8088b7f88b.png)

Repro:
[script.zip](https://github.com/prisma/studio/files/3821632/script.zip)

**Comment by madebysid** [comment]
Fixed with alpha.293. Was a side-effect of a breaking change from Photon. Will go out with today's hotfix as well.
