### ISSUE TITLE
prisma studio error

### ISSUE THREAD

**Issue by garyro** [prisma/studio#276]
I've attached my schema file

**Error dump**
e is null

**Stacktrace**

    in u
    in div
    in u
    in div
    in lc
    in div
[schema.prisma.txt](https://github.com/prisma/studio/files/3825538/schema.prisma.txt)

    in u

**Comment by garyro** [comment]
I can not read my original issue (not sure why). Sorry I haven't followed up I think the problem I was having was related to query-engine-linux-glibc-libssl1.1.0  for whatever reason I had several instances of it running. I assume from things not exiting properly. Once I removed them this issue and a few others disappeared. Now when I have a problem the first thing I check is, is more than one instance of the query engine running (which seems to happen periodically). Anyway this issue seems to be solved.

**Comment by madebysid** [comment]
Ah, okay! Please reopen if you see this in the future!
