### ISSUE TITLE
Error when trying to create a record

### ISSUE THREAD

**Issue by chrisdrackett** [prisma/studio#278]
Just trying to add a user via studio. I get the following:

**Error dump**

Invalid `photon.users.create()` invocation:

{
  data: {
    id: '',
    createdAt: '2019-11-12T17:52:20.468Z',
    updatedAt: '2019-11-12T17:52:20.468Z',
    name: 'Bob',
    email: 'bob@bob.com',
    following: {
      set: []
      ~~~
    },
    followers: {
      set: []
      ~~~
    },
    logs: {
      set: []
      ~~~
    },
    projects: {
      set: []
      ~~~
    },
    items: {
      set: []
      ~~~
    },
    itemsCreated: {
      set: []
      ~~~
    },
    projectsCreated: {
      set: []
      ~~~
    }
  },
  select: {
    id: true,
    createdAt: true,
    updatedAt: true,
    name: true,
    email: true,
    following: true,
    followers: true,
    logs: true,
    projects: true,
    items: true,
    itemsCreated: true,
    projectsCreated: true
  }
}

Unknown arg `set` in data.following.set for type UserCreateManyWithoutFollowingInput. Did you mean `select`? Available args:
type UserCreateManyWithoutFollowingInput {
  create?: UserCreateWithoutFollowersInput
  connect?: UserWhereUniqueInput
}
Unknown arg `set` in data.followers.set for type UserCreateManyWithoutFollowersInput. Did you mean `select`? Available args:
type UserCreateManyWithoutFollowersInput {
  create?: UserCreateWithoutFollowingInput
  connect?: UserWhereUniqueInput
}
Unknown arg `set` in data.logs.set for type LogCreateManyWithoutLogsInput. Did you mean `select`? Available args:
type LogCreateManyWithoutLogsInput {
  create?: LogCreateWithoutOwnerInput
  connect?: LogWhereUniqueInput
}
Unknown arg `set` in data.projects.set for type ProjectCreateManyWithoutProjectsInput. Did you mean `select`? Available args:
type ProjectCreateManyWithoutProjectsInput {
  create?: ProjectCreateWithoutMembersInput
  connect?: ProjectWhereUniqueInput
}
Unknown arg `set` in data.items.set for type ItemCreateManyWithoutItemsInput. Did you mean `select`? Available args:
type ItemCreateManyWithoutItemsInput {
  create?: ItemCreateWithoutLogInput
  connect?: ItemWhereUniqueInput
}
Unknown arg `set` in data.itemsCreated.set for type ItemCreateManyWithoutItemsCreatedInput. Did you mean `select`? Available args:
type ItemCreateManyWithoutItemsCreatedInput {
  create?: ItemCreateWithoutCreatorInput
  connect?: ItemWhereUniqueInput
}
Unknown arg `set` in data.projectsCreated.set for type ProjectCreateManyWithoutProjectsCreatedInput. Did you mean `select`? Available args:
type ProjectCreateManyWithoutProjectsCreatedInput {
  create?: ProjectCreateWithoutCreatorInput
  connect?: ProjectWhereUniqueInput
}



**Stacktrace**
Error: 
Invalid `photon.users.create()` invocation:

{
  data: {
    id: '',
    createdAt: '2019-11-12T17:52:20.468Z',
    updatedAt: '2019-11-12T17:52:20.468Z',
    name: 'Bob',
    email: 'bob@bob.com',
    following: {
      set: []
      ~~~
    },
    followers: {
      set: []
      ~~~
    },
    logs: {
      set: []
      ~~~
    },
    projects: {
      set: []
      ~~~
    },
    items: {
      set: []
      ~~~
    },
    itemsCreated: {
      set: []
      ~~~
    },
    projectsCreated: {
      set: []
      ~~~
    }
  },
  select: {
    id: true,
    createdAt: true,
    updatedAt: true,
    name: true,
    email: true,
    following: true,
    followers: true,
    logs: true,
    projects: true,
    items: true,
    itemsCreated: true,
    projectsCreated: true
  }
}

Unknown arg `set` in data.following.set for type UserCreateManyWithoutFollowingInput. Did you mean `select`? Available args:
type UserCreateManyWithoutFollowingInput {
  create?: UserCreateWithoutFollowersInput
  connect?: UserWhereUniqueInput
}
Unknown arg `set` in data.followers.set for type UserCreateManyWithoutFollowersInput. Did you mean `select`? Available args:
type UserCreateManyWithoutFollowersInput {
  create?: UserCreateWithoutFollowingInput
  connect?: UserWhereUniqueInput
}
Unknown arg `set` in data.logs.set for type LogCreateManyWithoutLogsInput. Did you mean `select`? Available args:
type LogCreateManyWithoutLogsInput {
  create?: LogCreateWithoutOwnerInput
  connect?: LogWhereUniqueInput
}
Unknown arg `set` in data.projects.set for type ProjectCreateManyWithoutProjectsInput. Did you mean `select`? Available args:
type ProjectCreateManyWithoutProjectsInput {
  create?: ProjectCreateWithoutMembersInput
  connect?: ProjectWhereUniqueInput
}
Unknown arg `set` in data.items.set for type ItemCreateManyWithoutItemsInput. Did you mean `select`? Available args:
type ItemCreateManyWithoutItemsInput {
  create?: ItemCreateWithoutLogInput
  connect?: ItemWhereUniqueInput
}
Unknown arg `set` in data.itemsCreated.set for type ItemCreateManyWithoutItemsCreatedInput. Did you mean `select`? Available args:
type ItemCreateManyWithoutItemsCreatedInput {
  create?: ItemCreateWithoutCreatorInput
  connect?: ItemWhereUniqueInput
}
Unknown arg `set` in data.projectsCreated.set for type ProjectCreateManyWithoutProjectsCreatedInput. Did you mean `select`? Available args:
type ProjectCreateManyWithoutProjectsCreatedInput {
  create?: ProjectCreateWithoutCreatorInput
  connect?: ProjectWhereUniqueInput
}

    at Document.validate (/Users/cwd/src/calm/node_modules/prisma2/build/index.js:327234:23)
    at UserClient.get _document [as _document] (eval at Photon.start (/Users/cwd/src/calm/node_modules/prisma2/build/index.js:93134:32), <anonymous>:267:22)
    at UserClient.then (eval at Photon.start (/Users/cwd/src/calm/node_modules/prisma2/build/index.js:93134:32), <anonymous>:288:63)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by madebysid** [comment]
@chrisdrackett I've been able to figure out what the problem here is, expect a fix soon. Will update here!

**Comment by madebysid** [comment]
@chrisdrackett Try out alpha.309, that includes a fix for this!

**Comment by madebysid** [comment]
@chrisdrackett Try out alpha.337, that includes a fix for this!
