### ISSUE TITLE
Following graphql-auth tutorial, Error in query graph construction

### ISSUE THREAD

**Issue by darknoon** [prisma/studio#279]
I tried adding my own fields, but it turns out just doing the new Category type from the tutorial breaks in studio:

https://github.com/prisma/prisma2/blob/master/docs/tutorial.md

**Error dump**
Error in Photon: 
Error: Reason: Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findManyPost", inner: ObjectValidationError { object_name: "Post", inner: FieldValidationError { field_name: "categories", inner: FieldNotFoundError } } } })

    at NodeEngine.handleErrors (/Users/andrew/Developer/DesignTools/hello-prisma/node_modules/prisma2/build/index.js:338814:15)
    at /Users/andrew/Developer/DesignTools/hello-prisma/node_modules/prisma2/build/index.js:338774:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Stacktrace**
Error: Error in Photon: 
Error: Reason: Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findManyPost", inner: ObjectValidationError { object_name: "Post", inner: FieldValidationError { field_name: "categories", inner: FieldNotFoundError } } } })

    at NodeEngine.handleErrors (/Users/andrew/Developer/DesignTools/hello-prisma/node_modules/prisma2/build/index.js:338814:15)
    at /Users/andrew/Developer/DesignTools/hello-prisma/node_modules/prisma2/build/index.js:338774:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PhotonFetcher.eval (eval at Photon.start (/Users/andrew/Developer/DesignTools/hello-prisma/node_modules/prisma2/build/index.js:93134:32), <anonymous>:73:31)
    at Generator.throw (<anonymous>)
    at rejected (/Users/andrew/Developer/DesignTools/hello-prisma/node_modules/prisma2/build/index.js:114739:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by madebysid** [comment]
Hey @darknoon, apologies on the delay, I've just pushed out alpha.309 with a bunch of related fixes that should hopefully address this as well. Could you try it out (`npm i -g prisma2@alpha`)and let me know if you're still stuck?

**Comment by madebysid** [comment]
Hey @darknoon, apologies on the delay, I've just pushed out alpha.309 with a bunch of related fixes that should hopefully address this as well. Could you try it out (npm i -g prisma2@alpha)and let me know if you're still stuck?

**Comment by darknoon** [comment]
@madebysid trying to update to that alpha I ran into a version compatibility issue between photonjs and prisma2: https://gist.github.com/darknoon/235642d683c454ef4278f9d2c6e04f39

I fixed it and I'm trying again.

**Comment by darknoon** [comment]
Fixed that, now stuck on [this error](https://gist.github.com/darknoon/b1e6d76d21ed2622beb6ded324a8abe2):

```
Error: Could not find photon package at @generated/photon. Check that you have configured your Photon generator block in schema.prisma correctly and run prisma generate.
```

**Comment by madebysid** [comment]
Right, so there have been a few breaking changes, which means photon is now being generated in a different directory. A full description of it all will be released with tomorrow's preview release, including updated examples. This Slack community is where it'll be posted about: https://slack.prisma.io/ (#prisma2-preview channel)

Sorry about the confusion, I somehow missed that you were following along with the tutorial. Please try this out after tomorrow's announcement, and feel free to ping someone on there as well if you're still seeing errors. :)

**Comment by darknoon** [comment]
Thanks, Sid. I will check in tomorrow.

**Comment by darknoon** [comment]
Hey @madebysid, I couldn't find the announcement yesterday. Could you link it to me?

**Comment by madebysid** [comment]
Apologies on the delay @darknoon, we found a couple of issues with the release, so we had to delay it a bit. Here's more details: https://prisma.slack.com/archives/CKQTGR6T0/p1574696519402800

Let me know if you're stuck still, and I'll get back to you!

**Comment by darknoon** [comment]
@madebysid hey, I'm hitting a pretty similar issue on preview 17. Did a complete clean `prisma2 init`, and just adding any kind of new type I get this in the management console.

<img width="1280" alt="Screen Shot 2019-11-25 at 11 58 53" src="https://user-images.githubusercontent.com/355540/69561194-f93a5d80-0f7a-11ea-888f-d9a39edaeee8.png">

**Comment by madebysid** [comment]
@darknoon, Hmm that's possibly because the model you added does not exist on your database yet. I'm guessing you're opening Studio via `prisma2 dev`. Do you see any errors on there? If not, if you `prisma2 init`ed with a demo script, does a simple `photon.<modelName>.findMany()` via a script work?

**Comment by darknoon** [comment]
@madebysid Is there a special step I need to take after adjusting schema to have it update the database?

No errors in `prisma2 dev`, here is my `d` output:

```
Changes in datamodel since last prisma2 lift save

  model Post {
    id String @default(cuid()) @id
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    published Boolean @default(true)
    title String
    content String?
    author User?
  }
  
  model User {
    id String @default(cuid()) @id
    email String @unique
    password String
    name String?
    posts Post[]
  }
  
  model Parrot {
    id String @default(cuid()) @id
    name String
  }




```

**Comment by madebysid** [comment]
@darknoon Like we discussed on Slack, this was happening when you add a new model to your schema. Restarting `prisma2 dev` fixes this error.
I was able to figure out the root issue, and it is now fixed. It will land in a patch release we have planned for tomorrow. Will let you know here when it is out.

**Comment by madebysid** [comment]
@darknoon A fix for this is not out with preview17.1, could you give this another shot?

**Comment by madebysid** [comment]
I'm going to close this, since I'm fairly certain this is now fixed, but please reopen if you're still seeing this!

**Comment by darknoon** [comment]
Yeah, I haven't seen this anymore.
