### ISSUE TITLE
error when trying to view data

### ISSUE THREAD

**Issue by chrisdrackett** [prisma/studio#282]
I've gotten to the point that I can view 6 out of my 7 tables in studio. However on the 7th I get the following error:

1. Prisma2 version (`prisma2 -v`): prisma2@2.0.0-preview016.2

2. Logs from Developer Tools Console, if any:
```
Error in Photon: 
Error: Reason: Attempted to serialize scalar 'null' with incompatible type 'String'

    at NodeEngine.handleErrors (/Users/cwd/src/calm/node_modules/prisma2/build/index.js:338814:15)
    at /Users/cwd/src/calm/node_modules/prisma2/build/index.js:338774:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

4. Prisma2 schema (if relevant):
```
model Log {
  id        String    @default(cuid()) @id @unique
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt

  owner     User      @relation("UserLogs")

  type      LogType
  date      String

  items     Item[]    @relation("ItemLog")

  checkIns  CheckIn[] @relation("LogCheckin")
}
```

**Comment by madebysid** [comment]
@chrisdrackett Hmm, can't seem to reproduce on latest preview with the schema you've provided.
Perhaps it was fixed. If you still see this after updating, could you post your full schema as well? Thanks!

**Comment by madebysid** [comment]
Going to go ahead and close this. Please reopen and let me know if you're still running into this!

**Comment by charleslouis** [comment]
Hi @madebysid 
Got this too with `npx prisma studio --experimental`.
`Attempted to serialize scalar 'null' with incompatible type 'String'`

It follows inserts in DB using psql directly in which I post only some of the fields for a user.

Let me know if you need more info.

**Comment by madebysid** [comment]
Hey @charleslouis, I'm pretty sure what you're seeing is a Prisma Client error. Does the error reported here sound similar: https://github.com/prisma/prisma/issues/2442? (Regardless of your schema models)

I've been seeing a bunch reports from people with what sound like similar issues:
https://github.com/prisma/studio/issues/416
https://github.com/prisma/studio/issues/406

The Client team will probably pick this up this week and get it fixed. Once that happens, I will push out a new Studio release too! I'd recommend following the threads above.

I think what you're seeing is a general error that shows up for specific schemas. If you can quote your schema here, that'd help. I can then try to create another issue on the prisma/prisma repo and that will hopefully make it easier for the right people to spot a pattern :D
