### ISSUE TITLE
Encountering an error in Prisma Studio after running "prisma2 dev"

### ISSUE THREAD

**Issue by jwld** [prisma/studio#284]
Datamodel:
```
generator photon {
  provider = "photonjs"
}

model Expansion {
  levelMin  Int
  name      String
  // meta
  createdAt DateTime @default(now())
  id        String   @default(cuid()) @id @unique
  updatedAt DateTime @updatedAt
}

model Mount {
  expansion Expansion
  name      String
  // meta
  createdAt DateTime @default(now())
  id        String   @default(cuid()) @id @unique
  updatedAt DateTime @updatedAt
}
```

Error:
```
Error in Photon: 
Error: Reason: Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findManyMount", inner: ObjectValidationError { object_name: "Mount", inner: FieldValidationError { field_name: "expansion", inner: FieldNotFoundError } } } })

    at NodeEngine.handleErrors (/usr/local/lib/node_modules/prisma2/build/index.js:338814:15)
    at /usr/local/lib/node_modules/prisma2/build/index.js:338774:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by madebysid** [comment]
@jwld I've actually been seeing errors like this off and on but haven't been able to consistently reproduce them. Are you using Postgres?

**Comment by madebysid** [comment]
Hey @jwld, I've just pushed out alpha.309, that has a couple of fixes for similar errors. Could you try installing it with `npm i -g prisma2@alpha` and let me know if you still see this? Thanks!

**Comment by johndevor** [comment]
I am seeing a similar error after creating a new templated prisma db using sqlite:
```
Error: Reason: Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findManyUser", inner: ObjectValidationError { object_name: "User", inner: FieldValidationError { field_name: "password", inner: FieldNotFoundError } } } })
```

**Comment by jwld** [comment]
@pantharshit00 tried clearing the site data and no luck
@madebysid Yep using postgres! I'm seeing this error all the time right now.

Just recreated it by:
- Created a blank project, ran the setup with `prisma2 init`, connecting to a fresh local postgres db
- Ran `prisma2 dev` then opened prisma studio and all was fine
- Added `test: Int` to the `User` schema generated by `init`:
```
model User {
  id    String  @default(cuid()) @id @unique
  email String  @unique
  name  String?
  test  Int
  posts Post[]
}
```

After those steps I'm now seeing a similar error:
```
Error in Photon: 
Error: Reason: Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findManyPost", inner: ObjectValidationError { object_name: "Post", inner: FieldValidationError { field_name: "author", inner: ObjectValidationError { object_name: "User", inner: FieldValidationError { field_name: "test", inner: FieldNotFoundError } } } } } })

    at NodeEngine.handleErrors (/usr/local/lib/node_modules/prisma2/build/index.js:338814:15)
    at /usr/local/lib/node_modules/prisma2/build/index.js:338774:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by madebysid** [comment]
@jwld Thanks so much for that, I was able to fix this, it will be out with the next alpha. Will let you know here!

**Comment by madebysid** [comment]
Hey @jwld @johndevor , I've just pushed out alpha.337, that has a couple of fixes for similar errors. Could you try installing it with `npm i -g prisma2@alpha` and let me know if you still see this? Thanks!

**Comment by johndevor** [comment]
@madebysid Works now with a blank project with basic APIs! It asked me to update my photon package and that did the trick. 

That said, it isn't working when I choose to setup a boilerplate with options js/graphql/auth, showing this error (and it did not ask me to update photon in this case):

```
Failed to generate Photon client: TypeError: Cannot destructure property `photonDmmf` of 'undefined' or 'null'.
    at Photon.generateClient (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/index.js:434263:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Photon.start (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/index.js:434120:43)
    at async connect (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/photon-worker.js:45:31)
    at async process.<anonymous> (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/photon-worker.js:9:18)
Error starting Photon: TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at Photon.start (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/index.js:434120:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async connect (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/photon-worker.js:45:31)
    at async process.<anonymous> (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/photon-worker.js:9:18)
Error connecting to photon TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at connect (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/photon-worker.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async process.<anonymous> (/Users/john/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/photon-worker.js:9:18)
photon worker, starting photon
starting photon
{ schemaPath: '/Users/john/Desktop/hello-prisma/prisma/schema.prisma' }
{
  tempDataModelPath: '/private/var/folders/8z/26v1j2p933gd15pjlp_mfryc0000gn/T/8e542d7d-9482-4045-8860-c1039c7c2041'
}
```
I tried updating the prisma2 version in the auth boilerplate but that didn't do the trick.

**Comment by jwld** [comment]
@madebysid  It's _possibly_ fixed - it's working right now, but took a bit of hacking around rebuilding the database and reinstalling the library. Was seeing various errors in the process, including the one above, but right now it seems to be working :)

**Comment by madebysid** [comment]
@johndevor Ah that's expected. We introduced a breaking change that might break the prisma2 init flow for the alpha channel. 
We have a release coming up today that will update the examples to account for this change. That should then make sure that prisma2 init clones the right project. 
If you're on our Slack community, there will be a post on the #prisma2-preview channel when we push it out  (along with details about this breaking change, it'll make things much simpler now). 

If you can try out what you just did after the release and confirm that everything works as expected then, then I can indeed consider this fixed. If not, I'll look into it again :D

**Comment by johndevor** [comment]
@madebysid That appears to have fixed it. Thanks!

**Comment by madebysid** [comment]
Awesome, I'll go ahead and close this then!
