### ISSUE TITLE
ID not generated when creating new records

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#286]
1. Prisma2 version (`prisma2 -v`):

```
prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0
```

2. Logs from Developer Tools Console, if any:

```
prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0

```

4. Prisma2 schema (if relevant):

```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator photonjs {
  provider = "photonjs"
}

model User {
  id    String  @id @default(cuid())
  name  String
  email String? @unique
}
```

Now when I crate a new record in Studio, no `id` is being set. When trying to create another record, I (logically) get this error:

![image](https://user-images.githubusercontent.com/4058327/69151662-58135900-0adb-11ea-906b-58e9ee672488.png)

**Comment by nikolasburk** [comment]
Just to confirm, Studio sends an empty string as ID to the query engine:

```
Sending photon request:  photon.users.create(
{
  "data": {
    "id": "",
    "name": "asd",
    "email": "asd"
  },
  "select": {
    "id": true,
    "name": true,
    "email": true
  }
}
```

![image](https://user-images.githubusercontent.com/4058327/69225488-c9f0ae80-0b7e-11ea-9a8d-d5edec4ea098.png)

**Comment by madebysid** [comment]
@nikolasburk Ah perfect, this is fixed now, will be out soon

**Comment by madebysid** [comment]
@nikolasburk This should now be fixed with alpha.337, please give it a shot and let me know if you're still seeing this!
