### ISSUE TITLE
Make it clearer that the error bar can be clicked

### ISSUE THREAD

**Issue by sdnts** [prisma/studio#294]
It seems people do not realize that you can click on the error bar on top to see the full error. Perhaps we should introduce an explicit button / make the text in there look like a link so it is obvious that the error can be "opened"

**Comment by matthewmueller** [comment]
**Some options**

I think something like this would be fine. An X is pretty self-explanatory and a chevron in front usually indicates more details. 

![image](https://user-images.githubusercontent.com/170299/75772824-f8b91c00-5d4c-11ea-8595-f8ea0883801b.png)

I'd also be okay going more explicit with something like this:

![image](https://user-images.githubusercontent.com/170299/75772891-18504480-5d4d-11ea-85e4-0a285aea84d2.png)

**Comment by janpio** [comment]
Is the error bar still a thing?

**Comment by janpio** [comment]
No.
