### ISSUE TITLE
Enum dropdown doesn't scroll if it extends off-screen

### ISSUE THREAD

**Issue by jwld** [prisma/studio#295]
Using the latest alpha build.

If you add enough values to an enum to push the full list off screen, it's difficult to select values at the bottom of the list since it doesn't scroll (can still be done with keyboard controls, but you can't see what's focused once it goes off-screen).

Checked in Chrome and Safari ✌️

**Comment by madebysid** [comment]
Ah whoops, didn't think of that! Will push out a fix soon!

**Comment by madebysid** [comment]
@jwld I've set a maximum height for the enum dropdown in the latest alpha (alpha.389 as of now), please reopen if you still find issues!

**Comment by jwld** [comment]
Great cheers 👍
