### ISSUE TITLE
Selected row is weirdly indented

### ISSUE THREAD

**Issue by schickling** [prisma/studio#299]
![image](https://user-images.githubusercontent.com/1567498/69648110-82a36b80-101f-11ea-9285-0cbff5138c4d.png)

**Comment by madebysid** [comment]
Should now be fixed, can't see this anymore on the demo app

**Comment by schickling** [comment]
Seems to be still there.

![F15E2766-60D6-4C98-9559-2E4363C1B19C](https://user-images.githubusercontent.com/1567498/69882671-d0211200-1285-11ea-89ee-89d593ed3738.jpeg)

**Comment by madebysid** [comment]
Was the result of a rollback I did, try again now?
