### ISSUE TITLE
General keyboard shortcuts

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#3]
Action Items:
1. Use a more robust shortcut management library

Expected Outcomes:
1. Shortcuts that people expect to "just work", like new windows, new queries etc. to "just work".

**Comment by madebysid** [comment]
Out with alpha.169.
This will be an ongoing process, so closing this.

**Comment by schickling** [comment]
@madebysid does this follow what's outlined [in the spec](https://github.com/prisma/specs/tree/master/studio#keyboard-navigation)?

**Comment by madebysid** [comment]
Ah no not all of them, a few common ones for tabs were done, other focus based shortcuts are still unimplemented. Will add them as part of #91!
