### ISSUE TITLE
Clearer error message when Photon generation fails

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#302]
For errors like [this](https://user-images.githubusercontent.com/17841919/69658623-8dbfc100-104a-11ea-8593-f2d10827a140.png), the message does not mean anything to the end-user. 
I could perhaps see if photon generation failed and fall back in a more graceful/friendlier way.

**Comment by divyenduz** [comment]
Unassigned myself as Matt and Sid are working on this. Please feel free to re-assign me if you need any input from me.

**Comment by matthewmueller** [comment]
Do we still run into this @madebysid ?

**Comment by madebysid** [comment]
@matthewmueller Yea theoretically this could still happen, but the exact error is now hidden behind the `Details` section of the fatal error dialog that lets you send us an error report / clear cache and reload.
I guess we've made it somewhat actionable for the user, so we can close this.
