### ISSUE TITLE
Dumped error after trying to save changes on studio

### ISSUE THREAD

**Issue by outerlook** [prisma/studio#304]
trying to edit some fields on studio. After clicked to save changes, this happened.

![image](https://user-images.githubusercontent.com/12937160/69894999-d60b0780-1306-11ea-9ac0-093046614403.png)

is it helpful to raise this issue?

**Error dump**
pn.get(...) is null

**Stacktrace**
Ln/<@http://localhost:5555/studioBundle.js:87:30908
Ln@http://localhost:5555/studioBundle.js:87:30548
In/<@http://localhost:5555/studioBundle.js:87:30103
In@http://localhost:5555/studioBundle.js:87:30048
Dn/n<@http://localhost:5555/studioBundle.js:87:31295
Dn@http://localhost:5555/studioBundle.js:87:31271
Pn/this.commit<@http://localhost:5555/studioBundle.js:87:34380
$@http://localhost:5555/studioBundle.js:16:6357
i@http://localhost:5555/studioBundle.js:16:6129
u@http://localhost:5555/studioBundle.js:16:23509
rt/</u<@http://localhost:5555/studioBundle.js:16:23788
rt/<@http://localhost:5555/studioBundle.js:16:23395
$@http://localhost:5555/studioBundle.js:16:6357
i@http://localhost:5555/studioBundle.js:16:6129
onClick@http://localhost:5555/studioBundle.js:87:79379
g@http://localhost:5555/studioBundle.js:65:1025
w@http://localhost:5555/studioBundle.js:65:1168
S/<@http://localhost:5555/studioBundle.js:65:1314
S@http://localhost:5555/studioBundle.js:65:1400
D@http://localhost:5555/studioBundle.js:65:1849
L@http://localhost:5555/studioBundle.js:65:1661
j@http://localhost:5555/studioBundle.js:65:2010
Cn@http://localhost:5555/studioBundle.js:65:29065
le@http://localhost:5555/studioBundle.js:65:114833
Dn@http://localhost:5555/studioBundle.js:65:29681
On@http://localhost:5555/studioBundle.js:65:30638
jn@http://localhost:5555/studioBundle.js:65:29926
t.unstable_runWithPriority@http://localhost:5555/studioBundle.js:73:3465
Jo@http://localhost:5555/studioBundle.js:65:45525
ae@http://localhost:5555/studioBundle.js:65:114600
Ln@http://localhost:5555/studioBundle.js:65:29349
i@http://localhost:5555/studioBundle.js:73:361354

**Comment by madebysid** [comment]
Hey @outerlook, could you share your schema file? From the screenshot, I can make out what changes you made. I can then try and reproduce this on my end as well!

**Comment by outerlook** [comment]
Sure! Where could I send to you privately?

**Comment by madebysid** [comment]
Just leave out your DB credentials and paste it here? It'd be helpful to know if you're on SQLite / MySQL / Postgres though.

**Comment by outerlook** [comment]
How about sending it to your mail? Would be more confortably for me not to keep that so public

**Comment by madebysid** [comment]
Sure, you'll find my email on my GitHub page.
Perhaps you'd also like to join our Slack community here: https://slack.prisma.io/ and DM me there. My username is `siddhant`. That would make communication much easier as well.

**Comment by madebysid** [comment]
Closing this as this should now be solved in the latest alpha. Please reopen if you're still running into issues!
