### ISSUE TITLE
Report Photon errors to Error Reporting Backend

### ISSUE THREAD

**Issue by janpio** [prisma/studio#305]
Currently `prisma2` only reports panics from the Migration Engine from Lift to the Error Reporting Backend. In general we can not add this to Photon and the Query Engine, as we only report after explicit consent from the user. That is a shame, because we would also like to know about the crashes there.

Tim had the idea, that in Studio we actually might be able to report Photon errors to the Backend, as the developer itself triggered them and could actively decide if to report or not.

To design this feature, please talk to @timsuchanek to get the API of the backend. He will also be able to give you pointers to what the current "Should this be reported?" prompt looks like and similar, or make sure that any additional fields that might be required are present in the target database.

**Comment by janpio** [comment]
Do you need any information on this? As this is the only way for us to get error reports from Photon, we are very eager to have this as soon as possible - best _before_ the MVPhoton release.

**Comment by madebysid** [comment]
This is now done [here's a preview](https://user-images.githubusercontent.com/7689783/73386995-1b7c8e80-42d0-11ea-8d5e-7ed5cc2c962f.png)

Whenever the query engine panics / we encounter an unknown error in Prisma Client, this dialog shows up and you can send a report to our error reporting service.

**Comment by madebysid** [comment]
There are two scenarios in which an error is sent to the error reporting backend:
1. If a Prisma Client request causes a Rust panic (i.e., the `error.isPanic` is `true`)
2. If Prisma Client returns an error that is unrecognized (i.e., the `errror.code` is `undefined`)

**Comment by janpio** [comment]
Does it submit this information to the error reporting backend in any way?
Which one is https://prisma-errors.netlify.com/report/2248 for example?
How would I use this information?
