### ISSUE TITLE
Streamline pagination flow

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#309]
Currently, pagination parameters (`first`, `skip` & `after`), shown in the UI as:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/7689783/70547743-b202be00-1b71-11ea-8567-051be3465dab.png">

are able to be controlled by both the user and Studio. These are also used when deciding the number of records to fetch for an open tab.

These parameters are subject to change for a lot of reasons:
1. When records are created (`first` argument changes)
2. When records are deleted (`first` & `after` arguments change)
3. When you add one or more filters (`first`, `skip` & `after` arguments change)
4. When you change the sort order of any field (`first`, `skip` & `after` arguments change)
5. Scrolling down to the bottom of the records list (`first` & `after` arguments change)
6. When you manually change any of them from the UI (`first`, `skip` & `after` arguments change)

1-5 are controlled by Studio. Any actions you take from the UI is translated into a corresponding Photon query. However, because of 6, Studio always has to take into account any changes the user made to the pagination queries. This leads to weird bugs where records don't show up or pagination params are not what you'd expect. The root of these issues is that Studio cannot take ownership of these values, which leads to complicated logic, and ultimately to "bugs" in the eyes of the end user. This also makes these confusing to work with both in the source code AND for the user, since values might change when they don't want them to etc.

After talking to @schickling, we decided we should figure out a better way for people to control pagination, ideally in a way that keep it away from Studio.

**Comment by matthewmueller** [comment]
This doesn't seem actionable to me. Can we re-write this to be actionable?

It feels like we need both, an automated mode for 1-5 and a manual mode for 6. We default to automated mode, but in manual studio doesn't do anything until the pagination is cleared by the user.

**Comment by madebysid** [comment]
@matthewmueller I'm not sure if I can make this actionable yet, this is one of those things we need to think about on a higher level first.

**Comment by matthewmueller** [comment]
After talking about this during our weekly meeting:

1. We're removing `after` (for now) since @@id with composite fields greatly complicated pagination and the UI for pagination.
2. We'll likely move `first` & `skip` into a unified filter system, but leave as is for now.
3. We'll be okay with the edge case of creating a record while filters are set potentially hiding that created record (it's how airtable and tableplus do it.)

**Comment by janpio** [comment]
Be aware that pagination stuff might be changed/simplified in the near future: https://github.com/prisma/specs/issues/376 So this might need to be touched again soon.
