### ISSUE TITLE
Hitting CMD + C should copy content of selected select to clipboard

### ISSUE THREAD

**Issue by schickling** [prisma/studio#310]
Hitting CMD + C should copy content of selected select to clipboard even in non-editing mode and no text selected but just a cell.

**Comment by madebysid** [comment]
This is now out on the [demo app](https://prisma-studio.now.sh). An alpha should be out tomorrow (some tests seem to be failing on the prisma2 release pipeline). 

A couple of other things I did additionally:
- Selecting a cell and pressing `Cmd+C` copies the cell's content (regardless of whether you're in edit mode or not) to clipboard (this issue)
- Selecting a single record and pressing `Cmd+C` copies the record's value as a JSON object to clipboard
- Selecting multiple records and pressing `Cmd+C` copies an array of record value to clipboard (subject to failure depending on the size of this array)
