### ISSUE TITLE
Wrong command suggestion when disconnected

### ISSUE THREAD

**Issue by scriptcoded** [prisma/studio#311]
1. Prisma2 version (`prisma2 -v`):
prisma2@2.0.0-preview017.2, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293

2. Logs from Developer Tools Console, if any:
None

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
None

When `prisma2 dev` is stopped in the terminal the following message gets shown in the IDE:
`prisma dev was disconnected. Please restart prisma dev in your terminal`

The command right now is `prisma2 dev`, and not `prisma dev`. I'm assuming this might be to be ready for the final release, but shouldn't it be `prisma2 dev` now anyways?

Cheers,
Malcolm

**Comment by janpio** [comment]
Also, there are two commands that could be used to start Studio: `prisma2 dev` and `prisma2 studio`. We should probably add a mechanism that recognizes that and shows the user the approprate command @madebysid

**Comment by madebysid** [comment]
Now that `prisma2 dev` is gone, this is unambiguous. I've changed the error to say `prisma2 studio`. Closing!
