### ISSUE TITLE
Add a floating help dropdown for useful actions

### ISSUE THREAD

**Issue by sdnts** [prisma/studio#315]
This is how Figma does it:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/7689783/71011657-167fc900-20ee-11ea-9898-8b91520a4c5d.png">

It could contain actions such as:
A link to the release notes
A way to report an issue
Documentation about keyboard shortcuts
Internal prisma versions used

among others

**Comment by matthewmueller** [comment]
Definitely need this feature, I'd prefer it not float on top of the data, but I'm not too opinionated on that.
