### ISSUE TITLE
Issue creating records in relation to the ID

### ISSUE THREAD

**Issue by LydiaF** [prisma/studio#316]
Hey :)

I am encountering a little issue when I am trying to create records that I don't have to enter any information for. In the first picture, it says that the ID will be auto-generated, but in the second picture, it says that an ID was not provided.

<img width="1397" alt="Screenshot 2019-12-17 at 21 23 34" src="https://user-images.githubusercontent.com/10000865/71035591-b00da180-2113-11ea-8364-e752db25be52.png">
<img width="856" alt="Screenshot 2019-12-17 at 21 27 08" src="https://user-images.githubusercontent.com/10000865/71035741-037fef80-2114-11ea-8567-29b5a41d515e.png">

Thank you for looking into this or letting me know what I am doing wrong!

**Comment by madebysid** [comment]
Hey @LydiaF, thanks for letting me know! This is indeed a bug and I've identified the cause for this. I'll let you know here when a fix is out.

For the time being, you can get around this by specifying a default value for your `id` field in your `schema.prisma` file

If `id` of `WorksheetPlatonic` is an Int, you should be able to do:
```prisma
model WorksheetPlatonic {
  id    Int     @id @default(autoincrement())
  ...
}
```

or if `id` is a String, try:
```prisma
model WorksheetPlatonic {
  id    String     @id @default(cuid())
  // OR
  id    String     @id @default(uuid())
  ...
}
```

More details about these `@default` values will follow in an upcoming release. You can join our [Slack community](https://slack.prisma.io/)'s #prisma2-preview channel to follow along if you wish.

**Comment by LydiaF** [comment]
Thank you so much for looking into this and the workaround!

**Comment by madebysid** [comment]
@LydiaF Can you try this out on the latest preview/alpha? Do note that there have been a couple of breaking changes since this surfaced, so you might need to adjust your project somewhat. You can find full details here: https://github.com/prisma/prisma2/releases

Please reopen if you're still running into this!
