### ISSUE TITLE
Allow Studio-server to accept a pre-generated photon

### ISSUE THREAD

**Issue by sdnts** [prisma/studio#321]
Currently, Studio always generates its own Photon, regardless of what the user's schema looks like.

Adding this option to the server would allow Prisma Labs to avoid having to do duplicate work. The Prisma2 CLI could also be smarter, so it could reuse the user's Photon for Javascript projects. Otherwise, it would fall back to generating its own Photon. (For Go projects etc.)

This would also greatly reduce the startup overhead for Studio currently, AKA, the "Getting things ready" banner would become pretty short lived.

**Comment by madebysid** [comment]
Things to do:
- [ ] Add an option to the StudioServer constructor to accept a path of (already generated) photon
- [ ] Clean up the StudioServer constructor API a bit
- [ ] Have more sensible defaults for `reactAppDir`, `photonWorkerPath` etc. so Labs doesn't have to know about implementation details. Also override these defaults in the CLI
- [ ] Use this new functionality in P2 CLI for JS projects so Studio doesn't generate its own Photon, but rather reuses the photon already generated by the CLI. For Go projects, fall back to current behaviour.
