### ISSUE TITLE
Should ID fields always be a sticky column?

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#326]
In the table view currently, the colunn with the checkbox (the gutter) is currently a sticky column, i.e., it does not scroll with the rest of the table (horizontally).

Should the ID column behave the same way?

**Comment by schickling** [comment]
We also need to consider the case of multi-field IDs and models without IDs.

**Comment by schickling** [comment]
Related: Should the record checkbox have a border?

My proposal: Only when scrolling horizontally like here:

![image](https://user-images.githubusercontent.com/1567498/71621842-0974d680-2bd2-11ea-9c3f-82449c4432ba.png)

**Comment by madebysid** [comment]
We've re-added checkboxes (for good this time!) and decided that the ID column has no need to be sticky / visible. Closing!
