### ISSUE TITLE
Trying to set a value to a string

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#327]
https://www.dropbox.com/s/gwp0g02d4ctz3hk/Screenshot%202019-12-24%2013.43.31.png?dl=0

**Error dump**
Cannot read property 'map' of undefined

**Stacktrace**
TypeError: Cannot read property 'map' of undefined
    at On (https://87-prisma-studio.now.sh/studioBundle.js:87:33677)

**Comment by madebysid** [comment]
@matthewmueller Did this happen when you pressed `Save Changes`? If so, then that's expected. Basically, the photon instance fails to commit your changes and fails as a result. I'll see if I can handle this error better though.

More here: https://github.com/prisma/studio/issues/317

**Comment by matthewmueller** [comment]
Ahhhh yes, I didn't realize it was read-only. Maybe we can add a banner at the top that says this is a read-only database.

**Comment by madebysid** [comment]
Possibly! I was thinking if there was a more generic way we could handle this via the query engine.

For example, this could also happen in a local environment, if, let's say you only have read access to a Postgres table. The error should, IMO be handled similarly.

**Comment by matthewmueller** [comment]
Ahh good point yah, e.g. `Error: this is a read-only database. `
