### ISSUE TITLE
Avoid visual elements "jumping" when loading/reloading

### ISSUE THREAD

**Issue by schickling** [prisma/studio#328]
https://www.loom.com/share/3d4e692f88ab433ba0fb424e955f75b2

**Comment by madebysid** [comment]
This should be much better now in alpha :D

**Comment by schickling** [comment]
There are still a bunch of jumping elements. @matthewmueller can you please work with @madebysid to improve this further? I'm happy to share more of my thoughts/ideas if needed 🙏

**Comment by matthewmueller** [comment]
The padding is fixed now, I don't see any other jumpiness. Happy to re-open if you notice any other jumpiness.
