### ISSUE TITLE
Feature: Filter enum fields in studio

### ISSUE THREAD

**Issue by seanemmer** [prisma/studio#329]
Prisma2 version (`prisma2 -v`): 2.0.0-preview019

This is currently not possible.  Seems like a popular filter (e.g. filter users by status, role, etc.)

**Comment by madebysid** [comment]
@seanemmer This is now possible in alpha.958 and onwards!

**Comment by madebysid** [comment]
@lewebsimple Huh, you're right, let me investigate what happened. (I'm also seeing scroll issues in that tooltip, I'll look at that too)
