### ISSUE TITLE
Option to bring your own photon (BYOP)

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/studio#330]
Currently Studio fully manages photon dependency. However in the case of [`graphql-santa-plugin-prisma`](https://github.com/prisma-labs/graphql-santa-plugin-prisma) photon is already managed. It would be ideal if studio could be run with a path reference to the generated photon runtime. Maybe there is also a use-case for accepting a reference to a photon client instance to even further reduce the overhead?

This issue/idea originally started in our [private] slack [here](https://prisma-company.slack.com/archives/CEYCG2MCN/p1576769054014000).

**Comment by jasonkuhrt** [comment]
@madebysid Oops, I think this is a duplicate of https://github.com/prisma/studio/issues/321?

**Comment by madebysid** [comment]
Yep indeed. Closing this one then!
