### ISSUE TITLE
[Feature Request] Use Prisma Studio as an admin dashboard

### ISSUE THREAD

**Issue by queicherius** [prisma/studio#332]
Is there any way to run Prisma Studio with migrations disabled, just as an admin dashboard in production? It solves 90% of the use cases I would have for a low-fidelity dashboard, it just needs some basic auth in front (e.g. from a load balancer)

**Comment by janpio** [comment]
If you are on the current preview, `prisma2 studio` should work. Did you mean that?

**Comment by queicherius** [comment]
Oh, that is exactly what I was looking for! Perfect, thank you!
I did not realize that was a command because the Prisma CLI did not list it (only init, dev, lift, introspect and generate).

**Comment by janpio** [comment]
Yes, that was intentional in the past and will be changed with the next release `preview020` - then `prisma2 studio` is a public command.
