### ISSUE TITLE
Invalid change for id - 

### ISSUE THREAD

**Issue by JCLMAQ** [prisma/studio#334]
1. Prisma2 version (`prisma2 -v`): 
### preview 20.3
2. Logs from Developer Tools Console, if any:
```

```
 
3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
### Yes
4. Prisma2 schema (if relevant):
```
model User {
  id    String  @id @default(uuid())
  name  String
}
```
![Invalid change](https://user-images.githubusercontent.com/3626284/73077433-73765800-3ec0-11ea-9399-cb3b21a9df31.png)

I have to introduce a value to be able to create the record, event if @default.

**Comment by madebysid** [comment]
Hey @JCLMAQ, if the default value isn't being populated, then it looks like a bug.
Are you also unable to provide a value manually (by double clicking the ID cell)? If so, then that is also related.
I'll pick this up and let you know when a fix is out on alpha.

**Comment by JCLMAQ** [comment]
Thanks for the answer. 
No, I am able to provide a value manually, and then the "1 invalid change" disappear, and it is possible to record the change.
By the way, with the preview18, I did not get the problems.

**Comment by greguintow** [comment]
That was happening to me, but I installed alpha and now prisma2 studio it's great, this issue can be closed when the alpha goes to normal release.

**Comment by madebysid** [comment]
@JCLMAQ & @greguintow I've indeed pushed out a fix for this on alpha. Please reopen if you're still seeing this!
