### ISSUE TITLE
Error when adding record in the prisma2 studio

### ISSUE THREAD

**Issue by tijsproost** [prisma/studio#338]
<Anything that helps us reproduce the error goes here>

**Error dump**
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20returnType%2C%20args%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Stacktrace**

    in div
    in sl
    in div
    in cc
    in div
    in hc
    in div
    in ForwardRef
    in div
    in ForwardRef
    in t
    in div
    in Va
    in bc
    in div
    in ha
    in nd
    in div
    in sd
    in div
    in div
    in _d
    in div
    in u

**Comment by homoky** [comment]
Same here. Clean project.

**Comment by madebysid** [comment]
Hey @tijsproost @homoky, are you running on prisma2@latest? Could you try this out on prisma2@alpha as well and see if it works there (`npm i prisma2@alpha`)? You will also need to update `@prisma/client` to `alpha`.

If it does, then the fix should land with the next preview release.
If not, your Prisma schema might help me reproduce the problem on my end.

Let me know!

**Comment by homoky** [comment]
Hey @madebysid,

I can confirm that on `prisma@latest` (2.0.0-preview021) the bug still occurs. But on the `prisma@alpha`, to be clear on version `prisma2@2.0.0-alpha.751` it is no issue anymore.

**Comment by madebysid** [comment]
Awesome! I'm going to close this then. It should also be fixed in on `latest` with this Thursday's release. Please reopen if you run into this again!
