### ISSUE TITLE
Autocomplete not working properly

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#339]
![image (8)](https://user-images.githubusercontent.com/170299/73950678-9e1ed280-48fc-11ea-8504-e19fc33c94c3.png)

**Comment by matthewmueller** [comment]
![image](https://user-images.githubusercontent.com/170299/73952201-040c5980-48ff-11ea-8b2f-9e0b575abce8.png)

**Comment by matthewmueller** [comment]
![image](https://user-images.githubusercontent.com/170299/73952313-138ba280-48ff-11ea-8518-9064d61db8b0.png)

**Comment by schickling** [comment]
This is still a key workflow we want to have available in the demo. Let’s please create a bug report for Now then if we believe it’s a problem on their end.
