### ISSUE TITLE
`console.log` on normal usage

### ISSUE THREAD

**Issue by janpio** [prisma/studio#344]
```
λ npx prisma2 -v
prisma2@2.0.0-alpha.785, binary version: 3e74ccae138e0c7330c1d8f2a67fb7a234d220e8
```

![image](https://user-images.githubusercontent.com/183673/74595481-029b0980-5042-11ea-812d-f489ce751a3f.png)

**Comment by madebysid** [comment]
@janpio Is the issue here the missing source maps warnings etc.?

**Comment by janpio** [comment]
Yes, all those warnings on normal usage are unexpected.
