### ISSUE TITLE
Close Sidebar button has smaller clickable area than Open Sidebar button 

### ISSUE THREAD

**Issue by janpio** [prisma/studio#345]
```
λ npx prisma2 -v
prisma2@2.0.0-alpha.785, binary version: 3e74ccae138e0c7330c1d8f2a67fb7a234d220e8
```

Close:
![image](https://user-images.githubusercontent.com/183673/74595503-53126700-5042-11ea-9871-0a1c65c0dd33.png)

Open:
![image](https://user-images.githubusercontent.com/183673/74595507-5f96bf80-5042-11ea-860e-500e106710ed.png)

**Comment by madebysid** [comment]
Fixed, will be out with the next alpha!
