### ISSUE TITLE
`TypeError: Zn.get(...).idField is undefined`

### ISSUE THREAD

**Issue by janpio** [prisma/studio#347]
```
λ npx prisma2 -v
prisma2@2.0.0-alpha.785, binary version: 3e74ccae138e0c7330c1d8f2a67fb7a234d220e8
```

Some schemas currently get:

` 
TypeError: Zn.get(...).idField is undefined
`

Example connection strings: 
`mysql://...@introspection-mysql-public-from-dumps.clfeqqifnebj.eu-west-1.rds.amazonaws.com:3306/nextcloud`
`mysql://...@introspection-mysql-public-from-dumps.clfeqqifnebj.eu-west-1.rds.amazonaws.com:3306/matomo`
(Full connection strings in https://github.com/prisma/introspection-engine-output/blob/master/connections/mysql_public.txt)

Should be reported quite a few times to Sentry as well.

**Comment by madebysid** [comment]
alpha.898 should fix this! Please reopen if this is still reproducible!
