### ISSUE TITLE
Minified React error #31 when adding a new entry to a model

### ISSUE THREAD

**Issue by sachaw** [prisma/studio#348]
Created a new model in my schema, migrated and generated it, then went to add a record to it with Prisma studio and keep getting this.

**Error dump**
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20returnType%2C%20args%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Stacktrace**

    in div
    in Uu
    in div
    in cc
    in div
    in hc
    in div
    in ForwardRef
    in div
    in ForwardRef
    in t
    in div
    in Va
    in bc
    in div
    in ha
    in nd
    in div
    in sd
    in div
    in div
    in _d
    in div
    in u

**Comment by madebysid** [comment]
@sachaw Thanks for reporting this! I've been working on some internal improvements that I believe should address this. I'll let you know here when I push it out to alpha and you can check it out!

**Comment by madebysid** [comment]
@sachaw Could you try updating to the latest alpha (2.0.0-alpha.898) using `npm i prisma2@alpha` and let me know if you still see this?

**Comment by sachaw** [comment]
Appears to be fixed.
