### ISSUE TITLE
Sending error report should probably also clear cache

### ISSUE THREAD

**Issue by janpio** [prisma/studio#356]
Currently errors often go away when clearing the cache and  reloading studio via that button. "Send error" does not have the same effect. So it would probably make sense to combine this functionality.

**Comment by madebysid** [comment]
@janpio I'm not sure if that's the best idea. I should fix issues with the cache if that's what is really causing all these issues. I think the initial loading of data when switching schemas is flaky & error prone at the moment, not the cache itself. I will investigate these & write some more tests for confidence.

Down the road, we will start saving user config / saved queries etc. in the cache, so clearing it should be an explicit action IMO.
