### ISSUE TITLE
Pagination error in studio with modified chinook and data

### ISSUE THREAD

**Issue by divyenduz** [prisma/studio#358]
Error in studio on scrolling on a long table: 

![image](https://user-images.githubusercontent.com/746482/75030018-84a48b80-54a3-11ea-8f97-eed1a08af905.png)

In my understanding, generated pagination query is incorrect, is uses `after` in place of `skip`. 

1. Prisma2 version (`prisma2 -v`):

```
divyendusingh [chinook]$ prisma2 --version
prisma2@2.0.0-alpha.814, binary version: f18ac64b68ddbf9f1537509ca0dc09c6848a241b
```

2. Logs from Developer Tools Console, if any:
```
Sending request to prisma client:  prisma.track.findMany({
  select: {
    Bytes: true,
    Composer: true,
    Milliseconds: true,
    Name: true,
    TrackId: true,
    UnitPrice: true,
    AlbumId: true,
    GenreId: true,
    MediaTypeId: true,
    invoiceLine: true,
    playlistTrack: true,
  },
  orderBy: {
    TrackId: "asc",
  },
  first: 100,
  skip: 0,
})
studioBundle.js:73 0
studioBundle.js:73 0
studioBundle.js:73 Sending request to prisma client:  prisma.track.findMany({
  select: {
    Bytes: true,
    Composer: true,
    Milliseconds: true,
    Name: true,
    TrackId: true,
    UnitPrice: true,
    AlbumId: true,
    GenreId: true,
    MediaTypeId: true,
    invoiceLine: true,
    playlistTrack: true,
  },
  orderBy: {
    TrackId: "asc",
  },
  first: 100,
  after: 100,
})
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

Yes

4. Prisma2 schema (if relevant):
https://github.com/prisma/chinook/tree/master/database-schema

**Comment by madebysid** [comment]
@divyenduz I think AUMFIDARR introduced a breaking change in the `after` argument. I've now fixed this and pushed out an update on alpha. Please reopen if you still see this!
