### ISSUE TITLE
Allow opening Studio in read-only mode depending on credentials' user access

### ISSUE THREAD

**Issue by janpio** [prisma/studio#359]
![image](https://user-images.githubusercontent.com/183673/75032514-0ba83280-54a9-11ea-87c7-7938e6958672.png)

$ C:\Users\Jan\Documents\prisma-chinook\cli-demo\node_modules\.bin\prisma2 -v
prisma2@2.0.0-alpha.814, binary version: f18ac64b68ddbf9f1537509ca0dc09c6848a241b

**Comment by madebysid** [comment]
@janpio We already have a dialog (and a configuration option) for read-only databases, I wonder if there's a way for studio-server to know if a database is read-only upfront (when running `prisma2 studio`).

I use it to open Studio in a "read-only" mode for the demo deployment at [https://prisma.studio](https://prisma.studio)

**Comment by janpio** [comment]
You can probably ask for the rights of the current user somehow, now sure if there is an API in Prisma Client besides `.raw`. Using that you could probably build something.

**Comment by madebysid** [comment]
I think we'l tackle this much more boardly with Cloud, so I'll close this.
