### ISSUE TITLE
Reload button doesn't work

### ISSUE THREAD

**Issue by timsuchanek** [prisma/studio#360]
When running the latest studio with a local mysql database, creating data outside of Studio and then pressing the reload button, it didn't update the UI.

You should be able to reproduce this with a basic Blog example.
If you can't, please let me know and I give you a full reproduction.

**Comment by sachaw** [comment]
Preview24+Postgres, button does not seem to work at all, for example, Script calls prisma.table.create(), shows up in db, but reload button does nothing, a refresh brings up the correct data.

**Comment by madebysid** [comment]
@sachaw Do you see any errors in the Console when the reload button does nothing?

**Comment by sachaw** [comment]
Loaded studio, created a few modals from within my application.

after clicking reload: 
![image](https://user-images.githubusercontent.com/11172820/76903685-62f5c300-68ee-11ea-9033-19426ba62788.png)

after refreshing the page:
![image](https://user-images.githubusercontent.com/11172820/76903738-786aed00-68ee-11ea-81ab-81eda036d5cc.png)

nothing in terminal, please let me know any other info you need.

**Comment by madebysid** [comment]
@sachaw I looked around a bit and I'm pretty sure what you're seeing is the same as: https://github.com/prisma/studio/issues/393 (it is the same root issue I'm pretty sure)

I'm going to fix it this week!

**Comment by madebysid** [comment]
@sachaw Could you try out alpha.1012? It includes a fix for this. You should now be able to create stuff outside Studio and have it show up by pressing the `Reload` button, as expected. Let me know if you're still unable to see new records!
