### ISSUE TITLE
Crash of Studio with Fields linked to an enum

### ISSUE THREAD

**Issue by JCLMAQ** [prisma/studio#361]
Description
When trying to create a new Todo record with Studio: 
the field 'state' is in red (message: 1 invalid change) with the default value and trying to change it result in a crash (or [Object Object]). The crash error: 
```
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20dbName%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

1. Prisma2 version (`prisma2 -v`):
preview-022
2. Logs from Developer Tools Console, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes
4. Prisma2 schema (if relevant):
```
model Todo {
  id          String    @id @default(uuid())
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  title       String
  content     String?
  state       TodoState @default(CREATION)
  published   Boolean   @default(false)
  public      Boolean   @default(false)
  mainTodo    Todo?     @relation(name: "subTodo")
  subTodo     Todo[]    @relation(name: "subTodo")
  author      User      @relation(name: "todoAuthor")
  assignedTo  User[]
  groupConcern Group[]
}

enum TodoState {
  CREATION
  STANDBY
  RUNNING
  DONE
}
```

**Comment by madebysid** [comment]
Hey @JCLMAQ, I was trying to reproduce this, but can't in the latest version (beta.5), so I think this might be fixed now. Could you try updating and let me know if that's the case for you too?

**Comment by JCLMAQ** [comment]
Yes, it is fixed in beta release 5.
Thanks. 
I close this issue.
