### ISSUE TITLE
Enter on a relationship weirdness

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#362]
via: https://prisma.studio

Video: https://www.dropbox.com/s/1yc1u49bir0dhsa/Studio%20Relations.mp4?dl=0

**Issues:**

1. Clears cell when you press enter
2. 1 pending change

**Expected:**

1. No change to the cell when you press enter
2. No pending change

**Comment by madebysid** [comment]
This shouldn't happen anymore, if I understand correctly. Was probably fixed with https://github.com/prisma/studio/issues/410!
