### ISSUE TITLE
Studio fails to run in preview 23 / latest alpha

### ISSUE THREAD

**Issue by seanemmer** [prisma/studio#365]
1. Prisma2 version (`prisma2 -v`):

prisma2@2.0.0-alpha.883, binary version: 60bbefbaebef5673fbf53cd54ee97ed0b97bca7a

2. Logs from Developer Tools Console, if any:

`prisma2 studio --experimental`

```
Failed to generate Prisma Client: Error: Schema parsing
error: Found argument '--enable_raw_queries' which wasn't expected, or isn't valid in this context
        Did you mean --enable-raw-queries?

USAGE:
    query-engine-darwin --enable-raw-queries

For more information try --help
    at Object.<anonymous> (/Users/sean/Developer/pearly/app/node_modules/prisma2/build/index.js:2:329997)
    at Generator.throw (<anonymous>)
    at rejected (/Users/sean/Developer/pearly/app/node_modules/prisma2/build/index.js:2:326047)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

Already updated to latest version

**Comment by janpio** [comment]
Do you have a local and a global install of `prisma2`?
Did you maybe forget to run the local install via `yarn prisma2 ...`?

I somehow managed to mess stuff up with the same error message by mixing those two up (although I do not really understand yet how).

My advice: Uninstall `prisma2`, `@prisma/client` and add it again, then `generate` new and/or start Studio with the correct command again. Problem should be gone.

**Comment by seanemmer** [comment]
Thanks for the advice.  I do not have a global install of Prisma2.  The following is the command I am running and you can see it is calling the local prisma2 binary:

```
$ yarn prisma2 studio --experimental
$ /Users/sean/Developer/pearly/app/node_modules/.bin/prisma2 studio --experimental
Failed to generate Prisma Client: Error: Schema parsing
...
```

I uninstalled and reinstalled @prisma/client and prisma2, regenerated the client and got the same error.

Interestingly, even when I don't generate the prisma client at all, I still get the same error.  It seems to be stemming from the prisma binary being an old version, but I don't see how that can be the case with the following dependencies:

```
    "@prisma/client": "2.0.0-alpha.883",
    "prisma2": "2.0.0-alpha.883"
```

**Comment by madebysid** [comment]
Hey @seanemmer, I was able to reproduce this on a new project as well.
I have a fix for this that I will push out to an alpha tomorrow morning. There is currently another issue with packaging that is forcing my hand, but I'll let you know when the alpha is out so you can check again. Sorry!

**Comment by seanemmer** [comment]
@madebysid ok, thanks for being on top of it, I'll be on the lookout for the next alpha.

**Comment by madebysid** [comment]
Hey @seanemmer, I just pushed out alpha.898. Could you try updating and let me know if you still see this?

**Comment by seanemmer** [comment]
@madebysid confirming, this bug is gone!
