### ISSUE TITLE
Error in Prisma Client request: Invalid findMany invocation

### ISSUE THREAD

**Issue by samrith-s** [prisma/studio#370]
1. Prisma2 version (`prisma2 -v`):
prisma2@2.0.0-alpha.904

2. Logs from Developer Tools Console, if any:
```bash
Error in Prisma Client request: 

Error: 
Invalid `prisma.troup.findMany()` invocation:

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "relation \"public.Troup\" does not exist", detail: None, hint: None, position: Some(Original(214)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(1139), routine: Some("parserOpenTable") }) }) })
    at PrismaClientFetcher.request (/Users/sam/.cache/prisma/studio/Users-sam-Work-troup-server/runtime/index.js:1:47359)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

generator client {
    provider = "prisma-client-js"
}

// Troup Model
model Troup {
    id          String       @id @default(cuid())
    createdAt   DateTime     @default(now())
    updatedAt   DateTime     @updatedAt
    members     Int          @default(1)
    maxMembers  Int          @default(25)
    profile     TroupProfile
    primaryUser User
}

model TroupProfile {
    id         String   @id @default(cuid())
    createdAt  DateTime @default(now())
    updatedAt  DateTime @updatedAt
    name       String   @unique
    adminEmail String?
    address    String?
    troup      Troup
}

// User Models
model User {
    id               String      @id @default(cuid())
    createdAt        DateTime    @default(now())
    updatedAt        DateTime    @updatedAt
    email            String      @unique
    password         String
    profile          UserProfile
    roles            Role[]
    troups           Troup[]
    createdTodos     Task[]      @relation("_Todo_Task_Author")
    contributedTodos Task[]      @relation("_Todo_Task_Contributor")
    ownedTodos       Task[]      @relation("_Todo_Task_Owner")
    createdPosts     Post[]      @relation("_Post_Author")
    contributedPosts Post[]      @relation("_Post_Contributor")
}

model UserProfile {
    id                     String   @id @default(cuid())
    createdAt              DateTime @default(now())
    updatedAt              DateTime @updatedAt
    firstName              String
    lastName               String
    isSuperAdmin           Boolean  @default(false)
    professionalCompetence String?
    referral               User?
    utm_source             String?
    utm_campaign           String?
    utm_medium             String?
    utm_term               String?
    utm_content            String?
}

// Post Models
model Post {
    id              String            @id @default(cuid())
    createdAt       DateTime          @default(now())
    updatedAt       DateTime          @updatedAt
    published       Boolean?          @default(value: false)
    title           String
    content         String
    label           Label[]
    author          User              @relation("_Post_Author")
    contributors    User[]            @relation("_Post_Contributor")
    troup           Troup             @relation("_Post_Parent")
    revisionHistory RevisionHistory[]
}

model Comment {
    id              String            @id @default(cuid())
    createdAt       DateTime          @default(now())
    updatedAt       DateTime          @updatedAt
    content         String            @default("")
    troup           Troup
    author          User
    post            Post              @relation("_Comment_Parent")
    revisionHistory RevisionHistory[]
}

// Todo Models
model Todo {
    id        String       @id @default(cuid())
    createdAt DateTime     @default(now())
    updatedAt DateTime     @updatedAt
    members   User[]
    columns   TodoColumn[]
}

model TodoColumn {
    id              String            @id @default(cuid())
    createdAt       DateTime          @default(now())
    updatedAt       DateTime          @updatedAt
    name            String
    revisionHistory RevisionHistory[]
}

model Task {
    id           String   @id @default(cuid())
    createdAt    DateTime @default(now())
    updatedAt    DateTime @updatedAt
    author       User     @relation("_Todo_Task_Author")
    assignee     User     @relation("_Todo_Task_Owner")
    contributors User[]   @relation("_Todo_Task_Contributor")
    state        State    @default(ACTIVE)
}

// Supporting models
model Label {
    id        String    @id @default(cuid())
    createdAt DateTime  @default(now())
    updatedAt DateTime  @updatedAt
    title     String
    color     String
    type      LabelType @default(GLOBAL)
    troup     Troup
    todo      Todo?
}

model Role {
    id        String    @id @default(cuid())
    createdAt DateTime  @default(now())
    updatedAt DateTime  @updatedAt
    troup     Troup     @relation(references: [id])
    user      User      @relation(references: [id])
    value     RoleValue @default(CONTRIBUTOR)
}

model RevisionHistory {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    content   String   @default("")
    updatedBy User
}

model StateHistory {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    state     State    @default(ACTIVE)
}

// Enums
enum RoleValue {
    SUPER_ADMIN ADMIN MODERATOR CONTRIBUTOR
}

enum State {
    ACTIVE INACTIVE CHURNING ARCHIVED
}

enum LabelType {
    GLOBAL SPECIFIC
}
```

**Comment by madebysid** [comment]
Hey @samrith-s, this is super weird, looks like thr Troup table does not exist? Could you perhaps verify that the DATABASE_URL is pointing to the correct postgres schema (`public`)?

There should also be a log in the DevTools Console logging out the exact query that went out. Could you also try running that query in a separate Node script and see if you get the same error? That'll help me verify if this is a Studio issue, or a deeper, Prisma Client issue. Thanks!

**Comment by samrith-s** [comment]
Hey, I actually get this for every single table.

In the console, this is what I get (error.stack):
```
Error: 
Invalid `prisma.user.findMany()` invocation:

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "relation \"public.User\" does not exist", detail: None, hint: None, position: Some(Original(196)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(1139), routine: Some("parserOpenTable") }) }) })
    at PrismaClientFetcher.request (/Users/sam/.cache/prisma/studio/Users-sam-Work-troup-server/runtime/index.js:1:47359)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by samrith-s** [comment]
So, it's all working now. 

What I did, is completely delete and setup Postgres from scratch. Then I created a migration and applied it.
```bash
yarn prisma2 migrate save --experimental
yarn prisma2 migrate up --experimental
```

Is there a way to delete this migration since I am setting my db up from scratch?

**Comment by madebysid** [comment]
> What I did, is completely delete and setup Postgres from scratch.
Oh, maybe your DB was in an unexpected state then.

> Is there a way to delete this migration since I am setting my db up from scratch?
Directly reversing a migration isn't supported yet. However, if you want to "reverse" a migration, you should be able to change your schema to match an older state and then create a new migration.

If you do have any more questions about `migrate`, then the best place would be to create issues in the https://github.com/prisma/migrate repository. I'm going to close this since the original issue seems to be resolved!

**Comment by samrith-s** [comment]
Yeah, I reckon it was my DB which was erroring out. A complete reset and the initial CreateTable migrations seem to have solved it.

**Comment by neomog** [comment]
Having this same issue

Below is the error on my browser, it works initially but after trying to change the db schema i keep receiving the error below:

 1 of 1 unhandled error
Server Error
Error: 
Invalid `prisma.post.findMany()` invocation:


  Can't reach database server at `ec2-54-162-211-113.compute-1.amazonaws.com`:`5432`

Please make sure your database server is running at `ec2-54-162-211-113.compute-1.amazonaws.com`:`5432`.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
pages\index.tsx (8:15) @ async getStaticProps

   6 | 
   7 | export const getStaticProps: GetStaticProps = async () => {
>  8 |   const feed = await prisma.post.findMany({
     |               ^
   9 |     where: { published: true },
  10 |     include: {
  11 |       author: {


I have tried to reverse the db schema state, but no changes


Below is the error in the console:

PS C:\Users\user pc\blogr-nextjs-prisma> npm run dev

> hello-next@1.0.0 dev
> next

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\user pc\blogr-nextjs-prisma\.env
warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.0.5
event - compiled client and server successfully in 48.7s (168 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 65.3s (317 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 2.7s (169 modules)
error - Error: 
Invalid `prisma.post.findMany()` invocation:


  Can't reach database server at `ec2-54-162-211-113.compute-1.amazonaws.com`:`5432`

Please make sure your database server is running at `ec2-54-162-211-113.compute-1.amazonaws.com`:`5432`.
wait  - compiling / (client and server)...
event - compiled client and server successfully in 7.2s (318 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 942 ms (318 modules)
error - Error: 
Invalid `prisma.post.findMany()` invocation:


  Can't reach database server at `ec2-54-162-211-113.compute-1.amazonaws.com`:`5432`

Please make sure your database server is running at `ec2-54-162-211-113.compute-1.amazonaws.com`:`5432`.



When i run "npx prisma studio", it works . please what could i be doing wrong?

**Comment by madebysid** [comment]
Hey @neomog, are you saying Studio works with that database URL, but not your (presumably) Next project's Prisma Client?

Do you have two `.env`s by any chance? Maybe Studio is reading the "correct" `.env` but not Next? It is probably also worth it to create a standalone Node script and use Prisma Client there directly to isolate the problem (run it directly instead of via Next). If this persists and you're sure this isn't something to do with your setup, I'd probably create an issue on https://github.com/prisma/prisma so the right people can help!

**Comment by j-funk** [comment]
I am having this same issue as well using Prisma Studio - can create/delete records no problem, but any `update` operation fails.  See screenshot:
<img width="1112" alt="Screen Shot 2022-04-21 at 12 05 50 AM" src="https://user-images.githubusercontent.com/4483540/164370103-10590300-db2c-4215-9839-992005e677b8.png">

Schema below:
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
    provider = "mysql"
    url = env("DATABASE_URL")
    referentialIntegrity = "prisma"
}

generator client {
    provider = "prisma-client-js"
    previewFeatures = ["referentialIntegrity"]
}

model Account {
    id                       String   @id @default(cuid())
    createdAt                DateTime @default(now())
    updatedAt                DateTime @updatedAt
    userId                   String
    type                     String
    provider                 String
    providerAccountId        String
    refresh_token            String? @db.VarChar(500)
    access_token             String? @db.VarChar(500)
    refresh_token_expires_in Int?
    expires_at               Int?
    token_type               String?
    scope                    String?
    id_token                 String? @db.Text
    session_state            String?
    oauth_token_secret       String?
    oauth_token              String?
    user User @relation(fields: [userId], references: [id], onDelete: Cascade)
    @@unique([provider, providerAccountId])
}

model Session {
    id           String   @id @default(cuid())
    sessionToken String   @unique
    expires      DateTime
    user         User?    @relation(fields: [userId], references: [id], onDelete: Cascade)
    userId       String?
}

model User {
    id            String    @id @default(cuid())
    createdAt     DateTime  @default(now())
    updatedAt     DateTime  @updatedAt
    name          String?
    email         String?   @unique
    password      String?
    emailVerified DateTime?
    image         String?
    role          String?   @default("user")
    accounts      Account[]
    sessions      Session[]
    galleries     Gallery[]
}

model VerificationRequest {
  id         Int      @default(autoincrement()) @id
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now()) @map(name: "created_at")
  updatedAt  DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "verification_requests")
}


// Gallery Models
model Gallery {
  id            Int                 @id @default(autoincrement())
  title         String
  description   String?
  isPrivate     Boolean             @default(true)
  curator       User                @relation(fields: [curatorId], references: [id], onDelete: Cascade)
  curatorId     String
  nfts          GalleriesOnNFTs[]
}

model NFT {
  id                        Int                 @id @default(autoincrement())
  name                      String
  symbol                    String
  description               String              @db.VarChar(1000)
  image                     String
  edition                   Int
  galleries                 GalleriesOnNFTs[]

}

model GalleriesOnNFTs {
  nft           NFT        @relation(fields: [nftId], references: [id])
  nftId         Int // relation scalar field (used in the `@relation` attribute above)
  rawrGallery       Gallery     @relation(fields: [galleryId], references: [id])
  galleryId     Int // relation scalar field (used in the `@relation` attribute above)
  assignedAt    DateTime    @default(now())
  assignedBy    String

  @@id([nftId, galleryId])
}

```

**Comment by janpio** [comment]
Your problem is different @j-funk and tracked here: https://github.com/prisma/prisma/issues/10758

**Comment by haneenmahd** [comment]
Have you tried using the `npx prisma db push`?

 It will fix this. I faced the same issue in my project, when I changed the schema without updating the db.

**Comment by adryeldeev** [comment]
I have the error similar to the first one, check it out:

/ 20230611190032
// https://backendpsql.vercel.app/

{
  "error": "\nInvalid `prisma.user.findMany()` invocation:\n\n\nCan't reach database server at `bd-user.cyapq1zdxu9o.us-east-2.rds.amazonaws.com`: `5432`\n\nPlease make sure your database server is running at `bd-user.cyapq1zdxu9o.us-east-2.rds.amazonaws.com`:`5432`."
}

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://cadastrouser:rootadmin123456@bd-user.cyapq1zdxu9o.us-east-2.rds.amazonaws.com:5432/bdawscreate"
}

model User{
  id Int @id @default(autoincrement())
  name String
  email String
  numero BigInt
}

**Comment by AlexGonRod** [comment]
Hi Here, I have a similar issue in my project one in Sveltekit. I have it hosted on vercel and this is the error log:
error:  
Invalid `prisma.dishes.findMany()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P05), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(412), routine: Some("StorePreparedStatement") }) }), transient: false })

Mi DB is hosted un supabase. I tried to restart it and nothing new happened. I also tried to do "npx prisma db push".

The weird thing is that this is not always failing, and only fails in production.

This is my schema, and of course, the table in supabase is not empty. As I said, it fails sometimes (more than I want)

``
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int    @id @default(autoincrement())
  user      String @unique
  password  String
  authToken String @unique
}

model Dishes {
  id          Int    @id @default(autoincrement())
  description String
  type        String
}

model Info {
  id          Int    @id @default(autoincrement())
  description String
  type        String
}
``

**Comment by mahshid22** [comment]
i have this error:
DATABASE_URL="postgresql://admin:12345@localhost:5432/mydb?schema=public"
 
 and that was because i have 2 .env file (one in my next dir and other in my packages/database) you sould link .env in databade to next .env and that's it.

**Comment by AlixanBALU** [comment]
Hey, 
It seems stupid but for me the error was comming from the file db.ts wich is a fix to this issue :
https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices
I tried everything, i cleared the cache, uninstalled / reinstalled my db, emptying my db, etc ..

And then i just restarted my computer and it worked, 
hope it helps.

**Comment by pablojsx** [comment]
Yeah I just closed and opened VSCODE and it worked.

**Comment by prasadsawant7** [comment]
> Yeah I just closed and opened VSCODE and it worked.

Really it worked! Thanks alot!

**Comment by Harshsaxenajii** [comment]
i got this error {"error":"\nInvalid `prisma.category.findMany()` invocation:\n\n{\n  include: {\n    products: true,\n    children: true\n    ~~~~~~~~\n  }\n}\n\nUnknown field `children` for include statement on model `Category`. Available options are marked with ?."} in my local this api is working file but in deployment it give an error. schema is :
model Category {
  id              Int        @id @default(autoincrement())
  name            String
  parentId        Int?
  valuesAvailable String[]
  images          String[]
  description     String?
  createdAt       DateTime   @default(now())
  updatedAt       DateTime   @default(now())
  parent          Category?  @relation("CategoryParent", fields: [parentId], references: [id])
  children        Category[] @relation("CategoryParent")
  products        Product[]
}

**Comment by Bharat-kasera** [comment]
it internet connection issue. when i connect to my college wifi then this error show. when i switch to my mobile internet connection it works perfectly.

**Comment by UmutDenizUral** [comment]
Solution of below problem is you have to go to your database and  add to your current IP address to your DB this will fix your problem. When you change your location this problem occurs
Error: PrismaClientKnownRequestError: 
Invalid `prisma.product.findMany()` invocation:


Raw query failed. Code: `unknown`. Message: `Kind: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Set Name: atlas-m6gdc6-shard-0, Servers: [ { Address: ac-mkm70z2-shard-00-00.ut7yuas.mongodb.net:27017, Type: Unknown, Error: Kind: I/O error: received fatal alert: InternalError, labels: {} }, { Address: ac-mkm70z2-shard-00-02.ut7yuas.mongodb.net:27017, Type: Unknown, Error: Kind: I/O error: received fatal alert: InternalError, labels: {} }, { Address: ac-mkm70z2-shard-00-01.ut7yuas.mongodb.net:27017, Type: Unknown, Error: Kind: I/O error: received fatal alert: InternalError, labels: {} } ] }, labels: {}`

**Comment by mscode07** [comment]
Getting this error, can anyone help?
`
 ⨯ PrismaClientValidationError: 
Invalid `prisma.user.findFirst()` invocation:
`

**Comment by ajiesep** [comment]
anyone help me?

Error: 
Invalid `prisma.property.findMany()` invocation:


Error querying the database: FATAL: Tenant or user not found

utils\actions.ts (171:22) @ async $$ACTION_6

  169 |   category?: string;
  170 | }) => {
> 171 |   const properties = await db.property.findMany({
      |                      ^
  172 |     where: {
  173 |       category,
  174 |       OR: [

**Comment by deepak2030x** [comment]
Error in Prisma Client request: 

Error: 
Invalid `prisma.troup.findMany()` invocation:

**If anyone facing above issue** 

just check in your package.json. remove @prisma/extension-accelerate package if it is present. also update both prisma and prisma/client to recent version. hope this works. It worked for me.

**Comment by bronz3beard** [comment]
> Hey [@neomog](https://github.com/neomog), are you saying Studio works with that database URL, but not your (presumably) Next project's Prisma Client?
> 
> Do you have two `.env`s by any chance? Maybe Studio is reading the "correct" `.env` but not Next? It is probably also worth it to create a standalone Node script and use Prisma Client there directly to isolate the problem (run it directly instead of via Next). If this persists and you're sure this isn't something to do with your setup, I'd probably create an issue on https://github.com/prisma/prisma so the right people can help!

Thank-you for this!! `"any chance? Maybe Studio is reading the "correct" `.env`"`
