### ISSUE TITLE
Latest Studio Version errors Invalid Record Value on first record it tries to find()

### ISSUE THREAD

**Issue by seanemmer** [prisma/studio#372]
1. Prisma2 version (`prisma2 -v`):
2.0.0-alpha.905

2. Logs from Developer Tools Console, if any:
```
[getRecordId] Invalid recordValue 
Object { modelId: "Account", recordValue: {…}, uniqueFields: (4) […] }
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

**Comment by madebysid** [comment]
Hey! Could you perhaps expand all keys of the error? (Specifically, the `recordValue` and `uniqueFields` keys)

I also have a feeling this is related to some new stuff we added to the schema, so your Prisma schema would be useful. I can then try and reproduce this.

Alternatively, if you have a repository that misbehaves the same way, sharing it would help me debug this as well.

**Comment by seanemmer** [comment]
Hi Sid, thanks for jumping on this.

Unfortunately this is for work so I can't provide the schema or expanded keys on github but could send them over to you on a private channel.

I've played around with studio and the bug appears to occur whenever I try to query for a model with multiple unique fields, or a model that is related to another model with multiple unique fields.

Let me know if that's enough or if you'd like to me to jump on Prisma Slack.  If you can't easily repro it in your environment I can work to spin up another one on my own but that will take a few days.

**Comment by madebysid** [comment]
@seanemmer Ah you can reach out on the [Prisma Slack](https://slack.prisma.io/) workspace then, that'd work too! My username on there is `siddhant`

**Comment by sachaw** [comment]
Similar issue here, But no info other than `Invalid recordValue`
Only happening for one model, all the others are fine.

```
model User {
  id                    String   @default(cuid()) @id
  activated             Boolean  @default(false)
  activationClaim       String?  @unique
  username              String   @unique
  name                  String
  avatar                String   @default("data:image/png;base64,iVBORwYII=...")
  password              String?
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
  groups                Group[]
  tokens                Token[]
  linkedAccounts        LinkedAccount[]
  userCredentials       UserCredential[]
}
```

**Comment by madebysid** [comment]
@seanemmer As per our conversation on Slack, I've just released alpha.925 that should address your problem.

For transparency: the underlying issue was the fact that the value of one of the `@unique` annotated fields in @seanemmer's table's row was `null`, which is what caused the crash.

So for a model like so:
```
model User {
    id        Int @id
    name  String? @unique
}
```
if the value of a record in this table is:  `{ id: 1, name: null }`, then Studio would crash.

@sachaw If your problem sounds similar, perhaps an update to the latest alpha fixes the issue for you too? My guess would be that the `activationClaim` in your `User` model might have been the culprit. If you still see this though, let me know!

**Comment by seanemmer** [comment]
Working, thanks @madebysid !
