### ISSUE TITLE
Remove the reload button

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#374]
The reload button seems to give the impression that Studio's state *needs* to be reloaded, and that it struggles to keep its state up-to-date, which isn't true. @matthewmueller suggested we get rid of it.

For historical context: The `Reload` button was added for the rare case when you add / remove / change rows in a table from outside Studio (using a script, for example) and then want to see these changes within Studio. For this case, people should reload the page entirely.

**Comment by janpio** [comment]
> The `Reload` button was added for the rare case when

This is my default case for using a database UI (after initially creating the DB). I want to see what kind of changes my app is executing and how the data is changing.

**Comment by matthewmueller** [comment]
Good point. Let's leave it for now. In the future, we should do something like twitter.

![image](https://user-images.githubusercontent.com/170299/76637745-9978ba00-654b-11ea-9f6d-564f344afdfe.png)
