### ISSUE TITLE
Add an option to not automatically open studio in browser

### ISSUE THREAD

**Issue by Errorname** [prisma/studio#385]
I would like to have an option for the `prisma2 studio` command so that it doesn't automatically open the browser, which can be annoying sometimes.

Something like `--without-open` or `--no-open` ?

If you agree on the name of the option, I can do the PR

**Comment by djgrant** [comment]
`BROWSER=none` is a nice standard for this behaviour https://github.com/facebook/create-react-app/pull/1148

**Comment by madebysid** [comment]
@Errorname @djgrant There's now a `--browser` option on 2.0.0-alpha.1154 that allows you to select which browser you want to open Studio in. You can set it to `none` as well to disable auto-opening.

In addition, there's also a `BROWSER` environment variable that behaves exactly the same.

I've also added a couple of examples in the output of `prisma studio --help`. Let me know how this works for you!

This will land on beta with the next release.

**Comment by djgrant** [comment]
Nice one! I tried this in `2.0.0-alpha.1154` but the browser still opened. I didn't see the help message either so maybe it's the wrong version?

**Comment by madebysid** [comment]
@djgrant Hmm interesting, I just tried alpha.1154 and see the thing working (and the help message).

Maybe update to the latest beta/alpha (beta.4 or alpha.1187) just to make sure?

**Comment by djgrant** [comment]
Ah, I updated `@prisma/client` instead of `@prisma/cli` 🤦‍♂️

Works as expected noww! Thanks!

**Comment by JHerwig** [comment]
For each project, I am using a separate browser instance (dedicated user profiles).   
```json
// launch.json
  {
      "type": "chrome",
      "request": "launch",
      "name": "client: chrome",
      "url": "http://localhost:4000",
      "userDataDir": "${workspaceFolder}/.vscode/chrome",
      "runtimeArgs": ["--disable-web-security"],
      "webRoot": "${workspaceFolder}",
  },
```
Are there detailed options for the browser?

**Comment by madebysid** [comment]
Hye @JHerwig, we use https://github.com/sindresorhus/open to open up the browser, so anything that applies to it, applies to the Prisma CLI as well. What kind of options are you looking for?
