### ISSUE TITLE
[Prisma-Studio] Values not selectable in Firefox

### ISSUE THREAD

**Issue by BjoernRave** [prisma/studio#387]
I would like to be able to select and copy values from prisma studio, currently it doesn't seem to be possible in firefox.

Firefox Version: 74.0 
OS: Mac Os Catalina

**Comment by madebysid** [comment]
Hey @BjoernRave, you should be able to select a cell (by clicking on it) and press Cmd/Ctrl + C to copy that cells value to your clipboard.

Let me know if this doesn't suffice though, and I'll reopen this!

**Comment by BjoernRave** [comment]
@madebysid ah okay, yeah that works. I guess it's fine for now
