### ISSUE TITLE
Negative value for row count on sidebar

### ISSUE THREAD

**Issue by sachaw** [prisma/studio#390]
prisma2@2.0.0-preview024

If a user loads prisma studio, and one of the models has 0 rows, then a row is added (outside of studio). If you then change the view in studio to another model and back again, the number (0) is not updated, if you then delete the newly created model, the number becomes a negative.

This would likely be fixed by updating the row count in the ui when when the user navigates to a given model and the updated records are fetched.

**Comment by madebysid** [comment]
@sachaw 😅 That sounds about right, thanks for the report!

> This would likely be fixed by updating the row count in the ui when when the user navigates to a given model and the updated records are fetched.

This could work!

**Comment by madebysid** [comment]
@sachaw alpha.1012 includes a fix for #393 and it should address this as well. Could you give it a shot and let me know if this is still an issue?
