### ISSUE TITLE
@unique in schema causing error at studioBundle.js:73

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#392]
1. Prisma2 version (`prisma2 -v`):
`2.0.0-preview024`

2. Logs from Developer Tools Console, if any:
```
[getRecordId] Invalid recordValue ObjectmodelId: "User"recordValue: {id: "e9727762-9479-4e24-aa69-7c6c72c93fc9", createdAt: "2020-03-27T00:52:38.090Z", updatedAt: "2020-03-27T05:13:36.438Z", userToContacts: Array(0), birthDay: 20, …}uniqueFields: (5) [fn, fn, fn, fn, fn]0: fn {…}1: fn {…}2: fn {…}3: fn {…}4: fn {…}length: 5__proto__: Array(0)__proto__: Object
(anonymous) @ studioBundle.js:73
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

Haven’t tried yet, since `2.0.0-preview025` should be coming out any moment.

4. Prisma2 schema (if relevant):
This causes an error:
```graphql
model User {
  id                      String    @default(uuid()) @id
  ...
  sysAuthCode             String?   @unique
  ...
}
```

while this doesn’t:
```graphql
model User {
  id                      String    @default(uuid()) @id
  ...
  sysAuthCode             String?
  ...
}
```

Currently I have one record in the `User` model. I suspect that making a field `unique` with at least one existing record, even though the `sysAuthCode` field for that one records is `null`, somehow invalidates the `@unique` injunction.

**Comment by madebysid** [comment]
Hey @heymartinadams, I assume this model _only_ has the @unique field and no @id field? If so, This is addressed in the latest alphas. The next preview (preview025, scheduled to be released today) should fix this. I'm keeping this open, let me know when you try the new versions out!

**Comment by heymartinadams** [comment]
@madebysid it does have an `id` field — updated my comment above. Will try out `preview025` now — if this error goes away I’ll update my comment.

**Comment by heymartinadams** [comment]
Tried out `preview025` and it actually now [causes an error](https://github.com/prisma/prisma2/issues/1959) in the migration part, so unable to test it.

**Comment by heymartinadams** [comment]
@madebysid, got it to work with `preview025`! Had to circumvent the above-referenced migration error by deleting the test database and re-seeding it from scratch. Using `@unique` now appears to work.

Closing this issue, unless you think it needs to be kept open.
