### ISSUE TITLE
Error Reporting does not report CLI version as version

### ISSUE THREAD

**Issue by janpio** [prisma/studio#394]
https://prisma-errors.netlify.com/report/2326

![image](https://user-images.githubusercontent.com/183673/77810977-9fb47d80-7097-11ea-9593-0f8e8b07e0ee.png)

**Comment by madebysid** [comment]
I'm not sure how this happened, just checked latest alpha and preview, and the versions seem to be resolved properly.

As background information: Studio receives CLI and binary versions from the CLI (when you run `prisma2 studio`), and uses the `sendPanic` method from the SDK to send this info to the error reporting backend, so how this happened has me really confused. :/

**Comment by madebysid** [comment]
Okay here's the underlying issue: https://github.com/prisma/prisma2/issues/2005

I've changed the call from Studio for now so the reports are correct, will change it again when the aforementioned issue is addressed. This will be out with alpha.987
