### ISSUE TITLE
Unable to set optional DateTime field to `null`

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#395]
## Issue
Unable to set optional DateTime field in Prisma Studio to `null`, see as follows:

![image](https://user-images.githubusercontent.com/11673745/77859860-9c68e100-71c0-11ea-90e2-95263a6c255e.png)

1. Prisma2 version (`prisma2 -v`): `preview025`

2. Logs from Developer Tools Console, if any: None, since unable to execute, i.e. save.

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)? Yes.

4. Prisma2 schema (if relevant):
```js
  sysEmailConfirmCode     String?   @unique
  // Unable to manually set `sysEmailConfirmExpires` to `null` in Prisma Studio
  sysEmailConfirmExpires  DateTime?
  sysPasswordResetCode    String?   @unique
  // Since not required, `sysPasswordResetExpires` field can be `null` after record is created
  sysPasswordResetExpires DateTime?
```

**Comment by madebysid** [comment]
@heymartinadams Did you reach this state by "emptying" the DateTime input? AKA: pressing backspace till the input was empty?

I think the issue here is that Studio thinks the value of that field is an empty string.

You raise a valid point, and one that I'll address right away: For optional fields, leaving them empty likely means you want to set them to `null`, rather than an empty string, for a vast majority of use cases. Would you agree?

**Comment by heymartinadams** [comment]
@madebysid exactly (and oops!) That would be a good UX improvement indeed ☺️

**Comment by heymartinadams** [comment]
Playing around with it more and realizing that I’m actually neither able to empty the `DateTime` input, nor replace it with `null` (by writing “null” into it). And when I attempt to “null” out a String field by writing `null` into it, it’s interpreted as a String called "null", not as `null`.

**Comment by madebysid** [comment]
@heymartinadams I just pushed out 2.0.0-alpha.1179, which has this change.
To be clear, now when you set an *optional* field's value to an empty string, it instead sets it to `null`. The same happens if you just press `Delete`/`Backspace` on the cell directly. Let me know how this feels.

**Comment by heymartinadams** [comment]
Sweet! Whereas if I delete a _required_ String field, it simply makes it empty, but not `null`. Smart. Thanks, @madebysid!

**Comment by heymartinadams** [comment]
Hi @madebysid,

Just checking: any thoughts about _automatically_ converting a non-required empty String field to `null` in Studio?

Recently switched a field from required to non-required and it had some empty string fields. As you can see below, had to manually enter and then remove data to convert them to `null`.

Not important, but mentioning in case it could be one of those good things to have.

![out](https://user-images.githubusercontent.com/11673745/81486794-32eee000-920c-11ea-93dc-d20ef680bdd1.gif)

**Comment by madebysid** [comment]
@heymartinadams I might have misunderstood, but do you mean changing them in your database? If so, I'm not sure if it's a good idea for Studio to be changing your DB contents without you knowing about it / initiating it.

Personally, I think in your specific situation, I wouldn't use Studio at all, I would use a script with Prisma Client queries that identify such records and update them.

**Comment by heymartinadams** [comment]
Makes sense, @madebysid.

**Comment by teddis** [comment]
This is still a problem in 2024, sadly (for me). I'm trying to seed my database. I want to clear a DateTime? field to null if tests have set it to a date. Instead I get "Unknown argument `last_sent_at`. Available options are marked with ?." error.
