### ISSUE TITLE
Close error button not working

### ISSUE THREAD

**Issue by sachaw** [prisma/studio#399]
prisma `2.0.0-alpha.1031` windows

error modal close button does not work, however the banner one does:
![image](https://user-images.githubusercontent.com/11172820/78466604-2a554680-7742-11ea-8785-ebb8ac068b02.png)
Nothing in console,
also I think `Dismiss` would be better wording.

**Comment by madebysid** [comment]
@sachawAh yes, I can see this too 😓 

I also agree that `Dismiss` might be more appropriate. I'll make these changes and let you know when a fix is out! (Soon)

**Comment by madebysid** [comment]
Hey! I've just pushed out 2.0.0-alpha.1126 that fixes this. Let me know if you/re still running into this!
