### ISSUE TITLE
Unable to update required one-to-one relation

### ISSUE THREAD

**Issue by seanemmer** [prisma/studio#401]
## Bug description

Unable to update required one-to-one relation

## How to reproduce

Create a one-to-one relation in your data model as in the docs
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#one-to-one-relations

Create a sample User and Profile in the DB
 
Open Prisma Studio, try to update either User.Profile or Profile.User and save

Following Error:

```
Invalid `prisma.user.update()` invocation:

The change you are trying to make would violate the required relation 'UserToProfile' between the `User` and `Profile` models.
```

## Expected behavior

The update should succeed

## Prisma information

Prisma Beta 1

## Environment & setup

Mac OSX

**Comment by madebysid** [comment]
Hey @seanemmer! Does this happen only in Studio or in a separate script as well?
I'll take a look at this soon.

**Comment by seanemmer** [comment]
Hi Sid, I have not run into this issue updating the model as part of a node script.

**Comment by madebysid** [comment]
Hey @seanemmer, sorry it took me song long to get to this, but could you try put the latest alpha and check if you're still seeing this? I just tried it out and I'm unable to reproduce. Let me know!
