### ISSUE TITLE
[Prisma Studio] As a user, I can do the same CRUD operations on the modal when trying to link two items

### ISSUE THREAD

**Issue by smakosh** [prisma/studio#404]
1. Prisma2 version (`prisma2 -v`):
```
2.0.0-beta.2
```

2. Logs from Developer Tools Console, if any:

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

4. Prisma2 schema (if relevant):

It would be nice to be able to create a new record when trying to link a specific item to another when there is nothing to link

![image](https://user-images.githubusercontent.com/20082141/79211020-8b190900-7e3d-11ea-9f4c-7c196c92a2fd.png)

**Comment by madebysid** [comment]
Hey @smakosh, thanks for the feature request and sorry for not replying sooner! 
As you might know, this is already possible in a regular Prisma Client script using the `create` parameter, but adding this in Studio would need at least some product / design input, so I'll pick this up soon when we have a clearer idea of what exactlt we want to do!
