### ISSUE TITLE
New tab popup is broken for large model names and large number of models

### ISSUE THREAD

**Issue by schickling** [prisma/studio#409]
Demo: https://prisma.studio/preview?project=sportsdb

![image](https://user-images.githubusercontent.com/1567498/80012243-4c362380-84cd-11ea-8e98-3e15fbbc9db3.png)

**Comment by madebysid** [comment]
Fixed now. The new tab dropdown now stretches as much as needed so all model names are visible (within reason). This makes it so model names are ellipsified only in the worst case.

A similar thing was happening in the sidebar as well, so that's fixed too.
