### ISSUE TITLE
Enter + Enter on a back-relation leads to edited fields

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#410]
On https://prisma.studio:

https://www.loom.com/share/8c9bad30ccf44b28bb1b225e1a860a85

**Comment by madebysid** [comment]
This is fixed on the latest alpha (and the demo deployment)

I noticed this kind of thing was happening on both relation lists and relations. Relation lists were set to `[]`, and relations were set to `null`.

Once I fixed this, I noticed that even when you didn't actually change the relation list / relation, the field was still marked as dirty. (the act of opening the dialog was marking the field as dirty). This no longer happens either.

There are also tests for both these cases.
