### ISSUE TITLE
Where can i find the source code for the prisma studio

### ISSUE THREAD

**Issue by khanakia** [prisma/studio#419]
1. Prisma2 version (`prisma -v`):

2. Logs from Developer Tools Console, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@alpha`)

4. Prisma2 schema (if relevant):
```
Where can i find the source code for the prisma studio
```

**Comment by madebysid** [comment]
Hi @khanakia, Studio isn't yet open source, you'll find more details here: https://github.com/prisma/studio/issues/76, I'd suggest following that thread for updates :)
