### ISSUE TITLE
Unknown arg Error every studio launch.

### ISSUE THREAD

**Issue by CarbonTTV** [prisma/studio#421]
Hello, recently my computer was shut down in the time that Prisma was running as well. (I don't know if this relates but I'm going to keep it) and now on, every launch of Studio gives me this error despite PrismaCLI and the SQL server is just fine and functioning properly. I tried to look for an answer for this but was unable to locate one. Thanks for the great product, sorry if this is my mistake (newish to prisma), and thanks for the help in advance.

1. Prisma2 version (`prisma -v`):
2.0.0-beta.7
2. Logs from Developer Tools Console, if any:
```
Studio started at http://localhost:5555
Error in request:  {
  telemetry: true,
  message: 'Unknown arg `first` in first for type guilddata. Did you mean `cursor`?\n',
  stack: 'Error: Unknown arg `first` in first for type guilddata. Did you mean `cursor`?\n' +
    '\n' +
    '    at Document.validate (C:\\Users\\monto\\AppData\\Roaming\\Prisma\\Studio\\-Users-monto-Downloads-OnePrismaSummit\\runtime\\index.js:1:100210)\n' +
    '    at Object.s [as guilddata] (C:\\Users\\monto\\AppData\\Roaming\\Prisma\\Studio\\-Users-monto-Downloads-OnePrismaSummit\\runtime\\index.js:1:70857)\n' +
    '    at Object.n.<computed> [as findMany] (C:\\Users\\monto\\AppData\\Roaming\\Prisma\\Studio\\-Users-monto-Downloads-OnePrismaSummit\\runtime\\index.js:1:72200)\n' +
    '    at eval (eval at Photon.request (C:\\Users\\monto\\Downloads\\OnePrismaSummit\\node_modules\\@prisma\\cli\\build\\index.js:2:2320106), <anonymous>:5:55)\n' +
    '    at Photon.request (C:\\Users\\monto\\Downloads\\OnePrismaSummit\\node_modules\\@prisma\\cli\\build\\index.js:2:2320295)\n' +
    '    at PhotonService.respond (C:\\Users\\monto\\Downloads\\OnePrismaSummit\\node_modules\\@prisma\\cli\\build\\index.js:2:1312846)\n' +
    '    at WebSocket.StudioServer.onWSMessage (C:\\Users\\monto\\Downloads\\OnePrismaSummit\\node_modules\\@prisma\\cli\\build\\index.js:2:2528084)\n' +
    '    at WebSocket.emit (events.js:315:20)\n' +
    '    at WebSocket.EventEmitter.emit (domain.js:485:12)\n' +
    '    at Receiver.receiverOnMessage (C:\\Users\\monto\\Downloads\\OnePrismaSummit\\node_modules\\@prisma\\cli\\build\\index.js:2:2700686)',
  isPanic: undefined,
  code: undefined
} {
  query: 'prisma.guilddata.findMany({\n' +
    '  first: 100,\n' +
    '  select: {\n' +
    '    guildID: true,\n' +
    '    guildName: true,\n' +
    '    guildOwner: true,\n' +
    '    guildPrefix: true,\n' +
    '  }\n' +
    '})'
}
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@alpha`)
Yes (2.0.0-alpha.1273)
4. Prisma2 schema (if relevant):
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model guilddata {
  guildID     Int     @default(autoincrement()) @id
  guildName   String
  guildOwner  String
  guildPrefix String?
}
```

**Comment by wamburu** [comment]
Getting same error with [`2.0.0-beta.7`](https://github.com/prisma/prisma/releases/tag/2.0.0-beta.7).
The pagination format has been updated but breaks studio.

I have no idea who to fix this, stuck too.

**Comment by primaryperson** [comment]
I have problem the same. I started use version [2.0.0-beta.7](https://github.com/prisma/prisma/releases/tag/2.0.0-beta.7)

**Comment by FrankFang** [comment]
Same here #422 .
Just downgrade to 2.0.0-beta.6

**Comment by madebysid** [comment]
Hey everyone, there was a breaking change with pagination in Prisma Client with 2.0.0-beta.7 which broke Studio, as most of you noticed. I've just pushed out 2.0.0-alpha.1290 that should fix this. 

Could you try updating? The fix will also land with the next beta sometime this week.

**Comment by CarbonTTV** [comment]
Perfecto! Works perfect for me over here on 2.0.0-alpha.1290 and the new 2.0.0-alpha.1291!
