### ISSUE TITLE
Prisma studio don't work by version 2.0.0-beta.7

### ISSUE THREAD

**Issue by primaryperson** [prisma/studio#423]
When did update scheme pagination (first, last to take)
Prisma studio didn't get update select default
![image](https://user-images.githubusercontent.com/32566617/83339137-743a5300-a2d3-11ea-8cc0-fb3acdd6414b.png)

**Comment by madebysid** [comment]
Hey everyone, apologies for this!
There was a breaking change with pagination in Prisma Client 2.0.0-beta.7 that caused Studio to break too. I've just pushed out 2.0.0-alpha.1290 that fixes this. Could you try updating?

This will also land on beta with the next release (sometime this week)

**Comment by madebysid** [comment]
@macrozone I agree. Once Prisma Client hits GA (soon!), breaking changes will taken much more seriously, and problems like this should not occur.
