### ISSUE TITLE
[Feature Request] Add Authentication

### ISSUE THREAD

**Issue by nahtnam** [prisma/studio#428]
Hey,

Love the idea of Prisma Studio. I was wondering what the thoughts for the following features is:

> Add some sort of password or OAuth system so we can deploy it and manage our DBs (multiple dbs at once would be nice) sort of like PHPMyAdmin

I understand that these might be out of the scope of the project, just wondering what the consensus is.

**Comment by madebysid** [comment]
Hey @nahtnam! Coincidentally, this was recently brought up internally as well, and we think we'd like to build something like this. Admittedly this is something that we'll tackle quite a ways in the future though, after Studio is released as GA (not --experimental like it is right now).

Is your second point a different feature request? If so, could you perhaps create a second issue for it so it is tracked correctly? If not, then I think I misunderstood it, could you elaborate how it is related to authentication?

**Comment by nahtnam** [comment]
Hey, thanks for the reply. The second request is different, I'll create a different ticket for that and edit my post

**Comment by koleary94** [comment]
Hey @nahtnam and the prisma team! Really appreciate all of the progress on this tool and the recent release of the GUI! I am curious if there's been any further internal discussion surrounding this topic? I'm trying to think of some clever ways to add auth to either the gui or web experience for one of our clients that hopefully isn't too far out of line with the approach Studio will use in the future. Thanks!

**Comment by nahtnam** [comment]
Hi,

If you really need to host Prisma studio and want to secure it, I'd recommend using either Cloudflare Access or Twingate to hide/secure your interface

**Comment by martzoukos** [comment]
Hey @koleary94 !

We currently don't have this exact functionality in our plans but we do consider having some kind of a hosted version of Studio in the future. In fact we could have some (very rough) prototypes with a couple of these ideas that we would like to test. Would you be open to a 45' session where I would walk you through it and ask a couple of questions about your use cases?

If yes, you can pick a slot from my [Calendar](https://calendly.com/martzoukos/45-minute-meeting-clone?month=2020-12). 

@nahtnam , you would of course be very welcome to book one slot too :).

**Comment by dankolesnikov** [comment]
@martzoukos Is there a timeline on Prisma Studio being hosted and point to our Postgres hosted on Heroku? We are ready to pay you money for this!

**Comment by martzoukos** [comment]
Hey @dankolesnikov !

You should be able to do that at https://cloud.prisma.io/ . Let me know if that works or not.

PS: We'll be sending our bank account information soon 😁

**Comment by madebysid** [comment]
Also going to go ahead and close this issue because I believe https://cloud.prisma.io/ is exactly what this was asking for. Let me know otherwise!

**Comment by ScribeSavant** [comment]
@nahtnam If you still need it there is a fastify plugin for that (unofficial) https://github.com/ScribeSavant/prisma-studio-fastify

**Comment by LeakedDave** [comment]
I'm unable to see my database tables on cloud.prisma.io? I only see Accelerate and Pulse configuration

**Comment by MatheusGxx** [comment]
> Não consigo ver minhas tabelas de banco de dados em cloud.prisma.io? Só vejo a configuração Accelerate e Pulse

estou com o mesmo problema.
