### ISSUE TITLE
In the "connect to X" view I would like to connect when clicking on a row

### ISSUE THREAD

**Issue by timsuchanek** [prisma/studio#430]
In this view, when I click on a cell, it selects the cell, which is useless in this screen.
Instead it should select the row.

![image](https://user-images.githubusercontent.com/1094804/85844229-ac359880-b7a2-11ea-9716-1a32d8bffe1e.png)

**Comment by madebysid** [comment]
@tim the relation modal is no longer exists. RIP. In the new relation editor, you cannot select cells, which should solve this problem.
