### ISSUE TITLE
Loading state shows unexpected data

### ISSUE THREAD

**Issue by janpio** [prisma/studio#432]
This is from current version of https://prisma.studio/preview?project=chinook

![studio1](https://user-images.githubusercontent.com/183673/86343465-4ab97200-bc59-11ea-9129-be194f0e5bf5.gif)

These are the important frames:

1.
<img width="1046" alt="studio1-0 15" src="https://user-images.githubusercontent.com/183673/86343502-586ef780-bc59-11ea-9e5e-54ff42914c59.png">
<img width="1046" alt="studio1-1 17" src="https://user-images.githubusercontent.com/183673/86343507-59a02480-bc59-11ea-8126-1c8c2dd5243e.png">
When loading `PlaylistTrack`, it first shows the `PlaylistId` as 1,2,3,4,5,... before loading the correct 1,1,1,1,1,1...

2.
<img width="1046" alt="studio1-2 34" src="https://user-images.githubusercontent.com/183673/86343536-61f85f80-bc59-11ea-92c3-946329f0256b.png">
<img width="1046" alt="studio1-3 37" src="https://user-images.githubusercontent.com/183673/86343543-64f35000-bc59-11ea-9033-c7abe5305b98.png">
For `Playlist` it defaults the `PlaylistId` to 1 before showing the real one, and the number of relations to 0 before showing the real one.

**Comment by janpio** [comment]
Sidd posted a comment explaining this here: https://github.com/prisma/studio/issues/446#issuecomment-652993185

**Comment by madebysid** [comment]
This will be fixed with the next `dev` version of @prisma/cli (currently building)
