### ISSUE TITLE
When opening relation accordion number of connected items is not shown any more

### ISSUE THREAD

**Issue by janpio** [prisma/studio#435]
This is from current version of https://prisma.studio/preview?project=chinook

![image](https://user-images.githubusercontent.com/183673/86344834-12b32e80-bc5b-11ea-8934-bbb8712a0c41.png)
![image](https://user-images.githubusercontent.com/183673/86344883-2199e100-bc5b-11ea-88a8-e5ff9e1dc13a.png)

**Comment by madebysid** [comment]
Fixed on latest `dev`
