### ISSUE TITLE
Selecting and then unselecting item in Relation accordion still leaves "1 pending change"

### ISSUE THREAD

**Issue by janpio** [prisma/studio#437]
This is from current version of https://prisma.studio/preview?project=chinook

1. Open a relation accordion
2. Select one of the entries shown
3. Correctly told "1 pending change"
4. Deselect checkbox again
5. Footer still says "1 pending change"

**Comment by madebysid** [comment]
I think this is the same thing as: https://github.com/prisma/studio/issues/420.

Currently, actions (connecting to a record, updating a field etc.) do not cancel each other out. So when you change the relation back to its original value, Studio doesn't know that. It just thinks you touched the relation, so it must be a change.

I think this cancelling thing is a great thing to have though, so I want to pick it up soon. Closing this in favour of #420 then!
