### ISSUE TITLE
Scrolling down in relation accordion does not show entries

### ISSUE THREAD

**Issue by janpio** [prisma/studio#438]
This is from current version of https://prisma.studio/preview?project=chinook

![image](https://user-images.githubusercontent.com/183673/86345262-99680b80-bc5b-11ea-814f-7a9df120c8cb.png)
Stays like this. No indication if it is still loading data or broken.

**Comment by janpio** [comment]
Console logging also does not indicate anything is being loaded.

**Comment by madebysid** [comment]
This will be fixed with the next `dev` version of @prisma/cli (currently building)
