### ISSUE TITLE
Styling of editing Int is different from editing String

### ISSUE THREAD

**Issue by janpio** [prisma/studio#440]
This is from current version of prisma.studio/preview?project=chinook

The `String` is positioned as the normal display, for the `Int` the input jumps to the left:
![studio3](https://user-images.githubusercontent.com/183673/86345740-375bd600-bc5c-11ea-8499-01892b253085.gif)

**Comment by madebysid** [comment]
@janpio What browser are you using? I'm unable to see this on Firefox or Chrome

**Comment by janpio** [comment]
Chrome on Windows, but I can also not reproduce it now. Strange.
