### ISSUE TITLE
Prevent Studio to edit autogenerated PK fields

### ISSUE THREAD

**Issue by janpio** [prisma/studio#442]
https://prisma.studio/preview?project=chinook let's me edit the PK values of the tables, although afaik that is not supported by Prisma Client.

**Comment by madebysid** [comment]
Are you sure? Just tried that on a Prisma Client script and it works. Is it specific instances where it doesn't work perhaps?

Here's my script FWIW:
```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const main = async () => {
  await prisma.user.create({
    data: {
      id: 1,
      email: "test",
      name: "test",
    },
  });
  await prisma.user.update({
    where: {
      id: 1,
    },
    data: {
      id: 2,
    },
  });
  console.log(await prisma.user.findMany());
  await prisma.disconnect();
};

main().catch(async (e) => console.log(e));

```

It doesn't work on Studio currently though, because the script I generate is incorrect.

**Comment by janpio** [comment]
Afaik you can not edit auto generated values. (I assumed the PK here was auto generated)

**Comment by madebysid** [comment]
@janpio It seems you can do that too, just checked. I've also fixed the problem in Studio, so you can change ID fields' values. Pending release.

**Comment by janpio** [comment]
See internal discussion: https://prisma-company.slack.com/archives/CEYCG2MCN/p1594043305397600

**Comment by madebysid** [comment]
So now the behaviour would be: Studio allows you to edit these special PK fields, but you see an error when you commit your changes. Going to keep this open so that we can perhaps disallow editing them in the first place.
