### ISSUE TITLE
When scrolling in a table the "Reload" button is replaced with "Reloading" while new data is loaded

### ISSUE THREAD

**Issue by janpio** [prisma/studio#444]
prisma.studio/preview?project=chinook

Doesn't "reload" load the complete table content new vs. just load additional data? 
This also being used as a loading indicator feels like it used for something different.

**Comment by madebysid** [comment]
Do you mean that the `Reload` button changes during infinite scrolling? (When it probably shouldn't?)

**Comment by janpio** [comment]
Yes, when scrolling the "Reload" button changes to "Reloading" (in deactivated state) while it loads.

**Comment by madebysid** [comment]
The reload button is now an icon, and doesn't have a "loading" state, so I guess this is obsolete now!
