### ISSUE TITLE
Loading state show wrong data first

### ISSUE THREAD

**Issue by janpio** [prisma/studio#446]
Via https://prisma.studio/preview?project=chinook

1. PlaylistId first shows the same number of entries as the previews table I was in (playlist), and uses 1,2,3,4... before showing real data:
<img width="1046" alt="studio1-0 15" src="https://user-images.githubusercontent.com/183673/86347477-a5090180-bc5e-11ea-8c65-4a3a02e0c525.png">
<img width="1046" alt="studio1-1 17" src="https://user-images.githubusercontent.com/183673/86347479-a5a19800-bc5e-11ea-83ba-a55554d39e0a.png">

2. Other way around, Playlist shows too many entries first with PlaylistId = 1 and 0 relations - before it loads the correct data:
<img width="1046" alt="studio1-2 34" src="https://user-images.githubusercontent.com/183673/86347482-a6d2c500-bc5e-11ea-8f1e-ac1821717074.png">
<img width="1046" alt="studio1-3 37" src="https://user-images.githubusercontent.com/183673/86347485-a6d2c500-bc5e-11ea-8073-263d4762d949.png">

**Comment by madebysid** [comment]
This is likely the same thing as https://github.com/prisma/studio/issues/432. This is also related to #447 

Basically, I haven't implemented a loading component yet. So you see values from an older model just before the new values are loaded in (the number of rows, sometimes cell values might show up incorrectly too).

Once the loader comes in (the skeleton rows that you see in a relation accordion), it will mask this. I'm closing this in favour of #432!

**Comment by janpio** [comment]
This was indeed a duplicate of https://github.com/prisma/studio/issues/432 that I could not find any more before.
