### ISSUE TITLE
Loading state is not really indicated

### ISSUE THREAD

**Issue by janpio** [prisma/studio#447]
Via https://prisma.studio/preview?project=chinook

See screenshot from https://github.com/prisma/studio/issues/446 for loading states that do not indicate in any way that things are still loading. No spinner, no icon indicating it in any other way besides the data being wrong:

<img width="1046" alt="studio1-0 15" src="https://user-images.githubusercontent.com/183673/86347477-a5090180-bc5e-11ea-8c65-4a3a02e0c525.png">
<img width="1046" alt="studio1-2 34" src="https://user-images.githubusercontent.com/183673/86347482-a6d2c500-bc5e-11ea-8f1e-ac1821717074.png">

**Comment by madebysid** [comment]
This will be fixed with the next `dev` version of @prisma/cli (currently building)

**Comment by janpio** [comment]
I now see "recatangles" with rounded corners in the content. Is that it?

**Comment by madebysid** [comment]
@janpio yeah, they’re meant to be skeleton rows.
