### ISSUE TITLE
Can not sort or filter in relation accordion

### ISSUE THREAD

**Issue by janpio** [prisma/studio#449]
I can only scroll through the list of many, many items and hope I find the one I am looking for.

**Comment by madebysid** [comment]
No sort, but searching is now possible. Do I close or would you like to keep it open so sort can be supported?

**Comment by janpio** [comment]
Feel free to close and open a new issue for the sorting is you think this might be relevant.

**Comment by madebysid** [comment]
Created https://github.com/prisma/studio/issues/608 for sorting, closing this one
