### ISSUE TITLE
Temporary error telemetry flow in Studio

### ISSUE THREAD

**Issue by schickling** [prisma/studio#45]
- Interactive prompt (options: yes, always, no, never)
- Link to temporary telemetry docs (see https://github.com/prisma/prisma2/issues/396)

**Comment by madebysid** [comment]
@schickling Could this be moved to the next cycle's candidate? Not completely sure what this entails, and me not being here this week doesn't help either.

**Comment by janpio** [comment]
Will pick up again with @tim when both are back.

**Comment by nikolasburk** [comment]
Does this need an extra spec or is this enough? https://prisma-specs.netlify.com/cli/telemetry/

Basically the wording in Studio should be similar, but I'm guessing the UI will be a bit different?

If there should be an extra spec, where should it live ideally?
