### ISSUE TITLE
[Feature Request] Allow Custom Functions

### ISSUE THREAD

**Issue by nahtnam** [prisma/studio#451]
Hey,

Thoughts on the following feature request?

> Allow us to add custom buttons that will execute prisma code. For example, I would like to create an account with a temporary password so I could create a `createAccount` function that will take in some input fields and generate a record but with a hashed password

Sort of like what retool.com is doing but built straight into prisma studio?

**Comment by madebysid** [comment]
Hey @nahtnam, thanks for the feature request! Something like this is possible, although I admit we haven’t really looked into it in detail too much, so the UX might be a bit off. 

Whenever you try to close a dirty tab (a tab you’ve made changes to, like sorting it, hiding columns etc), you can save a tab and it will show up as such in the sidebar. 

Of course, this isn’t ideal, so I’ll keep this issue open!
