### ISSUE TITLE
`codicon` font missing

### ISSUE THREAD

**Issue by hexrcs** [prisma/studio#453]
As shown in the screenshot below, hovering over the space next to the line numbers in the Monaco editor does not display an arrow to fold the code block. Seems like the `codicon` font is missing.

![image](https://user-images.githubusercontent.com/26751752/86532046-11863980-bec7-11ea-9aba-4921d77817a7.png)

There's an error in the console saying a `http://localhost:5555/9242107df7da7c6ad3cadf3133abcd37.ttf` file 404'ed.

Browser version: Chrome 83.0.4103.116, Guest profile
`@prisma/cli` version: v2.1.3 (darwin) (363f5a521d6b06543e53d134652a0037a3096d41), bundled in `nexus-plugin-prisma` v0.10.0

**Comment by madebysid** [comment]
@hexrcs Oooh, thanks for the investigation, I'll add that font in!

**Comment by madebysid** [comment]
@hexrcs What browser are you on? I tried Chromium derivatives, Firefox and Safari, can't seem to see this, even after a hard reload.

**Comment by hexrcs** [comment]
I was on Chrome 83 stable, using a guest profile. Sorry for forgetting to add this info, edited the issue.

I will upgrade Nexus and the Prisma plugin today and see if the issue is still there.

**Comment by hexrcs** [comment]
The font is still missing in v2.2.2. See [this screencast](https://www.youtube.com/watch?v=6LouTqW9OLo).

**Comment by madebysid** [comment]
Ah, I just tried it on that specific version (2.2.2) and was able to see it. I don't see it anymore on 2.3.0-dev.43 though, could you confirm?

**Comment by hexrcs** [comment]
Cleared `node_modules` and tested on both v2.3.0-dev.43 and v2.3.0-dev.44 in guest profile, still missing somehow. :(

**Comment by madebysid** [comment]
Never really figured out what this was, but we've removed the Code Editor temporarily (till after GA), so I guess this is technicallly "fixed"? :D
