### ISSUE TITLE
Stuck at "Getting things ready" when Studio is open in multiple places

### ISSUE THREAD

**Issue by niyazpk** [prisma/studio#454]
When I run `npx prisma studio --experimental`, the page loads, and shows the message "Getting things ready" at the top and then nothing happens. The page is blank, and nothing loads.

I was able to connect to this DB a few hours ago, and I am still able to connect to it at the same endpoint using my mysql client. I have tables and data in the DB, and I can see and query them using various other clients.

Retried with `npx prisma generate && npx prisma migrate save --experimental && npx prisma migrate up --experimental && npx prisma studio --experimental` and the issue still persists.

1. Prisma2 version (`prisma -v`): 6.14.4

2. Logs from Developer Tools Console, if any:
```
Socket connection established
serverBus.js:1 Replaying 0 queued events
studioBundle.js:73 Studio version 0.229.0
DevTools failed to load SourceMap: Could not load content for http://localhost:5555/serverBus.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:5555/studioBundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:5555/studioBundle.4cca927db5078ef704f2.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Updated and tried. Yes the issue persists.

4. Prisma2 schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @niyazpk, this is likely not an issue with your MySQL DB, but with Studio itself.

First: the version you've quoted for the prisma CLI (6.14.4) looks funky. It should be `2.1.3`. Perhaps double check to be sure?

Since you say that you're still seeing it on `dev`, do you see any logs on the DevTools console / Terminal window after this update? (I'm unable to reproduce this)

I'm guessing this is a remote DB, so can you confirm if you can run a simple Prisma Client query outside of Studio as well? You might have a script like so:

```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const main = async () => {
  await prisma.user.findMany(); // Replace this with a query that makes sense in your context
  await prisma.disconnect();
};

main().catch(async (e) => console.log(e));

```

Studio on `dev` has a few significant changes under the hood, so any details you can provide will be super useful to fix potential regressions / issues before the next (2.2.0) release!

**Comment by niyazpk** [comment]
For the CLI version, looks like I used the wrong command:

```
$ npm prisma -v
6.14.4

$ npx prisma -v
Environment variables loaded from prisma/.env
@prisma/cli          : 2.1.3
Current platform     : darwin
Query Engine         : query-engine 363f5a521d6b06543e53d134652a0037a3096d41 (at /<redacted>/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 363f5a521d6b06543e53d134652a0037a3096d41 (at /<redacted>/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 363f5a521d6b06543e53d134652a0037a3096d41 (at /<redacted>/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 363f5a521d6b06543e53d134652a0037a3096d41 (at /<redacted>/node_modules/@prisma/cli/prisma-fmt-darwin)
```

I am not able to reproduce this issue anymore. I will update this again if I run into this in the future.

FWIW, the issue went away once I closed a bunch of studio tabs in some other windows in my browser. Not clear why this should matter. Probably just a coincidence?

**Comment by madebysid** [comment]
@niyazpk Aha, so that's it! 
I'm already aware that opening Studio in multiple places causes issues like this. I don't see an actual Github issue for it though, so I've changed the title of your issue to reflect this, hope you don't mind!

**Comment by madebysid** [comment]
Latest `dev` version of `@prisma/cli` (`2.7.0-dev.60` as of writing) now includes a fix that allows Studio to be open in multiple places. Please give it a shot and let me know if it works as expected!
This will also land on 2.7.0 this Tuesday.
