### ISSUE TITLE
"null" as a string the default empty value of required string fields

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#456]
Possible solutions:

- Default to an empty string
- Show red that it's an invalid value

![CleanShot 2020-07-06 at 12 44 14](https://user-images.githubusercontent.com/170299/86585251-6e94f480-bf86-11ea-98c3-3eeec179b21e.gif)

**Comment by madebysid** [comment]
@matthewmueller This is a regression. For required fields, the "cleared" value is supposed to be an empty string (since it is more common to want to do that)

**Comment by madebysid** [comment]
fixed on latest `dev`
