### ISSUE TITLE
Text editing operations shouldn't change based on data type

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#458]
Talked about this before but I'm more convinced now that this should be adjusted.

Potential solution:

- No matter the data type, up and down arrows will always move you front to back.
- We can add specialized UI for specific data types (calendar for date types, up/down icon for numbers, etc.)

![CleanShot 2020-07-06 at 12 48 16](https://user-images.githubusercontent.com/170299/86585638-0f83af80-bf87-11ea-87f6-348629c8090a.gif)

**Comment by madebysid** [comment]
@matthewmueller Ah this seems to be to be a difference between `<input type="text" /> and `<input type="number" />`. But its simple enough to change I suppose. I'll do what `<input type="text" />` does (up/down moves you front to back) in both cases

**Comment by madebysid** [comment]
This is done now. All inputs behave like `<input type="text" />`
