### ISSUE TITLE
Can't select a related row in "add row" dialog

### ISSUE THREAD

**Issue by timsuchanek** [prisma/studio#461]
I just created an empty user
![image](https://user-images.githubusercontent.com/1094804/86812584-78e6e980-c07f-11ea-9100-42e1595f5970.png)

and would like to connect to it:

![image](https://user-images.githubusercontent.com/1094804/86812559-708eae80-c07f-11ea-8cad-3f768d77246c.png)

But it's not there. Even reloading Studio doesn't help.
After creating a second user, the first one shows  up 🤷 
![image](https://user-images.githubusercontent.com/1094804/86812825-bc415800-c07f-11ea-9b77-d5814de56a9d.png)

**Comment by madebysid** [comment]
I think @heymartinadams saw the same thing in https://github.com/prisma/studio/issues/467, but that should be fixed. Could you try this out on latest `dev` too, @timsuchanek?

**Comment by heymartinadams** [comment]
I’m now on `2.3.0-dev.28` and it works correctly for my particular use-case.

**Comment by madebysid** [comment]
Going to close this, but please reopen if this resurfaces!
