### ISSUE TITLE
Table view doesn’t show new field

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#466]
Creating a new field via `prisma migrate save --experimental` and `prisma migrate up --experimental --verbose` doesn’t show up in Prisma Studio `table` view (even after performing `prisma generate`), but it *does* show up in Prisma Studio `tree` view.

1. Prisma2 version (`prisma -v`):

```
@prisma/cli          : 2.2.0
Current platform     : darwin
Query Engine         : query-engine 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /.../node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /.../node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /.../node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 45c4da4dd3ccd6a322796b228bdf937c7ce884e8 (at /.../node_modules/@prisma/cli/prisma-fmt-darwin)
```

2. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes

4. Prisma2 schema (if relevant):

before:
```prisma
model User {
  gender            String?
}
```

after:
```prisma
model User {
  gender            String?
  genderPronoun     String?
}
```

The `genderPronoun` field doesn’t show up in `table` view, only `tree` view.

**Comment by heymartinadams** [comment]
Ah! Seeing that `table` view had the new field **deselected**. Took me a while to catch onto it, even though the “26 Fields” button was highlighted yellow, implying that not all fields were showing.

Wonder if there’s a better UX for this use-case.

**Comment by heymartinadams** [comment]
Also, once I added the new field to the `table` view, it shows up at very end of table, rather than how I have the fields organized, which is relational fields first, then scalar fields, sorted alphabetically.

**Comment by madebysid** [comment]
@heymartinadams Thanks for letting me know!

So there's a couple of problems you've noticed:
1. A new field does not automatically get selected after being added.
2. The order of fields looks arbitrary when you show/hide them. The order should be the same as your schema.

Fortunately, both of these will be fixed in the latest `@prisma/cli@dev` version. Due to an issue with our release pipeline though, it'll likely go out on Monday though. I'll let you know when that happens.

**Comment by madebysid** [comment]
Out now on `dev`! Will also land on 2.3.0
