### ISSUE TITLE
Int fields are `0` instead of `null`

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#468]
`prisma@2.3.0-dev.7`, `commit 225c75492b90e646e0224803ae30926eb676bdd0`

Several records that have been populated with their `units` fields as `null` show up as `0` in Studio. In the image below, the record that has `0` should be `null`. And if you double-click on it, like in the record above it, it shows up as `null`.

Obviously, for `Int` fields we can’t have `null` fields show up as `0`.

![image](https://user-images.githubusercontent.com/11673745/87213537-9499fc00-c2da-11ea-839c-fba654c52f57.png)

Prisma schema:
```
model Lodging {
  units  Int?
}
```

**Comment by madebysid** [comment]
@heymartinadams Thanks for reporting! I've fixed this now. There seems to be some issue in our release pipeline, so I'll let you know when this is released (likely on Monday)

**Comment by madebysid** [comment]
This is out on `dev` now, will land on 2.3.0!
