### ISSUE TITLE
Tree view: Some scalars are missing an icon

### ISSUE THREAD

**Issue by schickling** [prisma/studio#47]
![image](https://user-images.githubusercontent.com/1567498/63578531-f9e4e180-c590-11e9-897a-2f1a51c825e4.png)

**Comment by madebysid** [comment]
Specifically:
1. Numbers
2. Enums
3. DateTime

**Comment by kuldar** [comment]
I added the SVGs for the missing types. Here's an overview of all of the current icons.
![types](https://user-images.githubusercontent.com/1710629/63732491-e1b4e100-c874-11e9-861e-51a90d89c4ac.png)
