### ISSUE TITLE
Allow cascading deletes

### ISSUE THREAD

**Issue by sdnts** [prisma/studio#473]
Here's Tim running into it: https://github.com/prisma/studio/issues/463
Here's the issue for Prisma Client to support it: https://github.com/prisma/prisma/issues/2810

If it ends up being automatic, then there isn't anything to do in Studio, but if there's a separate API for it, then Studio should handle it accordingly.

Either way, I need to decide what to do when it lands.

**Comment by danactive** [comment]
@sdnts Delete on cascade has been released https://github.com/prisma/prisma/releases/tag/2.26.0
