### ISSUE TITLE
[feature] Deselect a relation inside Studio?

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#476]
Prisma version: `2.3.0`

Is it possible to deselect an optional relation in Studio? Clicking on the optional relation brings up the overlay, but unable to deselect the relation from there.

For example, while in an `event` record, deselect an optional relation to a `venue`.

```prisma
model Event {
  venue              Venue?      @relation("EventsToOVenue", fields: [venueId], references: [venueId])
  venueId            String?
}

model Venue {
  venueId            String      @unique
  events             Event[]     @relation("EventsToOVenue")
}
```

![image](https://user-images.githubusercontent.com/11673745/88248798-40d2cf80-cc57-11ea-8747-39f5e52e2e75.png)

**Comment by madebysid** [comment]
@heymartinadams You should be able to click on that cell and press the `Delete` key. In fact, the delete key works on all cells. It sets the value of the cell to the lowest valid value (https://github.com/prisma/studio/issues/124#issuecomment-568742913)

It's not very discoverable though, so I'll keep this open!

**Comment by heymartinadams** [comment]
Wonder if this issue may already have been resolved, @madebysid.

**Comment by madebysid** [comment]
It should be indeed. There are now checkboxes within the relation table, which should make the operation more obvious.
