### ISSUE TITLE
[feature] Test an action prior to execution

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#481]
Prisma2 version (`prisma -v`): 2.4.0

In every day use, this happens quite frequently:
![image](https://user-images.githubusercontent.com/11673745/89355209-b08d8500-d66f-11ea-807a-20debc2c42ac.png)

What a sweet message by the way 😄 

Usually, because I forgot to first delete a required relation (e.g. several `UserSession` records connected to a `User` I attempted to delete).

Would it be wise (or even possible) to do a preliminary test to see if an action is even possible, before giving the developer the choice to proceed with it? Perhaps, the green button could be disabled instead, with an error message next to it.

![image](https://user-images.githubusercontent.com/11673745/89355266-d4e96180-d66f-11ea-80f9-085a282b3bec.png)

**Comment by heymartinadams** [comment]
ps: *love* the new Studio look, @madebysid! Excellent work (assuming this was you).

**Comment by madebysid** [comment]
@heymartinadams I do some primitive validation of actions, so perhaps this is a case I've missed. Could you share your schema and what exactly causes this? I don't think I understood exactly what you're doing. 

Also, I'm glad you like the new look, it was actually designed and implemented by @hrescak :D

**Comment by heymartinadams** [comment]
Using this, with 1 `User` having several `UserSession`s, try to delete that `User`.

```prisma

model User {
  id                String         @default(uuid()) @id
  createdAt         DateTime       @default(now())
  updatedAt         DateTime       @updatedAt
  UserSession       UserSession[]  @relation("RUserToUserSessions")
}

model UserSession {
  id            String         @default(uuid()) @id
  createdAt     DateTime       @default(now())
  updatedAt     DateTime       @updatedAt
  user          User           @relation("RUserToUserSessions", fields: [userId], references: [userId])
  userId        String
}
```

**Comment by madebysid** [comment]
Ah you seem to have run into the same issue as https://github.com/prisma/studio/issues/463. I believe this has to do with cascading deletes, which currently aren't supported. I'm closing this then in favour of https://github.com/prisma/studio/issues/473, hope that's okay!

I also tried your schema in a standalone script (outside Studio) and saw an error too.
