### ISSUE TITLE
[feature] Group action button with other buttons

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#482]
Prisma2 version (`prisma -v`): `2.4.0`

Minor feedback:
![image](https://user-images.githubusercontent.com/11673745/89372321-b187dc00-d69a-11ea-85a7-effdf3abfda2.png)

Using a large 27” screen, it’s always a bit of a production to move from the left side of the screen all the way to the far right side to confirm an action, only to then move the mouse all the way back to the left side to reload/refresh the results. Silly, I know.

Any chance you might consider moving the “Discard changes” and the “Save x change” buttons over to the left as well?

**Comment by hrescak** [comment]
This is good feedback, thank you @heymartinadams !

**Comment by madebysid** [comment]
@heymartinadams Just pushed out `@prisma/cli` `2.5.0-dev.14` with this changes. Do try it out and let us know how it feels!

**Comment by heymartinadams** [comment]
Awesome, @hrescak and @madebysid. So functional. Thank you! 🙏🏼✨

**Comment by heymartinadams** [comment]
Another suggestion: to keep the buttons visible and disabled when not usable, so the user is not surprised when a button with a different function suddenly appears underneath the cursor. Otherwise, there might be a potential for user error (e.g. first clicking on “Delete 1 record” → accidentally clicking a second time right away on “Save 1 change”)

![gif](https://user-images.githubusercontent.com/11673745/89933961-b847af00-dbc4-11ea-9083-a3b9adbc7f4a.gif)

**Comment by madebysid** [comment]
@heymartinadams Funnily enough, @hrescak & I had the exact same conversation today. We're planning on re-introducing the row-level checkboxes that you can use to select & deselect rows. This will indirectly address this.

What's happening here is that clicking outside the table is deselecting all rows. As a consequence, the `Delete Record` button goes away, and that in turn causes the `Save Changes` button to shift. Once the checkboxes are back, this will no longer happen (at least not "accidentally"), and so this "shifting" behaviour should be gone.

**Comment by madebysid** [comment]
@heymartinadams Latest version of the CLI (2.5.0-dev.46) includes these checkboxes. Feedback welcome!

**Comment by hrescak** [comment]
@madebysid i think we still need to prevent selection by means other than the checkbox for this to be in a good spot

**Comment by heymartinadams** [comment]
Omg that’s beautiful!! 😍 Absolutely stunning. Thank you, @madebysid and @hrescak! Such a pleasure to work in Studio.

**Comment by heymartinadams** [comment]
I also love that if you click on a relation, you show the results in an overlaid bubble rather than have the relation records show up between the original records.

**Comment by madebysid** [comment]
@heymartinadams Ah that's the interval where you've saved your changes but the request to Prisma Client hasn't finished yet, is it?

So I've made two changes that should fix this for good: 1: clicking outside the table no longer deselects all rows, & 2: while committing, the discard button is also disabled. (they will be on @prisma/cli@2.5.0-dev.69+ and will also land in 2.5.0)

Let me know if this still feels wonky!
