### ISSUE TITLE
Cache error

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#484]
1. Prisma2 version (`prisma -v`): `2.5.0-dev.5`

2. Logs from Developer Tools Console, if any:

I deleted an entire model `Payment`, and replaced it with a different model `FinancePayment`. Ever since, Studio is giving me the white screen of death, along with the following errors in the console:
![image](https://user-images.githubusercontent.com/11673745/89491643-8d90cd00-d764-11ea-8394-d86d80a210a4.png)

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes

Error persists even with removing prisma cache, deleting and rebuilding the `node_modules` folder. *However, issue is resolved when opening Prisma Studio in incognito mode!*

**Comment by madebysid** [comment]
Ah @heymartinadams, this is most definitely related to a performance "fix" I made recently. 
You should be able to get rid of the issue by clearing your IndexedDB from your DevTools, and then restarting Studio. This also explain why opening it up in Incongnito solves the problem too. 

Before you do that though, could you check what the IndexedDB version is? And also what object stores exist in there? It'll help me get to the bottom of this, thank you!

**Comment by heymartinadams** [comment]
Hi @madebysid, as follows:

IndexedDB Version 10, on Chrome 84.0.4147.105 on macOS

![image](https://user-images.githubusercontent.com/11673745/89574958-d5a20500-d7e1-11ea-86ed-79ae410b7943.png)

And in the `projects` store, you see this (both `Payment` and `Payout` tables no longer exist):
![image](https://user-images.githubusercontent.com/11673745/89575034-fa967800-d7e1-11ea-8823-0cfa8a979721.png)

For the `scripts` store, you see this:
![image](https://user-images.githubusercontent.com/11673745/89575134-2b76ad00-d7e2-11ea-8f24-96d9cce302ed.png)

`sessions`:
![image](https://user-images.githubusercontent.com/11673745/89575198-46492180-d7e2-11ea-9b31-417691b93e69.png)

Lmk if you need more info.

**Comment by madebysid** [comment]
@heymartinadams This is already super helpful. In case you haven't cleared your IndexedDB, could. you also confirm what the contents of the `tabs` object store are? I'm almost certain that the script you've shown in open in an active tab, which is why you;re seeing this error.

Either way, I know what the issue is now, will fix!

**Comment by heymartinadams** [comment]
Deleted the `tabs` object store already, sorry.

**Comment by madebysid** [comment]
Ah no isses, I'm guessing your problem is solved, but I'll keep this issue open till I can investigate what might have caused this.

**Comment by madebysid** [comment]
Hmm, I haven't been able to reproduce this again, but if you (or anyone else stumbling across this thread) manages to do it, please let me know so I can reopen!
