### ISSUE TITLE
List of fields to show/hide columns for models with a lot of fields is long and tedious to operate

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/studio#487]
Whenever wanting to hide all columns of a model with a lot of fields, you have to tick/untick each of them manually.
A (de)select all option would be nice

1. Prisma2 version (`prisma -v`): https://prisma.studio/preview?project=sportsdb

2. Logs from Developer Tools Console, if any:
`Studio version 0.248.0`

**Comment by madebysid** [comment]
There's a Select All / Deselect All button in the Fields dropdown now!
