### ISSUE TITLE
Opening the relations view is considered making a change

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/studio#488]
## What
Whenever double clicking to open the relations view to look at the relation, and then clicking outside the relations' view area to discard it, the app considers that I made a change which is not the case.
That's confusing

## Details
`Studio version 0.248.0`

**Comment by madebysid** [comment]
This should be fixed now!

There's one caveat: for relation lists, if you deselect a record then select the same thing again, it is considered a change. I decided that handling that case is not worth the hassle. Let me know if you disagree, and I'll reopen!

**Comment by thebiglabasky** [comment]
Yes, it makes sense since the thing was touched.
