### ISSUE TITLE
Design idea: Apply "type icons" from tree view to table header

### ISSUE THREAD

**Issue by schickling** [prisma/studio#49]
Apply this ...

![image](https://user-images.githubusercontent.com/1567498/63578698-50eab680-c591-11e9-8425-0f982816997a.png)

... to the table header (maybe even go from two lines to one line in order to be more space efficient)

![image](https://user-images.githubusercontent.com/1567498/63578641-31ec2480-c591-11e9-81c5-1d427df7731c.png)

**Comment by kuldar** [comment]
Here's a mockup of the idea. 

It does allow to save some vertical space, although the downside is lack of type visibility for relations and which values are optional. (If it's not as important, we could also put that information in a tooltip visible on hover).

![table-type-icons](https://user-images.githubusercontent.com/1710629/63732876-7ec44980-c876-11e9-9b00-c81070af58cb.png)

**Comment by madebysid** [comment]
Out with alpha.169
