### ISSUE TITLE
Editing of enum & boolean lists is sub-par

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#505]
Currently, it is just a regular input with no suggestions. We should design a proper editing workflow for these, no matter how uncommmon these types are

**Comment by nikolasburk** [comment]
Just came across this as well! Strong plus one for having a dedicated UI element (e.g. a switch) for boolean values.

**Comment by madebysid** [comment]
There's now a better workflow for editing scalar lists available on https://prisma.studio. A new `dev` version of the Prisma CLI will also go out soon with this change. Let me know how this feels!
