### ISSUE TITLE
Relation table is missing a min-height

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#506]
The relation table's height is too small, when a table has very few rows in it

![Screenshot 2020-08-25 at 14 12 40](https://user-images.githubusercontent.com/1710629/91167741-27e98e00-e6dd-11ea-9e39-ca1c721fdb88.png)

**Comment by madebysid** [comment]
There's now a min height (that is equal to the height of 2 rows). When wee have an empty state, we can adjust it!
