### ISSUE TITLE
Filtering records by id also shows unsaved records

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#509]
![search-limbo-record](https://user-images.githubusercontent.com/1710629/91171560-59655800-e6e3-11ea-9c6a-e370ee9cbb7e.gif)

Not sure if this is an expected behaviour or not.

**Studio version:** 0.267.0

**Schema:**
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  email String  @unique
  id    Int     @default(autoincrement()) @id
  name  String?
  posts Post[]
}

model Post {
  authorId  Int?
  content   String?
  id        Int     @default(autoincrement()) @id
  published Boolean @default(false)
  title     String
  author    User?   @relation(fields: [authorId], references: [id])
}
```

The project & database is from the Prisma Next.js example project.
https://github.com/prisma/prisma-examples/tree/master/javascript/rest-nextjs

**Comment by madebysid** [comment]
Did some investigation, this would hold for any filter you apply (to any field).
Since Studio cannot filter records that haven't been created yet, we decided to keep this behaviour, since the only real way to do it would be duplicate Prisma Client functionality, which obviously isn't worth it.
