### ISSUE TITLE
What would temporary tab titles be?

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#51]
In other words, tabs that were created by detaching from a preset, but aren't yet saved.

Currently, I'm using `Copy of <model-name>`

**Comment by kuldar** [comment]
One downside to prefixing new tabs with `Copy of` is that it's very easy to get into a `Copy of Copy of Copy of Users` situation.

If the names don't need to be unique, then maybe the easiest behavior right now would be to keep the same name until user changes it? 

Or alternatively we could append a number to the name so duplicating `Users` becomes `Users 1` and duplicating `Users 1` becomes `Users 1.1` etc.

**Comment by madebysid** [comment]
The names don't have to be unique, so I've changed the behaviour so that the tab title stays the same until you "save" the tab!
