### ISSUE TITLE
Blank screen when trying to filter a string field

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#510]
![filter-string](https://user-images.githubusercontent.com/1710629/91172305-99790a80-e6e4-11ea-8915-ec4fbbbafddf.gif)

**The error:**
![Screenshot 2020-08-25 at 15 07 11](https://user-images.githubusercontent.com/1710629/91172336-ac8bda80-e6e4-11ea-95bc-3d379d42a4ec.png)

**Studio version:** 0.267.0

**Schema:**
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  email String  @unique
  id    Int     @default(autoincrement()) @id
  name  String?
  posts Post[]
}

model Post {
  authorId  Int?
  content   String?
  id        Int     @default(autoincrement()) @id
  published Boolean @default(false)
  title     String
  author    User?   @relation(fields: [authorId], references: [id])
}
```

The project & database is from the Prisma Next.js example project.
https://github.com/prisma/prisma-examples/tree/master/javascript/rest-nextjs

**Comment by madebysid** [comment]
Fixed now! Will go out with the next `dev` release!
