### ISSUE TITLE
Allow filtering by relation fields

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#520]
Currently, you can only add a filter for scalar & enum fields. Prisma Client allows you to filter by relations, so Studio should too.

**Comment by thebiglabasky** [comment]
Re-posting here:

Supporting that as a 2-step process could be good indeed:

* Initial: don't crash and show a filter that is not even editable could work. Alternatively, having it editable without any editing help, typos in there basically making the filter invalid as for other fields
* Later: having better support for filtering on relations (need to define "better" though) Probably something with some kind of sub-menu could be good, although I'd leave that to @hrescak to coordinate if/once we get there.

I'm not sure that we should prioritize the "Later" milestone just yet until we've heard more about it.

**Comment by martzoukos** [comment]
Updated specs as of 08.12.2020 discussion:
1. Allow for filtering by "relation"ID field
2. Once you select the relation field, another dropdown next to it appears where the scalar properties of the related model appear (whatever the Client gives us, we can't have all the fields).
3. We only filter by 1 level deep.
