### ISSUE TITLE
Filtering issue (not/equals/contains/startsWith) when "" empty string field Value 

### ISSUE THREAD

**Issue by tkinte** [prisma/studio#528]
Trying to set a filter  **equals, contains** \... an **empty string** ("")  throws an error.
But **in, notIn \[\"\"\]** works correctly.

1. Prisma2 version (`prisma -v`):
`Environment variables loaded from prisma\.env
@prisma/cli          : 2.6.0  
Current platform     : windows
Query Engine         : query-engine 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules\@prisma\cli\prisma-fmt-windows.exe)
Studio               : 0.272.0
Preview Features     : connectOrCreate, transactionApi, distinct`
2. Logs from Developer Tools Console, if any:
```
[runQuery] Error in Prisma Client request: 

SyntaxError: Unexpected string
    at new AsyncFunction (<anonymous>)
    at Photon.request (C:\Program Files\EA_HOME\GraphQL\essential-postgres-prisma-nexus\node_modules\@prisma\cli\build\index.js:2:1616880)
    at PhotonService.respond (C:\Program Files\EA_HOME\GraphQL\essential-postgres-prisma-nexus\node_modules\@prisma\cli\build\index.js:2:868739)
    at WebSocket.StudioServer.onWSMessage (C:\Program Files\EA_HOME\GraphQL\essential-postgres-prisma-nexus\node_modules\@prisma\cli\build\index.js:2:774607)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:486:12)
    at Receiver.receiverOnMessage (C:\Program Files\EA_HOME\GraphQL\essential-postgres-prisma-nexus\node_modules\@prisma\cli\build\index.js:2:473381)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:486:12)
    at Receiver.dataMessage (C:\Program Files\EA_HOME\GraphQL\essential-postgres-prisma-nexus\node_modules\@prisma\cli\build\index.js:2:1516117) 

Object
code: "prisma.frame.findMany({↵  where: {↵    AND: [↵      {↵        frameName: {↵          startsWith: ":ESSENTIAL-C",↵        },↵      },↵      {↵        slotName: {↵          notIn: [":DIRECT-INSTANCES"],↵        },↵      },↵      {↵        facetName: {↵          **equals: """"**,↵        },↵      },↵    ]↵  },↵  take: 100,↵  skip: 0,↵  select: {↵    frameName: true,↵    frameType: true,↵    slotName: true,↵    facetName: true,↵    isTemplate: true,↵    valueIndex: true,↵    valueType: true,↵    shortValue: true,↵    longValue: true,↵  }↵})"
error: {stack: "SyntaxError: Unexpected string↵    at new AsyncFun…ode_modules\@prisma\cli\build\index.js:2:1516117)", message: "Unexpected string"}
__proto__: Object
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma2 schema (if relevant):
```

```
![Prisma Studio - Google Chrome 02-09-20 22_09_37](https://user-images.githubusercontent.com/11148442/92032271-333a5a80-ed6a-11ea-99d4-f23e85bc49c6.png)
![Prisma Studio - Google Chrome 02-09-20 22_08_36](https://user-images.githubusercontent.com/11148442/92032274-33d2f100-ed6a-11ea-9931-2d773c5df79e.png)
![Prisma Studio - Google Chrome 02-09-20 22_06_29](https://user-images.githubusercontent.com/11148442/92032278-346b8780-ed6a-11ea-8591-6e1b313d3575.png)
![Prisma Studio - Google Chrome 02-09-20 22_05_57](https://user-images.githubusercontent.com/11148442/92032279-346b8780-ed6a-11ea-85c6-fcd5221ce95f.png)

**Comment by madebysid** [comment]
Hey @tkinte, thanks for reporting this, I am able to see this behaviour too.

Here's what's happening: When you type in `""` in the filter field, you're actually searching for the literal value `""` in your `facetName` field, instead of an empty string. Moreover, if you empty out the field (type nothing in), then Studio thinks you want to search for `null` instead. Essentially, there's no way to actually search for an empty string from the filters.

I've just pushed out `v2.7.0-dev.6` with a couple of changes that should address this. You'll have to update `@prisma/cli` & `@prisma/client` (if you use it) to this version (or above)
You can now type in `"test"` & `test` and they'll both mean the same thing. That should also support your use case for searching for an empty string now!

Let me know if this is still an issue.
