### ISSUE TITLE
Better flow for creating an "empty" script

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#53]
As I understand it, the only way currently is to open an existing model/saved tab and change either the code or the query builder. (so that it detaches itself from the preset)

There used to be a `New Query` button, whose equivalent is essentially what's missing with tabs.

Maybe the New tab dropdown could have such an option

**Comment by kuldar** [comment]
Good point, I think we should definitely have a "New databrowser" action in the "quick open" menu, but we should also add an explicit button in the sidebar perhaps.

![new-databrowser](https://user-images.githubusercontent.com/1710629/63733057-483afe80-c877-11e9-8f9c-8b2d9ceac4b6.png)
![new-databrowser-hover](https://user-images.githubusercontent.com/1710629/63733056-483afe80-c877-11e9-8a0c-aa6a23bebcdd.png)

**Comment by madebysid** [comment]
Just to confirm: when you create a new saved tab, it would really be a detached version of the first model' preset then?

**Comment by idan** [comment]
@madebysid Dependent on #9 and #129?

Marking low impact, not sure about effort since the tabs work is unclear to me in scope.

**Comment by madebysid** [comment]
@idan I don't think this is dependent on #9, but #129 is relevant. If we can figure out a way to solve #129, then this is pretty low effort.

The question right now is: What happens when you click on this newly created tab? Which model does it open? If we just want to default to the first model (and let the user change the model as they want), then too, this is low effort.

**Comment by idan** [comment]
I sketched two possibilities for discussion

![studio_new_tab](https://user-images.githubusercontent.com/22723/66054430-d5ade600-e4e8-11e9-9018-78a57efe8267.jpg)

Option A, when you click on the new tab button, a popover appears at the position of the new tab button with a filterable list of models. It's possible to take the entire sidebar contents as a component and embed it there.

Option B, when you click on the new tab button, a blank slate appears with guidance text, and the sidebar is focused (and shown if it is currently hidden). The blank slate copy should be something like "Choose a model".

Come to think of it, option C is to embed the sidebar component in the blank slate itself, like the popover. Have some copy like "Choose a model for this tab" followed by the modelpicker. I like this on the basis of it being more direct/obvious, and also it's easier in terms of "what if I have multiple new tabs open". Works and feels like the new tab page in web browsers. We can display models you use most frequently at the top of the list.

**Comment by idan** [comment]
See more sketches from @schickling in #129

**Comment by idan** [comment]
Scheduled as a candidate for discussion at sync. Would like to get a sense for whether this is for beta or post-beta.

**Comment by madebysid** [comment]
Will naturallly pop up when designing scripts / playgrounds again, so closing!
