### ISSUE TITLE
Introduce a way to create a record

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#54]
I've put in a plus button next to the Run button, but I'm not sure if that's where we want it. Couldn't find an up-to-date artboard with it on Figma.

**Comment by kuldar** [comment]
I think that's an ok placement for the button for now. But perhaps label it "Add row"?

![dashboard](https://user-images.githubusercontent.com/1710629/63733177-994af280-c877-11e9-9ab8-1d6ec7f1f469.png)

**Comment by schickling** [comment]
This still seems broken.

**Comment by madebysid** [comment]
Can you check if it works now? I pushed some changes to alpha

**Comment by madebysid** [comment]
@schickling Possibly fixed now?
