### ISSUE TITLE
Can't filter by null values

### ISSUE THREAD

**Issue by flybayer** [prisma/studio#549]
1. Prisma version (`prisma -v` or `npx prisma -v`): 2.7.1
2. Logs from Developer Tools Console or Command line, if any: NONE
3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`): YES

Unless I'm missing something, there's no way to filter rows by null values. For some reason I've needed to do this a lot, and it's quite frustrating for it not to work 😅

**Comment by madebysid** [comment]
@flybayer You're right, there isn't. I suppose sorting by that column could work, but that's no solution :D
We'll look into this!

**Comment by madebysid** [comment]
@flybayer I've just pushed out a `dev` version of the Prisma CLI (`2.8.0-dev.47`). The latest Studio now contains two extra "operations" for optional fields in the filters, `isNull` and `isNotNull`:
![Screenshot 2020-09-25 at 20 53 12](https://user-images.githubusercontent.com/7689783/94305237-2677e380-ff71-11ea-8578-6adaa4cb8939.png)

These should let you filter by null values. Let me know how that works out!

This will also go out with 2.8.0 this Tuesday, in case you do not want to use a `dev` version.

**Comment by flybayer** [comment]
Awesome, thanks!!

**Comment by nihiluis** [comment]
Was this removed?

**Comment by SpBills** [comment]
Is this still here?
