### ISSUE TITLE
Studio enforces optional fields to be filled

### ISSUE THREAD

**Issue by zakthedev** [prisma/studio#551]
**Studio keeps asking to enter the fields owner and ownerID even tho they are optional (see schema below).**

1. Prisma version (`prisma -v` or `npx prisma -v`):

**Prisma CLI version: prisma/1.34.10 (windows-x64) node-v13.8.0**

2. Logs from Prisma Studio:

![image](https://user-images.githubusercontent.com/25425675/94173795-b72cc180-fe94-11ea-8937-ea6c40595ec6.png)

3. Prisma schema (if relevant):
```
model Client {
  id   Int    @default(autoincrement()) @id
  name String
  cars Car[]
}

model Car {
  id      Int     @default(autoincrement()) @id
  model   String
  owner   Client? @relation(fields: [ownerID], references: [id])
  ownerID Int?
}
```

Note: when I use pgAdmin 4 it work without issues:

![image](https://user-images.githubusercontent.com/25425675/94174210-4b972400-fe95-11ea-9773-d386c4e3fcc3.png)

**Comment by madebysid** [comment]
Hey @rightroad, thanks for reporting! Unfortunately, I can't seem to be able to reproduce this.

I'm also noticing that your Prisma CLI version looks funny, it should ideally be `2.x.x`. Could you make sure you're on the latest Prisma2 version (`2.7.1` as of writing) and see if this is still an issue?
(I believe you are on the latest version and the version mismatch might just be an `npx` thing, but I'd like to be sure :D)

Either way, I've just pushed out a `dev` version of the CLI (`2.8.0-dev.47`) that renders an additional question mark next to a field icon to signify an optional field, like so:
![Screenshot 2020-09-25 at 16 55 37](https://user-images.githubusercontent.com/7689783/94282314-f409be80-ff4f-11ea-8b71-b48e635b2340.png)

If you update your CLI and Client to `2.8.0-dev.47` and do not see the question mark, then it means that Studio doesn't see the field as optional, which would be very weird indeed. Please let me know if this happens.

If you do not want to use a `dev` version, you can also wait till Tuesday, when CLI `2.8.0` will be released, and you can check against that instead.

Let me know what you find!

**Comment by rightroad** [comment]
Thank you Sid for your reply! 

I had a global version of prisma installed and that's why it returned that weird version (from npm install prisma) but I'm actually using nexus-plugin-prisma 0.19.0 that include prisma/cli 2.7.0 and studio 0.287.0

I was able to reproduce the issue with that setup so I will be waiting for 2.8.0 release and see if this will be solved.

**Comment by madebysid** [comment]
Hey @rightroad, 2.8.0 went out last week, could you try updating and check if fields have an additional question mark next to their name? If so, are you still able to reproduce this?

**Comment by madebysid** [comment]
Going to go ahead and close this, but please feel free to reopen if you're still seeing this!
