### ISSUE TITLE
type Enum not showing properly

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#557]
For `prisma@2.8.0` I’m seeing an error for a field that displays enums:
![image](https://user-images.githubusercontent.com/11673745/94978275-84f11480-04d1-11eb-8cbe-e3a1f1404491.png)

```prisma
model UserImage {
  ...
  name        String?
  description String?
  type        ImageType @default(PROFILE)
  url         String
  ...
}

enum ImageType {
  HERO
  PROFILE
}
```

Once I double-click on one of the red fields, I get this error:
![image](https://user-images.githubusercontent.com/11673745/94978354-dd281680-04d1-11eb-94cb-5704e5eafd28.png)

**Comment by madebysid** [comment]
Hey @heymartinadams, I did some investigation and it seems this is the same issue as https://github.com/prisma/studio/issues/556, so I'm closing this, hope that's okay! :)
