### ISSUE TITLE
Visual query builder: Better filter workflow

### ISSUE THREAD

**Issue by schickling** [prisma/studio#56]
![image](https://user-images.githubusercontent.com/1567498/63601432-af318c80-c5c5-11e9-896d-d09eda1a5c30.png)

**Comment by madebysid** [comment]
Specifically:
When you add a new filter, it is "invalid" by default. So no records match, hence the white screen.

Perhaps we always add a valid filter, or defer filtering until after you close the tooltip. Both can get annoying though.

**Comment by idan** [comment]
Let's do the defer-query-execution thing right now; something better can be done post-beta.

**Comment by madebysid** [comment]
What I've done is add validation to these filters. Invalid filters are ignored. This has the effect of solving this issue. The first filter that you add is automatically "invalid" until changed when added, so records do not disappear.

I think this solution is more elegant that query defers, and also brings more functionality.

Closing, but if there are more things we'd want to do to this flow, feel free to reopen.
