### ISSUE TITLE
Studio doesn't let me save the newly created record

### ISSUE THREAD

**Issue by ryands17** [prisma/studio#560]
## Bug description

Studio doesn't allow me to save a record and the Save button is always disabled. Workaround currently is to refresh. Related Slack thread: https://prisma-company.slack.com/archives/CC8F34ALF/p1601885948000600

## How to reproduce

1. Create a model and run the migration steps

```prisma
model User {
  id        Int      @id @default(autoincrement())
  name      String?
  createdAt DateTime @default(now())
}
```

2. Run `npx prisma studio`

It will look like this when I enter a record (the _Saving changes_ button remains):

![image](https://user-images.githubusercontent.com/19697099/95073492-97b25600-072a-11eb-9fb3-33672e164f01.png)

It works fine on a refresh though.

## Expected behavior

Should allow to save the added record.

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: 12.18.4
- Prisma version: 2.8.0
```

**Comment by madebysid** [comment]
Ah, didn't notice you created this @ryands17 :D, I created https://github.com/prisma/studio/issues/562 for this issue. This should be fixed now in the latest `dev` release (2.9.0-dev.43 & above) and will also go out with the 2.8.1 patch release today. Closing!

**Comment by petekgithub** [comment]
Hello, this ticket has been closed but I have encountered the same problem and I can't proceed any further. could you please explain and I didn't see the solution. thanks!

**Comment by Ashmit72** [comment]
![Screenshot_2023-12-20_11_36_04](https://github.com/prisma/studio/assets/114178696/9e07abc4-2462-4dec-a6e8-c8481ff99b93)

I am also unable to save my data here it returns some strange code which i cannot copy. Can anyone help please

**Comment by kebele** [comment]
> ![Screenshot_2023-12-20_11_36_04](https://private-user-images.githubusercontent.com/114178696/291793333-9e07abc4-2462-4dec-a6e8-c8481ff99b93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNzQzOTksIm5iZiI6MTcwMzM3NDA5OSwicGF0aCI6Ii8xMTQxNzg2OTYvMjkxNzkzMzMzLTllMDdhYmM0LTI0NjItNGRlYy1hNmU4LWM4NDgxZmY5OWI5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QyMzI4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjAwMzgxOTE3ZjRlOTMzZGFlMjc1ZGJjMTU3MDc4YjRmYzYxNmI5YzMwMzhjM2QyZjQxY2YwN2Q3NmMxYTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7c689uohdgn_9zaqN3YOUpPDl4jpew_Jc9cAq6DpaI0)
> 
> I am also unable to save my data here it returns some strange code which i cannot copy. Can anyone help please

same problem

**Comment by gap579137** [comment]
Same issue here

**Comment by AchyutJadhav** [comment]
same issue

**Comment by renanmachad** [comment]
same issue >(

**Comment by arnold-aswan** [comment]
same issue
