### ISSUE TITLE
Case insensitive searching

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#561]
We stabilized `insensitiveFilters` in 2.8.0

How does this extend to Studio? For now, I've made it so all filters are `mode: "insensitive"`, since that made the most sense to have in a UI (in my opinion)

How do we allow people to configure this? Should this be configurable at all (for sake of simplicity)?

Also note that there are caveats that we should take into account when thinking about this:
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/case-sensitivity

**Comment by thebiglabasky** [comment]
No need to configure this for now imo. This also depends on the underlying database's configuration and mode: insensitive is only available for Postgres anyway.

**Comment by heymartinadams** [comment]
It sure would be useful for customer support-heavy enterprises. My side project uses Prisma w/ Postgres and unfortunately I didn’t force-lowercase all email addresses during migration, so there are those customers who ask us to look up their data, which we can’t find because their email address is `TheBigLebowski@gmail.com` 🤦🏻‍♂

**Comment by madebysid** [comment]
@heymartinadams That's a fair use case. Ideally, all searches would be case insensitive, but since only Postgres supports it for now, we'd like to not have different behaviour for searches depending on the underlying database, which is why this is a little tricky.

**Comment by madebysid** [comment]
So after a bit of discussion, we landed on the decision to allow case-insensitive searches on Postgres (without config though, for now).
The reasoning was that most people using Prisma do not switch databases on-the-fly very often, so tiny differences in search functionality is worth it since it does have its use. In the current CLI `dev` version (2.11.0-dev.35), you should be able to see this in action. This will also land with 2.11.0 next week.

If I understood you correctly @heymartinadams, you should be able to just use `thebig` in a `String` field's filter and get back all of `thebig...`, `theBig...`, `TheBig...`, `tHeBiG...` etc. Let me know if it doesn't work as you expect!
