### ISSUE TITLE
npx prisma studio doesn't work on WSL 1

### ISSUE THREAD

**Issue by foodornt** [prisma/studio#563]
## Bug description
when I run `npx prisma studio` on my ubuntu 18.04 wsl 1 machine it says it can't spawn the process powershell.exe
here's the error:
```
/home/darda/JS/hello-prisma/node_modules/@prisma/cli/build/index.js:2
module.exports=function(e,t){"use strict";var n={};function __webpack_require__(t){if(n[t]){return n[t].exports}var r=n[t]={i:t,l:false,exports:{}};var i=true;try{e[t].call(r.exports,r,r.exports,__webpack_require__);i=false}finally{if(i)delete n[t]}r.l=true;return r.exports}__webpack_require__.ab=__dirname+"/";function startup(){return __webpack_require__(4317)}t(__webpack_require__);return startup()}({7:function(e,t,n){"use strict";var r=this&&this.__createBinding||(Object.create?function(e,t,n,r){if(r===undefined)r=n;Object.defineProperty(e,r,{enumerable:true,get:function(){return t[n]}})}:function(e,t,n,r){if(r===undefined)r=n;e[r]=t[n]});var i=this&&this.__exportStar||function(e,t){for(var n in e)if(n!=="default"&&!Object.prototype.hasOwnProperty.call(t,n))r(t,e,n)};Object.defineProperty(t,"__esModule",{value:true});t.generatorHandler=t.GeneratorError=t.GeneratorProcess=void 0;var o=n(6921);Object.defineProperty(t,"GeneratorProcess",{

Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## How to reproduce
By running `npx prisma studio` in the project directory

## Expected behavior
start the studio

## Prisma information
```graphql
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env(MY_DATABASE_URL_DONT_WORRY_ABOUT_IT)
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  createdAt DateTime @default(now())
  content   String?
  published Boolean  @default(false)
  auther    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  userId Int     @unique
  user   User    @relation(fields: [userId], references: [id])
}

model User {
  id      Int      @id @default(autoincrement())
  name    String?
  email   String   @unique
  posts Post[]
  profile Profile?
}
```

## Environment & setup

- OS: WSL 1 Ubuntu 18.04.
- Database: PostgresQL
- Node.js version: v10.22.0
- Prisma version:

```
Prisma CLI version: prisma/1.34.10 (linux-x64) node-v10.22.0
```
but this is not the same as npx prisma, which prints out the following:
```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.8.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.294.0
```

**Comment by madebysid** [comment]
Hey @foodornt, I'll see if I can reproduce this.

1. Do you know if this happens on WSL2 as well?
2. Can you try running `npx prisma studio --browser=none` and see if this is still reproducible?
3. The error seems to imply that `powershell.exe` wasn't found, so I did a quick search and found this: https://stackoverflow.com/questions/57750620/how-to-fix-error-spawnsync-powershell-exe-enoent. Could you try this as well?

In all cases, this would still be a bug, but I'm trying to figure out what exactly is causing this :)

**Comment by janpio** [comment]
(Powershell not being available in WSL would not surprise me - the question is more why Studio would try to spawn powershell in a WSL environment... any idea what Studio is trying to do here @madebysid?)

**Comment by madebysid** [comment]
I believe it is `sindresorhus/open` trying to open up a browser, but I'll know for sure when I investigate!

**Comment by aaronfulkerson** [comment]
@madebysid I can confirm that this also happens on WSL2 and running npx prisma studio --browser=none prevents the process from crashing.

**Comment by foodornt** [comment]
Uhmmmm, I switched to linux guys. should I close this issue or not?

**Comment by aaronfulkerson** [comment]
@foodornt no.

**Comment by foodornt** [comment]
@aaronfulkerson aight

**Comment by madebysid** [comment]
@aaronfulkerson I've fixed this in `@prisma/cli` `2.11.0-dev.20`, could you try updating and see if this is still an issue? I've made it so errors that occur when opening the browser are now ignored (as they should have been from the start IMO), since they aren't supposed to be fatal.

When 2.11.0 goes out next week, I'd recommend updating to that version rather than use a `dev` version in the long run.

Let me know if you're still seeing this!

**Comment by madebysid** [comment]
@aaronfulkerson This should no longer be an issue with `@prisma/cli 2.11.0-dev.21` & above, could you try updating and see if this is still an issue? I've made it so errors that occur when opening the browser are now ignored (as they should have been from the start IMO), since they aren't supposed to be fatal.

When 2.11.0 goes out next week, I'd recommend updating to that version rather than use a dev version in the long run.

Let me know if you're still seeing this!

**Comment by aaronfulkerson** [comment]
@madebysid thank you!
