### ISSUE TITLE
[design] Favicon

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#564]
`v2.9.0-dev.61`

Question, why not use the Prisma logo instead? Since Prisma Studio is such a critical product in Prisma’s lineup, seems like a legit place for the Prisma brand, no? Just a thought, feel free to close.

![image](https://user-images.githubusercontent.com/11673745/95639594-e07d4e00-0a4d-11eb-897a-70eb1a3f00d3.png)

**Comment by madebysid** [comment]
Haha looks like I forgot to respond. The favicon you see is the semi-official Studio logo. It is also used in the Electron app. I think I'll close this for now :D
