### ISSUE TITLE
[feature] Reopen most recently opened tab

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#569]
`prisma 2.9.0`

We often look up relations, and open new tabs as a result (as described in https://github.com/prisma/studio/issues/476).

However, after closing the tab of the relation we just looked up, we’re not brought back to the previous tab. Instead, we have to specifically:
1. discard the unsaved layout (which is confusing, as mentioned in https://github.com/prisma/studio/issues/548); then
2. re-select that tab to go back to where we left off.

Instead, what if upon opening filtered records in new tab, upon closing that tab, **we’re instantly brought back to the original tab?**

While it may seem an insignificant user experience improvement, it’s one of those teeny tiny user experience improvements that would make Studio even more awesome IMO.

![Screen Recording 2020-10-23 at 1 41 53 PM](https://user-images.githubusercontent.com/11673745/97053341-9f9a3480-1537-11eb-9c9d-9d0adf4e59f1.gif)

**Comment by madebysid** [comment]
@heymartinadams Ah I think this is because Studio tries to focus the "next" tab in the tab list when you close a tab. I suppose an easy way to "fix" this would be to instead focus the "previous" tab when you close one, but I'll let @hrescak look at this as well, in case he has a more elegant solution

**Comment by madebysid** [comment]
@heymartinadams On `@prisma/cli@2.16.0-dev.12`, I've made a change so that when closing a tab, the previous tab is now focused. Plus, I found a bug around this as well.
I think if you try out Studio on there, you should find tab management more natural. Let me know if it doesn't!
