### ISSUE TITLE
[design] Cell overflow

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#576]
Prisma version: `2.10.2`

Cell of type `json` overflows when I activate it.

<img width="433" alt="Screen Shot 2020-11-09 at 12 36 50 PM" src="https://user-images.githubusercontent.com/11673745/98593704-67f5f100-2288-11eb-8d21-285d081c722c.png">

**Comment by madebysid** [comment]
Hey, thanks for letting me know! I've fixed this with `2.11.0-dev.59`, and it should also land with the stable `2.11.0` scheduled for release today.
