### ISSUE TITLE
Cannot read property 'forceUpdate' of null 

### ISSUE THREAD

**Issue by ghattrell** [prisma/studio#577]
1. Prisma version (`prisma -v` or `npx prisma -v`):

```
@prisma/cli          : 2.11.0
@prisma/client       : Not found
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.311.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
studioBundle.js:395 [BootstrapStore.init] Studio bootstrap failed
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes

4. Prisma schema (if relevant):
```
Not relevant
```

When running npx prisma studio in a docker container which is purely there to run prisma studio I get this error. Any guidance would be much appreciated.

![Screenshot 2020-11-19 at 18 03 47](https://user-images.githubusercontent.com/8737504/99705435-9f874900-2a91-11eb-9bce-f4fd2c847382.png)

**Comment by ghattrell** [comment]
Solved the problem, sorry for any time wasted

**Comment by madebysid** [comment]
No issues, nice to see this resolved!
