### ISSUE TITLE
n.update is not a function

### ISSUE THREAD

**Issue by marceloverdijk** [prisma/studio#583]
1. Prisma version (`prisma -v` or `npx prisma -v`):

`2.12.0`

2. Logs from Developer Tools Console or Command line, if any:
```
n.update is not a function
TypeError: n.update is not a function
    at wn.add (http://localhost:5555/mainChunk.js:395:90538)
    at we (http://localhost:5555/mainChunk.js:16:9232)
    at wn.o (http://localhost:5555/mainChunk.js:16:9128)
    at wn.add (http://localhost:5555/mainChunk.js:395:103359)
    at we (http://localhost:5555/mainChunk.js:16:9232)
    at wn.o (http://localhost:5555/mainChunk.js:16:9128)
    at http://localhost:5555/mainChunk.js:395:134398
    at Array.forEach (<anonymous>)
    at Object.hydrate (http://localhost:5555/mainChunk.js:395:134369)
    at ir.init (http://localhost:5555/mainChunk.js:395:160493)
```

![image](https://user-images.githubusercontent.com/197004/100286748-9dcaf300-2f73-11eb-8937-75e9721ff551.png)

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):

Note the user I connect with in `DATABASE_URL` has only READ privileges on the tables. Could that be the issue?

**Comment by madebysid** [comment]
Hi @marceloverdijk, thanks for reporting this!
I don't think your readonly access should have anything to do with this. Studio does not attempt to modify your database unless you make changes and press `Save`. I presume you're seeing this as soon as you open Studio?

The (minified) logs also suggest something similar.

1. I think the first thing you could try is hitting that `Discard all unsaved changes` button.
2. If that doesn't do anything, can you try launching Studio on a separate project? Easiest way to do this is to create a new directory somewhere, and write a new `schema.prisma` file in a `prisma` directory with these contents:

```
generator client {
  provider = "prisma-client-js"
}

datasource ds {
  provider = "sqlite"
  url      = "file:dev.db"
}

model Model1 {
  id     Int     @id
  name String
}
```

Then run `npx prisma migrate save --experimental && npx prisma migrate up --experimental` (resolving any prompts that come up), then run `npx prisma studio` and see if Studio launched. If it does, then this might indicate a problem with your current project

Could try these things out and let me know what you find please? I can then perhaps start investigating :)

**Comment by marceloverdijk** [comment]
Hmm, I tried again and now Studio loads without an issue.
Yesterday I also tried 2 times and I got the above error twice.

I will close this issue for now and come back when it happens again.
Thx for your help.

**Comment by madebysid** [comment]
Oh, weird, but I'm glad it was resolved. Please do reopen if you see this again!
