### ISSUE TITLE
Shortcuts to navigate between tabs

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#584]
From Chrome, VS Code and many other apps I'm used to be able to navigate between tabs using keyboard shortcuts.

- <kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>[</kbd> OR  <kbd>CMD</kbd>+<kbd>OPTION</kbd>+<kbd>←</kbd>: Navigate to left tab
- <kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>]</kbd> OR  <kbd>CMD</kbd>+<kbd>OPTION</kbd>+<kbd>→</kbd>: Navigate to right tab

**Comment by madebysid** [comment]
This will be a useful thing to have in the Electron app at the very least!
