### ISSUE TITLE
Prisma studio errors showing in the web-app

### ISSUE THREAD

**Issue by johnslemmer** [prisma/studio#586]
Getting this error about `Unable to init PersistenceStore` when I open up the Prisma studio.

![image](https://user-images.githubusercontent.com/18610918/100527369-beb76200-3186-11eb-9b00-b92f34b80378.png)

This is in a blitzjs project, but I was referred to Prisma to maybe find help with my issue.  Here is my original issue filed over there: https://github.com/blitz-js/blitz/issues/1519

1. Prisma version (`prisma -v` or `npx prisma -v`):
```
@prisma/cli          : 2.12.1
@prisma/client       : 2.12.1
Current platform     : darwin
Query Engine         : query-engine cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.322.0
```

2. Logs from Developer Tools Console or Command line, if any:

There aren't any.

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes

4. Prisma schema (if relevant):
```

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

// --------------------------------------

model User {
  id             Int       @default(autoincrement()) @id
  createdAt      DateTime  @default(now())
  updatedAt      DateTime  @updatedAt
  name           String?
  email          String    @unique
  hashedPassword String?
  role           String    @default("user")
  sessions       Session[]
}

model Session {
  id                 Int       @default(autoincrement()) @id
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  expiresAt          DateTime?
  handle             String    @unique
  user               User?     @relation(fields: [userId], references: [id])
  userId             Int?
  hashedSessionToken String?
  antiCSRFToken      String?
  publicData         String?
  privateData        String?
}
```

**Comment by johnslemmer** [comment]
I also just tried following your [quickstart](https://www.prisma.io/docs/getting-started/quickstart-typescript) and got this error

```
Unable to init PersistenceStore
Error: Unable to init PersistenceStore
    at Bt (http://localhost:5555/mainChunk.js:395:80791)
    at Object.init (http://localhost:5555/mainChunk.js:395:87928)
    at async ir.init (http://localhost:5555/mainChunk.js:395:160461)
```

**Comment by madebysid** [comment]
Hi @johnslemmer, thanks for bringing this up! PersistenceStore here refers to IndexedDB, which is what seems to fail to load. What browser are you using? Do you see any other errors in the DevTools Console about IndexedDB? That may give me a clue about why initialization failed.
If nothing else works, could you see if a `Prisma Studio` database exists in your browser's IndexedDB? If so, what version is it? You can also try manually deleting it and see what happens. Let me know what you find :)

**Comment by johnslemmer** [comment]
Hi @madebysid 

I was able to delete the `Prisma Studio` IndexedDB from my browser.  And seemingly things now work correctly.  Thanks for that tip.  For anyone else finding this issue.  The quick fix is to run: `window.indexedDB.deleteDatabase('Prisma Studio')
` in your browser's console log.



For posterity I have answered all your questions and dropped a bunch a logs about the state of my browser right before I deleted the database.

- I'm using up to date Chrome.
- Here is output around the IndexedDB:

```
const db = window.indexedDB.open('Prisma Studio')
undefined
db
IDBOpenDBRequest {onblocked: null, onupgradeneeded: null, result: IDBDatabase, error: null, source: null, …}error: nullonblocked: nullonerror: nullonsuccess: nullonupgradeneeded: nullreadyState: "done"result: IDBDatabase {name: "Prisma Studio", version: 1, objectStoreNames: DOMStringList, onabort: null, onclose: null, …}source: nulltransaction: null__proto__: IDBOpenDBRequest
```
- Here is a dump of the browser console:
```
Studio version 0.322.0
mainChunk.js:395 Websocket connection established
mainChunk.js:395 Replaying 0 queued requests
(index):1 GET http://localhost:5555/fonts/Inter.ttf net::ERR_ABORTED 404 (Not Found)
mainChunk.js:395 ------Starting IndexedDB migration------
mainChunk.js:395 Uncaught DOMException: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.
    at e.createObjectStore.keyPath (http://localhost:5555/mainChunk.js:395:82774)
    at http://localhost:5555/mainChunk.js:395:86913
    at o (http://localhost:5555/mainChunk.js:395:82333)
    at http://localhost:5555/mainChunk.js:395:82344
    at http://localhost:5555/mainChunk.js:395:82721
    at http://localhost:5555/mainChunk.js:395:86913
    at o (http://localhost:5555/mainChunk.js:395:82333)
    at Ut (http://localhost:5555/mainChunk.js:395:82359)
    at Yt (http://localhost:5555/mainChunk.js:395:86891)
    at IDBOpenDBRequest.<anonymous> (http://localhost:5555/mainChunk.js:395:87363)
    at IDBOpenDBRequest.o (http://localhost:5555/mainChunk.js:395:56312)
o @ mainChunk.js:395
IndexedDB (async)
(anonymous) @ mainChunk.js:395
init @ mainChunk.js:395
init @ mainChunk.js:395
async function (async)
init @ mainChunk.js:395
we @ mainChunk.js:16
o @ mainChunk.js:16
ir @ mainChunk.js:395
(anonymous) @ mainChunk.js:395
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:363
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
mainChunk.js:395 Uncaught (in promise) DOMException: Uncaught exception in event handler.
i @ mainChunk.js:395
o @ mainChunk.js:395
mainChunk.js:395 [PersistenceStore.init] Unable to init PersistenceStore {} {nativeError: {…}}
(anonymous) @ mainChunk.js:395
overrideMethod @ react_devtools_backend.js:2430
Bt @ mainChunk.js:395
init @ mainChunk.js:395
async function (async)
init @ mainChunk.js:395
init @ mainChunk.js:395
async function (async)
init @ mainChunk.js:395
we @ mainChunk.js:16
o @ mainChunk.js:16
ir @ mainChunk.js:395
(anonymous) @ mainChunk.js:395
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:363
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
mainChunk.js:395 [BootstrapStore.init] Studio bootstrap failed {message: "Unable to init PersistenceStore", stack: "Error: Unable to init PersistenceStore↵    at Bt (…t (http://localhost:5555/mainChunk.js:395:160461)"} {nativeError: {…}}
(anonymous) @ mainChunk.js:395
overrideMethod @ react_devtools_backend.js:2430
Bt @ mainChunk.js:395
init @ mainChunk.js:395
async function (async)
init @ mainChunk.js:395
we @ mainChunk.js:16
o @ mainChunk.js:16
ir @ mainChunk.js:395
(anonymous) @ mainChunk.js:395
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:363
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
mainChunk.js:395 Uncaught (in promise) Error: Studio bootstrap failed
    at Bt (mainChunk.js:395)
    at ir.init (mainChunk.js:395)
Ht @ mainChunk.js:395
Bt @ mainChunk.js:395
init @ mainChunk.js:395
async function (async)
init @ mainChunk.js:395
we @ mainChunk.js:16
o @ mainChunk.js:16
ir @ mainChunk.js:395
(anonymous) @ mainChunk.js:395
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:363
n @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
(anonymous) @ mainChunk.js:1
```

**Comment by madebysid** [comment]
Ah, cool that this was resolved. Thanks for those logs, they're helpful!
I guess I'll close this issue for now, but the error is interesting, given that this doesn't seem to be happening to others.

If you do run into this again (or anyone else who happens upon this issue), could you do me a favor and dump the contents of IndexedDB? Here's a script that will do that: https://gist.github.com/madebysid/2f084889730528511d5da12984491678

I'm proper confused, but perhaps IndexedDB contents will help :D

**Comment by mblarsen** [comment]
Ran into this error on 2.12.1

**Comment by madebysid** [comment]
@mblarsen 2.12.1 is pretty old now, could you try updating to 2.15.0 and let me know if you still see this?

**Comment by mblarsen** [comment]
Unfortunately, I'm not in position to update. We have successfully used this version for quite some time, but then the error started to appear. I know you don't have a lot to go on. When we eventually will be able to upgrade I'll try to make a note again here.

**Comment by simoncrypta** [comment]
I have the same issue running on Safari ( 14.0.2 on M1 ) Work fine on Chrome

**Comment by aeharake** [comment]
Works in chrome but not in firefox.

**Comment by cipto-hd** [comment]
Initially have similar error in Chrome, but i  can get to work by click Clear Site Data on "Developer Tools -> Application -> Storage"

**Comment by madebysid** [comment]
I wonder if you're in an Incognito / Private window? I believe some browsers will not let apps write to IndexedDB in thoses cases. I'm not sure why clearing site data (which I presume just empties out IndexedDB) fixes it though.

**Comment by kleydon** [comment]
I'm encountering this in FireFox.
>>could you see if a Prisma Studio database exists in your browser's IndexedDB?
Just checked; no IndexedDB entries.

**Comment by cellulosa** [comment]
> I'm encountering this in FireFox.
> 
> > could you see if a Prisma Studio database exists in your browser's IndexedDB?
> 
> Just checked; no IndexedDB entries.

Same here. Is there anything we can provide to help debug this?
