### ISSUE TITLE
Row expands to screen size when detail view opened

### ISSUE THREAD

**Issue by timsuchanek** [prisma/studio#588]
https://prisma-studio.now.sh/preview?project=chinook

Studio version 0.324.0

![image](https://user-images.githubusercontent.com/1094804/101339792-294f5880-387f-11eb-952e-f25aad6b5a3f.png)

**Comment by madebysid** [comment]
@timsuchanek Just tried it, it seems to be working as expected here, do you see any errors in the Console perhaps?

![Screenshot 2020-12-07 at 11 42 56](https://user-images.githubusercontent.com/7689783/101341436-5f8dd780-3881-11eb-9c1e-ff2d91a526bd.png)

**Comment by madebysid** [comment]
Closing, I suppose something I did broke this, and something else fixed it. Please reopen if you still see this!
