### ISSUE TITLE
Demo link not working - https://prisma.studio

### ISSUE THREAD

**Issue by anishkny** [prisma/studio#589]
Cannot open link: https://prisma.studio

```bash
curl https://prisma.studio
curl: (6) Could not resolve host: prisma.studio
```

**Comment by madebysid** [comment]
Hey @anishkny, I'm investigating, but until then, you can access the demo deployment at https://prisma-studio.now.sh

**Comment by madebysid** [comment]
We've managed to resolve this, and https://prisma.studio should work again. https://prisma-studio.now.sh will also always keep working :)
