### ISSUE TITLE
Better visibility for "Saved Tabs"

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#59]
Currently, I hide the Saved Tabs drawer completely if you have none. This makes it not-so-discoverable.

Maybe we can have an empty state that educates people how to used Saved tabs?

**Comment by kuldar** [comment]
Maybe something like this?
<img width="359" alt="Screenshot 2019-09-09 at 16 27 46" src="https://user-images.githubusercontent.com/1710629/64539444-cb9c2b80-d31e-11e9-88cf-3d0d57e3e57a.png">

**Comment by madebysid** [comment]
Bye bye saved tabs!
