### ISSUE TITLE
Zoom in/out with keyboard shortcuts

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#591]
In the standalone app, it would be awesome to be able to zoom in and out with the "typical" keyboard shortcuts:

- <kbd>CMD</kbd>+<kbd>+</kbd> OR <kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>+</kbd> to zoom in
- <kbd>CMD</kbd>+<kbd>-</kbd> OR <kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>-</kbd> to zoom out

**Comment by madebysid** [comment]
Great news! This is already done and will be available with the next release (2.13.0)
