### ISSUE TITLE
Auto-updating does not re-open the app

### ISSUE THREAD

**Issue by hrescak** [prisma/studio#595]
the update downloads, the app quits but it doesn't re-open on its own.

**Comment by madebysid** [comment]
Do you happen to remember which version you updated from? Does this also happen from 0.329.0 -> 0.330.0?

We did some cert changes and fixed some things that should have fixed this.

**Comment by janpio** [comment]
On Windows 0.330.0 did indeed restart automatically.

**Comment by hrescak** [comment]
it was updating to 0.329.0. Let me update to 0.330.0 now and lets see

**Comment by hrescak** [comment]
It indeed does not reopen either.
More information:
- Big Sur 11.0.1
- No database windows open other than welcome window before updating.

Tiny sidenote but it'd be good to see progress on the download.
