### ISSUE TITLE
prisma studio out of work

### ISSUE THREAD

**Issue by primaryperson** [prisma/studio#598]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```
![image](https://user-images.githubusercontent.com/32566617/103026558-e539a480-455c-11eb-9701-37b18d7cc8a0.png)

**Comment by madebysid** [comment]
Hey @primaryperson, I'm going to need more information to act on this. 
1. What error exactly do you see?
2. What does your schema look like?
3. What version of Prisma (& Studio) are you on?
4. What made this happen? Does Studio crash on start?
5. Can you open you the 'Show details' accordion in the screenshot to show me what the error is?
6. Do you see any errors in your DevTools Console? Any in your terminal you ran 'npx prisma studio' in?

**Comment by madebysid** [comment]
I'm going to close this for now, but if you still see this, please let me know! More details would also be appreciated.
