### ISSUE TITLE
Designs for when you try to close a dirty tab

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#60]
Came up with this hot mess:

<img width="765" alt="Screenshot 2019-08-23 at 20 36 12" src="https://user-images.githubusercontent.com/7689783/63615448-aa7cd080-c5e5-11e9-9d5d-d40870bef200.png">

**Comment by kuldar** [comment]
Few style adjustments to the modal

![dirty-tab-confirmation](https://user-images.githubusercontent.com/1710629/63733239-d7e0ad00-c877-11e9-9243-561f22f0550f.png)

**Comment by madebysid** [comment]
Available in alpha.161
