### ISSUE TITLE
Cannot open intended Model using Prisma Studio's search window with keyboard shortcut

### ISSUE THREAD

**Issue by sthtnr** [prisma/studio#603]
1. Prisma version (`prisma -v` or `npx prisma -v`):
@prisma/cli          : 2.13.1
@prisma/client       : 2.3.0
2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Yes it does.
4. Prisma schema (if relevant):
```

```
# How to reproduce

1. Go to https://prisma.studio/preview?project=capabilities
2. Type `with` in a search box
3. Select any Model with keyboard shortcut (i.e. Use the arrow keys to move the focus, and then press Enter)
4. Model `with_all_field_types` will open regardless of which Model you specify with keyboard shortcut

**Comment by madebysid** [comment]
Whoops, I can reproduce this. I'll fix this ASAP (and add tests for it 😓)

**Comment by madebysid** [comment]
This should be fixed in the latest `@prisma/cli@dev` version soon, but it will also go out with 2.15.0 next week :)
