### ISSUE TITLE
Standalone App download takes forever from Github links

### ISSUE THREAD

**Issue by thellimist** [prisma/studio#605]
When  I try to download any app (Windows, MacOS or Linux), the download stays at 0% on Chrome - forever. 

My internet speed is 50mbs. It's probably related with source of the content.

**Comment by madebysid** [comment]
I doubt it has anythng to do with the content @thellimist, but Github does occasionally do this in my experience. If you cancel and try again in a few seconds, you should be fine. Let me know if you're consistently seeing this though!

**Comment by thellimist** [comment]
I tried around 8 times 2 days ago, it was consistently buggy.

I can confirm that now, I tried again and it works fine.

Thanks!
