### ISSUE TITLE
Add ability to open the same script in multiple tabs

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#61]
Currently, one and only one session holds one script, AND any changes to a script are made on the script itself. This makes it impossible to open the same script in multiple tabs.

To be able to do this, I need to do these things:

1. Save all changes to a script in the session rather than the script, so that you can open a dirty version of the script in one tab, and a clean version in another. Also make sure saving the dirty one makes the clean one dirty and vice versa (Sid knows what this means)
2. Do not bind one session to one script. Clean the API up a little to allow for two sessions to hold the same script. (SessionStore.getByScriptId is the culprit)

**Comment by madebysid** [comment]
@schickling Leaving a comment here to make sure we actually do want to support this. I don't see why not.

**Comment by schickling** [comment]
Yes, we definitely want to remove this limitation.

**Comment by madebysid** [comment]
Internal restructuring done. Will be usable when Preview tabs show up.
