### ISSUE TITLE
hoge

### ISSUE THREAD

**Issue by RyomaDKishimoto** [prisma/studio#610]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Closing this, since this seems to have been created in error.
