### ISSUE TITLE
db error: FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by doronnac** [prisma/studio#616]
1. Prisma version (`prisma -v` or `npx prisma -v`):
@prisma/cli          : 2.15.0
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.340.0

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "stack": "Error: Error querying the database: db error: FATAL: sorry, too many clients already\n    at LineStream.<anonymous> (/Users/admin/.cache/prisma/studio/bf8bfa09/runtime/index.js:27006:31)\n    at LineStream.emit (events.js:315:20)\n    at LineStream.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at LineStream.Readable.push (_stream_readable.js:212:10)\n    at LineStream.Transform.push (_stream_transform.js:152:32)\n    at LineStream._pushBuffer (/Users/admin/.cache/prisma/studio/bf8bfa09/runtime/index.js:24043:19)\n    at LineStream._transform (/Users/admin/.cache/prisma/studio/bf8bfa09/runtime/index.js:24037:10)\n    at LineStream.Transform._read (_stream_transform.js:191:10)",
  "message": "Error querying the database: db error: FATAL: sorry, too many clients already",
  "clientVersion": "2.13.1"
}
Error: Error starting Prisma Client: {
  "stack": "Error: Error querying the database: db error: FATAL: sorry, too many clients already\n    at LineStream.<anonymous> (/Users/admin/.cache/prisma/studio/bf8bfa09/runtime/index.js:27006:31)\n    at LineStream.emit (events.js:315:20)\n    at LineStream.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at LineStream.Readable.push (_stream_readable.js:212:10)\n    at LineStream.Transform.push (_stream_transform.js:152:32)\n    at LineStream._pushBuffer (/Users/admin/.cache/prisma/studio/bf8bfa09/runtime/index.js:24043:19)\n    at LineStream._transform (/Users/admin/.cache/prisma/studio/bf8bfa09/runtime/index.js:24037:10)\n    at LineStream.Transform._read (_stream_transform.js:191:10)",
  "message": "Error querying the database: db error: FATAL: sorry, too many clients already",
  "clientVersion": "2.13.1"
}
    at ir.init (http://localhost:5555/mainChunk.js:395:163053)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Nope, everything seems to be fine when going alpha

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @doronnac, this is interesting, Studio only ever uses one Prisma Client instance. Do you have another script running that is perhaps overflowing the DB? Are you able to consistently reproduce this? As it stands, I'd need a little more info / context to figure out what's happening here.

**Comment by doronnac** [comment]
My guess is prisma-nexus + nextjs quick reload.
The only thing that works for me once this happens is restarting the database.

**Comment by madebysid** [comment]
@doronnac Okay so this has to do with NextJS + Prisma and we have a recommended workaround here: https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices

(You may also need this: https://github.com/prisma/docs/issues/1311)

I'm closing this as this is more of an issue with NextJS + Prisma rather than Studio!
