### ISSUE TITLE
Prisma studio fatal error

### ISSUE THREAD

**Issue by tommyprand** [prisma/studio#618]
1. Prisma version (`prisma -v` or `npx prisma -v`):
@prisma/cli          : 2.15.0
@prisma/client       : 2.15.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.340.0

2. Logs from Developer Tools Console or Command line, if any:
```
Unable to process `count` query
Ht@http://localhost:5555/mainChunk.js:395:80909
Bt@http://localhost:5555/mainChunk.js:395:81055
http://localhost:5555/mainChunk.js:395:162151
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Yes

4. Prisma schema (if relevant):
```
Not really relevant
```

<img width="1244" alt="Schermata 2021-01-25 alle 11 46 05" src="https://user-images.githubusercontent.com/43755903/105695909-eadf2d00-5f02-11eb-922d-0452b8aef6a1.png">

**Comment by madebysid** [comment]
@tommyprand Hmm, if you're consistently seeing this, then a schema would indeed be helpful :D

**Comment by madebysid** [comment]
Hey I'm going to go ahead and close this, but if this is still happening consistently, more information would be helpful!

**Comment by maikesama** [comment]
You need to run first:
npx prisma migrate dev
npx prisma generate
