### ISSUE TITLE
Support connections to databases using just connection strings

### ISSUE THREAD

**Issue by khrj** [prisma/studio#619]
Hey,
I really like Prisma studio but its inconvenient to find / make the schema for a database when I just want to connect to it. It also makes sharing access with someone who has Prisma studio hard, since I have to send over the schema too.
Would it be possible for Prisma studio to connect using just a connection string (possibly using `prisma introspect` behind the scenes)?

**Comment by madebysid** [comment]
Hey @KhushrajRathod, that's a great idea!

We actually used to have this in the Electron app, and we'll likely bring it back. I'll keep you posted!

**Comment by KhushrajRathod** [comment]
Cool!
