### ISSUE TITLE
Cannot view/edit Bytes

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#622]
`Bytes` are basse64 encoded fields. It is currently not possible to view / edit them from Studio

```
datasource db {
  ...
  previewFeatures = ["nativeTypes"]
}

model User {
  id Int @id
  bytes Bytes
}
```

**Comment by madebysid** [comment]
This should now be possible

**Comment by HarmNullix** [comment]
How?

**Comment by def-ilya** [comment]
![image](https://github.com/prisma/studio/assets/99794516/631e53b9-2708-4191-87a7-11fb2fed1659)

Still a very real issue it seems in V5.  Screenshot is example of passing in Hello World from Buffer.from, then base64 encoded.

@sdnts

**Comment by sdnts** [comment]
Hey, I don't work on Studio anymore, but cc @janpio to see if we want to reopen this.
I'd also suggest creating a new issue so the right people can see it.

**Comment by janpio** [comment]
Please open a new issue @def-ilya and provide all the information you can. Thanks.
