### ISSUE TITLE
Can't fill in Decimal type

### ISSUE THREAD

**Issue by yannicksuc** [prisma/studio#629]
1. Prisma version (`prisma -v` or `npx prisma -v`):
Prisma : 2.16.1, Studio : 0.346.0

2. Logs from Developer Tools Console or Command line, if any:
No logs, but here what it's looks like :
![image](https://user-images.githubusercontent.com/25967079/107879929-0c1cb300-6edc-11eb-86d1-79ac28743853.png)
Working One :
![image](https://user-images.githubusercontent.com/25967079/107879945-20f94680-6edc-11eb-9f50-d7cb11988599.png)

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Yes

4. Prisma schema (if relevant):
```
model Product {
  ...
  price         Decimal     @db.Decimal(10,2) @default(0)
  ...
}
```

**Comment by madebysid** [comment]
Hey Yannick, this is known and I've managed to add support for Decimals in Studio. It'll go out with this Tuesday's release. I'll let you know when that happens!

**Comment by madebysid** [comment]
This should be available in tomorrow's release. Please do reopen if you find more issues!

**Comment by yannicksuc** [comment]
Thanks, I will check it out soon !
