### ISSUE TITLE
Improve sidebar hover interaction

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#63]
It is very easy to accidentally close the sidebar when moving your cursor from the sidebar's 50x50px button to an actual model.

Although it will be possible to have the sidebar stick by expanding it, just creating this issue so we can have a discussion.

**Comment by kuldar** [comment]
I think what would help a lot already is to mimick the `padmin-prototype` behaviour, and have the sidebar stay open during the whole sidebar area hovering, not just the 50x50 icon.

https://padmin-prototype.netlify.com

![sidebar](https://user-images.githubusercontent.com/1710629/63732748-f8a80300-c875-11e9-9489-1f0b9c3179c2.gif)

**Comment by madebysid** [comment]
Should be happening now
