### ISSUE TITLE
Demo project fatal error

### ISSUE THREAD

**Issue by sunnysid3up** [prisma/studio#630]
Hello, the demo project from Studio's README gets fatal error when I try to access it:  `https://prisma.studio/demo?project=sportsdb`

<img width="452" alt="image" src="https://user-images.githubusercontent.com/17933228/107969264-e1714e00-6ff2-11eb-87f4-ad4c05f130a5.png">

**Comment by madebysid** [comment]
Hey Sunny, am I correct in assuming that only the SportsDB project is broken?

**Comment by sunnysid3up** [comment]
Hi sid, yes you are correct. Only the SportsDB project is broken.

**Comment by rainy-me** [comment]
Hi, I can't open any demo projects right now.  They all throw `Error in HTTP Request undefined` due to POST `https://prisma.studio/api` returns 404 for all of them.
