### ISSUE TITLE
error

### ISSUE THREAD

**Issue by eduardmarinca** [prisma/studio#633]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
@eduardmarinca This is very inactionable, could you add a few more details about what the error was?
