### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by timscodebase** [prisma/studio#636]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```
Unable to process `count` query
r@http://localhost:5555/main.js:16:52340
http://localhost:5555/main.js:16:52482
http://localhost:5555/main.js:402:147840
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

**Comment by madebysid** [comment]
@timscodebase Are you seeing this consistently? Could you share your schema with me? That could help me start to debug this

**Comment by ksslv** [comment]
Commenting in case someone else stumbles upon this issue -- I got this error and the solution for me was making sure that the database server (in my case - PostgreSQL) was ready and running.

**Comment by madebysid** [comment]
I've recently made some changes to fix https://github.com/prisma/studio/issues/649 that I believe should fix this as well. Please let me know if this is still happening and I'll reopen!
