### ISSUE TITLE
Prisma Studio prevents saving changes when nullable values

### ISSUE THREAD

**Issue by kevinmarrec** [prisma/studio#639]
Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.353.0
```

Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
```
Yes
```
Prisma schema (if relevant):
```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       Int     @id @default(autoincrement())
  required String  @unique
  optional String?
}

```

## Issue

Prisma Studio doesn't save changes until I add values in **nullable values** :

![image](https://user-images.githubusercontent.com/25272043/109015924-ea7ab300-76b5-11eb-9844-a09a4d8540a7.png)

Clicking on "Save 1 change" does nothing.

Adding a value in `optional` column works :

![image](https://user-images.githubusercontent.com/25272043/109016260-46ddd280-76b6-11eb-87ab-7e636ad8256e.png)

I also tried to remove value afterwards, it still block from saving :

![image](https://user-images.githubusercontent.com/25272043/109016350-6412a100-76b6-11eb-8f06-733967e06f55.png)

It seems then there's an issue with nullable `?` fields in model.

**Comment by madebysid** [comment]
@kevinmarrec Do you see an error when you press `Save changes`?

I wonder if this is the same thing as https://github.com/prisma/studio/issues/638

**Comment by kevinmarrec** [comment]
@madebysid No error so far
- No error on UI
- No error in browser console
- No error in terminal console

**Comment by madebysid** [comment]
Oh oh I see, this is then the same issue as https://github.com/prisma/studio/issues/632. #632 was not limited to `DateTimes`. I've fixed that in a`dev` version (there's a comment on that issue).
If you can try out the `dev` version (or the Electron app), and let me know if this is fixed for you too, I can go ahead and close this! You can also wait till next Tuesday, when a Prisma CLI release is supposed to go out and check then.

Let me know!

**Comment by kevinmarrec** [comment]
@madebysid 

Indeed, everything works smoothly on 
```
Studio               : 0.345.0
```

I had to remove `prisma` dependency after installing `@prisma/cli@dev` to have the new version :)

Thanks for your help

**Comment by madebysid** [comment]
Nice! To reiterate though, I don't recommend using a `dev` CLI version in the long run! You should be able to use the stable CLI version starting next Tuesday.
Closing!

**Comment by kevinmarrec** [comment]
@madebysid Yes sure, but why is the dev version (whick works) is **2.16.0-dev** and not **2.17.0-dev** ? Also it's using **Studio 0.345** which works but it's older version than the one shipped with sable version **0.353.0**

**Comment by kevinmarrec** [comment]
I guess the last public `-dev` version available is `2.16.0-dev.68`

![image](https://user-images.githubusercontent.com/25272043/109022966-a5a64a80-76bc-11eb-8571-b4aeedf9615f.png)

And that on this version the issue was not happening, that's why I thought this as "fixed" but's it's older and not newer version.

So I can't confirm yet it works on the new one.

I'm gonna try desktop version.

**Comment by madebysid** [comment]
Oh so you've stumbled across a little bit of a mess haha.

We deprecated `@prisma/cli` in favour of `prisma`.
As a result, we stopped publishing `dev` versions to `@prisma/cli`. Instead, they are now published to `prisma`. Stable versions are still going to be pushed to `@prisma/cli` for a month or so allow for easy transitions for users.
No one usually notices this since no one uses these `dev` versions :D 

So what you want to do is install `prisma@2.18.0-dev.6` (or later), and you'll find Studio version 0.355.0 in there that should have this fix. Does this make sense? Can you try this out?

**Comment by kevinmarrec** [comment]
@madebysid Totally makes sense, and yes it works (on `2.18.0-dev.27`) :)
