### ISSUE TITLE
Prisma Studio

### ISSUE THREAD

**Issue by Manubi** [prisma/studio#641]
1. Prisma version:
prisma 2.17.0

2. Prisma schema:
<img width="734" alt="CleanShot 2021-02-28 at 16 22 14@2x" src="https://user-images.githubusercontent.com/20935138/109423797-23ca6000-79e1-11eb-9fe0-47aeceaad071.png">

3. Studio
![CleanShot 2021-02-28 at 16 26 53](https://user-images.githubusercontent.com/20935138/109423944-d8648180-79e1-11eb-909f-aa2fcbbf982b.png)

Problem:
Studio wont let me add a row unless I add every single field in the row. Adding single fields with postico works fine. Imho there should be better user feedback why I can't add the row.

**Comment by madebysid** [comment]
Hey @Manubi, do you see an error when that happens? Or does the 'Save Changes' button not do anything when you press it?

Does https://github.com/prisma/studio/issues/639 sound like what you're seeing as well? If so, this is fixed and will be out with 2.18.0 (or you can look at the dev version, details in that issue's comment).

**Comment by Manubi** [comment]
Sounds the same as #639
