### ISSUE TITLE
Link to error documentation is not clickable

### ISSUE THREAD

**Issue by arthurdenner** [prisma/studio#646]
Hi! 👋🏽 

When an error happens inside Studio, a link to its docs is shown but currently the link it's not clickable due to the `button` + `a` tags.

![image](https://user-images.githubusercontent.com/13774309/111894619-92ad3e80-8a0c-11eb-9f4c-efec5aa7cb1c.png)
---
1. Prisma version (`prisma -v` or `npx prisma -v`):
@prisma/cli: 2.16.0-dev.68
@prisma/client: 2.19.0

2. Logs from Developer Tools Console or Command line, if any:
N/A

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Yes.

4. Prisma schema (if relevant):
N/A

**Comment by madebysid** [comment]
Haha, thanks for letting me know @arthurdenner, I'll fix this with the next version!

**Comment by madebysid** [comment]
This is fixed in 0.370.0, and will be out with tomorrow's release!
