### ISSUE TITLE
Error when changing the number of related records

### ISSUE THREAD

**Issue by DennieMello** [prisma/studio#651]
When trying to add several new records, the error "The records for relation` CategoryParentChildren` between the `Category` and` Category` models are not connected. "Occurs because an empty field" disconnect: [] "is created.

![Снимок экрана 2021-04-08 в 01 45 11](https://user-images.githubusercontent.com/39631512/113944230-e2617780-980c-11eb-8fd2-ec66fc0a89fe.jpg)

![Снимок экрана 2021-04-08 в 01 52 39](https://user-images.githubusercontent.com/39631512/113944407-20f73200-980d-11eb-8553-d13776c2eb1d.jpg)

1. Prisma version 2.20.1, Electron 0.359.0 (0.359.0.8155):

2. Logs from Developer Tools Console or Command line, if any:
```
Type: undefined
Message: The records for relation `CategoryParentChildren` between the `Category` and `Category` models are not connected.

Code: undefined

Query:
prisma.category.update(
{
  where: {
    id: 30,
  },
  data: {
    children: {
      connect: [
        {
          id: 2,
        },
        {
          id: 3,
        },
        {
          id: 1,
        },
      ],
      disconnect: [

      ],
    },
  },
  select: {
    id: true,
    children: true,
  },
}
)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

unknown

**Comment by madebysid** [comment]
Hey @DennieMello, thanks for reporting this! I was able to see this happen, but only for models with self relations, do you see the same? Either way, this is a bug, and I will look into this!

**Comment by DennieMello** [comment]
> Hey @DennieMello, thanks for reporting this! I was able to see this happen, but only for models with self relations, do you see the same? Either way, this is a bug, and I will look into this!

Yes, the error occurs in the case of self-relational models.

**Comment by madebysid** [comment]
This should be fixed now. It will be available in tomorrow's release!
