### ISSUE TITLE
Studio unexpectedly creates empty SQLite database file

### ISSUE THREAD

**Issue by janpio** [prisma/studio#652]
I have created a new project with `npx prisma init`, changed the datasource provider to `sqlite` and added a minimal model:

```
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

When I set the `DATABASE_URL` env var to `file:foo` is creates an empty `foo.bar` file when running `npx prisma studio`. Studio shows the `User` model, but clicking it of course fails as it does not really exist in the database.

**Comment by madebysid** [comment]
@janpio That's probably Client. Studio doesn't have logic to handle things like this. On a fresh project, I did what you said and ran a `findMany` query using a script and saw the same. Isn't that expected hough? If not, I'll transfer this to `prisma/prisma`

**Comment by janpio** [comment]
I think I had the same realization back then already:
https://github.com/prisma/prisma/issues/6495
