### ISSUE TITLE
Unable to find query engine

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#659]
## Prisma version

`2.20.1`. The issue persists even after updating to the latest alpha: `2.22.0-dev.3`. Prisma Studio itself loads, but queries cannot be performed.

**I’m able to run Prisma Client in the app without a hitch; just not Prisma Studio.**

## Error logs

```
Message: Error in Prisma Client request: 

Query engine binary for current platform "darwin" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/Users/.../node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin")

Searched Locations:

**NOTHING HERE**


To solve this problem, add the platform "undefined" to the "generator" block in the "schema.prisma" file:
generator studio-client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
```

## Debugging attempts

Also, please note the following:

1. Located the query engine no problem in `node_modules/@prisma/engines/query-engine-darwin`; it appears Prisma Client is not looking anywhere (see my comment above: **NOTHING HERE**) — or at least not in the correct place.
2. I recently did `npx yarn-deduplicate && yarn` — wondering if that might have messed things up; deleted `node_modules` and `yarn.lock` and reinstalled, but error persists.
3. Regenerated Prisma Client several times, but error persists.
4. Ran Prisma Studio in incognito mode in Chrome, and also in standard mode in Safari, to no effect.
5. Deleted the `.prisma` cache folder in the root of my username folder on my computer `/Users/.../.prisma`, also to no effect.
6. Deleted the **IndexedDB** in the browser, also to no effect.
![image](https://user-images.githubusercontent.com/11673745/114617889-8ad46900-9c5d-11eb-9562-acd1ded3fa92.png)

## Schema

```prisma
datasource db {
  provider = "postgresql"
  url      = env("APP_DATABASE_DEV")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

**Comment by janpio** [comment]
Does it work if you remove the `binaryTargets` temporarily from your schema?

**Comment by heymartinadams** [comment]
Still won’t, @janpio. 😕

**Comment by bmcilw1** [comment]
@janpio mine also does not work if I remove the binaryTargets. I started without them and added them because it wasn't working.

**Comment by janpio** [comment]
To confirm the paths:
- `/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin` does not exist
- `/node_modules/@prisma/engines/query-engine-darwin` does exist
Correct?

**Comment by janpio** [comment]
I can confirm the problem on Windows as well:

```
Message: Error in Prisma Client request: 

Query engine binary for current platform "[1mwindows[22m" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "[4mC:\Users\Jan\Documents\throwaway\studioBinaryRepro\node_modules\prisma\node_modules\@prisma\engines\query-engine-windows.exe[24m")

Searched Locations:




To solve this problem, add the platform "undefined" to the "[4mgenerator[24m" block in the "schema.prisma" file:
[92mgenerator studio-client {[39m
[92m  provider      = "prisma-client-js"[39m
[92m  binaryTargets = ["native"][39m
[92m}[39m

Then run "[92mprisma generate[39m" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
  
  Query:
  prisma.user.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    email: true,
    name: true,
  }
})
```

There is no `node_modules` under `C:\Users\Jan\Documents\throwaway\studioBinaryRepro\node_modules\prisma`.

**Comment by heymartinadams** [comment]
> To confirm the paths:
> 
> * `/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin` does not exist
> * `/node_modules/@prisma/engines/query-engine-darwin` does exist
>   Correct?

Correct. Gosh, hadn’t noticed until now that it was looking in `/node_modules/prisma/node_modules/...`

For what it’s worth, our schema files are located in a `prisma` folder in the app’s root: `/prisma/dev/schema.prisma` and `/prisma/prd/schema.prisma`.

**Comment by madebysid** [comment]
Hey everyone, I've found the issue, and we'll get on this ASAP. In the mean time, you should be able to work by running `NODE_ENV=production npx prisma studio` (AKA manually setting the `NODE_ENV` environment variable).

**Comment by heymartinadams** [comment]
Downgrading to `2.19.0` makes it work again, FYI.

**Comment by BenjaminGuzman** [comment]
I have the same problem on Fedora 33.

```
Message: Error in Prisma Client request: 

Query engine binary for current platform "[1mrhel-openssl-1.1.x[22m" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "[4m<hidden route on purpose>/admin/node_modules/prisma/node_modules/@prisma/engines/query-engine-rhel-openssl-1.1.x[24m")

Searched Locations:




To solve this problem, add the platform "undefined" to the "[4mgenerator[24m" block in the "schema.prisma" file:
[92mgenerator studio-client {[39m
[92m  provider      = "prisma-client-js"[39m
[92m  binaryTargets = ["native"][39m
[92m}[39m

Then run "[92mprisma generate[39m" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
```
And the route `admin/node_modules/prisma/node_modules/` does not exists.

However the executable `/admin/node_modules/prisma/query-engine-rhel-openssl-1.1.x` does exist.
And the same binary exists in `admin/node_modules/@prisma/engines/query-engine-rhel-openssl-1.1.x`.

I ran `sha256sum` on both files and their sums are the same.

The solution is probably just changing the path to look for the engine binary in different directory, but I'm not sure, this is my first day using prisma.

**Note**: Running the studio in production mode as suggested by @madebysid solved the problem in my case.

**Comment by Jolg42** [comment]
Happy to say the fix was shipped in the `2.21.1` patch release 🎊

**Comment by DavidTParks** [comment]
I am still getting this issue even with the new 2.21.1 patch FYI

**Comment by madebysid** [comment]
@DavidTParks hmm interesting, can you post your error stacktrace? Is it the same as the one that was posted earlier? Also probably worth it to run `prisma -v` to confirm you're on the latest version.

**Comment by DavidTParks** [comment]
Ran prisma-v here are my versions:
```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
Preview Features     : napi
```

I am enabling the napi preview feature in my schema.prisma file

Then, when trying to run npx prisma studio or use the desktop application I am getting the following error

Message: Error in Prisma Client request: 

```
Unable to load NAPI Library from /Users/davidparks/Projects/clipbindr/node_modules/@prisma/engines/query-engine-darwin, Library may be corrupt
  
  Query:
  prisma.video.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    title: true,
    assetId: true,
    playbackId: true,
    thumbnail: true,
    url: true,
    views: true,
    comments: true,
    createdAt: true,
    updatedAt: true,
    published: true,
    commentsEnabled: true,
    authorId: true,
    author: true,
    videoLikes: true,
    videoDislikes: true,
  }
})
```

**Comment by madebysid** [comment]
Ah, yeah let's create a different issue for this. Studio not working with NAPI is expected curently.
