### ISSUE TITLE
Add "Reload" button + report issue flow

### ISSUE THREAD

**Issue by schickling** [prisma/studio#66]
![image](https://user-images.githubusercontent.com/1567498/63651485-f7f25e00-c709-11e9-8ef6-bdb424a13e84.png)

**Comment by kuldar** [comment]
Here is an updated design for the errors. It might look less jarring if the error modal doesn't take up the whole screen, but shows the disabled UI in the background (maybe even grayscaled). Optionally a suitable place for mild panic icon.

I'm guessing the "Report an issue" button would link to a new Github issue form.

![error](https://user-images.githubusercontent.com/1710629/63732609-4b34ef80-c875-11e9-9acf-e6f29c32b57f.png)
![error-smiley](https://user-images.githubusercontent.com/1710629/63732608-4a9c5900-c875-11e9-83bd-64882bc287de.png)
![error-big](https://user-images.githubusercontent.com/1710629/63732606-4a9c5900-c875-11e9-963c-c3eb87de16b3.png)

**Comment by madebysid** [comment]
Out with alpha.169

Unfortunately, the mild panic emoji is not in the standard emoji set, so we can't use that. A regular PNG image is nowhere near as crisp, especially right next to the text.
