### ISSUE TITLE
Prisma Studio cannot find query engine binary on latest Mac OS X, but `@prisma/client` can

### ISSUE THREAD

**Issue by bmcilw1** [prisma/studio#660]
## Bug description

Prisma Studio cannot find the query engine binary for the latest update for MacOS

## How to reproduce

1. Install latest MacOS X updates to system
2. Install `prisma` and `@prisma/client` to repo via `npm install`
3. Run `npx prisma init`
4. Connect to a MySQL db and run `npx prisma db pull` to get a schema, or skip and use the schema provided below
5. Run `npx prisma generate`. See that no errors are thrown.
6. In code, you can now use the prisma client to successfully get data. View no errors are given and data is retrieved
   ```ts
   import { PrismaClient } from '@prisma/client'
   const prisma = new PrismaClient()

   ...
   ````
7. Run `npx prisma studio`. See that it launches successfully and loads lists of models
8. Click on a model to open model view. See that no results are displayed and an error dialog is shown to the user.

Error Pic: 
![image](https://user-images.githubusercontent.com/1582095/114616992-2b7e5500-9c6d-11eb-9a3e-d50e96ef3b06.png)

```text
Message: Error in Prisma Client request: 

Query engine binary for current platform "[1mdarwin[22m" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "[4m/Users/brianmcilwain/source/ah-applications-nx/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin[24m")

Searched Locations:




To solve this problem, add the platform "undefined" to the "[4mgenerator[24m" block in the "schema.prisma" file:
[92mgenerator studio-client {[39m
[92m  provider      = "prisma-client-js"[39m
[92m  binaryTargets = ["native"][39m
[92m}[39m

Then run "[92mprisma generate[39m" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
  
  Query:
  prisma.account.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    creationDate: true,
    firstName: true,
    lastName: true,
    gender: true,
    dateOfBirth: true,
    updateDate: true,
    updatedBy: true,
    email: true,
    phone: true,
    locale: true,
    locked: true,
    organizationId: true,
    accountState: true,
    bookSimpleUrl: true,
    priorityLevel: true,
    testAccount: true,
    personId: true,
    deactivatedDate: true,
    dataInvalidatedDate: true,
    programTierOid: true,
    OptionListItem: true,
    AdvisorSession: true,
    Biometric: true,
    Connection_AccountToConnection_childAccountId: true,
    Connection_AccountToConnection_parentAccountId: true,
    ReportConnection: true,
    Role: true,
    UserBehavior: true,
    UserCondition: true,
    UserProgram: true,
    XChatAccount: true,
  }
})
  
```
9. Open JavaScript Console. See that an additional error has been thrown in the console
```text
vendor.c4d0f081.js:31 [runQuery] Error in Prisma Client request: 

Query engine binary for current platform "darwin" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/Users/brianmcilwain/source/ah-applications-nx/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin")

Searched Locations:




To solve this problem, add the platform "undefined" to the "generator" block in the "schema.prisma" file:
generator studio-client {  provider      = "prisma-client-js"  binaryTargets = ["native"]}Then run "prisma generate" for your changes to take effect.Read more about deploying Prisma Client: https://pris.ly/d/client-generator Object undefined
(anonymous) @ vendor.c4d0f081.js:31
```

## Expected behavior

Prisma studio as ran via `npx prisma studio` should be able to open a model without showing an error. This is particularly expected to be the case as the prisma client seems to be able to access the binary without an issue.

It is also possible that my super crazy imported schema below is messing something up with prisma studio. But, I think that less likely as the prisma client has no issues accessing data and therefore the correct query engine binary.

It is also strange that weird unicode characters are displayed in the error message and are not pretty printed.

## Prisma information

*Removed for simplicity as the bug has been reproduced without it on multiple platforms*

## Environment & setup

- OS: macOS 11.2.3 (20D91)
- Database: MySQL
- Node.js version: v14.16.1
- Prisma version: 

```
prisma               : 2.21.0
@prisma/client       : 2.21.0
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by bmcilw1** [comment]
Seems like a duplicate of https://github.com/prisma/studio/issues/659

**Comment by madebysid** [comment]
@bmcilw1 I'll close this in favor of #659 then. I also posted a workaround on that thread till we fix this on stable (which should be soon)
