### ISSUE TITLE
Prisma Studio not working with napi preview feature

### ISSUE THREAD

**Issue by DavidTParks** [prisma/studio#662]
Enabling the new napi preview feature does not let you use Prisma Studio desktop or web version. 

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["napi"]
}
```

Ran prisma-v here are my versions:
```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
Preview Features     : napi
```

I am enabling the napi preview feature in my schema.prisma file. This error does not occur if i remove the napi preview feature.

Then, when trying to run npx prisma studio or use the desktop application I am getting the following error on first load @madebysid 

```
Message: Error in Prisma Client request: Unable to load NAPI Library from .../node_modules/@prisma/engines/query-engine-darwin, Library may be corrupt
```

_Originally posted by @DavidTParks in https://github.com/prisma/studio/issues/659#issuecomment-820538714_

**Comment by Jolg42** [comment]
Prisma Studio not working with NAPI is expected currently.

_Originally posted by @madebysid in https://github.com/prisma/studio/issues/659#issuecomment-820605767_

Note: NAPI is a Preview feature that only works with Prisma Client right now.

**Comment by madebysid** [comment]
Hey @DavidTParks, sorry it's been a while, but the latest version of Studio now ignores the 'nApi` feature flag if it is set. This allows it to at least launch correctly regardless of whether or not you have the feature flag set.

In the future, Studio will respect the `nApi` flag and use the Node-API to work internally as well.

Closing since the original issue shoudl be resolved now. Let me know if not, and I'll reopen!

**Comment by madebysid** [comment]
Today's relase of Studio makes it so Studio itself also uses the Node-API library if the preview feature is toggled on
