### ISSUE TITLE
[Prisma Cloud] Project URL for orgs

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#665]
**Describe the bug**
Reticent to create a new project using Prisma Cloud since it uses my personal GitHub handle: `https://cloud.prisma.io/heymartinadams` instead of the name of the app in the handle that I know we’ll need to use. *Note* This also should not be the GitHub org name, since the GitHub org name is not quite the same as the name of the app.

**Additional context**
Would love it if we can choose our own custom handle.

**Comment by madebysid** [comment]
👋  Thanks for trying out the platform! This is on our radar and should be fixed very soon. I'll let you know here when that happens!

**Comment by madebysid** [comment]
I seem to have misread/misunderstood this issue, are you suggesting project URLs should not be tied to any user/org’s handle?

If not, can you elaborate a little? Thank you!

**Comment by heymartinadams** [comment]
Here’s what I’d like to see. Currently, when I go to Prisma Cloud, I head on over to https://cloud.prisma.io/**heymartinadams**/ecstatic/databrowser

Instead, since this is a company, I’d like to be able to head on over to https://cloud.prisma.io/**ecstatic**/databrowser

Our company’s GitHub org handle is @ecstaticapps, so I don’t want to be able to use that one either. Instead, my request is to let us enter a custom handle, like **ecstatic**. 🙂
