### ISSUE TITLE
npx prisma studio fails to start up on the browser 

### ISSUE THREAD

**Issue by Toyz** [prisma/studio#666]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
{
  "prisma": "2.21.2",
  "@prisma/client": "2.21.2",
  "current-platform": "darwin",
  "query-engine": "query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)",
  "migration-engine": "migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)",
  "introspection-engine": "introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)",
  "format-binary": "prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)",
  "default-engines-hash": "e421996c87d5f3c8f7eeadd502d4ad402c89464d",
  "studio": "0.371.0"
}
```

2. Logs from Developer Tools Console or Command line, if any:
```
GET http://localhost:3000/@vite/client net::ERR_ABORTED 404 (Not Found)
(index):29 GET http://localhost:3000/src/index.tsx net::ERR_ABORTED 404 (Not Found)
(index):25 GET http://localhost:3000/@react-refresh net::ERR_ABORTED 404 (Not Found)
(index):30 Uncaught ReferenceError: PrismaStudio is not defined
    at (index):30
```

**Comment by Toyz** [comment]
It feels like there is a missing dep when using `npx prisma studio`

**Comment by madebysid** [comment]
@Toyz Thanks for reporting this! This is super weird, it looks like somehow Studio is trying to load its "development" server (aka the server I use while building Studio; hence the Vite stuff)

I'm unfortunately not able to see this on 2.21.2. Do you by any chance have `NODE_ENV` set to `development` on your shell? Maybe an `export NODE_ENV=development` you forgot about? `echo $NODE_ENV` should let you know if that's the case. Let me know if that isn't set and you're still seeing this!

**Comment by Toyz** [comment]
I just did `NODE_ENV=production yarn prisma studio` and it fixed it so it seems it was just he `NODE_ENV` i should of checked that before reporting this bug!

**Comment by huangyanxiong01** [comment]
@Toyz thinks your anwser

**Comment by madebysid** [comment]
Hey everyone, I've made changes on the latest `dev` version of `prisma` so that Studio doesn't go into "development mode" when NODE_ENV is set incorrectly. `NODE_ENV` is such a common env var that I think it would have been really annoying is Studio depended on it too.

@Toyz if you could try this `dev` version out with your setup and let me know if all's good, that'd be great!

I'd also recommend upgrading to the latest stable version of `prisma` when it comes out rather than sticking to the `dev` version, since it occasionally contains unannonuced breaking changes.

**Comment by Toyz** [comment]
I try out the changes later today for sure!
