### ISSUE TITLE
No way to delete a hosted studio project or edit the project url

### ISSUE THREAD

**Issue by kitze** [prisma/studio#668]
I wanted to try the hosted studio and I messed up the URL. I cannot change my URL in setting so I want to delete the project. Seems there's no delete button yet.

**Comment by madebysid** [comment]
👋 Thanks for trying out the platform! This one's on our radar and is one of the first things we're working on now. I'll let you know when this is out!

**Comment by kitze** [comment]
Thanks @madebysid!

**Comment by jasonkuhrt** [comment]
Hey @kitze we just deployed the ability to delete projects.

Project URLs still cannot be changed, so keeping this issue open until then.

**Comment by kitze** [comment]
@jasonkuhrt awesome!

**Comment by madebysid** [comment]
You should now also be able to change project  URLs. Please keep the feedback coming!
