### ISSUE TITLE
Inviting members to project not working.

### ISSUE THREAD

**Issue by BJDubb** [prisma/studio#669]
**Describe the bug**
When attempting to invite members to your project, the modal shows a "Could not find the requested user." message

**To Reproduce**
1. Go to 'https://cloud.prisma.io/YourUsername/YourProjectName/settings'
2. Click on 'Invite User'
3. Enter the user's Github name
4. Click on 'Add to project'
5. See error

**Expected behavior**
Adds the specified user to the project as a member

**Screenshots**
https://cdn.discordapp.com/attachments/605627952708976641/837238408572567552/unknown.png

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [90.0.4430.85]

**Additional Info**
May require the user to link their Github with Prisma beforehand. If that is the case, a more descriptive error message such as "The specified user has not yet  linked their Github with Prisma" could be used.

**Comment by martzoukos** [comment]
Hey BGDubb. 

Thank you for trying out the product and submitting your issue. 

> May require the user to link their Github with Prisma beforehand. If that is the case, a more descriptive error message such as "The specified user has not yet linked their Github with Prisma" could be used.

This is indeed the case and updating the error is a good first step. We have an email invitation flow in our mid-term plans, so we'll let you know here how that goes.

**Comment by kkarimi** [comment]
The UX for this feature is not super clear - i.e. there is a set error that says "User could not be found", it's not clear if its because that user does not have access to the private repo, or why they can't be found.

**Comment by madebysid** [comment]
Hey everyone! IIUC the issue here was only that the error message wasn’t clear, correct? We’ve improved it now, and it explicitly says: `Cannot find user ${username}. Users must sign up to the Prisma Data Platform before they can be added to a project`. Does that make it better?

Closing this, but if there are more issues / suggestions for improvements, I’m more than happy to reopen!

**Comment by kkarimi** [comment]
Cheers 🙌
