### ISSUE TITLE
Tree view: Error when expanding an empty list

### ISSUE THREAD

**Issue by schickling** [prisma/studio#67]
![image](https://user-images.githubusercontent.com/1567498/63651506-338d2800-c70a-11e9-8cb8-bcd98f5aeb24.png)

![image](https://user-images.githubusercontent.com/1567498/63651480-ee68f600-c709-11e9-8f30-a2e7f72e12d4.png)

**Comment by madebysid** [comment]
Possibly related to https://github.com/prisma/studio/issues/68

**Comment by madebysid** [comment]
Added a loading state for records, and a fallback for when you open a record before it is fetched. I'm pretty sure these two were related, because I was able to see this error as well. Fix is out with alpha.175
