### ISSUE TITLE
unable to open prismA studio

### ISSUE THREAD

**Issue by nasneem** [prisma/studio#673]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @nasneem I'll need a bit more information about what it is that's failing so I can start investigating. I'll reopen this when you add some more context!
