### ISSUE TITLE
Tree view: Add loading indicator (and other improvements)

### ISSUE THREAD

**Issue by schickling** [prisma/studio#68]
https://www.loom.com/share/5dc4914512f64d27b3a31f9f2468479e

**Comment by kuldar** [comment]
For the gray preview info loading, we probably don't want the state to be too distracting. Maybe a variation of pulsating three dots is subtle enough for a loading state?

https://codepen.io/cely717/pen/yYZOZR

**Comment by madebysid** [comment]
Out with alpha.175
