### ISSUE TITLE
Project selection in desktop app: Previously connected projects are not remembered

### ISSUE THREAD

**Issue by schickling** [prisma/studio#69]
![image](https://user-images.githubusercontent.com/1567498/63653793-4f9ec280-c726-11e9-9f81-2613c3fe8625.png)

**Comment by madebysid** [comment]
Does this also happen when you've selected `Save as project`?

If you don't, connections won't be remembered since we do not want to save credentials for "connect-only" projects.
Maybe we can save the connection, but prompt them to enter credentials when they try to open a recent project?

**Comment by idan** [comment]
Marked candidate for discussion during upcoming sync, specifically in context of shift towards init/dashboard experience.

**Comment by idan** [comment]
Deprioritized because electron

**Comment by madebysid** [comment]
Closing, since this should work as expected now!
