### ISSUE TITLE
Refreshing on local prisma studio causes an error to be thrown

### ISSUE THREAD

**Issue by meeoh** [prisma/studio#693]
**Describe the bug**
When running prisma studio, if I ever refresh this error gets thrown:

```
Prisma Studio is up on http://localhost:5555
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'fields' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    |     ...
    |     index 0 -> object with constructor 'Object'
    --- property 'type' closes the circle
    at JSON.stringify (<anonymous>)
    at serialize (/Users/shameel/Projects/Bedtime-Stories-App/Bedtime-Stories-Backend/node_modules/prisma/build/index.js:131814:17)
    at HTTPNodeTransport.respond (/Users/shameel/Projects/Bedtime-Stories-App/Bedtime-Stories-Backend/node_modules/prisma/build/index.js:131829:34)
    at /Users/shameel/Projects/Bedtime-Stories-App/Bedtime-Stories-Backend/node_modules/prisma/build/index.js:140730:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

When I open prisma studio for the first time it works completely fine, and theres no issues. I'm not sure if this is something to do with my schema (because it works on first load always, so I wouldnt think so).

**To Reproduce**
1. Run `prisma studio`
2. Once the page opens, refresh it
3. View the logs in the terminal

**Expected behavior**
Expected refreshing to simply refresh the page

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Big Sur 11.3.1
 - Chrome

**Comment by madebysid** [comment]
Hey @meeo, this sounds like the same issue as https://github.com/prisma/studio/issues/675, can you trying updating Prisma CLI to the latest version?

Let me know if you still see this, and I'll reopen!
