### ISSUE TITLE
Getting Fatal error

### ISSUE THREAD

**Issue by asharabu** [prisma/studio#694]
1. Prisma version (`prisma -v` or `npx prisma -v`):

/opt/app $ npx prisma -v
warn @prisma/cli has been renamed to prisma.
Please uninstall @prisma/cli: npm remove @prisma/cli
And install prisma: npm i prisma
@prisma/cli          : 2.16.0-dev.68
@prisma/client       : 2.23.0
Current platform     : linux-musl
Query Engine         : query-engine abf73b00c32ac832220839da2b8ec439b02e2519 (at node_modules/@prisma/cli/node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli abf73b00c32ac832220839da2b8ec439b02e2519 (at node_modules/@prisma/cli/node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core abf73b00c32ac832220839da2b8ec439b02e2519 (at node_modules/@prisma/cli/node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt abf73b00c32ac832220839da2b8ec439b02e2519 (at node_modules/@prisma/cli/node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.345.0

2. Logs from Developer Tools Console or Command line, if any:

![image](https://user-images.githubusercontent.com/42669995/119822012-d3e03400-bf10-11eb-8e03-88a099f0d4d7.png)

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes, still error
4. Prisma schema (if relevant):
```
https://github.com/calendso/calendso/blob/main/prisma/schema.prisma
```

**Comment by madebysid** [comment]
Hey @asharabu, that looks like a really old version of Prisma CLI (and Studio). Can you try upgrading to the latest version (2.23.0) and check if you're still seeing this?

**Comment by asharabu** [comment]
@madebysid  Prisma studio worked when upgraded version to the latest Prisma version 2.24.0.
