### ISSUE TITLE
Failed to load resource (404) when running npx prisma studio

### ISSUE THREAD

**Issue by thecodelearner** [prisma/studio#697]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma               : 2.24.0
@prisma/client       : 2.24.0
Current platform     : darwin
Query Engine         : query-engine f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : f3e341280d96d0abc068f97e959ddf01f321a858
Studio               : 0.397.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Chrome Console:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:5555/assets/index.js (index.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:5555/assets/vendor.js (vendor.js, line 0)
```

Loading the schema up in the Prisma Studio App works perfectly fine, but `npx prisms studio` throws this error.

**Comment by thecodelearner** [comment]
sorry if this is a duplicate but the only issues with a similar error I could find were back from 2020 on prisma/cli@2.0.0+ and not on the current @prisma package.

**Comment by madebysid** [comment]
Hey @thecodelearner, I'm not able to see this with prisma@2.24.0 unfortunately.

Do you have anything else running on port 5555 by any chance? Might be a longshot, but I think the Android Emulator runs on that port by default (https://github.com/prisma/studio/issues/567). If you do have it running, running Studio on a different port might help.

If not, running `lsof -i:5555` will tell you if anything else is listening on `:5555`. Let me know!

**Comment by thecodelearner** [comment]
nope, nothing running on port 5555, I get no errors in the terminal, the 404 errors come up on the console when localhost:5555 opens up with a blank page.

**Comment by thecodelearner** [comment]
upgraded to 2.24.1

```
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0
```

------
https://user-images.githubusercontent.com/22259087/120822689-4f2a9100-c574-11eb-961c-d33f5a0fc52c.mov


---------


<img width="731" alt="image" src="https://user-images.githubusercontent.com/22259087/120822518-1c809880-c574-11eb-811a-af7881203cc6.png">

**Comment by madebysid** [comment]
This is super weird, because I still cannot see this, and I haven't seen anyone else face this either.
Can you go into your `node_modules/prisma/build/public` folder and see if you can actually see Studio's assets in there?
Do you have the Prisma CLI installed globally? If so, can you try making it a `devDependency` of your project?

If all else fails, maybe create a brand new Prisma project and see what happens? You'll need to create a folder, install `prisma` and `@prisma/client`, create a simple dummy schema and run `npx prisma studio` (you don't even need a real database, if Studio's front end loads correctly then it'll show an error in a dialog, but at least we'll know it loads up correctly)

**Comment by thecodelearner** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/22259087/120887909-2c9b8500-c613-11eb-9151-d32204ef1eba.png">

Nope, can't see any `index.js` or `vendor.js` asset files here


I don't have Prisma CLI installed, snippet of my project's `package.json`:

```
dependencies: {
    ....
    "@prisma/client": "^2.24.1",
    "@next-auth/prisma-adapter": "^0.4.4-canary.64",
}

....

devDependencies: {
    ....
    "prisma": "^2.24.1",
}
```

**Comment by thecodelearner** [comment]
oh weird, creating a new project does indeed load up prisma studio correctly in the browser.
Wonder if that is because `prisma: "^2.24.1"` is not a devDependency?

Here's what I just did:

```
 code mkcd pristudio-test
➜  pristudio-test npm init --y
Wrote to /Users/sahil/code/pristudio-test/package.json:

.....

➜  pristudio-test npm install prisma @prisma/client

added 4 packages, and audited 5 packages in 15s

found 0 vulnerabilities

➜  pristudio-test npx prisma init

✔ Your Prisma schema was created at prisma/schema.prisma.
  You can now open it in your favorite editor.

Next steps:
1. Set the DATABASE_URL in the .env file to point to your existing database. If your database has no tables yet, read https://pris.ly/d/getting-started
2. Set the provider of the datasource block in schema.prisma to match your database: postgresql, mysql or sqlite.
3. Run prisma db pull to turn your database schema into a Prisma data model.
4. Run prisma generate to install Prisma Client. You can then start querying your database.

More information in our documentation:
https://pris.ly/d/getting-started
    
➜  pristudio-test npx prisma studio
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Prisma Studio is up on http://localhost:5555

➜  pristudio-test cat package.json 
{
  "name": "pristudio-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@prisma/client": "^2.24.1",
    "prisma": "^2.24.1"
  }
}

```

**Comment by thecodelearner** [comment]
So I copied the `assets` dir from a fresh prisma Install into my original project (which for some reason did not have that directory at all...?), everything seemed to work fine until I get this error on my terminal:


```
➜  carbon-ghost git:(main) npx prisma studio
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Prisma Studio is up on http://localhost:5555
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at /Users/sahil/code/carbon-ghost/node_modules/prisma/build/index.js:110883:58
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Prima Studio, the Mac app on the other hand, loads up all data perfectly, in all cases.

**Comment by thecodelearner** [comment]
Making the BigInt field a string does load up studio correctly and everything works fine, however I'm curious as to why the `node_modules/prisma/build/public/assets` dir was missing from my project installation.

I did a clean install (`rm -rf node_modules .next && yarn install`) and the `assets` dir went flying out the wazoo again :/ 

@madebysid help.

**Comment by madebysid** [comment]
Okay this does not help 😅 , 'm even more confused now.

1. The fact that Studio works on a new project is good, this means there's something in your current project that's deleting the assets folder. Maybe a `postinstall` script or something?
2. It's super weird that copying the `assets` folder to your own project shows you the Bigint serialization error, considering that it was fixed an released with Prisma 2.23.0. You shouldn't have to change your schema to accomodate this. In your new project, what version of Studio do you see? (You can run `prisma -v`, or look at your browser's DevTools, Studio logs its version there as well)
3. If re-installing dependencies deletes the assets folder from Studio, this too points to some process doing it on `postinstall`.

I'm unfortunately not sure what's going on, but at least we know it is something in your current project?

**Comment by thecodelearner** [comment]
@madebysid I agree, I might've made it seem more complex than it actually is, so to break down here's the crux: somehow the prisma studio's assets dir is being deleted by some dependencies.

1. I don't have an explicit `postinstall` script in my project, the only dependencies I'm using are prisma/client, chakra-ui, next-auth, next-auth/priasma-adapter and nextjs.
2. [Prisma is v2.24.1](https://github.com/prisma/studio/issues/697#issuecomment-854799380) (weird getting the serialization issue on prisma v2.24.1)
3. I have no idea on how to go around debugging postinstall scripts from any internal dependencies, any pointers would be of real help here

happy to share the repo with you so you can test it out too.

**Comment by thecodelearner** [comment]
hello folks, any updates here please?

**Comment by madebysid** [comment]
Hey, yeah let's look at your repo then, maybe I can try to reproduce the problem at my end as well. Could you temporarily invite me to it? If not, you can also make a copy of it and remove everything sensitive from it and invite me there.

**Comment by thecodelearner** [comment]
@madebysid invited you to the repo.

**Comment by madebysid** [comment]
Great news, I'm able to reproduce this on your repo! I'm investigating now.

**Comment by madebysid** [comment]
Ah you have a `.yarnclean` file that has `assets` on line 12 that's the culprit. Removing it fixes Studio.

It's probably not my place to make suggestions, but `yarn clean` has always been a bit too keen in my experience. I'd recommend just getting rid of it entirely or at the very least review its contents. For example, I see you have `__tests__` in there, which might accidentally remove tests you've written (if you put them in that directory).

Either way, changing your `.yarnclean` file should resolve this, so I'm closing!

**Comment by ElijahJunnior** [comment]
I had the same problem but I managed to solve it with the command: npx prisma studio -p 4000

**Comment by pantharshit007** [comment]
hey @sdnts I am also encountering the same issue but there is a catch here:
it shows a blank white page in Brave and Prisma Studio UI on Chrome 

but the error remains the same
`Failed to load resource: the server responded with a status of 404 (Not Found)
inter-all-400-normal.4c1f8a0d.woff:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)

Package.json:
```
{
  "name": "week-10.0.2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^20.12.5",
    "prisma": "^5.12.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.4.4"
  },
  "dependencies": {
    "@prisma/client": "^5.12.1"
  }
}
 ```

I do have assets folder in my node dir

**Comment by pantharshit007** [comment]
code I am trying to run:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // ... you will write your Prisma Client queries here
  await prisma.user.create({
    data: {
      email: "jethiya@example.com",
      name: "jethiya",
    },
  });
}

main()
  .then(async () => {
    console.log("Query executed");
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error("error: " + e);
    await prisma.$disconnect();
    process.exit(1);
  });

```


output once I run `npx prisma studio`
![image](https://github.com/prisma/studio/assets/97608579/31bc2988-7566-42f1-a707-6f0624a229a8)

**Comment by pantharshit007** [comment]
I am new to Prisma so I don't know its working .. as of now
I followed the [doc](https://www.prisma.io/docs/getting-started/quickstart)

**Comment by Chitransh-j** [comment]
@ElijahJunnior Thanks you're a life saver ! But do you have any idea why does it fail to run on port 5555 ?

**Comment by janpio** [comment]
@Chitransh-j Android emulator sometimes blocks port 5555. Could that be the case for you?

**Comment by janpio** [comment]
Studio unfortunately does not correctly throw an error, just created https://github.com/prisma/studio/issues/1250 for this. But good you could figure it out 🥳

**Comment by Chitransh-j** [comment]
Ok! Now I understand. The port was indeed occupied.  :)

BTW, Is there any way I can benefit from discovering this bug? I would appreciate some recognition or credit for identifying it. As a fresher, having this on my resume and github would be very helpful.

**Comment by janpio** [comment]
We don't have a bug bounty or anything like that, sorry. Also, this bug has been reported multiple times before, as you can see in the issue I created. But thank you anyway, we appreciate you writing here.

**Comment by Chitransh-j** [comment]
Fair enough ! Cheers. 🥂

I'll still probably tell my potential recruiter that I did help in finding a bug in a major firm just for a better chance of getting selected :)

Have a good day ! @janpio

**Comment by janpio** [comment]
If that works, and the recruiter reaches out to me I will definitely confirm your contribution here.

**Comment by edtimer** [comment]
Faced the same issue but the cause was a mismatch in versions between prisma and @prisma/client in package.json
For example the following worked:

>    "@prisma/client": "^5.21.1",
>     "prisma": "^5.21.1",

    
But using the following caused 404
```
    "@prisma/client": "^5.21.1",
    "prisma": "^5.22.0",
```

**Comment by JesusJimenezC** [comment]
Same issue here, with the same versions mentioned by @edtimer.
![image](https://github.com/user-attachments/assets/e162d8f7-a269-44fd-88a0-b914c0f2c70b)
