### ISSUE TITLE
Static IP address

### ISSUE THREAD

**Issue by mayerlench** [prisma/studio#698]
As per the docs on enabling a static ip for my account 

> Static IP for whitelisting
> The Prisma Data Platform can have a static IP which you can use to whitelist in order to connect to your database through our Data Browser.
> 
> You can create an issue with your request and we will enable it for you. Please note that while this is a feature that will be part of a paid plan in the future, it is currently offered for free while we are in Early Access.

Can you enable static ip address for my prisma data platform

here is my URL https://cloud.prisma.io/mayerlench

**Comment by martzoukos** [comment]
Hey @mayerlench .

I've enabled the feature for you Project. Can you send me an email at `martzoukos@prisma.io` so that I can send you back the static IP to use?

Thank you!
