### ISSUE TITLE
Error openning Studio

### ISSUE THREAD

**Issue by vanessadcamara** [prisma/studio#700]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey I'd need a few more details for this to be actionable. What error do you see?
