### ISSUE TITLE
Crash in simple datasource only schema

### ISSUE THREAD

**Issue by aredridel** [prisma/studio#701]
1. Prisma version (`prisma -v` or `npx prisma -v`): Prisma studio Version 0.394.0 (0.394.0.9048)

2. Logs from Developer Tools Console or Command line, if any:

Not from the console, but the error message in prisma studio
```
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at Object.hydrate (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/renderer/assets/index.js:1:75342)
    at ki.init (file:///Applications/Prisma%20Studio.app/Contents/Resources/app.asar/renderer/assets/index.js:1:104417)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`) N/A

4. Prisma schema (if relevant):
```
datasource db {
  provider = "mysql"
  url      = "mysql://root:@localhost/mage_202105"
}
```

**Comment by madebysid** [comment]
Thanks for reporting @aredridel, I'll get this fixed in the next stable Prisma version!

**Comment by madebysid** [comment]
This is now fixed, will be out with tomorrow's release. Please reopen if you still see if after!
