### ISSUE TITLE
Cannot create records if using unsupported type

### ISSUE THREAD

**Issue by rymnc** [prisma/studio#702]
1. Prisma version (`prisma -v` or `npx prisma -v`): 
```bash
prisma               : 2.24.0
@prisma/client       : 2.24.0
Current platform     : rhel-openssl-1.1.x
Query Engine         : query-engine f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/query-engine-rhel-openssl-1.1.x)
Migration Engine     : migration-engine-cli f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.1.x)
Introspection Engine : introspection-core f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.1.x)
Format Binary        : prisma-fmt f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.1.x)
Default Engines Hash : f3e341280d96d0abc068f97e959ddf01f321a858
Studio               : 0.397.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Could not find rootField undefined for action create for model
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes

4. Prisma schema (if relevant):
```
model TestModel {
  id Int @id @default(autoincrement())
  ip Unsupported("inet") 
}
```

Creation of records is disallowed using @prisma/client and prisma studio. The create function does not exist on the client stub, and the studio errors out with `Could not find rootField undefined for action create for model`

**Comment by madebysid** [comment]
Hey @rymnc If I understand you correctly, then this is expected. The `Unsupported` type is just that: unsupported (by Prisma).

In your case though, you can use `Inet` through a native type (https://www.prisma.io/docs/concepts/database-connectors/postgresql#native-type-mappings):

```
model TestModel {
  id Int @id @default(autoincrement())
  ip String @db.Inet
}
```
