### ISSUE TITLE
Prisma studio requires having prisma client installed when it shouldn't

### ISSUE THREAD

**Issue by m-abdelwahab** [prisma/studio#703]
Working through this [tutorial](https://vercel.com/guides/nextjs-prisma-postgres), where the steps are:

1.`npm i -D prisma`
2. `npx prisma init`
3. `npx prisma db push`
4. `npx prisma studio` <- error in this step

Installing prisma client fixes the issue but this is unexpected behavior. Because running `db push` should install prisma client

1. Prisma version (`prisma -v` or `npx prisma -v`):

```text
prisma               : 2.24.1
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0

```

2. Logs from Developer Tools Console or Command line, if any:

```bash
Unable to get DMMF from Prisma Client:  Error: Cannot find module '@prisma/client'
Require stack:
- /Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at eval (eval at resolvePrismaClient (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110600:75), <anonymous>:1:9)
    at PCW.resolvePrismaClient (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110600:75)
    at PCW.getDMMF (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110427:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PrismaService.respond (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110692:50)
    at async /Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110867:35 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js'
  ]
}
```

 [reproduction](
https://user-images.githubusercontent.com/27310414/121392499-c040be80-c94f-11eb-8297-6ec868ff7c8f.mp4
)

**Comment by madebysid** [comment]
This is now fixed in the latest `dev` version, will be out with tomorrow's release!

**Comment by TarakKadia** [comment]
> Working through this [tutorial](https://vercel.com/guides/nextjs-prisma-postgres), where the steps are:
> 
> 1.`npm i -D prisma` 2. `npx prisma init` 3. `npx prisma db push` 4. `npx prisma studio` <- error in this step
> 
> Installing prisma client fixes the issue but this is unexpected behavior. Because running `db push` should install prisma client
> 
> 1. Prisma version (`prisma -v` or `npx prisma -v`):
> 
> ```
> prisma               : 2.24.1
> @prisma/client       : Not found
> Current platform     : darwin
> Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-darwin)
> Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-darwin)
> Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-darwin)
> Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
> Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
> Studio               : 0.397.0
> ```
> 
> 2. Logs from Developer Tools Console or Command line, if any:
> 
> ```shell
> Unable to get DMMF from Prisma Client:  Error: Cannot find module '@prisma/client'
> Require stack:
> - /Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
>     at eval (eval at resolvePrismaClient (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110600:75), <anonymous>:1:9)
>     at PCW.resolvePrismaClient (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110600:75)
>     at PCW.getDMMF (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110427:41)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async PrismaService.respond (/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110692:50)
>     at async /Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js:110867:35 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/m-abdelwahab/Desktop/prisma-with-supabase/node_modules/prisma/build/index.js'
>   ]
> }
> ```
> 
>  reproduction.mp4

Thank you. 4th step works for me
