### ISSUE TITLE
Custom DB environment variable

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#706]
**Describe the bug**
We use an environment variable manager (Doppler.com) rather than .env files. As such, our environment variable is currently not accessible to the Prisma Data Platform.

This obviously won’t let us use the Prisma Data Platform, since it cannot access our database.

Any solutions? Any workarounds?

**Comment by madebysid** [comment]
I don't think an easy workaround exists currently, this will have to be built as its own feature :D

**Comment by madebysid** [comment]
Out of curiosity, do you inject the database URL at runtime then?

**Comment by heymartinadams** [comment]
We inject the database URL at build time via a custom build script. Inside that build script, the database URL variable gets created dynamically: Doppler CLI gets installed, then the NextJS build command is called using that dynamically-created variable.

**Comment by madebysid** [comment]
That would be cool! I'm only interested in how you're supplying the database URL to Prisma at build time :D

**Comment by heymartinadams** [comment]
We inject the database URL at **build time** via a custom build script. Inside that build script, the database URL variable gets created dynamically: Doppler CLI gets installed and run, then the NextJS build command is called using that dynamically-created variable. Here’s what happens:

```js
// Packages
import shell from 'shelljs'

// This is run on Vercel
const ScriptBuild = async () => {
  shell.exec(
    `(curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh`
)

  // Set environment from branch (!) that’s being deployed to Vercel; this is a workaround since Vercel only has two environments that can be deployed: `preview`, and `production`; and we want to use more than those two
  const env = process.env.BRANCH

  // When we deploy the `dev` branch or `feature` branches to Vercel, Doppler will connect to the root `dev` environment and database
  const token = `DOPPLER_TOKEN_` + env.toUpperCase()

  shell.exec(`doppler setup --token ${process.env[token]} --config ${env}`)

  shell.exec(`prisma generate --schema=./prisma/${env}/schema.prisma`)

  shell.exec(`doppler run -- next build`)
}

ScriptBuild()
```

**Comment by heymartinadams** [comment]
We inject the database URL at **build time** via a custom build script. Inside that build script, the database URL variable gets created dynamically: Doppler CLI gets installed and run, then the NextJS build command is called using that dynamically-created variable. Here’s what happens:

```js
// Packages
import shell from 'shelljs'

// This is run on Vercel
const ScriptBuild = async () => {
  shell.exec(
    `(curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh`
)

  const env = process.env.ENV

  const token = `DOPPLER_TOKEN_` + env.toUpperCase()

  shell.exec(`doppler setup --token ${process.env[token]} --config ${env}`)

  shell.exec(`prisma generate --schema=./prisma/${env}/schema.prisma`)

  shell.exec(`doppler run -- next build`)
}

ScriptBuild()
```
