### ISSUE TITLE
URL-decode the `schemaPath` when creating a new project

### ISSUE THREAD

**Issue by ljosberinn** [prisma/studio#707]
**Describe the bug**
The GQL request to setup the project fails when trying to (presumably) importing a schema file within a folder containing `@`.

Path to `schema.prisma`: https://github.com/ljosberinn/keystone-heroes/blob/master/packages/%40keystone-heroes/db/prisma/schema.prisma

![image](https://user-images.githubusercontent.com/29307652/121748708-b662bb00-cb09-11eb-9211-7122e2a57d92.png)

Both `packages/%40keystone-heroes/db/prisma/schema.prisma` (taken from URL) and the actual path in the folder structure `packages/@keystone-heroes/db/prisma/schema.prisma` fail with:

![image](https://user-images.githubusercontent.com/29307652/121748798-e01be200-cb09-11eb-8550-fec548a3a267.png)

**Comment by madebysid** [comment]
Hey @ljosberinn, thanks for reporting! Have you tried using the literal `@` instead (without URL-encoding it)?

I was able to create a project then. Nonetheless, I think we could URL-decode your schema location internally as well to avoid this, espoecially since anyone would run into this if they just copy the URL from Github.

**Comment by ljosberinn** [comment]
yes! I've mentioned above:

> Both `packages/%40keystone-heroes/db/prisma/schema.prisma `(taken from URL) and the actual path in the folder structure `packages/@keystone-heroes/db/prisma/schema.prisma` fail (...)

👋

**Comment by madebysid** [comment]
Oh whoops, looks like I totally missed that.

That's interesting though, I just tried the exact path you had in a private repo, and was able to create one.

I wonder if it's the branch name that's incorrect then. I see your repo's main branch is called `master`, and not `main`, can you try changing that?

The `branch` field should probably be populated depending on what your repo's main branch is, that could be an improvement!

**Comment by ljosberinn** [comment]
🤦‍♂️ I'm sorry, I created this project far after githubs switch to `main`, I have no idea why it's master and that is indeed the source of the error 🤣 thanks!

**Comment by madebysid** [comment]
I'm going to keep this open so we can fix the URL decode thing!

**Comment by madebysid** [comment]
This is fixed now, sorry about the delay!
