### ISSUE TITLE
Prisma Studio Refresh

### ISSUE THREAD

**Issue by SpaceForever** [prisma/studio#713]
1. Prisma version (`prisma -v` or `npx prisma -v`):
2.25.0

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "stack": "Error: \u001b[91m\u001b[1mGet config: \u001b[22m\u001b[39m\u001b[91mSchema Parsing P1012\u001b[39m\n\u001b[91m\u001b[39m\n\u001b[91m\u001b[39m\u001b[91merror: Error validating: This line is not a valid definition within a datasource.\u001b[39m\n\u001b[91m  -->  schema.prisma:9\u001b[39m\n\u001b[91m   | \u001b[39m\n\u001b[91m 8 |   provider = \"postgresql\"\u001b[39m\n\u001b[91m 9 |   url      = // env(\"DATABASE_URL\")\u001b[39m\n\u001b[91m10 | }\u001b[39m\n\u001b[91m   | \u001b[39m\n\u001b[91m\u001b[39m\n\u001b[91mValidation Error Count: 1\u001b[39m\n\n    at getConfigBinary (C:\\Users\\space\\node_modules\\prisma\\build\\index.js:102508:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.getConfig5 (C:\\Users\\space\\node_modules\\prisma\\build\\index.js:102412:14)\n    at async getGenerators (C:\\Users\\space\\node_modules\\prisma\\build\\index.js:106720:20)\n    at async Object.getGenerator (C:\\Users\\space\\node_modules\\prisma\\build\\index.js:106928:24)\n    at async PCW.getDMMF (C:\\Users\\space\\node_modules\\prisma\\build\\index.js:108603:41)\n    at async PrismaService.respond (C:\\Users\\space\\node_modules\\prisma\\build\\index.js:108916:50)\n    at async C:\\Users\\space\\node_modules\\prisma\\build\\index.js:109091:35",
  "message": "\u001b[91m\u001b[1mGet config: \u001b[22m\u001b[39m\u001b[91mSchema Parsing P1012\u001b[39m\n\u001b[91m\u001b[39m\n\u001b[91m\u001b[39m\u001b[91merror: Error validating: This line is not a valid definition within a datasource.\u001b[39m\n\u001b[91m  -->  schema.prisma:9\u001b[39m\n\u001b[91m   | \u001b[39m\n\u001b[91m 8 |   provider = \"postgresql\"\u001b[39m\n\u001b[91m 9 |   url      = // env(\"DATABASE_URL\")\u001b[39m\n\u001b[91m10 | }\u001b[39m\n\u001b[91m   | \u001b[39m\n\u001b[91m\u001b[39m\n\u001b[91mValidation Error Count: 1\u001b[39m\n"
}
ki/this.init@http://localhost:5555/assets/index.js:1:103826

```

**Comment by madebysid** [comment]
@SpaceForever The error seems obfuscated by all the unicode characters, but it says that there's something wrong in your Prisma Schema's `datasource`. Can you show me your schema (just the datasource should be enough)

**Comment by SpaceForever** [comment]
I realised the issue was because I was running prisma studio from the incorrect directory, and that one used postgresql. Can prisma studio not render PostgreSQL? The issue is solved, but here is the old schema``` datasource db {  provider = "postgresql"  url      = // env("DATABASE_URL")} ``` Ah yes, and the url was commented out. Of course there was an error.  All fixed, thank you!  From: SiddhantSent: 18 June 2021 10:57To: prisma/studioCc: SpaceForever; MentionSubject: Re: [prisma/studio] Prisma Studio Refresh (#713) @SpaceForever The error seems obfuscated by all the unicode characters, but it says that there's something wrong in your Prisma Schema's datasource. Can you show me your schema (just the datasource should be enough)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
