### ISSUE TITLE
Fatal Error - HTTP 500 - Internal Server Error

### ISSUE THREAD

**Issue by moroshko** [prisma/studio#714]
I started getting a fatal error on my project:

https://cloud.prisma.io/moroshko/my-place-psychology/databrowser

```
Error in HTTP Request (Status: 500)
{}
```

I didn't push any changes lately, so I assume something has changed on the Prisma Studio side.

Is there any other information I can provide to help debug this?

**Comment by janpio** [comment]
Can confirm and reproduce, on it.

**Comment by janpio** [comment]
Fix is live and Cloud can be used again. Sorry about the inconvenience, you just experienced our first real production outage I think. I hope this will not happen more often in the future. Thanks for your understanding.

**Comment by moroshko** [comment]
All good @janpio. Thanks a lot for fixing this so quickly!
