### ISSUE TITLE
Error in HTTP Request (Status: 500) on cloud

### ISSUE THREAD

**Issue by AhmedElywa** [prisma/studio#715]
Logs from Developer Tools Console or Command line, if any:
![image](https://user-images.githubusercontent.com/4535142/123848174-af181b80-d917-11eb-8a24-f3e188b17f6e.png)

**Comment by madebysid** [comment]
Hey! Could you share your schema as well? I'm unable to see this on my own project, so I'll try using your schema as well :D

**Comment by AhmedElywa** [comment]
@madebysid I sent to you on slack

**Comment by madebysid** [comment]
👋 We chatted on Slack, but I'll leave this comment here for documentation. The issue turned out to be the `nApi` and `referentialActions` feature flags. I've since fixed this on cloud.prisma.io :D
