### ISSUE TITLE
binaryTargets error

### ISSUE THREAD

**Issue by carru93** [prisma/studio#718]
1. Prisma version (`prisma -v` or `npx prisma -v`):
prisma               : 2.23.0
@prisma/client       : 2.26.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../.local/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../.local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../.local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../.local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "stack": "TypeError: binaryTargets.flatMap is not a function\n    at validateGenerators (/home/emanuele/work/fullstack/api/node_modules/prisma/build/index.js:107182:53)",
  "message": "binaryTargets.flatMap is not a function"
}
Error: Error starting Prisma Client: {
  "stack": "TypeError: binaryTargets.flatMap is not a function\n    at validateGenerators (/home/emanuele/work/fullstack/api/node_modules/prisma/build/index.js:107182:53)",
  "message": "binaryTargets.flatMap is not a function"
}
    at ki.init (http://localhost:5555/assets/index.js:1:103816)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

enum Role {
  USER
  ADMIN
  SUPERADMIN
}

model User {
  id             Int       @id @default(autoincrement()) @db.UnsignedInt
  first_name     String?   @db.VarChar(125)
  last_name      String?   @db.VarChar(125)
  full_name      String?   @db.VarChar(250)
  email          String    @db.VarChar(255)
  old_email      String?   @db.VarChar(255)
  password       String    @db.VarChar(255)
  password_reset String?   @db.VarChar(300)
  lang           String    @default("it") @db.VarChar(2)
  active         Boolean   @default(false)
  role           Role      @default(USER)
  updated_at     DateTime  @updatedAt
  auth_reset     Boolean   @default(false)
  auth_reset_at  DateTime?
  created_at     DateTime  @default(now())
  deleted_at     DateTime?
  deleted        Boolean   @default(false)
  salt           String
  rf_tokens      rt_user[]
  group          Group[]

  @@map(name: "users")
}

model rt_user {
  id          Int      @id @default(autoincrement()) @db.UnsignedInt
  user        User     @relation(fields: [user_id], references: [id])
  user_id     Int      @db.UnsignedInt
  token       String   @db.Text
  expiry_date DateTime

  @@map(name: "rtUser")
}

model Group {
  id   Int    @id @default(autoincrement()) @db.UnsignedInt
  name String @db.VarChar(100)
  user User[]

  @@map(name: "groups")
}


```
5. Additional information
I get the ```binaryTargets.flatMap is not a function``` error also when I try to run the prisma migrate reset

**Comment by madebysid** [comment]
Hey @carru93, thanks for reporting this! Are you on Node 10?
Node 10 reached its EOL earlier this year, so my first suggestion would be to try upgrading (to v14 perhaps), and trying again.

Might I also suggest upgrading to the latest version of Prisma (2.26.0 as of writing) while you're at it? This will make sure this issue still exists (although I think the Node upgrade should fix it!)

Let me know!

**Comment by carru93** [comment]
Yeah it was an nvm problem, now it seems to work fine
