### ISSUE TITLE
Set default theme via query parameter

### ISSUE THREAD

**Issue by jakiestfu** [prisma/studio#721]
Would love to be able to set the default theme of the editor via query parameter. Our tool embeds the studio in an iFrame and has light/dark mode support so we'd like to change the theme of the studio via query parameter to match our app.

**Comment by madebysid** [comment]
Hey @jakiestfu, I think this can be arranged!

Trying to understand your setup: Do you run `npx prisma studio` on a server and forward all requests from the iframe? Where would this query param exist?

**Comment by jakiestfu** [comment]
It would exist on the client. I'd load and maintain the following:

```html
<iframe src='http://localhost:5555/?theme=dark'></iframe>
```

Leveraging CSS4 variables could make this easy. Or a bit of state sync via query param.

**Comment by madebysid** [comment]
Ah great. We already use CSS variables for theming, and using a query parameter on the client should be simple enough to implement.

Studio's open source-ness is still undecided, it'll be best to follow https://github.com/prisma/studio/issues/76!

**Comment by jakiestfu** [comment]
Have you had a chance to look into this further, @madebysid? 🙏

**Comment by madebysid** [comment]
Hey, sorry not yet, I'll try to do this next week!

**Comment by madebysid** [comment]
Hey so the latest version of Studio on Prisma 3.5.0 can now accept a `theme` query parameter that will be given top priority.
Better late than never right.. 😅 Thanks for being patient!

**Comment by marviobezerra** [comment]
I've tried to set the theme using query parameter but it does not work. Can you please confirm if it stills working?
