### ISSUE TITLE
Unable to connect to Google Cloud MySQL instance using Prisma Data Platform

### ISSUE THREAD

**Issue by BDJ-Corporation** [prisma/studio#724]
**Describe the bug**
I'm trying to use Prisma Data Platform. I followed all the process: connect to my github account, select my project, define where is my schema located inside my project repository, and I provided a connection string when asked me to connect to some database. When I wrote my connection string (I supposed that should use the same connection string that I used to run prisma in my repository) just happen anything. Says "Creating a project. Your fresh new project is almost ready" but after a few minutes just stop and ask me again to connect to my database.

Also I Added a screenshot of the errors that threw me in my web navigator console.

**To Reproduce**
1. Go to 'https://www.prisma.io/blog/whats-new-in-prisma-q2-2021-z70muetl386d'
2. Click on 'Try Prisma's Online Data Browser' button.
3. Should send you to **https://cloud.prisma.io/**
4. Click on "Continue with Github" button.
5. Click on "Authorize Prisma" to link your Github account with prisma.
6. Will show you a form to Create Project where you should: select one repo, give a project name, define an Url, define the schema path, and select the Github branch.
7. After this, will show a new form where you could select the Database Engine you use, and write the connection string.
8. Select "MySQL" engine and write the connection string (I used this connection string syntax -> mysql://<user>:<password>@<ip>/<database>) and press the "Connect to Database" button. (FYI, I'm trying to connect to a Google Cloud MySQL instance using the public ip).
9. Will show you a new header on the top saying "Creating a project. Your fresh new project is almost ready".
10. Here is when shows me the "error". Just ends and ask me again to write the database connection string. No feedback at all.

**Expected behavior**
idk, should connect to my database? 

**Screenshots**

![image](https://user-images.githubusercontent.com/76407077/124980751-6688ee00-dffa-11eb-873f-8ac0e4c89966.png)

**Desktop (please complete the following information):**
 - OS: iOS Mac (Big Sur 11.4 with M1)
 - Browser: Google Chrome
 - Version: Version 91.0.4472.114 (Build oficial) (arm64)

**Additional context**
I'm trying to connect to a Google Cloud MySQL instance using the public ip.

**Comment by janpio** [comment]
Seems that Cloud can not connect to your database and is bad at handling that specific error.

Can you create a Prisma project locally with `npx prisma init`, then configure it to use that connection string and then see if `npx prisma db pull` works and creates a schema?

How did you create your database exactly? We would of course like to reproduce the error and knowing that would be very helpful.
