### ISSUE TITLE
Ability to remove invalid/unused schemes

### ISSUE THREAD

**Issue by cehenriques** [prisma/studio#726]
Prisma version:
@prisma/studio-electron 0.410.0

It would be nice if I could remove invalid or unused schemes from the first screen of Prisma Studio Desktop. I can add schemes using the "Select Schema" feature, but then I cannot remove them from the list, at least from the UI.

**Comment by madebysid** [comment]
@cehenriques thanks for the feature request! I think this is reasonable, I'll figure something out and let you know when it is released!

**Comment by madebysid** [comment]
This is now possible in the latest Electron app release!
