### ISSUE TITLE
ConnectorError timeout SQLite Prisma Studio v 0.410.0

### ISSUE THREAD

**Issue by ridhwaans** [prisma/studio#729]
I have the new desktop update from https://github.com/prisma/studio/releases   

Whenever I open a `prisma.schema` of my project but any schema for that matter, going to view any relation from the main page results in the stalled message `Fetching rows in this table...`.  

However when I run `prisma studio` via my project terminal and go to `http://localhost:5555` it works as expected. It just doesnt work in the app (windows 10)  

1. Prisma version (`prisma -v` or `npx prisma -v`) taken from prisma project:
```
Environment variables loaded from .env
prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../.nvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../.nvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../.nvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at ../../../.nvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 9b816b3aa13cc270074f172f30d6eda8a8ce867d
Studio               : 0.408.0
Preview Features     : referentialActions, orderByRelation
```
2. Logs from Developer Tools Console or Command line, if any:
![image](https://user-images.githubusercontent.com/1103336/125204664-5a946a80-e24c-11eb-9d10-cb51cc7748ec.png)

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

n/a

**Comment by madebysid** [comment]
Hey @ridhwaans, thanks for reporting this! Is this new or was this happening on older releases of the desktop app as well?

**Comment by ridhwaans** [comment]
yes this was not working in the older release also

**Comment by ridhwaans** [comment]
update: this issue still persists on v0.438 windows 11
