### ISSUE TITLE
Project dashboard

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#73]
Current proposal for the dasboard is to have it be the "root" view of a project. Gives an overview of the running processes and their statuses, as well as enables to take "project-level" actions.

![dashboard-view](https://user-images.githubusercontent.com/1710629/63733759-f5af1180-c879-11e9-972e-27a25c02d102.png)
![dashboard](https://user-images.githubusercontent.com/1710629/63733761-f647a800-c879-11e9-96c2-93e13c22647e.png)
![dashboard-notification](https://user-images.githubusercontent.com/1710629/63733846-44f54200-c87a-11e9-9d2c-8c8ea9596fea.png)

**Comment by idan** [comment]
IMO this is in the critical path for beta. Marking tentatively, happy to discuss @schickling @janpio @sorenbs
