### ISSUE TITLE
Databrowser crashes when viewing schema

### ISSUE THREAD

**Issue by Jcardif** [prisma/studio#733]
Used the "Create a Project flow" and selected the Music streaming service and SQL server as the database

On successful creation of the project, I navigated to the Databrowser tab and the following error was thrown

![image](https://user-images.githubusercontent.com/29174946/125582060-606a3969-d54d-4b82-a392-c29623cb2f9e.png)

![image](https://user-images.githubusercontent.com/29174946/125582622-e734c28a-61db-4b2b-a4c8-1a7b09688dc0.png)

**Comment by madebysid** [comment]
Hey @Jcardif, thanks for reporting this! I'll check this out with SQL Server.

Just to make sure we didn't mess up schema creation, could you clone the repository that was created for you and try running a query / opening Studio locally to see if that works?

If you're new to Prisma, I'm more than happy to give you more concrete steps!

**Comment by ruheni** [comment]
The Music streaming example seems to be using the `Json` type which is currently not supported by the SQL Server connector. 

![Screenshot 2021-07-14 at 21 10 12](https://user-images.githubusercontent.com/33921841/125671768-d48670a5-6616-49b9-8e9a-e43ac9337c0f.png)

Cloning the repo, then updating the `previewFeatures` block, seeding and running studio works fine locally.

**Comment by janpio** [comment]
> Cloning the repo, then updating the `previewFeatures` block, seeding and running studio works fine locally.

What exactly needs to changed in `previewFeatures` to make this work?

**Comment by ruheni** [comment]
Including `sqlServer` in the `previewFeatures` block. I forgot to say I removed the `Json` field

**Comment by ruheni** [comment]
The template was updated and should be fixed in the next deployment.
