### ISSUE TITLE
Limbo/"Dirty" states

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#74]
Once user changes or adds any data, the "limbo" cells are highlighted and the total number of changes is shown. If any of the changes are "illegal" (null value for non-null field etc), the "save" button is disabled.

![limbo](https://user-images.githubusercontent.com/1710629/63733884-66eec480-c87a-11e9-9642-3927e6b3467d.png)
![limbo-table-invalid](https://user-images.githubusercontent.com/1710629/63733882-66562e00-c87a-11e9-8782-00957bdd1e70.png)
![limbo-tree-invalid](https://user-images.githubusercontent.com/1710629/63733883-66eec480-c87a-11e9-9540-4c30c3365ccc.png)
![new-record-limbo](https://user-images.githubusercontent.com/1710629/63733886-66eec480-c87a-11e9-80c7-0d697d410227.png)

**Comment by idan** [comment]
Add to "commit bar" if there are invalid fields:
- error message in red like "You have invalid staged changes, please fix all of the fields highlighted in red."
- Disable the commit button while there are invalid changes.
