### ISSUE TITLE
Integrate prisma client logging to prisma local studio to act as devtool

### ISSUE THREAD

**Issue by sandbox-apps** [prisma/studio#742]
Show all queries executed and their metrics and event names (INSERT, UPDATE, ...) while in development.
So we can benchmark performance and perform optimization with optimal setup

**Comment by madebysid** [comment]
@sandbox-apps Could you create a feature request on https://github.com/prisma/prisma insead? This will have to be a general Prisma Client feature. When that happens, Studio should automatically start doing that as well without changes!

**Comment by madebysid** [comment]
Hey @sandbox-apps, you should be able to do that

**Comment by madebysid** [comment]
@sandbox-apps You should be able to doi that within Prisma Client directly: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging

Studio generates Prisma Client queries on its own, so I'm wondering how that would be useful for performance monitoring for your app? Could you elaborate?

**Comment by sandbox-apps** [comment]
Yeah, im talking about the actual prisma client (not the studio) that directly logs at the local studio.
Atleast we can save some overhead boilerplate in making the logger setup and possibly a .env where you dont wont to make a logging in production
