### ISSUE TITLE
Sort models alphabetically (or allow multiple sorting options)

### ISSUE THREAD

**Issue by ajmnz** [prisma/studio#748]
Right now, I'm unable to tell which criteria does Prisma Studio follow for sorting the list of models. Search is useful, but having your models sorted alphabetically or by record count would help a lot and improve UX.

**Comment by madebysid** [comment]
Hey @ajmnz, models should currently be ordered the same as your schema, but I agree that having them ordered alphabetically would be an improvement. I'll do that and let you know!

**Comment by madebysid** [comment]
I've just implemented this, this should be out in tomorrow's Prisma CLI release!

In the `All Models` section, models will now be sorted alphabetically, but the ones in the `Recent` section are ordered by timestamp of last use.
