### ISSUE TITLE
Feedback popup

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#75]
A proposal for a help button that opens a popup to leave feedback, as well as links to few key resources. To make feedback process tiny bit more playful, the slider could change emojis based on the scroll position. From 😡 to 😍

![feedback-slider](https://user-images.githubusercontent.com/1710629/63734082-25124e00-c87b-11e9-8145-9e34be4f494a.png)
![feedback-buttons](https://user-images.githubusercontent.com/1710629/63734081-2479b780-c87b-11e9-9f2a-eb983d991aee.png)

**Comment by idan** [comment]
This is super cute!

Are we using something like intercom already? As much as I love this UX, maybe cheaper for us to buy tools around this than build them.

**Comment by madebysid** [comment]
@idan Nope, not currently. Maybe we can think about that then!

**Comment by idan** [comment]
@schickling WDYT? re: buying https://www.intercom.com/pricing/

**Comment by janpio** [comment]
Intercom is in usage for Prisma1 Cloud (or Graphcool) - @divyenduz answered some of my questions there so can probably tell us more about Prisma's usage of Intercom.

**Comment by matthewmueller** [comment]
I think we should do something here before Studio GA. 

Agree with using Intercom.
