### ISSUE TITLE
Application Data Platform: Can't delete a Project

### ISSUE THREAD

**Issue by loklaan** [prisma/studio#750]
**Describe the bug**
Can not delete Project in Cloud.

**To Reproduce**
1. Go to create a Project [by importing](https://cloud.prisma.io/projects/new)
2. Fill in details correctly, and click "Create project"
3. Decide that you don't want to, or can't, continue the setup
4. Attempt to delete the Project

**Expected behavior**
There should be some way to delete/cancel a Project if it's not setup completely.

**Comment by madebysid** [comment]
Hey sorry for getting back so late on this, but this is definitely one of those little annoying things we're working on fixing!

**Comment by loklaan** [comment]
No worries mate - feel free to close this if you're tracking it internally or something. 👍

**Comment by madebysid** [comment]
Hey, the latest app should now let you delete a project even if you don't have a DB linked!
