### ISSUE TITLE
Invalid `prisma.user.create()` invocation

### ISSUE THREAD

**Issue by ShubhamSainiForcebolt** [prisma/studio#752]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @ShubhamSainiForcebolt I'm going to need more information to debug this. When did you see this? What does your schema look like? Are there logs in the DevTools console?
