### ISSUE TITLE
Need to be logged in to Heroku before I can provision a database for the 1st time

### ISSUE THREAD

**Issue by m-abdelwahab** [prisma/studio#753]
**Describe the bug**
When provisioning a database using Heroku for the first time and I'm not logged in I got an error

https://user-images.githubusercontent.com/27310414/127502714-3b61b935-094e-4d9d-b562-8e9441839fea.mp4

**To Reproduce**
1. Be logged out of Heroku and not have the Prisma Data Platform configured
2. try to provision a database

**Expected behavior**
I should get a login screen from Heroku

**Screenshots**

After being logged in and trying to provision a database I get this which is expected

![CleanShot 2021-07-29 at 15 38 41@2x](https://user-images.githubusercontent.com/27310414/127503660-d737c0db-f42e-4209-ad2b-d44cdbc97c14.png)

**Comment by madebysid** [comment]
I wonder why the login window is opening in a new tab instead of a new window. I believe @2color was seeing something similar as well (window closing right after opening)

**Comment by m-abdelwahab** [comment]
I guess to reproduce it you can remove the Prisma app from Heroku (to remove permissions) then try to provision a database
