### ISSUE TITLE
Static IP address

### ISSUE THREAD

**Issue by kladnik** [prisma/studio#760]
As per the docs on enabling a static ip for my account

> Static IP for whitelisting
> The Prisma Data Platform can have a static IP which you can use to whitelist in order to connect to your database through our Data Browser.
> 
> You can create an issue with your request and we will enable it for you. Please note that while this is a feature that will be part of a paid plan in the future, it is currently offered for free while we are in Early Access.

Can you enable static ip address for my prisma data platform

Here is my URL https://cloud.prisma.io/kladnik

Thank you!

**Comment by endor** [comment]
Hei @kladnik,

it looks like you haven't yet added a database to your project. Please do that and afterward can you please send me an email to `proessdorf@prisma.io`, so that I can send you back the static IP to use?

Thank you!

**Comment by kladnik** [comment]
Hi @endor.

I cannot add database, because I haven't listed the IP yet.
When I try adding the database I get `The database is not reachable`.

Am I missing something here?

**Comment by endor** [comment]
We've solved this by first creating a database configuration that is reachable, then enabling the static IP usage for that configuration and afterwards updating the configuration to reflect the database that only allows whitelisted connections.
