### ISSUE TITLE
Typo in landing page: `form` -> `from`

### ISSUE THREAD

**Issue by jonasws** [prisma/studio#761]
**Describe the bug**
There is a typo in the landing page (see screenshot): `form` really should say `from`.
<img width="877" alt="Screen Shot 2021-08-09 at 13 31 11" src="https://user-images.githubusercontent.com/2318955/128699750-d77030c7-7313-42b6-ab9b-d08cf684540a.png">

**Comment by madebysid** [comment]
Whoops, thanks for letting us know! I'll fix this asap.

**Comment by madebysid** [comment]
This should be fixed now!
