### ISSUE TITLE
Getting error while using Data Browser in Prisma Data Platform

### ISSUE THREAD

**Issue by penumatv** [prisma/studio#763]
Getting error while using Data Browser in Prisma Data Platform

<img width="342" alt="Capture" src="https://user-images.githubusercontent.com/41994139/129025681-5f7bb5dc-ffe7-42a4-8699-27bbf9a66946.PNG">

```
// An empty Prisma Schema with no models, perfect as a starting point for your own schema.

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

**Comment by madebysid** [comment]
Hey @penumatv, does this only happen for empty schemas? 
Can you also expand the `Show details` section so I can see what's in there?

**Comment by madebysid** [comment]
Hey, I'm going to close this, I'm assuming this was fixed, but if not, please let me know and I'll reopen!
