### ISSUE TITLE
Static IP request

### ISSUE THREAD

**Issue by scriptcoded** [prisma/studio#764]
I'd love to try out the new Data Platform but require a static IP address to be able to connect to my database. The docs mentioned raising an issue here, so here we go :)

Project URL: https://cloud.prisma.io/scriptcoded/adora

Thanks, the Prisma Data Platform seems really cool!

**Comment by madebysid** [comment]
Hey @scriptcoded, sorry I just saw this. Could you take care of this @endor?

**Comment by endor** [comment]
Hei @scriptcoded,

Please send me an email to proessdorf@prisma.io, so that I can send you back the static IP to use.

Thank you!

**Comment by scriptcoded** [comment]
> Hey @scriptcoded, sorry I just saw this. Could you take care of this @endor?

No worries @madebysid! We're just evaluating anyways :)

Thanks @endor! Excited to try it out!
