### ISSUE TITLE
Open shema issue

### ISSUE THREAD

**Issue by bulgaagithub** [prisma/studio#765]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hi @bulgaagithub, I'll need more information to be able to debug this. What error are you seeing? What exactly did you do that caused it?
