### ISSUE TITLE
Studio should pin prisma dependencies to avoid problems during `prisma` patch releases.

### ISSUE THREAD

**Issue by Jolg42** [prisma/studio#766]
During the `prisma/prisma` `2.29.1` patch release we randomly found out that we needed to override Studio's dependency because they are not pinned.
https://github.com/prisma/prisma/commit/88a9abe274be04eb6b35ff408b633db8bf2ceb2e

We could totally have miss that if there was no breaking change introduced on a more recent dev version when we did the release.

It seems that Studio was pinning the versions before and stopped after `2.27.0`
https://github.com/prisma/studio-code/commit/1b5dd7a8073401fbf55086a5c66b43fd4bc89233#diff-34be044c758fdb7c9dced6a2c56893d0ead78ae7b40869576f02d120e9ff0456

Is there a specific reason that needed us to unpin?

Happy to send a PR.

**Comment by millsp** [comment]
Ran into this today while doing a patch release

```ts
@prisma/studio-server 0.422.0
├─┬ @prisma/sdk 2.31.0-dev.19
│ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ ├─┬ @types/debug 4.1.7
│ │ │ └── @types/ms 0.7.31
│ │ ├─┬ debug 4.3.2
│ │ │ └── ms 2.1.2
│ │ └── ms 2.1.3
│ ├─┬ @prisma/engine-core 2.31.0-dev.19
│ │ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ │ ├─┬ @types/debug 4.1.7
│ │ │ │ └── @types/ms 0.7.31
│ │ │ ├─┬ debug 4.3.2
│ │ │ │ └── ms 2.1.2
│ │ │ └── ms 2.1.3
│ │ ├── @prisma/engines 2.31.0-11.c6aa2685dff09984e6656f5d99a90b9e90eabbce
│ │ ├─┬ @prisma/generator-helper 2.31.0-dev.19
│ │ │ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ │ │ ├─┬ @types/debug 4.1.7
│ │ │ │ │ └── @types/ms 0.7.31
│ │ │ │ ├─┬ debug 4.3.2
...
│ ├─┬ @prisma/generator-helper 2.31.0-dev.19
│ │ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ │ ├─┬ @types/debug 4.1.7
│ │ │ │ └── @types/ms 0.7.31
│ │ │ ├─┬ debug 4.3.2
│ │ │ │ └── ms 2.1.2
│ │ │ └── ms 2.1.3
│ │ ├─┬ @types/cross-spawn 6.0.2
│ │ │ └── @types/node 14.17.6
│ │ ├─┬ chalk 4.1.2
...
├─┬ @prisma/studio-pcw 0.422.0
│ ├─┬ @prisma/sdk 2.31.0-dev.19 peer
│ │ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ │ ├─┬ @types/debug 4.1.7
│ │ │ │ └── @types/ms 0.7.31
│ │ │ ├─┬ debug 4.3.2
│ │ │ │ └── ms 2.1.2
│ │ │ └── ms 2.1.3
│ │ ├─┬ @prisma/engine-core 2.31.0-dev.19
│ │ │ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ │ │ ├─┬ @types/debug 4.1.7
│ │ │ │ │ └── @types/ms 0.7.31
│ │ │ │ ├─┬ debug 4.3.2
│ │ │ │ │ └── ms 2.1.2
│ │ │ │ └── ms 2.1.3
│ │ │ ├── @prisma/engines 2.31.0-11.c6aa2685dff09984e6656f5d99a90b9e90eabbce
│ │ │ ├─┬ @prisma/generator-helper 2.31.0-dev.19
│ │ │ │ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ │ │ │ ├─┬ @types/debug 4.1.7
│ │ │ │ │ │ └── @types/ms 0.7.31
...
│ │ ├─┬ @prisma/generator-helper 2.31.0-dev.19
│ │ │ ├─┬ @prisma/debug 2.31.0-dev.19
│ │ │ │ ├─┬ @types/debug 4.1.7
│ │ │ │ │ └── @types/ms 0.7.31
│ │ │ │ ├─┬ debug 4.3.2
│ │ │ │ │ └── ms 2.1.2
│ │ │ │ └── ms 2.1.3
...
```

**Comment by martzoukos** [comment]
Check with @madebysid on Monday about the reasons for unpinning the deps, before proceeding with any changes.

**Comment by madebysid** [comment]
This is done now!

**Comment by Jolg42** [comment]
Sid
I just marked the SDK as a peerDependency, and now tha bundling seems to be failing: https://github.com/prisma/prisma/pull/9133/checks?check_run_id=3523811411
Do I have to do something else in the CLI as well @Joël?
This is the PR BTW: https://github.com/prisma/prisma/pull/9133

Tried an esbuild plugin but it failed
https://github.com/prisma/prisma/pull/9139

**Comment by Jolg42** [comment]
So this is not done for this release, Prisma CLI with this latest Studio breaks

Thread at https://prisma-company.slack.com/archives/CC8F34ALF/p1630350532018100

**Comment by madebysid** [comment]
I guess we can close this now?
All Prisma dependencies in Studio are `peerDependencies`. For local development, I have them added as `devDependencies`, and they're pinned to stable (although that shouldn't matter)

**Comment by Jolg42** [comment]
I think we can close indeed!

https://github.com/prisma/studio-code/blob/main/packages/pcw/package.json#L44-L45
