### ISSUE TITLE
npx prisma studio

### ISSUE THREAD

**Issue by Gloria0987** [prisma/studio#768]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hi @Gloria0987, I'll need more information to debug this. Do you see an error? What is it? What caused it?
