### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by MariaGreiner** [prisma/studio#769]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hi @MariaGreiner, I'll need a little more information about this to be able to debug. What caused this? What was the error?
