### ISSUE TITLE
Fatal Error when have relation attribute without declare preview feature 'referentialAction'

### ISSUE THREAD

**Issue by mxgs-p** [prisma/studio#777]
Prisma 3.0.2

Error parsing attribute \"@relation\": The relation field `profile` on Model `User` must not specify the `onDelete` argument in the @relation attribute without enabling the `referentialActions`

Schema warning if add that sentence.
Preview feature "referentialActions" is deprecated. The functionality can be used without specifying it as a preview feature.

**Comment by madebysid** [comment]
Hey @mxgs-p, are you using the Electron app? Unfortunately the electron app wasn't updated to use Prisma 3.0 yesterday, but I've just pushed out a new version that should fix this issue for you. You'll need to restart the Electron app to see the update.

Let me know if that's not the case, and I'll reopen.
