### ISSUE TITLE
How to add array data in prisma studio

### ISSUE THREAD

**Issue by DinhThuongNguyen** [prisma/studio#778]
1. Prisma version (3.0.2):

In Post model I have data type <images String[]> , I want to add some images to images manually but got error, how to not get the error again.
Sorry my english is not good.

I use postgres as database.

**Comment by madebysid** [comment]
Hey @DinhThuongNguyen, if you must use Studio, then you will have to manually add every image. When you double-click a table cell, you will be able to. 

Although, I'd recommend using a Prisma Client script if you have your data as a JSON object, it'll be must more convenient. 

Closing this, but please reopen if you find a problem!
