### ISSUE TITLE
Error when use @default(dbgenerated("gen_random_uuid()")) @db.Uuid

### ISSUE THREAD

**Issue by DinhThuongNguyen** [prisma/studio#779]
1. Prisma version (3.0.2):

[https://i.im.ge/2021/09/17/TN6UxM.png](url)
How to change code be error?
Sorry my english is not good !

**Comment by madebysid** [comment]
Hi @DinhThuongNguyen, do you only see this error in Studio? What happens if you try to run a Prisma Client script?

What version of prisma are you using? (You can run `prisma -v` to check this)
