### ISSUE TITLE
 EACCES: permission denied

### ISSUE THREAD

**Issue by Cavein254** [prisma/studio#789]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @Cavein254, I'll need more information to be able to debug this, please add some more context, and I'll reopen!
