### ISSUE TITLE
Request: Early Access Prisma Data Platform for Data Entry Management

### ISSUE THREAD

**Issue by PranavSathy** [prisma/studio#794]
**Describe the bug**
We (https://reverecre.com) would like access the Prisma Data Platform to manage our CloudSQL database in GCP (maintained via Prisma) for data entry work. We have 100ks + rows and would like to leverage the platform for entry work.

We simply need to whitelist the static IP address for the service for access to our CloudSQL instance.

**Comment by PranavSathy** [comment]
HI @madebysid , I can't create a project because my database is unreachable. Seems like a catch-22, since I will need to whitelist your IP address on my CloudSQL database to actually successfully create the project (at which point, I won't need to email proessdorf@).

**Comment by madebysid** [comment]
Ah right, that's unfortunately a limitation right now, but the good news is that we're actively working on this. In the future, there would be a way to use static IPs for all DB related operations.

@martzoukos can keep you updated when we ship this.
