### ISSUE TITLE
Breadcrumbs in databrowser

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#8]
**Idea needs verification**
Mock out a design for a databrowser that opens relations in a new, nested table.

1. Bob opens a `user` model
2. Bob clicks on a `posts` cell of a user record
3. The `user` table is replaced by `posts` table that shows only posts related to the user
4. Somewhere in the databrowser UI, a breadcrumbs element appearas with `User/Posts/` breadcrumb trail that would allow to navigate back through the relations.

**Comment by madebysid** [comment]
I believe this can be closed in favour of #9 with the introduction of tabs? Please reopen if I'm mistaken!

**Comment by schickling** [comment]
We've been meaning to keep this open until @kuldar has come up with a mockup in order to get feedback from the community 🙏
