### ISSUE TITLE
Arrow-button on the bottom-left doesn't make the sidebar stick

### ISSUE THREAD

**Issue by nikolasburk** [prisma/studio#80]
Arrow-button on the bottom-left doesn't make the sidebar stick.

![image (15)](https://user-images.githubusercontent.com/4058327/64182118-f93d2c80-ce67-11e9-8f3f-bd33025fafe5.png)
![image (16)](https://user-images.githubusercontent.com/4058327/64182119-f9d5c300-ce67-11e9-96d4-0145f6f34842.png)

**Comment by madebysid** [comment]
Fixed on alpha.161
