### ISSUE TITLE
Static IP Request

### ISSUE THREAD

**Issue by C-Sinclair** [prisma/studio#807]
Hi Prisma Team,

I'd love to try out the Prisma Data Platform, but the database I need to access requires a static IP address. 

Here's the url of the project:

https://cloud.prisma.io/C-Sinclair/lamplight/

Could you provide me with the static IP?

Thanks in advance, keep up the good work! :+1:

**Comment by madebysid** [comment]
I'm told this was resolved over Intercom, so closing!
