### ISSUE TITLE
Prisma Studio 

### ISSUE THREAD

**Issue by GoldenCredit101** [prisma/studio#808]
1. Prisma version (`prisma -v` or `npx prisma -v`):
- Prisma: 3.5.0

2. Logs from Developer Tools Console or Command line, if any:
```
Unable to process `count` query undefined 
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
yes
4. Prisma schema (if relevant):
```

```

**Comment by GoldenCredit101** [comment]
issue resolved

**Comment by Garrett1Tolbert** [comment]
> issue resolved

How did you resolve this issue?

**Comment by kleydon** [comment]
I'm still experiencing this issue, with prisma 3.8.1.
Is there a solution?

**Comment by limegorilla** [comment]
Can also reproduce this in Safari 15.5, but is working in Chrome
