### ISSUE TITLE
Adjust design for browser-based Studio

### ISSUE THREAD

**Issue by schickling** [prisma/studio#81]
![image](https://user-images.githubusercontent.com/1567498/64269088-259b8c00-ceee-11e9-9301-550f631f8aef.png)

**Comment by idan** [comment]
Is this specifically about the data browser, or also about the other things that will be part of studio (init flow, dashboard)? cc @schickling @kuldar

**Comment by madebysid** [comment]
We've replaced the empty space with a (non-working, currently) DB icon on the left, so closing!
