### ISSUE TITLE
Fatal Error in Prisma Data Platform

### ISSUE THREAD

**Issue by Renuja99** [prisma/studio#811]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
A non recoverable error has occurred and studio has to be restarted. Please consider this error to us by opening an issue on Github 
and attaching the error details.
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @Renuja99, could you elaborate? What action caused this? Is this reproducible? Any details would help. Thanks!

**Comment by Renuja99** [comment]
Yes..sure.. Here's what I did step by step
- Created a new project using cloud.prisma.io
- Gave it a project name, connected my GitHub account
-  Then when selecting a template I chose an empty schema template
- Then selected Heroku PostgreSQL as the database provider

Then the project gets created , a new repository is created , sometimes a new app gets created in my Heroku account , sometimes it does not..

And the given error keeps popping when I enter the newly created projects' Data Browser menu

Everything works fine for the Blog template but it never worked for the Empty template .I did it for like 5 to 6 times..Thanks in advance if you can help...

**Comment by madebysid** [comment]
Ah, if you're picking the `Empty` template, then your database likely has no tables. If you expand the `Details` section of this fatal error, what do you see?

If you change your Prisma schema and add a model, then migrate your DB so it also has the cirresponding table, this should work (assuming I diagnosed the problem correctly)

This is also likely why the Blog template works. Let me know what you find!

**Comment by Renuja99** [comment]
I didn't try the **Empty** template after that , I went with the existing NextJS blog app, updated the blog  prisma schema file in the github repositary and then copied the connection string from the heroku app  to my existing app and did a `npx prisma db push` and was able to connect to the cloud database. Thanks a lot for the support. I'll try doing the same to the `Empty` template and comment again
