### ISSUE TITLE
I'm getting this error when loading my tables

### ISSUE THREAD

**Issue by paktola-web** [prisma/studio#815]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @paktola-web, could you provide a few more details? I'll reopen this when you do!
