### ISSUE TITLE
Error facing while viewing database

### ISSUE THREAD

**Issue by guru-marimuthu** [prisma/studio#823]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @guru-marimuthu, I'll need more information to act on this.
