### ISSUE TITLE
Just started to following Prisma Tutorial from youtube, and this is happens

### ISSUE THREAD

**Issue by 1stdeddy2nd** [prisma/studio#827]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by madebysid** [comment]
Hey @1stdeddy2nd, what happened exactly? I'll need more information to be able to do aynthing here.

**Comment by 1stdeddy2nd** [comment]
> Hey @1stdeddy2nd, what happened exactly? I'll need more information to be able to do aynthing here.

Nah that just my bad, github asking me to click some button and create this discussion. Im sorry, you can close it
