### ISSUE TITLE
Preserve expanded nodes on results tree when switching between tabs

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#83]
Currently, you share the same tree component between all tabs, and it is keyed by the tab id. This causes React to re-mount the component when switching between tabs. This is needed so that internal state is reset (expanded nodes in one tab do not interfere with expanded nodes in another tab).

It would be ideal if this state is preserved somehow without having to have separate components for every tab.

**Comment by idan** [comment]
I think there's a more generalized discussion here about clientside state and persisting it — if we do that right, we get this for "free" @madebysid ? See also #174.

@madebysid how much impact does this have on perf? This sounds like "we wish it were better but it's not a disaster". Correct?

If that's correct, then maybe we can drop this issue in favor of an exploration on state management and figuring out how to do that better. In either case, if it isn't a perf bug then it's post-beta.

**Comment by madebysid** [comment]
@idan Agree, it is definitely a nice-to-have. I don't think this will affect performance too much either. Post-beta sounds good to me.

**Comment by madebysid** [comment]
This is now done as a side-effect of another fix, closing!
