### ISSUE TITLE
Prisma Sudio fails on startup in Safari, for valid schema but not-yet-initialized database

### ISSUE THREAD

**Issue by kleydon** [prisma/studio#834]
1. Prisma version (`prisma -v` or `npx prisma -v`):
3.81

2. Logs from Developer Tools Console or Command line, if any:
```
Unable to process `count` query undefined
```

This bug is experienced in Safari, when Prisma Studio is opened, but a database has not yet been initialized using `migrate`.

It did not occur in Chrome, under the same conditions.

**Comment by janpio** [comment]
An error when the database does not exist yet or does not have the model defined in your schema file is pretty expected though, isn't it? It's just that the error message is not the most helpful here for sure.

**Comment by janpio** [comment]
Hello,

can you please provide more details of the error message or fill in the details of the issue like logs from Developer Tools Console and your Prisma schema?

Thank you.
