### ISSUE TITLE
Fatal Error in Data Browser

### ISSUE THREAD

**Issue by abhiram11** [prisma/studio#837]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```Environment variables loaded from .env
prisma                  : 3.8.1
@prisma/client          : Not found
Current platform        : windows
Query Engine (Node-API) : libquery-engine hashkey (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli hashkey (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core hashkey (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt hashkey (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : hashkey
Studio                  : 0.452.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Error in HTTP Request (Status: 500)
{}
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes, I also restarted the studio by refreshing and clicking on re-run the studio prompt.
 
4. Prisma schema (if relevant):
```
N/A as I selected empty schema during database creation
```

**Comment by janpio** [comment]
Hello,

can you please provide more details of the error message or fill in the details of the issue like logs from Developer Tools Console and your Prisma schema?

Thank you.
