### ISSUE TITLE
Error in HTTP Request (Status: 404) {}

### ISSUE THREAD

**Issue by willin** [prisma/studio#840]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/1890238/151355155-d2e12279-e06e-4aa4-bf59-e71d7c7f54d3.png">

willin/hanhan

**Comment by janpio** [comment]
Hello,

can you please provide more details of the error message or fill in the details of the issue like logs from Developer Tools Console and your Prisma schema?

Thank you.
