### ISSUE TITLE
404s in data browser.

### ISSUE THREAD

**Issue by sioanis** [prisma/studio#875]
Receiving the following error:

Fatal Error:

A non-recoverable error has occurred and Studio has to be restarted. Please consider reporting this error to us by opening an issue on GitHub and attaching the error details. If this persists, please clear out your IndexedDB and try again.

Details:
```
Error in HTTP Request (Status: 404)
{}
```

<img width="482" alt="Screen Shot 2022-03-10 at 2 15 49 AM" src="https://user-images.githubusercontent.com/3586765/157608736-c1e0e8db-add7-4239-b79e-1ad8aeaefb87.png">

**Comment by janpio** [comment]
Hello,

can you please provide more details of the error message or fill in the details of the issue like logs from Developer Tools Console and your Prisma schema?

Thank you.

**Comment by sioanis** [comment]
Sounds good. I was able to resolve this.
