### ISSUE TITLE
Prisma studio not able to load assets

### ISSUE THREAD

**Issue by SheldonNunes** [prisma/studio#877]
Hi there I am having an issue where prisma studio is not able to load the necessary assets `index.js` and `vendor.js`. I have tried running with `yarn` and `npx` with no luck, deleting and reinstalling my `node_modules` folder didn't fix it either. 

1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
Preview Features        : orderByRelation
```

2. Logs from Developer Tools Console or Command line, if any:
```
GET http://localhost:5555/assets/index.js net::ERR_ABORTED 404 (Not Found) localhost/:12          
GET http://localhost:5555/assets/vendor.js net::ERR_ABORTED 404 (Not Found) localhost/:13          
```

4. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes tried with latest prisma `3.10.0`

6. Prisma schema (if relevant):
```

```

**Comment by SheldonNunes** [comment]
> Did this work for you before?
No it has never worked for me :'(
I did get the Prisma Studio app working but not the cli one

>Can you open these links in new tabs manually?
I tried and get `404` response `Cannot GET /assets/index.js`

**Comment by mohasi** [comment]
@janpio I am getting the same 404 errors, and have never had it working:
```
yarn prisma -v    
yarn run v1.22.19
Environment variables loaded from .env
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
Done in 0.67s.
```

Trying to launch from terminal in VS Code but the page is blank.

```
yarn prisma studio
yarn run v1.22.19
$ C:\dev\myapp\node_modules\.bin\prisma studio
Environment variables loaded from .env
Prisma schema loaded from server\database\schema.prisma
Prisma Studio is up on http://localhost:5555
```

Errors:
![image](https://user-images.githubusercontent.com/47725053/210179438-5b86c35b-6728-4493-8834-b19fa0c8b236.png)

**Comment by Valetek** [comment]
raising this case up as I came onto this recently, was working before and suddenly was not, I m investigating the cause so I might post again

**Comment by Valetek** [comment]
Well as weird as it is, look like the problem might came when installing the prisma package or generating prisma client, reinstalling prisma and regenerating client seems to works properly

@SheldonNunes Hope you figured out how to solve your problem since your last comment

**Comment by janpio** [comment]
We can reopen this as soon as someone has a reliable way to reproduce this. Thanks.
