### ISSUE TITLE
Prisma Studio is not showing data at preview 10

### ISSUE THREAD

**Issue by shoaibsharif** [prisma/studio#88]
I can't see my data on Prisma Studio after installing primsa2.0.0-preview-10. It is showing up this error:
```
Project load failed:  TypeError: Cannot read property 'id' of undefined
    at oi.switch (studioBundle.js:108)
    at $ (studioBundle.js:16)
    at oi.i (studioBundle.js:16)
    at li.init (studioBundle.js:108)
```

![Screenshot from 2019-09-07 11-21-54](https://user-images.githubusercontent.com/29075110/64478750-c47bee80-d161-11e9-926b-da27cabc9098.png)

**Comment by madebysid** [comment]
Hey @shoaibsharif, could you try updating to the latest alpha and try this again? `npm i -g prisma2@alpha`

**Comment by shoaibsharif** [comment]
Yeah. You are right. Sorry for the late reply. I was reviewing your test on Ubuntu and MacOS. I confirmed that after upgrading `prisma2@alpha`, I am not facing any issue so far.

**Comment by radicand** [comment]
Thanks for this tip, I was running through the tutorial using `npx` commands instead of the global install and found I needed to do `npx prisma2@alpha dev` to solve this issue as well.
