### ISSUE TITLE
Error message: Weird stacktrace encoding

### ISSUE THREAD

**Issue by schickling** [prisma/studio#89]
![image](https://user-images.githubusercontent.com/1567498/64613716-1f6a4b80-d3d7-11e9-9946-5dec30a7fd35.png)

**Comment by madebysid** [comment]
Have stripped out ANSI characters from the stacktrace as well. 
What caused this though? This is a fatal error, which probably means it came from a generated script.

**Comment by madebysid** [comment]
Fixed with alpha.174. This happened with an invalid limbo state right?
Since I'm looking into limbo states anyway, I'll create some primitive validation as well.

**Comment by madebysid** [comment]
Closing since this should be fixed. Tracking validation here: https://github.com/prisma/studio/issues/90
