### ISSUE TITLE
Studio hangs in Chrome but not in Firefox (for eg)

### ISSUE THREAD

**Issue by denik1981** [prisma/studio#898]
**Describe the bug**
_Please take a look for my underline OS and Node version because this might be related only to them as well._

Studio hangs at loading when using Chrome but works well in Firefox, to name a green-light example.
The codebase that I'm using to work with is public so you can reproduce it with the same codebase.

[https://github.com/calcom/cal.com](https://github.com/calcom/cal.com)

**To Reproduce**

_I think the best way to reproduce this will be to pin to node 14.19.0 and probably Ubuntu 20.04.1 as well_

1. `git clone https://github.com/calcom/cal.com`
2. `yarn` 
3. `yarn workspace @calcom/prisma db-reset` //makes prisma migrations, starts postrgres (docker) and seedes the db.
4. `yarn db-studio` // starts prisma studio 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 
 - Browser: Chrome  99.0.4844.84  (at the moment, latest)
 - Node 14.19.0
 - Yarn 1.22.17
 
## Aditional Notes

I don't think this is related to #870 because the Studio actually starts loading but it hangs after building the table headers. I cannot see any data nor use it. At some point forces me to close it because it eats all of my memory in Chrome. I'm not seeing any kind of error in the console as well.

**Comment by denik1981** [comment]
Seems a third-party cookie was for some reason hanging studio in Chrome, but I must say that cleaning localhost:5555 was not enough. I started working again once I cleaned the entire Chrome History for all sites. I will close this as I don't have enough information to identify which third-party cookie was the one to blame for.

**Comment by janpio** [comment]
That is _weird_. Did you when cleaning the cookies maybe also clean out IndexedDB? That is used by Studio and is sometimes not the most reliable in browsers. That woulc have been my guess.
