### ISSUE TITLE
Opening relations in new tabs

### ISSUE THREAD

**Issue by kuldar** [prisma/studio#9]
**Behavior**

1. Bob opens a `user` model
2. Bob clicks on a `posts` cell of a user record
3. The `posts` table with users posts is opened in a new tab and immidiately opened

**Comment by madebysid** [comment]
Is this what we're going with to replace the details bar? A potential downside here is that long fields get pretty difficult to preview since we truncate them (in the table at least, for the tree, I could just increase the height of the row, but even that will have its limits)

**Comment by idan** [comment]
@schickling is this something in the critical path? It looks like there's already a lot of work done here so scheduling for Beta, but if not then we should push to post-beta

**Comment by madebysid** [comment]
There's now a `Open in New Tab` button in the relation table that should accomplish this :D
