### ISSUE TITLE
npx prisma error

### ISSUE THREAD

**Issue by neofirst** [prisma/studio#905]
1. Prisma version (`prisma -v` or `npx prisma -v`):
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : windows

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
  not work

4. Prisma schema (if relevant):
```

```
![image](https://user-images.githubusercontent.com/70267158/161655090-2eb485ab-6f93-40ee-92af-2a82b60ae34d.png)
![제목 없음](https://user-images.githubusercontent.com/70267158/161655132-15791bcf-fb09-46c7-a515-cc61d101cf0f.png)

**Comment by neofirst** [comment]
![1](https://user-images.githubusercontent.com/70267158/161655286-ee8415a6-bc84-45dc-bbd5-e9130e13b2cc.png)

**Comment by neofirst** [comment]
planetscale mysql db init ...
but... same error
prisma : 3.10.0 and 3.11.1
@prisma/client : 3.10.0 and 3.11.1

**Comment by janpio** [comment]
The log output screenshot you are posting does not look like it is from Studio, but a normal app running Prisma Client - correct?

What are you doing in Studio that causes these errors?

**Comment by neofirst** [comment]
p{margin-top:0;margin-bottom:0}
    


    I well not speak englishOnly npx prisma studio run1. Planetscale init2. Db push3. npx prisma studioBut yesterday not errorToday errorAlso i am not modify code---- 원본 메일 ----보낸 사람 : Jan ***@***.***>받는 사람 : ***@***.***>참조 : ***@***.***>, ***@***.***>날짜 : 22.04.05 19:32 GMT +0900제목 : Re: [prisma/studio] npx prisma error (Issue #905)
The log output screenshot you are posting does not look like it is from Studio, but a normal app running Prisma Client - correct?
What are you doing in Studio that causes these errors?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/prisma/studio/issues/905#issuecomment-1088537761",
"url": "https://github.com/prisma/studio/issues/905#issuecomment-1088537761",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by janpio** [comment]
Can you click "Show details" on the Studio error modal and share what it says in there? That might have more information on what is going wrong for you.

**Comment by janpio** [comment]
Your English is perfectly fine, don't worry 👍 Happy to wait until you had time to look at this again and get more information.

**Comment by neofirst** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you for your advice..I try take it---- 원본 메일 ----보낸 사람 : Jan ***@***.***>받는 사람 : ***@***.***>참조 : ***@***.***>, ***@***.***>날짜 : 22.04.05 21:42 GMT +0900제목 : Re: [prisma/studio] npx prisma error (Issue #905)
Can you click "Show details" on the Studio error modal and share what it says in there? That might have more information on what is going wrong for you.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/prisma/studio/issues/905#issuecomment-1088656800",
"url": "https://github.com/prisma/studio/issues/905#issuecomment-1088656800",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neofirst** [comment]
p{margin-top:0;margin-bottom:0}
    


    here screenshot

--------- 원본 메일 ---------

    
        보낸사람: Jan Piotrowski ***@***.***>
        받는사람: prisma/studio ***@***.***>
        
            참조: Neo ***@***.***>, Author ***@***.***>
        
        날짜: 22.04.05 21:42 GMT +0900
        제목: Re: [prisma/studio] npx prisma error (Issue #905)
        
        
    
    
        
Can you click "Show details" on the Studio error modal and share what it says in there? That might have more information on what is going wrong for you.

**Comment by janpio** [comment]
That unfortunately did not arrive here - I think you have to open https://github.com/prisma/studio/issues/905 again and post it directly instead of via email.

**Comment by DNYLA** [comment]
Last time I had this error I had to clear cookies + cache. For some reason, a value that was cached or in the cookies was causing studio to crash. This was when I was using V 3.6.X or 3.7.x of Prisma so it might auto clear cache  now.

**Comment by neofirst** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you your advi..hahaOther mechine(?) is good connectedcash is not reasonNot understand ㅠㅠUm.. i well not speak englishKorean:이해해주세요^_^---- 원본 메일 ----보낸 사람 : ***@***.***>받는 사람 : ***@***.***>참조 : ***@***.***>, ***@***.***>날짜 : 22.04.12 22:39 GMT +0900제목 : Re: [prisma/studio] npx prisma error (Issue #905)
Last time I had this error I had to clear cookies + cache. For some reason, a value that was cached or in the cookies was causing studio to crash. This was when I was using V 3.6.X or 3.7.x of Prisma so it might auto clear cache  now.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/prisma/studio/issues/905#issuecomment-1096743068",
"url": "https://github.com/prisma/studio/issues/905#issuecomment-1096743068",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by djafta** [comment]
You must have the same version for @prisma/client and prisma

I got same error and and solved using 
```
yarn add prisma@stable
yarn add @prisma/client@stable
```

**Comment by petradonka** [comment]
As far as I understood, clearing the cache did not fix this issue. 

Is the issue still happening for you? If yes, could you try to share the screenshot again after you click "Show details" on the Studio error modal to share what it says in there?

You could also try clearing the IndexedDB, as explained here: https://github.com/prisma/studio/issues/895#issuecomment-1083051249
