### ISSUE TITLE
Implement keyboard shortcuts

### ISSUE THREAD

**Issue by schickling** [prisma/studio#91]
Would be great to implement the following keyboard shortcuts: https://github.com/prisma/specs/tree/master/studio#keyboard-navigation

Related to #3.

**Comment by schickling** [comment]
Ideally this also includes support for #104.

**Comment by idan** [comment]
Discussed today during studio mega-planning. We should not interfere with normal operation of the browser (e.g. new tab) but makes sense to override existing behavior like refresh or save. Need to do a pass on the shortcuts in the spec and decide here.

**Comment by idan** [comment]
#1 is a part of this

**Comment by madebysid** [comment]
Working with @matthewmueller, we now have a pretty decent keyboard experience for Studio. Small improvements will follow, but this is done, so I'm closing!
