### ISSUE TITLE
Mystery fatal error in Studio

### ISSUE THREAD

**Issue by cyrusae** [prisma/studio#917]
1. Prisma version (`prisma -v` or `npx prisma -v`):
8.3.1, using Studio in the localhost:5555 setup.

2. Logs from Developer Tools Console or Command line, if any: 
> A non-recoverable error has occurred and Studio has to be restarted. Please consider reporting this error to us by opening an issue on GitHub and attaching the error details. If this persists, please clear out your IndexedDB and try again.
```
Unable to process `count` query
undefined
```

4. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
As far as I can tell, yes.

5. Prisma schema (if relevant):
Unsure if relevant and it's quite long, but [it's all here](https://github.com/cyrusae/highlighter-public/blob/main/backend/prisma/schema.prisma).

I apologize for being unable to provide further information; I don't have any.

**Comment by janpio** [comment]
There is no Prisma 8.3.1 - can you please check again?
Are schema file and database fully in sync?
Is this reproducible if you `db push` the schema you linked to to a new database and then run studio for that?

**Comment by petradonka** [comment]
I'm closing this as we don't have enough info about the issue you encountered.

If this is still an issue, please reopen this and share some more details:
> There is no Prisma 8.3.1 - can you please check again?
> Are schema file and database fully in sync?
> Is this reproducible if you db push the schema you linked to to a new database and then run studio for that?
