### ISSUE TITLE
Can't access Prisma Studio after changing filters and refreshing page

### ISSUE THREAD

**Issue by bhajneet** [prisma/studio#920]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82151
    at Array.forEach (<anonymous>)
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
No. Same error in `3.13.0-dev.29`

4. Prisma schema (if relevant):
```

```

**Comment by bhajneet** [comment]
This has to do with the filters cached in browser. I can fix the issue by using incognito/private browsing or by clearing cache. However, it would be ideal to do this with a button press in the error message shown here:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/14130567/164733004-40fad4d4-92e5-4e15-965b-c5e3841aaaa4.png">

Basically have prisma studio close all of its tabs and reset all its filters with some button press here. Neither "Reopen Studio" nor "Discard all unsaved changes" does this for me currently. I have to manually delete the site data to get it to work.

To do that, I inspect site with Chrome Dev Tools, go to the Application tab, then under Storage I tap "Clear site data" to get back in.

Is there a way for user to resolve this with a GUI click in the message shown in the picture above?

**Comment by janpio** [comment]
See https://github.com/prisma/studio/issues/895

**Comment by janpio** [comment]
Is this reproducible for you @bhajneet when you use the filters again? Can you get it into the same situation again?
