### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by stvlley** [prisma/studio#929]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by petradonka** [comment]
Hello,

If you're still running into issues, please provide more details by filling in this issue with information such as the version you're using and relevant logs.

Thank you!
