### ISSUE TITLE
Invalid actions:  [   {     "id": "69c424f5-d1d7-4883-81a9-b00e523df23a",     "idbTableName": "actions",     "recordId": "tmp--dfc6a732-0546-4026-affa-09361f192a33",     "sessionId": "0e0e3f7e-33a5-4639-ab6f-8432ad5fec13",     "type": "update",     "value": {       "name": "iphone",       "price": 0     }   }

### ISSUE THREAD

**Issue by Surajkumar70** [prisma/studio#931]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by petradonka** [comment]
Could you share some more information about which version you're using and at what point the error occurs?
