### ISSUE TITLE
Prisma Studio aw, snap crash in chrome

### ISSUE THREAD

**Issue by jeremygottfried** [prisma/studio#935]
**Describe the bug**
Prisma Studio is not loading in Chrome. It works in Safari

**To Reproduce**
1. npx prisma studio
2. open in chrome

**Expected behavior**
Prisma studio works

**Screenshots**
<img width="877" alt="Screen Shot 2022-05-11 at 11 19 31 AM" src="https://user-images.githubusercontent.com/34523280/167888084-1f88d510-3083-4491-bca2-c6f0394697f4.png">
<img width="911" alt="Screen Shot 2022-05-11 at 11 18 58 AM" src="https://user-images.githubusercontent.com/34523280/167888088-e32e723b-4f32-4363-b57d-5572f3cf19e4.png">
<img width="818" alt="Screen Shot 2022-05-11 at 11 18 39 AM" src="https://user-images.githubusercontent.com/34523280/167888089-2fb05fde-c575-43df-8869-23663e36bbd0.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chrome 101.0.4951.64
 - Version: Prisma Studio 0.459.0

**Comment by petradonka** [comment]
Which version of `prisma` are you using? You can find this info by running `prisma -v` or `npx prisma -v`.

**Comment by jeremygottfried** [comment]
Prisma version 3.13.0. This is still not fixed.

**Comment by d-ivashchuk** [comment]
hey @jeremygottfried! do you mind looking at the console output of your browser in the meantime you are having this error? might help us get better understanding of the problem, thanks!

**Comment by janpio** [comment]
Nothing obvious there.

Can you maybe use these? https://support.google.com/chrome/a/answer/6271282?hl=en

**Comment by jeremygottfried** [comment]
I dunno if it was a change on Chrome or Prisma, but it's working again. 💁
