### ISSUE TITLE
Unable to open Prisma Studio

### ISSUE THREAD

**Issue by abh006** [prisma/studio#938]
```
A non-recoverable error has occurred and Studio has to be restarted. Please consider reporting this error to us by opening an issue on GitHub and attaching the error details. If this persists, please clear out your IndexedDB and try again.
```
<img width="488" alt="image" src="https://user-images.githubusercontent.com/26924922/168538463-12f47efd-1639-42da-ab01-7a723111688d.png">

1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

2. Logs from Developer Tools Console or Command line, if any:
No unusual logs

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)
Yes, it does.

I am using PostgresQL on my docker container as the DB.
I tried `docker compose down -v`, but the issue persists

**Comment by abh006** [comment]
This is when I was trying to access Prisma studio with Firefox Developer Edition. 
But, this issue doesn't exist for Safari browser.

**Comment by westlag114** [comment]
I fixed this way.
https://github.com/prisma/studio/issues/895#issuecomment-1083051249
@abh006

**Comment by petradonka** [comment]
Could you click "Show details" on the Studio error modal and share what it says in there? That might have more information on what is going wrong for you.
