### ISSUE TITLE
`DomainError(ConversionFailure("Json` for json objects

### ISSUE THREAD

**Issue by shunkakinoki** [prisma/studio#942]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by petradonka** [comment]
Which version of `prisma` are you using (`prisma -v` or `npx prisma -v`)? Could you share some more details about what actions you're taking that result in this error?
