### ISSUE TITLE
prisma studio  `DomainError(ConversionFailure("Json` error

### ISSUE THREAD

**Issue by shunkakinoki** [prisma/studio#944]
### Bug description

 DomainError(ConversionFailure("Json  when quering Json in prisma studio

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by petradonka** [comment]
Which version of `prisma` are you using (`prisma -v` or `npx prisma -v`)? Could you share some more details about what actions you're taking that result in this error?
