### ISSUE TITLE
Adjust designs: Rename "Add row" to "Add record"

### ISSUE THREAD

**Issue by schickling** [prisma/studio#95]
![image](https://user-images.githubusercontent.com/1567498/64677131-52641c00-d477-11e9-899f-43a61fd70fd3.png)

**Comment by schickling** [comment]
@kuldar please also adjust in the designs.

**Comment by nikolasburk** [comment]
Should this be closed as it seems that this was implemented? cc @madebysid 

![image](https://user-images.githubusercontent.com/4058327/67672094-7623e880-f977-11e9-8a13-49c7ce74912b.png)

**Comment by madebysid** [comment]
@nikolasburk It is kept open as a reminder to change this in all designs as well.

**Comment by madebysid** [comment]
This is updated on latest Figma designs too I see, so closing
