### ISSUE TITLE
Date cell editing broken

### ISSUE THREAD

**Issue by schickling** [prisma/studio#96]
https://www.loom.com/share/cc4304cb311144ff897fe6eca4c6ddfa

**Comment by madebysid** [comment]
@kuldar Do you think date cells should be edited as strings, or would there be a custom date selector of sorts?

Once we have validation (pretty soon), string inputs would suffice IMO. Thoughts?

**Comment by johannesschobel** [comment]
Dear @madebysid ,
i think, it would be best to have a "calendar selector" (i.e., like in apps where you select a date) in order to ensure that the date is properly formatted for the underlying database. What do you think?

All the best

**Comment by madebysid** [comment]
@johannesschobel Agree! This is what we'll be building in soon:
<img width="486" alt="Screenshot 2019-10-02 at 09 54 45" src="https://user-images.githubusercontent.com/7689783/66027210-bb7d0380-e4fa-11e9-9c37-122e0062123e.png">

**Comment by johannesschobel** [comment]
That looks awesome..
I would, however, suggest to add a Textfield as well (with proper placeholder format) so that I can add a value myself.

Entering a birthdate via calendar may be very annoying, if you need to go back 40 years or so ;)

**Comment by idan** [comment]
Marked candidate for discussion during upcoming sync.

Datepickers are a source of so many UI edge-cases, IDK whether this is something we want to do for beta or post-beta.

**Comment by madebysid** [comment]
> Datepickers are a source of so many UI edge-cases

@idan I totally agree, which is why I've been putting this off, and consider this high effort as well. Datetimes are still visible in Studio, but conveniently editing them won't be possible without this.

We could allow basic editing by treating Datetimes as strings that are validated after editing. Then we can possibly have this done quicker.

**Comment by madebysid** [comment]
Dates can now be edited as a string in alpha.242+, so I'm closing this issue. The bulk of the task, which is creating a datepicker is now tracked here: https://github.com/prisma/studio/issues/226
