### ISSUE TITLE
[cloud.prisma.io] - Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by lamualfa** [prisma/studio#960]
## Description

I've seen similar [issues](https://github.com/prisma/studio/issues?q=is%3Aissue+is%3Aopen+BigInt) about the use of `BigInt` within `schema.prisma`. But this happened in the cloud.prisma.io ecosystem. I can't do anything to reproduce the problem. Should I upgrade my prisma version in the local and push it to the repository?

![image](https://user-images.githubusercontent.com/39755201/172355769-a220c985-c0a2-4ee4-ab42-b27d81703638.png)

<hr>

## Environment

- Node.js 16
- Prisma 3.14
- Windows 11
- Chrome
- PostgreSQL 15

**Comment by lamualfa** [comment]
@petradonka Nice. But sorry, I can't check it because I changed the `BigInt` type to the `String` one last week. Probably I won't switch it back because the app is already in production. But thanks for the fixes.

**Comment by petradonka** [comment]
Well, good to hear that you've resolved the issues you were running into, either way. I'll close this now, thanks for the update!
