### ISSUE TITLE
Prisma Studio cannot save updated rows or entries

### ISSUE THREAD

**Issue by edukumannah** [prisma/studio#964]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by petradonka** [comment]
Could you share a bit more info about what you're seeing? Do you get an error when trying to save?
