### ISSUE TITLE
Prisma Client Error

### ISSUE THREAD

**Issue by semgoSE** [prisma/studio#965]
**Describe the bug**

**To Reproduce**
1. Go to 'prisma,cloud'
2. Click on our project
3. Choose model Tag

**Expected behavior**
Dont see error

**Screenshots**
http://joxi.ru/8An5P67CzZ8aQ2

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome 102.0.5005.115

**Comment by petradonka** [comment]
We'll look into this.

Is the error consistent, or does the query and Data Browser sometimes work for you?

**Comment by semgoSE** [comment]
The error is constant

**Comment by petradonka** [comment]
Thanks for confirming! We're looking into this.

**Comment by luanvdw** [comment]
@semgoSE to help narrow the investigation can you confirm if;

1. the error you are receiving on the Data Browser is only for the `Tag` model and or are you getting the same behaviour for all models of the schema associated to this `production` environment.
2. the same error is present when viewing the Tag model in the other environment (dev) associated with the same project.
