### ISSUE TITLE
Prisma automatically changes the id

### ISSUE THREAD

**Issue by macehack** [prisma/studio#979]
I enter the telegram ID, click save
![image](https://user-images.githubusercontent.com/32418995/178085816-2e6edc2b-499a-423d-9c3b-6ae322d2d9a8.png)

and Prisma automatically changes it to a completely different one - what should I do?
![image](https://user-images.githubusercontent.com/32418995/178085842-fca74867-eea2-44a8-b9cb-c34d224298b6.png)

Gif: https://i.imgur.com/7EWUgRq.gif

**Comment by janpio** [comment]
Does it always change it to this number? How is that field defined in your Prisma model? Does the same happen when you use the Query Console in PDP or run a Prisma Client query directly in your app?
