### ISSUE TITLE
Occasional error in prisma using planetscale DB led to fatal error in prisma studio

### ISSUE THREAD

**Issue by AbhiraajV** [prisma/studio#982]
1. Prisma version (`prisma -v` or `npx prisma -v`): 4.0.0

2. Logs from Developer Tools Console or Command line, if any:
```
Server error: `ERROR 70100 (1317): vttablet: rpc error: code = Aborted desc = transaction 1657910919706442582: ended at 2022-07-17 07:04:29.816 UTC (exceeded timeout: 20s) (CallerID: planetscale-admin)'

Non recoverable error has occured and studio has to restart

```

Multiple restarts later studio is still not up

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by d-ivashchuk** [comment]
Hey! Could you share a little bit more detail in terms of what you were doing when this happened please. Did it work before for the table you were trying to access or it's something new that you've added?

**Comment by AbhiraajV** [comment]
It was working before as I was transferring large amount of data to planetscale. I made changes to the schema ( String => VarChar(1000) ) and since then I've been receiving this error for the studio

Not sure if that's what caused it cause prisma is working fine just the studio crashes

Also I was receiving timeout errors from Pscale when it wasn't able to handle the data I was trying to push at once

**Comment by d-ivashchuk** [comment]
You are using studio locally with `npx prisma studio`, not in Data Browser at **could.prisma.io** right?

**Comment by AbhiraajV** [comment]
Yes correct

**Comment by AbhiraajV** [comment]
> You are using studio locally with `npx prisma studio`, not in Data Browser at **could.prisma.io** right?

Also 2 independent projects use the same prisma client and running prisma studio from the 2nd project works fine

**Comment by AbhiraajV** [comment]
Invalid string length
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _t.serialize (http://localhost:5555/assets/index.js:1:49091)
    at _t.update (http://localhost:5555/assets/index.js:1:12197)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at _t.update (http://localhost:5555/assets/index.js:1:48948)
    at Cc (http://localhost:5555/assets/vendor.js:50:6994)
    at _t.n (http://localhost:5555/assets/vendor.js:50:6688)
    at http://localhost:5555/assets/index.js:1:82272
    at Array.forEach (<anonymous>)

**Comment by AbhiraajV** [comment]
> Invalid string length RangeError: Invalid string length at JSON.stringify () at _t.serialize (http://localhost:5555/assets/index.js:1:49091) at _t.update (http://localhost:5555/assets/index.js:1:12197) at Cc (http://localhost:5555/assets/vendor.js:50:6994) at _t.n (http://localhost:5555/assets/vendor.js:50:6688) at _t.update (http://localhost:5555/assets/index.js:1:48948) at Cc (http://localhost:5555/assets/vendor.js:50:6994) at _t.n (http://localhost:5555/assets/vendor.js:50:6688) at http://localhost:5555/assets/index.js:1:82272 at Array.forEach ()

these are some logs when studio crashes.

**Comment by d-ivashchuk** [comment]
Could you please peek at your IndexedDB data like outlined [here](https://developer.chrome.com/docs/devtools/storage/indexeddb/)

Is there anything that looks off maybe?

**Comment by xenos1337** [comment]
Hi, I fixed this issue clearing IndexedDB

**Comment by petradonka** [comment]
That's good to hear, thanks for keeping us in the loop.
