### ISSUE TITLE
prisma studio aint showing..pls kindly resolve

### ISSUE THREAD

**Issue by dipzcoded** [prisma/studio#984]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by petradonka** [comment]
Could you share a bit more info about the issue you're seeing? Is there an error, are there any logs you could share? What are the steps you're taking?
