### ISSUE TITLE
Horizontal scrolling does not work

### ISSUE THREAD

**Issue by petradonka** [prisma/studio#992]
Value rows in Studio and the Prisma Data Platform's Data Browser can not be scrolled horizontally when there are more columns than the available width allows. The horizontal scroll bar is not visible either.

https://user-images.githubusercontent.com/7353770/181249908-a31dd3cc-710c-42b7-ab82-f1b99eb44147.mov

**Comment by stephyswe** [comment]
any contribution thanks ? :)

**Comment by clayrisser** [comment]
This is completely useless without the ability to scroll right. Most databases have lots of columns.
