### ISSUE TITLE
non recoverable error has been occuring many times  to clear that manually want to clear the chache in chrome

### ISSUE THREAD

**Issue by gokulVettri** [prisma/studio#996]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```

```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by petradonka** [comment]
Thanks for opening an issue.

I understand that you've had many non-recoverable errors. Could you share some more details about that, e.g. logs that have more information about the kind of error you're running into? The error popup should have an expandable section that contains more information.
It would also help to understand what exactly you meant in the issue title by "to clear that manually want to clear the chache in chrome". Could you tell me more about what you're looking for?
